// Ordered art and game definitions. Every recipe has a distinct named output.
export const RAW_ROWS=[
 ['wood','木材','stack of cut logs','forest'],['bamboo','竹材','green bamboo stalks','forest'],['hardwood','硬木','dark hardwood log','forest'],['twig','树枝','bundle of thin twigs','forest'],['resin','树脂','golden resin in a little cup','forest'],
 ['bark','树皮','curled brown bark','forest'],['fiber','植物纤维','bundle of pale plant fibers','forest'],['leaves','嫩叶','fresh green leaves','forest'],['mushroom','蘑菇','three brown mushrooms','forest'],['honey','蜂蜜','honey jar with dipper','forest'],
 ['stone','石材','gray rocks','mine'],['ore','星晶矿石','turquoise star crystal ore','mine'],['copper','铜矿','orange copper ore','mine'],['iron','铁矿','dark silver iron ore','mine'],['quartz','石英','clear white quartz cluster','mine'],
 ['crystal','紫晶','purple amethyst cluster','mine'],['clay','陶土','reddish clay lumps','mine'],['sand','细沙','small beige sand pile','mine'],['coal','煤块','black coal chunks','mine'],['salt','岩盐','pink rock salt chunks','mine'],
 ['seed','通用种子','cloth pouch of mixed seeds','farm'],['wheat','小麦','golden wheat sheaf','farm'],['tomato','番茄','red tomato pair','farm'],['pumpkin','南瓜','orange ribbed pumpkin','farm'],['carrot','胡萝卜','orange carrots with green tops','farm'],
 ['corn','玉米','golden corn cob','farm'],['potato','土豆','three brown potatoes','farm'],['rice','稻米','rice panicles and bowl of rice','farm'],['strawberry','草莓','red strawberries with leaves','farm'],['cotton','棉花','fluffy white cotton branch','farm'],
 ['flax','亚麻','blue flowering flax stalks','farm'],['herb','草药','green medicinal herb sprig','greenhouse'],['mint','薄荷','mint leaves','greenhouse'],['lavender','薰衣草','violet lavender sprigs','greenhouse'],['rose','玫瑰','red rose blossoms','greenhouse'],
 ['sunflower','向日葵','golden sunflower bloom','greenhouse'],['bluegrass','蓝草','indigo blue flowering plant','greenhouse'],['mulberry','桑叶','serrated mulberry leaves','greenhouse'],['wax','蜂蜡','yellow beeswax honeycomb','forest'],['amber','琥珀','warm amber nugget','forest'],
 ['fish','海鱼','silver blue fish','fishing'],['shrimp','海虾','pink shrimp','fishing'],['crab','螃蟹','red crab','fishing'],['ink','乌贼墨','squid with dark ink droplet','fishing'],['seaweed','海藻','green seaweed fronds','shore'],
 ['shell','贝壳','pink scallop shell','shore'],['pearl','珍珠','open oyster with pearl','shore'],['coral','珊瑚碎片','pink washed-up coral fragments','shore'],['driftwood','漂流木','pale twisted driftwood','shore'],['seasalt','海盐','white sea salt in shell dish','shore']
];
// name|art description; categories are actual uses, not cosmetic rarity copies.
export const PRODUCT_ROWS=[
 ['灯笼|wooden lantern with warm candle','田间锄头|wood handled iron hoe','矿工镐|iron pickaxe with wooden handle','浇水壶|turquoise watering can','伐木斧|wood handled axe','收割镰|curved harvesting sickle','海风木椅|carved wooden chair','木板|stack of milled planks','鸟屋|little roofed birdhouse','竹编屏风|bamboo room divider','林间书柜|wooden bookshelf','树脂风铃|amber resin wind chime'],
 ['花茶|cup of flower tea','薄荷凉饮|glass of mint iced tea','蜂蜜柠香饮|golden honey tea with mint','玫瑰茶包|pink rose teabags','薰衣草奶茶|lavender tea in purple cup','海盐气泡饮|blue fizzy drink','南瓜香茶|pumpkin orange tea','草莓果饮|strawberry red drink','竹筒清茶|green tea in bamboo cup','暖手茶炉|little ceramic tea stove','六味茶礼盒|six colorful tea tins in gift box','珍珠茶盏|iridescent pearl teacup'],
 ['海岛料理|fish stew in bowl','番茄烩饭|tomato red rice plate','烤玉米|grilled corn on wooden platter','土豆浓汤|creamy potato soup','香草烤鱼|roasted herb fish','海虾米饭|shrimp rice bowl','蘑菇饭团|mushroom rice triangle','南瓜焗饭|baked rice in pumpkin','蟹肉拼盘|crab feast platter','竹筒野炊饭|bamboo rice bowl','海岛宴席|large mixed seafood feast tray','星夜便当|star decorated bento box'],
 ['花束|pink mixed flower bouquet','薄荷盆栽|mint plant in clay pot','玫瑰胸花|rose boutonniere','向日葵花环|sunflower wreath','薰衣草香囊|lavender embroidered sachet','竹篮花饰|flower basket','叶片桌花|green leaf table arrangement','海贝花瓶|flower vase covered in seashells','流苏花帘|hanging flower curtain','节庆花门|arched floral doorway','珊瑚花雕|pink coral flower sculpture','四季花灯|floral lamp with four colors'],
 ['主题服装|festive purple dress','亚麻衬衫|cream linen shirt','棉布围裙|green cotton apron','海风草帽|wide straw hat with blue ribbon','矿工手套|brown leatherlike work gloves','花园披肩|pink floral shawl','星空斗篷|navy star cape','海盐条纹裙|blue striped skirt','玫瑰礼服|red rose formal dress','航海制服|navy sailor uniform','珍珠发饰|pearl hair comb','折光舞衣|iridescent dance costume'],
 ['星图|blue star chart scroll','观星手册|astronomy book','简易望远镜|brass telescope on tripod','月相挂盘|moon phase wall disc','流星许愿瓶|bottle filled with star shapes','星座徽章|gold constellation brooch','双筒望远镜|brass binoculars','星砂标本|glowing sand vial','银河天球仪|celestial blue globe','航星罗盘|star navigation compass','月影台灯|crescent moon table lamp','彗星奇观|glass comet display sculpture'],
 ['海藻饲料|seaweed fish food jar','卵石底砂|bag of aquarium pebbles','贝壳躲藏屋|shell aquarium shelter','水草栽培篮|aquatic plant basket','小鱼缸|small round fish bowl','过滤器|simple aquarium filter','珊瑚展台|coral aquarium stand','潮汐水景|decorative tidal water tank','海虾育养盒|shrimp nursery tank','夜光水母灯|jellyfish-shaped glowing lamp','环礁水族箱|large reef aquarium','海洋观察档案|marine observation album'],
 ['航海日志|old nautical journal','植物图鉴|botanical field book','矿物图鉴|mineral book with crystal','手工笔记|craft notebook','书签套装|set of colored bookmarks','纸张|stack of cream handmade paper','岛屿地图册|island atlas','星空诗集|star themed poetry book','读书灯|green reading lamp','书籍修复包|book restoration kit','精装共创手册|ornate co-creation handbook','故事收藏箱|box of story scrolls'],
 ['信号灯|red maritime signal lamp','航标浮筒|red white navigation buoy','海风旗|triangular blue flag','灯塔油灯|brass lighthouse oil lamp','雾号|brass fog horn','航线图|nautical route map','潮汐计|wooden tide gauge','航灯透镜|circular glass lighthouse lens','反光路标|reflective signpost','码头引航牌|harbor pilot sign','远航信标|tall glowing beacon','晨光纪念灯|miniature lighthouse lamp'],
 ['海岛货篮|basket of island groceries','干花货包|bundle of dried flowers','蔬果礼包|colorful vegetable gift hamper','矿石样品箱|wooden mineral sample crate','茶点礼包|tea and pastry gift set','摊位价签|wooden market price tags','编织购物袋|woven tote bag','便携展示架|portable market display shelf','岛屿特产盒|island specialty gift box','主题市集招牌|festive market sign','珍珠纪念品|pearl souvenir charm','共创展销台|decorated artisan booth'],
 ['草药药剂|green game potion bottle','薄荷舒缓包|mint comfort sachet','棉布绷带|rolled cotton bandages','草本热敷袋|herbal warming pouch','净水杯|clean water cup','药草分装盒|herbal compartment box','蜂蜡护手膏|beeswax hand cream tin','薰香休息枕|lavender pillow','诊所工具托盘|neat clinic tool tray','应急护理包|red white first aid bag','康复花篮|recovery flower basket','居民健康手账|health journal'],
 ['漂流信|letter in bottle','岛屿明信片|illustrated island postcard','压花信封|pressed flower envelope','竹纸信笺|bamboo paper letter sheets','蜂蜡封印|wax sealing stamp','邮票册|colorful stamp album','木质邮袋架|wooden mail sorting rack','航海邀请函|nautical invitation card','派对请柬|festive party invitation','共创委托书|artisan commission scroll','珍珠信封扣|pearl envelope fastener','远方故事包|bundle of travel letters'],
 ['竹笛|green bamboo flute','沙锤|wooden shaker pair','木制响板|wooden castanets','海贝口哨|shell whistle','手鼓|small frame drum','亚麻琴套|linen instrument bag','海风吉他|wooden acoustic guitar','音乐盒|carved wind-up music box','星夜乐谱|blue musical score','舞台节拍器|wooden metronome','岛屿唱片|vinyl record in island cover','潮声竖琴|shell shaped harp'],
 ['海岛相片|island photo in frame','木质相框|wooden photo frame','花园相册|flower themed photo album','航拍地图|aerial island photograph','摄影反光板|folding silver reflector','竹木三脚架|bamboo camera tripod','暗房显影盒|photo developing tray','海风镜头|camera lens with blue trim','派对留影册|party photo guestbook','星空摄影架|night camera tracking mount','珍珠纪念相框|pearl ornate picture frame','晨光影集|deluxe island photo album'],
 ['育苗盘|green seedling tray','薄荷种苗|mint seedlings in pots','玫瑰种苗|rose seedlings','薰衣草种苗|lavender seedlings','棉花种苗|cotton seedlings','亚麻种苗|flax seedlings','滴灌管|coiled garden irrigation tube','竹制苗架|bamboo seedling shelf','温室肥料|herbal compost bag','遮光帘|greenhouse shade curtain','种子收藏盒|seed specimen box','四季花圃|miniature four-season flower bed'],
 ['陶器|brown clay pot','茶杯|cream ceramic teacup','花瓶|tall blue ceramic vase','小碟|shallow ceramic dish','香薰炉|ceramic incense burner','调色盘|ceramic artist palette','花纹茶壶|floral teapot','海贝陶碗|shell glazed bowl','陶制灯罩|perforated clay lamp shade','水族陶洞|aquarium ceramic cave','星空瓷瓶|navy star glazed vase','岛屿陶雕|island landscape ceramic sculpture'],
 ['渔竿|wooden fishing rod and reel','竹制鱼篓|bamboo fishing creel','贝壳浮漂|shell fishing float','鱼饵盒|small bait box','海虾鱼饵|shrimp bait pouch','备用钓线|spool of fishing line','精制鱼钩|three silver fishing hooks','海风渔网|woven fishing net','潮汐钓具包|nautical fishing tackle bag','远投钓竿|long graphite blue fishing rod','珍珠鱼漂|pearl fishing bobber','冠军钓具箱|ornate champion tackle chest'],
 ['面包|golden crust bread loaf','蜂蜜小面包|honey rolls','草莓饼|strawberry pastry','玉米松饼|corn muffin','南瓜派|orange pumpkin pie','香草薄脆|herb crackers','奶香米饼|white rice cookie','薰衣草曲奇|lavender cookies','海盐蝴蝶酥|salt palmier pastry','庆典花冠面包|braided flower crown bread','星灯蛋糕|star lantern decorated cake','共创茶点塔|three tier pastry stand'],
 ['矿物标本|mineral specimen under glass','压叶标本|pressed leaf specimen','海贝标本|seashell specimen box','航海绳结板|nautical knots board','陶片复原盘|restored ceramic plate','旧地图展卷|old map exhibition scroll','岛史展签|museum information plaque','珊瑚收藏柜|coral specimen cabinet','珍珠展架|pearl display stand','琥珀奇观|amber insect display','流星展柜|meteor crystal showcase','晨光岛沙盘|miniature island diorama'],
 ['亚麻靠垫|linen sofa cushion','棉布毛毯|folded cotton blanket','竹编坐垫|bamboo woven floor mat','香草安睡袋|herbal sleep sachet','海风窗帘|blue curtains','花园地毯|floral rug','壁炉木箱|firewood box','床头收纳架|bedside organizer','海贝夜灯|shell night lamp','温暖摇椅|wooden rocking chair','珍珠镜台|pearl vanity mirror','岛主会客桌|ornate island host table'],
 ['烟花|festive firework rocket','花雨烟花|flower shaped fireworks rocket','海蓝礼花|blue fireworks tube','金色喷泉|golden fountain firework','星光纸筒|star decorated paper tube','彩芯套装|colorful fantasy firework cores','庆典引线盒|festive fuse spool box','花火礼盒|fireworks gift box','流星花火|comet firework rocket','音乐花火组|music coordinated firework set','海岛花火屏|fantasy fireworks backdrop','晨光天幕|grand star fireworks launcher'],
 ['演出海报|illustrated concert poster','布景幕布|velvet stage curtain','竹木麦架|bamboo microphone stand','灯光滤片|colored stage lighting gels','演出胸牌|performer badge','彩排指示牌|rehearsal sign','节拍提示器|stage cue timer','星空聚光灯|star blue spotlight','派对背景墙|festive backdrop wall','服装快换架|costume rack','庆典灯阵|decorative light rig','海风音乐舞台|miniature concert stage'],
 ['营地火种盒|camp tinder box','竹制餐具|bamboo camp utensils','亚麻吊床|linen hammock','轻便营灯|portable camp lantern','海风帐篷|blue camping tent','保温食盒|insulated camp food box','防风屏|folding wind shield','露营茶壶|camp kettle','观星睡袋|navy star sleeping bag','营地路灯|camp path lantern','派对大篷|large festival tent','海岛露营沙盘|campground miniature model'],
 ['船板|curved wooden boat plank','防水树脂|waterproof resin tin','竹篙|long bamboo boat pole','船绳|coil of nautical rope','船桨|wooden oar','航海工具箱|shipwright tool chest','救生浮环|red white life ring','海风船帆|blue sail','小舟模型|wooden rowboat model','码头缆桩|wooden mooring bollard','庆典游船|festive boat model','晨光渡船|deluxe passenger ferry model'],
 ['画作|framed island painting','矿物颜料|pigment jars','竹木画笔|bamboo paintbrushes','棉布画板|canvas panel','折纸套件|colored origami paper kit','蓝草染料|indigo dye bottle','海岛拓印|leaf and shell print','陶瓷画盘|painted ceramic palette','共创工坊徽章|artisan workshop badge','四季画屏|four panel painted screen','星光挂毯|star woven tapestry','海岛共创奇观|elaborate collaborative island sculpture']
];
