import {neutralCraftGame} from './craftGameReplay.js';
import {CO_CREATION_EXAMPLES,validateCoCreationPack,coCreationChallenge} from './cocreation.js';
import {RECIPE_BY_ID,ALL_RECIPES} from './contentCatalog.js';import {BUILDINGS} from './world.js';import {itemMarkup} from './artStore.js';import {mountRoomGame} from './roomGames.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),phases={draft:'草稿',submitted:'待审核',changes_requested:'待修改',approved:'已审核'},difficulty=['','轻松','标准','挑战'];
export function createCoCreationUI(api){
 let doc=null,chosen=null,flight=0,engine=null,trace=[],timer=null,uiTimer=null,playing=false,view='shelf',draft=null,closed=false,stopping=false;
 const root=()=>document.getElementById('modalRoot'),key=theme=>'hd-cocreation-'+theme+'-pending',cacheKey=()=> 'hd-cocreation-'+api.theme()+'-editor';
 const pending=()=>{try{return JSON.parse(localStorage.getItem(key(api.theme()))||'null')}catch{return null}};
 async function request(operation,body){const theme=api.theme(),r=await fetch('/api/cocreation/'+theme+(operation?'/'+operation:''),{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,cache:'no-store',signal:AbortSignal.timeout(15000)}),data=await r.json();if(!r.ok)throw Object.assign(Error(data.error||'共创服务暂不可用'),{code:data.code,status:r.status});return data;}
 async function command(input){if(flight)throw Error('共创操作正在确认');const old=pending();if(old&&old.requestId!==input.requestId)throw Error('上次共创操作待确认，请先核对');const body=old||{...input,requestId:crypto.randomUUID(),expectedVersion:doc.version};if(!old)localStorage.setItem(key(api.theme()),JSON.stringify(body));flight++;const theme=api.theme();try{const r=await request('action',body);if(api.theme()===theme)doc=r.document;localStorage.removeItem(key(theme));return r;}catch(e){if(e.code&&e.status<500)localStorage.removeItem(key(theme));throw e;}finally{flight--;}}
 const row=()=>doc?.packages?.[chosen],latest=()=>row()?.versions.at(-1);
 function shell(title,subtitle,body,footer=''){api.openModal(title,subtitle,body,footer);root().querySelector('.modal').classList.add('cocreation-modal');closed=false;}
 function bind(selector,fn){root().querySelectorAll(selector).forEach(b=>b.onclick=()=>fn(b));}
 function recoverMarkup(){return pending()?'<section class="co-recovery"><b>上次操作结果待确认</b><p>保留原请求核对，版本与成绩不会重复登记。</p><button class="primary" id="coRetry">核对上次操作</button></section>':'';}
 function afterShell(){bind('#coRetry',async()=>{try{const p=pending(),r=await command(p);trace=[];if(r.selection)chosen=r.selection.packageId;await open();api.toast('上次共创操作已核对');}catch(e){api.toast(e.message);}});}
 async function open(){stopPreview();view='shelf';try{const r=await request('');doc=r.document;if(chosen&&!doc.packages[chosen])chosen=null;shelf();}catch(e){shell('共创工坊','把一个小想法，变成能被别人玩懂的挑战。','<p class="co-error">'+esc(e.message)+'</p>','<button class="primary" id="coReload">重试读取</button>');bind('#coReload',open);}}
 function shelf(){
 view='shelf';const rows=Object.values(doc.packages);
 shell('共创工坊','小岛上的创作者书架 · 导入、打磨、审核与岛内试玩',
 recoverMarkup()+'<section class="co-hero"><span>HYPER DIMENSION / CO-CREATION</span><h3>留下一份，你设计的海岛体验。</h3><p>选一座建筑，写清挑战，再邀请另一位岛主试玩。审核版本、作者和练习纪录都会留在本机服务。</p><ol class="co-pipeline"><li>导入草稿</li><li>编辑挑战</li><li>提交审核</li><li>岛内试用</li><li>保留与回退</li></ol></section>'+
 (doc.trial?'<section class="co-running"><b>继续上次练习 · '+esc(doc.trial.name)+'</b><p>关卡和操作已保存在共创档案。退出页面不改关卡；明确结束才收起本局。</p><button class="primary" id="coResume">继续练习</button><button class="secondary" id="coEnd">结束本局</button></section>':'')+
 '<div class="co-section-title"><h3>作者作品</h3><button class="secondary" id="coNew">新建挑战包</button></div><div class="co-catalog">'+(rows.length?rows.map(r=>{const v=r.versions.at(-1),a=r.active&&r.versions.find(v=>v.number===r.active.version),c=coCreationChallenge((a||v).pack,(a||v).pack.challenges[0].id);return'<button class="co-card" data-co-package="'+r.id+'">'+itemMarkup(c.recipe.item,api.theme())+'<span><small>'+esc(a?'岛内启用 · v'+a.number:phases[v.phase]+' · v'+v.number)+'</small><b>'+esc((a||v).pack.title)+'</b><em>'+esc((a||v).pack.author)+' · '+(a||v).pack.challenges.length+' 项挑战</em><p>'+esc((a||v).pack.summary)+'</p></span></button>';}).join(''):'<p class="hint">从一份课程示例开始，修改标题、操作提示和难度，做出自己的第一份挑战。</p>')+'</div>'+
 '<section class="co-import"><h3>从模板开始</h3><div class="co-example-list">'+CO_CREATION_EXAMPLES.map((p,i)=>'<button class="secondary" data-co-example="'+i+'">'+esc(p.title)+' →</button>').join('')+'</div><label>导入 .hdpack.json 文件<input id="coFile" type="file" accept=".json,.hdpack.json,application/json"></label><p>每包最多6个挑战。素材随岛上建筑与关联图纸使用像素/折纸两套资源。</p></section>'+
 '<section class="co-credit"><h3>课程与练习</h3><p>150分钟做一份有主题、能完成、说明清晰并可回退的共创包。试玩记录与正式制作独立；制作物品请进入关联建筑。</p><button class="secondary" id="coCourse">查看课程路线与资料</button></section>',
 '<button class="secondary" id="coBack">返回后台</button>');
 afterShell();bind('#coBack',api.back);bind('#coNew',()=>editor(cloneExample()));bind('[data-co-example]',b=>editor(structuredClone(CO_CREATION_EXAMPLES[Number(b.dataset.coExample)])));bind('[data-co-package]',b=>{chosen=b.dataset.coPackage;details();});bind('#coCourse',course);bind('#coResume',mountPreview);bind('#coEnd',async()=>{try{await command({operation:'trial_cancel',runId:doc.trial.runId});shelf();}catch(e){api.toast(e.message);shelf();}});
 const file=root().querySelector('#coFile');file.onchange=async()=>{try{const f=file.files[0];if(!f)return;if(f.size>48000)throw Error('文件超过48KB，请使用课程模板');editor(validateCoCreationPack(JSON.parse(await f.text())));}catch(e){api.toast(e.message);}};
 }
 function cloneExample(){const p=structuredClone(CO_CREATION_EXAMPLES[0]);p.id='opc-my-island-'+Math.floor(Date.now()/1000);p.title='我的第一份海岛挑战';p.author=api.state().playerProfile.name||'岛主';return p;}
 function details(){
 view='detail';const r=row(),v=latest();if(!r)return shelf();const active=r.active&&r.versions.find(x=>x.number===r.active.version);
 shell(esc(v.pack.title),'作者 '+esc(v.pack.author)+' · '+phases[v.phase]+' · v'+v.number,
 recoverMarkup()+'<section class="co-summary"><p>'+esc(v.pack.summary)+'</p><div class="co-badges"><span>'+esc(v.pack.license)+'</span><span>'+v.pack.challenges.length+' 项挑战</span><span>'+(active?'当前岛内版本 v'+active.number:'尚未启用')+'</span></div><p>'+esc(v.pack.themeNotes[api.theme()])+'</p></section>'+
 '<section><h3>岛内试玩</h3><div class="co-challenges">'+(active||v).pack.challenges.map(c=>{const recipe=RECIPE_BY_ID[c.recipeId];return'<article class="co-challenge">'+itemMarkup(recipe.item,api.theme())+'<div><small>'+esc(BUILDINGS[recipe.building].name)+' · '+difficulty[c.difficulty]+' · 目标 '+c.minQuality+'</small><h4>'+esc(c.title)+'</h4><p>'+esc(c.brief)+'</p><button class="primary" data-co-play="'+c.id+'" '+(!active?'disabled':'')+'>岛内试玩</button><button class="secondary" data-co-recipe="'+recipe.item+'">前往正式制作</button></div></article>';}).join('')+'</div></section>'+
 '<section class="co-version-section"><h3>审核与版本</h3><p>提交后冻结内容摘要；修改审核通过的作品会另建草稿。发布和回退保留原作者与历史。</p>'+r.versions.slice().reverse().map(x=>'<article class="co-version"><div><b>v'+x.number+' · '+phases[x.phase]+(r.active?.version===x.number?' · 岛内启用':'')+'</b><code>'+x.hash.slice(0,12)+'</code><p>'+esc(x.review?.note||'尚无审核说明')+'</p></div><div>'+(['draft','changes_requested'].includes(x.phase)&&x===v?'<button class="secondary" data-co-edit="'+x.number+'">修改草稿</button>':'')+(x.phase==='draft'?'<button class="primary" data-co-submit="'+x.number+'">提交审核</button>':'')+(x.phase==='submitted'?'<button class="primary" data-co-review="'+x.number+'">查看并审核</button>':'')+(x.phase==='approved'?'<button class="primary" data-co-activate="'+x.number+'">启用此版本</button>'+(x.publishedAt&&r.active?.version!==x.number?'<button class="secondary" data-co-rollback="'+x.number+'">回退到此版本</button>':''):'')+'<button class="secondary" data-co-export="'+x.number+'">导出版本</button></div></article>').join('')+'</section>'+
 '<section><h3>本作品练习记录</h3>'+doc.results.filter(x=>x.packageId===r.id).slice(-8).reverse().map(x=>'<p class="co-result-row">v'+x.packageVersion+' · '+esc(x.challengeId)+' · '+({passed:'目标达成',practiced:'练习记录',cancelled:'已结束'})[x.outcome]+(x.result?' · 品质 '+x.result.quality:'')+'</p>').join('')+'</section>',
 '<button class="secondary" id="coShelf">返回作品书架</button><button class="primary" id="coFork">编辑下一版</button>');
 afterShell();bind('#coShelf',shelf);bind('#coFork',()=>editor(structuredClone(v.pack),r.id));bind('[data-co-edit]',()=>editor(structuredClone(v.pack),r.id));bind('[data-co-submit]',b=>transition('submit',Number(b.dataset.coSubmit)));bind('[data-co-activate]',b=>transition('activate',Number(b.dataset.coActivate)));bind('[data-co-rollback]',b=>transition('rollback',Number(b.dataset.coRollback)));bind('[data-co-review]',b=>review(Number(b.dataset.coReview)));bind('[data-co-export]',b=>exportVersion(Number(b.dataset.coExport)));bind('[data-co-play]',b=>begin(b.dataset.coPlay));bind('[data-co-recipe]',b=>api.detail(b.dataset.coRecipe));
 }
 async function transition(operation,version,note,decision){const v=row().versions.find(v=>v.number===version),page=root().querySelector('.modal');try{await command({operation,packageId:chosen,version,hash:v.hash,...(note?{note,decision}:{})});if(page.isConnected)details();api.toast({submit:'版本已提交，内容已冻结',activate:'此版本已在岛内启用',rollback:'已回退到选择的历史版本',review:'审核结果已记录'}[operation]);}catch(e){api.toast(e.message);if(page.isConnected&&pending())details();}}
 function editor(pack,id=null){
 view='editor';draft=structuredClone(pack);chosen=id;let c=draft.challenges[0],savedDraft;try{savedDraft=JSON.parse(localStorage.getItem(cacheKey())||'null')}catch{}if(savedDraft?.id===id&&savedDraft.pack?.id===pack.id){draft=savedDraft.pack;c=draft.challenges[0];}
 shell(id?'编辑共创挑战':'新建共创挑战','把标题、目标和提示写给第一次游玩的岛主。',
 recoverMarkup()+'<form id="coEditor" class="co-editor"><div class="co-fields">'+[['coId','作品编号',draft.id,70],['coTitle','作品名称',draft.title,40],['coAuthor','作者',draft.author,40]].map(([key,name,val,max])=>'<label>'+name+'<input id="'+key+'" value="'+esc(val)+'" maxlength="'+max+'" '+(key==='coId'&&id?'disabled':'')+' required></label>').join('')+'<label>内容授权<select id="coLicense">'+['CC-BY-4.0','CC0-1.0','All-Rights-Reserved'].map(v=>'<option '+(v===draft.license?'selected':'')+'>'+v+'</option>').join('')+'</select></label></div><label>作品介绍<textarea id="coSummary" maxlength="320" rows="3">'+esc(draft.summary)+'</textarea></label>'+
 '<section class="co-challenge-editor"><h3>第一项挑战</h3><label>挑战名称<input id="coChallengeTitle" maxlength="50" value="'+esc(c.title)+'"></label><label>关联建筑与图纸<select id="coRecipe">'+ALL_RECIPES.map(r=>'<option value="'+r.id+'" '+(c.recipeId===r.id?'selected':'')+'>'+esc(BUILDINGS[r.building].name+' · '+r.name)+'</option>').join('')+'</select></label><div class="co-fields"><label>关卡种子<input id="coSeed" type="number" min="1" max="4294967295" value="'+c.seed+'"></label><label>难度<select id="coDifficulty">'+[1,2,3].map(n=>'<option value="'+n+'" '+(n===c.difficulty?'selected':'')+'>'+difficulty[n]+'</option>').join('')+'</select></label><label>品质目标<input id="coQuality" type="number" min="55" max="95" value="'+c.minQuality+'"></label></div><label>挑战说明<textarea id="coBrief" rows="4" maxlength="400">'+esc(c.brief)+'</textarea></label><label>操作提示 · 每行一条<textarea id="coHints" rows="4">'+esc(c.hints.join('\n'))+'</textarea></label></section>'+
 '<details class="co-advanced"><summary>完整模板 · 多挑战与双画风说明</summary><p>可补充最多6项挑战，保留本地关联图纸。选用完整JSON时，以上表单不会覆盖它。</p><label><input id="coUseJson" type="checkbox"> 本次保存使用完整模板</label><textarea id="coJson" rows="20" spellcheck="false"></textarea></details><p id="coValidation" class="co-feedback" role="status">可以先保存草稿，再查看审核与试玩效果。</p></form>',
 '<button class="secondary" id="coDiscard">返回书架</button><button class="primary" id="coSave">校验并保存草稿</button><button class="secondary" id="coSaveSubmit">保存并提交审核</button>');
 root().querySelector('#coJson').value=JSON.stringify(draft,null,2);afterShell();
 function readPack(){if(root().querySelector('#coUseJson').checked)return validateCoCreationPack(JSON.parse(root().querySelector('#coJson').value));const v=k=>root().querySelector('#'+k).value,p=structuredClone(draft);Object.assign(p,{id:v('coId'),title:v('coTitle'),author:v('coAuthor'),summary:v('coSummary'),license:v('coLicense')});Object.assign(p.challenges[0],{title:v('coChallengeTitle'),recipeId:v('coRecipe'),seed:Number(v('coSeed')),difficulty:Number(v('coDifficulty')),minQuality:Number(v('coQuality')),brief:v('coBrief'),hints:v('coHints').split('\n').map(s=>s.trim()).filter(Boolean)});return validateCoCreationPack(p);}
 root().querySelector('#coEditor').oninput=()=>{try{localStorage.setItem(cacheKey(),JSON.stringify({id,pack:readPack()}));root().querySelector('#coValidation').textContent='编辑已在浏览器暂存，保存后写入本机共创档案。';}catch(e){root().querySelector('#coValidation').textContent=e.message;}};
 const save=async submit=>{const page=root().querySelector('.modal');try{const p=readPack(),r=await command({operation:id?'edit':'import',...(id?{packageId:id}:{}),pack:p});chosen=r.selection.packageId;localStorage.removeItem(cacheKey());if(submit){const v=latest();await command({operation:'submit',packageId:chosen,version:v.number,hash:v.hash});}if(page.isConnected)details();api.toast(submit?'草稿已保存并提交审核':'共创草稿已写入本机');}catch(e){if(page.isConnected)root().querySelector('#coValidation').textContent=e.message;api.toast(e.message);}};
 bind('#coSave',()=>save(false));bind('#coSaveSubmit',()=>save(true));bind('#coDiscard',shelf);
 }
 function review(n){const v=row().versions.find(v=>v.number===n);shell('审核 v'+n+' · '+esc(v.pack.title),'确认主题、可完成目标、提示与双画风，再决定是否启用。',
 '<dl class="co-review-facts"><dt>作者与授权</dt><dd>'+esc(v.pack.author+' · '+v.pack.license)+'</dd><dt>冻结摘要</dt><dd><code>'+v.hash+'</code></dd><dt>像素风</dt><dd>'+esc(v.pack.themeNotes.pixel)+'</dd><dt>折纸风</dt><dd>'+esc(v.pack.themeNotes.origami)+'</dd></dl><ol class="co-review-challenges">'+v.pack.challenges.map(c=>'<li><b>'+esc(c.title)+'</b><p>'+esc(BUILDINGS[RECIPE_BY_ID[c.recipeId].building].name)+' · '+difficulty[c.difficulty]+' · 品质≥'+c.minQuality+' · 种子 '+c.seed+'</p><p>'+esc(c.brief)+'</p><ul>'+c.hints.map(h=>'<li>'+esc(h)+'</li>').join('')+'</ul></li>').join('')+'</ol><label>审核说明<textarea id="coReviewNote" rows="4" minlength="4" maxlength="500" placeholder="写明可完成性、提示清晰度与需要调整的地方"></textarea></label>',
 '<button class="secondary" id="coReviewBack">返回版本</button><button class="secondary" id="coChanges">退回修改</button><button class="primary" id="coApprove">审核通过</button>');
 bind('#coReviewBack',details);bind('#coChanges',()=>transition('review',n,root().querySelector('#coReviewNote').value,'request_changes'));bind('#coApprove',()=>transition('review',n,root().querySelector('#coReviewNote').value,'approve'));
 }
 async function exportVersion(n){try{const r=await request('export/'+chosen+'/'+n),url=URL.createObjectURL(new Blob([JSON.stringify(r.pack,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=chosen+'-v'+n+'.hdpack.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);api.toast('已导出该版本，素材仍来自岛上目录');}catch(e){api.toast(e.message);}}
 async function begin(challengeId){const active=row().active,page=root().querySelector('.modal');try{const r=await command({operation:'trial_begin',packageId:chosen,version:active.version,hash:active.hash,challengeId,worldKey:api.state().saveSlot||'legacy-'+api.theme()});if(page.isConnected)mountPreview();}catch(e){api.toast(e.message);if(page.isConnected&&pending())details();}}
 async function flush(){if(!doc?.trial||flight||!trace.length)return false;engine?.setTransportPaused?.(true);const runId=doc.trial.runId,old=pending();if(old&&(old.operation!=='trial_checkpoint'||old.runId!==runId))return false;const events=old?old.events:trace.slice(0,2048);try{await command(old||{operation:'trial_checkpoint',runId,batch:doc.trial.nextBatch,events});trace.splice(0,events.length);engine?.setTransportPaused?.(false);if(!playing&&trace.length)queueMicrotask(flush);return true;}catch(e){engine?.setTransportPaused?.(true);api.toast('练习进度待核对：'+e.message);return false;}}
 function mountPreview(){
 const t=doc.trial;if(!t)return shelf();stopPreview();trace=[];shell(esc(BUILDINGS[t.building].name)+' · '+esc(t.name),'共创练习 / '+esc(t.author)+' / v'+t.packageVersion+' · 不消耗材料',
 '<section class="co-play-brief"><p>'+esc(t.brief)+'</p><b>目标品质 '+t.minQuality+' · '+difficulty[t.difficulty]+'</b><details><summary>创作者的操作提示</summary><ol>'+t.hints.map(h=>'<li>'+esc(h)+'</li>').join('')+'</ol></details></section><div id="coGameRoot"></div><p class="co-play-note">练习成绩写入本机共创档案，正式制作需在关联建筑按原配方完成。</p>',
 '<button class="secondary" id="coSuspend">收起并保留进度</button><button class="secondary" id="coCancelTrial">结束本局</button><button class="primary" id="coFinish" disabled>提交本局成绩</button>');
 root().querySelector('.modal').classList.add('game-modal');playing=true;closed=false;const r=RECIPE_BY_ID[t.recipeId];
 trace.push({neutral:true});engine=mountRoomGame(root().querySelector('#coGameRoot'),t.building,finish,{theme:api.theme(),avatar:api.state().playerProfile.avatar,standalone:true,recipe:r,mode:String(t.difficulty),level:t.game.level||{id:t.building,seed:t.seed,difficulty:t.difficulty},resumeGame:neutralCraftGame(structuredClone(t.game)),onGameEvent:e=>trace.push(e),onOutcome:()=>flush(),onExit:()=>api.closeModal(),onRestart:async()=>{await cancelTrial();chosen=t.packageId;await begin(t.challengeId);},readBest:()=>({score:0,stars:0}),writeBest:()=>{}});
 bind('#coSuspend',api.closeModal);bind('#coCancelTrial',cancelTrial);bind('#coFinish',finish);timer=setInterval(flush,5000);uiTimer=setInterval(()=>{if(!playing||!engine)return;const claim=root().querySelector('[data-action="claim"],.activity-finish');if(claim&&!claim.disabled)root().querySelector('#coFinish').disabled=false;if(claim)claim.textContent='保存共创成绩';root().querySelectorAll('[data-action="difficulty"],[data-difficulty]').forEach(b=>{b.disabled=true;b.title='此挑战使用作者审核的难度';});const note=root().querySelector('.wk-save-note');if(note)note.textContent='种子与难度由审核版本固定，可同版本重试。';for(const small of root().querySelectorAll('.wk-result-card small'))if(small.textContent.includes('成绩已保存到此浏览器'))small.textContent='确认后，成绩保存到本机共创档案。';},250);
 }
 async function finish(){if(!doc?.trial||flight)return;engine?.setTransportPaused?.(true);while(trace.length){if(!await flush())return;}try{const r=await command({operation:'trial_finish',runId:doc.trial.runId});const receipt=r.receipt;stopPreview();chosen=receipt.packageId;details();api.toast(receipt.outcome==='passed'?'共创挑战达标 · 品质 '+receipt.result.quality:'练习已记录 · 目标品质 '+receipt.target);}catch(e){api.toast(e.message);}}
 async function cancelTrial(){if(flight)return;const t=doc?.trial;if(!t)return;stopPreview(false);trace=[];try{await command({operation:'trial_cancel',runId:t.runId});chosen=t.packageId;details();api.toast('本局已结束，正式库存不受影响');}catch(e){api.toast(e.message);}}
 function stopPreview(save=true){if(stopping)return;stopping=true;clearInterval(timer);clearInterval(uiTimer);timer=uiTimer=null;if(playing){engine?.destroy();engine=null;playing=false;if(save&&trace.length){trace.push({neutral:true});if(!flight)flush();}}stopping=false;}
 function course(){view='course';shell('150分钟 · 第一次海岛共创','从一个主题，到可试玩、可追溯、可回退的作品。',
 '<section class="co-hero"><span>OPC / BUILD A SMALL EXPERIENCE</span><h3>做一份别人能玩懂的挑战。</h3><p>完成成果：一份双画风挑战包、一次审核发布、一个实际试玩成绩、一个修改版本与回退记录。</p></section><ol class="co-course-list">'+[[15,'先玩与观察','试玩岛上茶席或陶艺。记下目标、失败原因和最有帮助的一条提示。'],[20,'选主题与建草稿','从模板导入，修改作者、挑战标题和迎客故事。'],[30,'改目标与关卡','选择建筑/图纸、关卡种子、难度和品质目标。写3条能帮助新手的具体提示。'],[25,'双画风与可完成性','检查图纸素材、界面留白、说明是否符合所选建筑。导出模板并互相检查。'],[25,'提交、审核与试玩','提交冻结版本，写审核说明，启用后实际试玩并确认成绩。'],[20,'修改与回退','创建v2，改进提示或难度，审核并启用；回退到v1验证历史仍可使用。'],[15,'展示与下一次共创','展示作者书架、实际成绩与版本记录，导出作品作为课后成果。']].map(([n,t,d])=>'<li><span>'+n+'分钟</span><div><h4>'+t+'</h4><p>'+d+'</p></div></li>').join('')+'</ol><p>课程先使用岛上已有的建筑、动作与双画风资源。完整模板可包含1–6个挑战，授权只覆盖作者填写的声明式内容。</p><div class="co-course-download"><a class="secondary" href="/assets/cocreation/course-v1.md" target="_blank" rel="noopener">授课讲义与检查清单</a><a class="secondary" href="/assets/cocreation/student-workbook-v1.md" target="_blank" rel="noopener">学员练习册与环境步骤</a></div>',
 '<button class="secondary" id="coCourseBack">返回作品书架</button><button class="primary" id="coCourseStart">从茶席模板开始</button>');bind('#coCourseBack',shelf);bind('#coCourseStart',()=>editor(structuredClone(CO_CREATION_EXAMPLES[0])));}
 return{open,stopPreview,busy:()=>flight>0||playing||!!pending(),inspect:()=>({doc,chosen,flight,playing,view,trace:trace.length,game:engine?.inspect(),pending:pending()})};
}
