import {CAREERS,career,relationship,purposeOptions} from './townSimulation.js';
import {ITEM_BY_ID} from './contentCatalog.js';
// Offline dialogue is grounded in actual work and relationship records, and is labelled local.
export function groundedConversation(ids,s,profiles,type,time=0,cooperation=null){const [a,b]=ids,ra=profiles(a),rb=profiles(b),rel=relationship(s,a,b),back=relationship(s,b,a),ca=career(a,s),cb=career(b,s),pa=purposeOptions(a,s,ra,time).find(x=>x.purposeId.startsWith('career:')),pb=purposeOptions(b,s,rb,time).find(x=>x.purposeId.startsWith('career:'));let lines=[],summary='',changes=[],emotions=[{id:a,mood:'平静'},{id:b,mood:'平静'}];
 const say=(speaker,text)=>lines.push({speaker,text});const update=(from,to,affinity,trust,tension=0,affection=0)=>changes.push({from,to,affinity,trust,tension,affection});
 if(type==='reconcile'&&rel.tension>12){const success=rel.affinity>-12;say(a,'上次的分歧还让我有些在意。我想听听你的打算。');say(b,success?'我们可以先把具体分工说清楚，各自保留想法。':'我现在还不能接受这个安排，想先把自己的工作做好。');say(a,success?'好，先做一件能一起核对结果的小事。':'那就先留点空间，等我们都想清楚再谈。');say(b,success?'可以，准备好了再核对物资。':'谢谢你理解，我需要一点时间。');update(a,b,success?2:0,success?1:0,success?-3:1);update(b,a,success?1:0,success?1:0,success?-2:0);summary=success?'谈清分工，分歧稍有缓和':'暂未和解，双方保留空间';emotions=ids.map(id=>({id,mood:success?'放松':'委屈'}));
 }else if(type==='confession'&&rel.affection>12&&rel.trust>8){const reciprocal=back.affection>12||back.affinity>18;say(a,'一起做事时我很安心，也想多了解工作之外的你。');say(b,reciprocal?'我也期待这样的相处，我们可以慢慢来。':'谢谢你说出来。我想先从更熟悉的朋友开始。');say(a,'好，你的感受和节奏也很重要。');say(b,'我们下次再聊聊各自喜欢的岛上生活。');update(a,b,1,1,0,1);update(b,a,1,1,0,reciprocal?2:0);summary=reciprocal?'表达亲近，双方愿意慢慢了解':'表达心意，对方希望先做朋友';emotions=[{id:a,mood:'心动'},{id:b,mood:reciprocal?'心动':'平静'}];
 }else if(type==='dispute'&&(rel.affinity<0||rel.tension>0)){say(a,'我们对安排还有不同意见，我需要你听听我的顾虑。');say(b,'我也想保留自己的判断，先说明各自需要什么。');say(a,pa?.resource?'我眼下需要'+ITEM_BY_ID[pa.resource].name+'，不想答应超出准备能力的事。':'我想按自己的工作步骤来完成。');say(b,'今天先各自准备，之后带着结果再讨论。');update(a,b,-1,0,2);update(b,a,0,0,1);summary='工作安排仍有分歧，暂时各自准备';emotions=ids.map(id=>({id,mood:'不满'}));
 }else if(type==='negotiate'&&cooperation?.plans){const ap=cooperation.plans[a],bp=cooperation.plans[b],an=ITEM_BY_ID[ap.resource].name,bn=ITEM_BY_ID[bp.resource].name;
 say(a,(cooperation.demand?'「'+cooperation.demand.name+'」还需要准备。':'我们按各自工作互相帮忙。')+'我来准备'+an+'。');
 say(b,'我的工作适合准备'+bn+'，这部分交给我。');say(a,'实际入库后再核对进度；如果物资已经备齐，就不重复做了。');say(b,'好，先完成手上的分工，做完再告诉你。');
 update(a,b,1,1);update(b,a,1,1);summary=(cooperation.demand?'为「'+cooperation.demand.name+'」':'按职业')+'商定分工：'+ra.name+'准备'+an+'，'+rb.name+'准备'+bn;
 }else if(type==='negotiate'&&pa?.resource){const raw=ITEM_BY_ID[pa.resource].name,available=s.inventory[pa.resource]||0;say(a,'我接下来需要'+raw+'，库存现在是 '+available+' 份，想核对一下分工。');say(b,'我正在处理'+CAREERS[b].title+'，不能立刻承诺交付。');say(a,'那先各自收集，完成后再确认能分出多少。');say(b,'可以，先看真实结果，再决定合作安排。');update(a,b,1,1,available===0?1:0);update(b,a,1,1);summary=available===0?'物资不足，核对分工并保留交付边界':'核对物资，约定按结果讨论协作';
 }else{type='friendship';say(a,ca.history.length?'我刚完成'+ca.history.at(-1).result+'。':'我正打算做'+CAREERS[a].title+'。');say(b,cb.history.length?'我这边刚完成'+cb.history.at(-1).result+'。':'我在准备'+CAREERS[b].title+'，还需要一点时间。');say(a,'听起来各有要忙的事，你最想保留哪部分自己的想法？');say(b,rb.personality.includes('安静')||rb.personality.includes('沉静')?'我喜欢先自己整理清楚，再给你看具体结果。':'我想试试自己的方案，也愿意听你的具体意见。');update(a,b,1,1);update(b,a,1,1);summary='交换真实工作进度，了解彼此的做事方式';emotions=ids.map(id=>({id,mood:'放松'}));}
 return {type,lines,summary,changes,emotions,source:'local'};}
