import {hudIllustration} from './uiArt.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function createDeviceBridgeUI({context,toast=()=>{}}){
 let panel=null,view=null,pair=null,timer=null,busy=false,returnFocus=null,signature='';
 async function api(operation='',data){const c=context();if(!c)throw Error('请先登录自己的小岛');const r=await fetch('/api/lan/bridge'+operation,{method:data?'POST':'GET',cache:'no-store',headers:{'X-HD-Island':c.id,...(data?{'Content-Type':'application/json'}:{})},body:data?JSON.stringify(data):undefined,signal:AbortSignal.timeout(12000)});const v=await r.json();if(!r.ok)throw Error(v.error||'原机配对暂时不可用');return v;}
 function paint(){if(!panel||!view)return;const key=JSON.stringify({view,pair});if(key===signature)return;signature=key;const body=panel.querySelector('.device-bridge-body'),scroll=body.scrollTop;
  const bound=view.bound,command=pair?'node tools/steward-bridge.mjs --server="'+location.origin+'" --workspace="你的工作区路径" --pair-code='+pair.code+' --state-dir="data/device-clients/connection-'+pair.code.slice(-8)+'"'+(location.protocol==='http:'&&!['127.0.0.1','localhost','[::1]'].includes(location.hostname)?' --allow-insecure-lan':''):'';
  body.innerHTML='<div class="device-intro"><small>MY STEWARD · MY WORKSPACE</small><h3>换一座岛，也能继续处理自己的事情。</h3><p>连接你自己的电脑后，管家在那里读取和修改选定文件夹里的资料；随行上岛时也可以继续工作、与其他管家交流。</p></div>'+(bound?'<section class="device-bound"><div><span class="device-presence '+(bound.online?'online':'offline')+'"></span><strong>'+esc(bound.name)+'</strong><small>'+esc(bound.platform)+' · '+(bound.online?'在线':'离线')+'</small></div><p>'+esc(bound.workspace)+'</p><p class="device-note">'+(bound.online?'新的管家委托会在这台原机执行。':'当前原机离线，文档委托暂停；重新运行连接端后恢复。')+'</p><button class="secondary" data-device-revoke="'+esc(bound.id)+'">解绑这台原机</button></section>':'<section class="device-empty"><b>还没有连接原机</b><p>当前管家使用岛屿服务的账号工作区。连接原机后改用你选定的真实文件夹。</p></section>')+'<section class="device-pair"><h3>配对你的电脑</h3><ol><li>在这里生成一次性配对码。</li><li>在原机的 Hyper Dimension 源码目录运行连接命令，并填写工作区路径。</li><li>核对两端显示的六位标记，再确认连接。</li></ol><button class="primary" id="devicePairBegin">'+(pair?'重新生成配对码':'生成配对码')+'</button>'+(pair?'<div class="device-pair-code"><small>十分钟内有效 · 只用于这次配对</small><strong>'+esc(pair.code)+'</strong><label for="devicePairCommand">复制到原机终端，替换工作区路径</label><textarea readonly id="devicePairCommand" rows="4">'+esc(command)+'</textarea><button class="secondary" id="devicePairCopy">复制命令</button><p>Windows 和 macOS 都使用同一命令。后续重新运行时不再填写配对码；保留原机连接状态目录。</p></div>':'')+'</section>'+view.pending.map(d=>'<section class="device-pending"><small>等待你的确认</small><h3>'+esc(d.name)+'</h3><p>'+esc(d.platform)+'<br>'+esc(d.workspace)+'</p><div class="device-verification"><span>原机显示的六位标记</span><strong>'+esc(d.verification)+'</strong></div><button class="primary" data-device-approve="'+esc(d.id)+'" data-verification="'+esc(d.verification)+'">标记一致，连接原机</button><button class="secondary" data-device-revoke="'+esc(d.id)+'">取消这次配对</button></section>').join('')+'<p class="device-note">在原机选定的工作区内执行。私人委托与文件成果只出现在自己的管家手账；对方管家交流使用岛屿见闻。</p>';
  body.scrollTop=scroll;body.querySelector('#devicePairBegin').onclick=()=>change('/pair',{});body.querySelectorAll('[data-device-approve]').forEach(b=>b.onclick=()=>change('/approve',{deviceId:b.dataset.deviceApprove,verification:b.dataset.verification}));body.querySelectorAll('[data-device-revoke]').forEach(b=>b.onclick=()=>change('/revoke',{deviceId:b.dataset.deviceRevoke}));
  const copy=body.querySelector('#devicePairCopy');if(copy)copy.onclick=async()=>{try{await navigator.clipboard.writeText(command);toast('连接命令已复制，请填写原机工作区路径');}catch{body.querySelector('textarea').select();toast('请复制已选中的命令');}};
 }
 async function refresh(){const current=panel;if(!current)return;try{const next=await api();if(panel!==current)return;view=next;if(pair&&pair.expiresAt<Date.now())pair=null;paint();if(panel.querySelector('#deviceBridgeMessage').textContent==='正在查看原机连接…')panel.querySelector('#deviceBridgeMessage').textContent=next.bound?(next.bound.online?'原机在线，管家可以继续工作。':'原机离线，重新运行连接端后恢复。'):'请选择你的原机工作区并完成配对。';}catch(e){if(panel===current)panel.querySelector('#deviceBridgeMessage').textContent=e.message;}}
 async function change(op,input){if(busy)return;busy=true;panel?.querySelectorAll('.device-bridge-body button').forEach(b=>b.disabled=true);const current=panel;try{const result=await api(op,input);if(panel!==current)return;if(op==='/pair')pair=result;else{view=result;if(op==='/approve')pair=null;}signature='';await refresh();panel.querySelector('#deviceBridgeMessage').textContent=op==='/approve'?'原机已连接，管家将使用这台电脑的工作区。':op==='/revoke'?'原机已解绑；进行中的操作请在原机核对成果。':'配对码已生成。';}catch(e){if(panel===current)panel.querySelector('#deviceBridgeMessage').textContent=e.message;}finally{busy=false;if(panel===current)panel.querySelectorAll('.device-bridge-body button').forEach(b=>b.disabled=false);}}
 function close(){if(busy){toast('正在登记配对，请稍候');return;}clearInterval(timer);panel?.remove();panel=null;returnFocus?.focus();}
 async function open(){if(panel)return;const c=context();if(!c)return;returnFocus=document.activeElement;signature='';view=null;const theme=document.body.dataset.theme||c.profile.theme;panel=document.createElement('div');panel.className='personal-steward-overlay device-bridge-overlay';panel.dataset.theme=theme;panel.innerHTML='<section class="personal-steward-panel device-bridge-panel" role="dialog" aria-modal="true" aria-label="连接我的原机"><header>'+hudIllustration('steward',theme)+'<div><small>ORIGINAL DEVICE</small><h2>连接我的原机</h2></div><button id="deviceBridgeClose" aria-label="关闭原机配对">×</button></header><div class="device-bridge-body"></div><footer id="deviceBridgeMessage" role="status">正在查看原机连接…</footer></section>';document.body.append(panel);panel.querySelector('#deviceBridgeClose').onclick=close;panel.addEventListener('keydown',e=>{if(e.key==='Escape'){e.stopPropagation();close();}});panel.querySelector('#deviceBridgeClose').focus();await refresh();if(panel)timer=setInterval(refresh,3000);}
 return {open,close,clear(){busy=false;pair=null;view=null;close();}};
}
