import {applyFireworksEvent,currentFireworksAct,fireworksSummary,fireworksWind,fireworksBurst,FIREWORKS_COLORS,FIREWORKS_SHAPES,FIREWORKS_LANES} from './fireworksRules.js';
import {itemMarkup,drawItem} from './artStore.js';import {drawAnimatedCharacter} from './characters.js';import {esc} from './journeyUI.js';
const laneNames=['左岸','中央','右岸'],glyphs={bloom:'✺',star:'✦',willow:'⌁'};
export function mountFireworks(root,ticket,controls,{theme,profile,portrait,ready,participants=[1,3,12],present=()=>true,sound=()=>{}}){
 const game=structuredClone(ticket.game);let ended=false,paused=false,transport=false,selected=0,last=0,frame=0,configKey='',reportKey='',effect=0,quitting=false,aimAt=0,lastPhase='';const bursts=new Set();
 const color=id=>FIREWORKS_COLORS.find(c=>c.id===id),shape=id=>FIREWORKS_SHAPES.find(c=>c.id===id),q=id=>root.querySelector('#'+id),text=(el,s)=>{if(el.textContent!==s)el.textContent=s;},locked=()=>paused||transport,emit=e=>{applyFireworksEvent(game,e);controls.trace(e);};
 root.innerHTML='<section class="fireworks-play" data-theme="'+theme+'"><header class="fireworks-scoreboard"><div><small>STAR TIDE / A NIGHT WE MADE TOGETHER</small><h3>把海风写成烟花，把今晚留给彼此</h3><p id="fireworksStatus" role="status"></p></div><div class="fireworks-badges"><span>幕次 <b id="fireworksRound">1 / 3</b></span><span>烟花 <b id="fireworksStock">6枚留用</b></span><span>合拍 <b id="fireworksHits">0 / 6</b></span></div></header>'+
 '<div class="fireworks-main"><section class="fireworks-scenery"><canvas id="fireworksCanvas" aria-label="根据海风瞄准星圈，真实轨迹烟花与三位协作居民"></canvas><div class="fireworks-stage-caption"><strong id="fireworksAct"></strong><span id="fireworksWind"></span></div><div class="fireworks-timeline" id="fireworksTimeline"></div><div class="fireworks-launch-controls"><button class="primary" id="fireworksLaunch0">'+itemMarkup('firework',theme,'fireworks-button-art')+'<span>发射第一枚</span><kbd>1</kbd></button><button class="primary" id="fireworksLaunch1">'+itemMarkup('firework',theme,'fireworks-button-art')+'<span>发射第二枚</span><kbd>2</kbd></button></div><p class="fireworks-feedback" id="fireworksFeedback">先看本幕约定，选择颜色、形状与发射位。拖动星空瞄准，留意海风会把烟花带向哪边。</p></section>'+
 '<aside class="fireworks-console"><div class="fireworks-act-letter" id="fireworksBrief"></div><div id="fireworksConfigs"></div><div class="fireworks-clock"><span id="fireworksClock">等待大家赴约</span><b id="fireworksPhase"></b></div><div class="fireworks-advance"><button class="primary" id="fireworksStart">大家到齐后开始</button><button class="primary hidden" id="fireworksSubmit">编排完成 · 开始本幕</button></div><details class="fireworks-help"><summary>操作说明 · 风向与节拍</summary><p>点选要调整的烟花，拖动星空瞄准，也可用方向键微调。星圈是最终绽放位置；提前发射，让飞行时间结束在亮拍。每枚只能发射一次。</p></details></aside></div>'+
 '<section class="fireworks-reports" id="fireworksReports"></section><section class="fireworks-results hidden" id="fireworksResults"></section><footer class="fireworks-controls"><button class="primary hidden" id="fireworksClaim">领取收益 · 归还未发射烟花</button><button class="secondary" id="fireworksPause">暂停本场</button><button class="secondary" id="fireworksCancel">结束本场 · 归还余下烟花</button></footer></section>';
 const canvas=q('fireworksCanvas'),ctx=canvas.getContext('2d'),density=Math.min(2,devicePixelRatio||1);canvas.width=960*density;canvas.height=540*density;
 const family=getComputedStyle(root).fontFamily;
 const actors=participants.map((id,i)=>({x:[300,380,590,665][i]??(300+i*80),y:519,npcId:id,direction:-Math.PI/2,phase:0,walkMix:0})),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
 function polygon(points,fill){ctx.fillStyle=fill;ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.fill();}
 function point(x,y,size,fill,alpha=1){ctx.globalAlpha=alpha;ctx.fillStyle=fill;if(theme==='pixel')ctx.fillRect(Math.round(x-size/2),Math.round(y-size/2),Math.ceil(size),Math.ceil(size));else{ctx.beginPath();ctx.moveTo(x,y-size);ctx.lineTo(x+size*.72,y);ctx.lineTo(x,y+size);ctx.lineTo(x-size*.72,y);ctx.closePath();ctx.fill();}ctx.globalAlpha=1;}
 function draw(ts){
  const time=ts/1000,act=currentFireworksAct(game);ctx.setTransform(density,0,0,density,0,0);ctx.clearRect(0,0,960,540);ctx.imageSmoothingEnabled=theme!=='pixel';
  const sky=ctx.createLinearGradient(0,0,0,540);sky.addColorStop(0,'#0c283b');sky.addColorStop(.65,theme==='pixel'?'#20505e':'#355968');sky.addColorStop(1,'#163d49');ctx.fillStyle=sky;ctx.fillRect(0,0,960,540);
  if(theme==='origami'){polygon([[0,0],[480,0],[960,350],[0,180]],'rgba(180,223,224,.045)');polygon([[960,0],[610,0],[320,360],[960,200]],'rgba(239,224,185,.035)');}
  for(let i=0;i<75;i++){const x=(i*137+31)%960,y=20+(i*67)%312,alpha=.18+.42*(.5+.5*Math.sin(time*.8+i*1.7));point(x,y,i%11===0?2.1:1.3,'#edf7e9',alpha);}
  ctx.fillStyle='#d9e9d6';ctx.beginPath();ctx.arc(838,77,23,0,Math.PI*2);ctx.fill();ctx.fillStyle='#153647';ctx.beginPath();ctx.arc(845,72,21,0,Math.PI*2);ctx.fill();
  for(let band=0;band<3;band++){const x=((time*(3+band)+band*310)%1210)-180,y=115+band*48;polygon([[x,y],[x+58,y-10],[x+151,y-7],[x+212,y],[x+155,y+8],[x+25,y+7]],'rgba(185,214,219,.035)');}
  ctx.fillStyle='#123d4b';ctx.fillRect(0,365,960,175);for(let y=375;y<486;y+=12)for(let i=0;i<8;i++){ctx.fillStyle='rgba(140,203,195,'+(.045+.04*Math.sin(time+y*.07+i))+')';ctx.fillRect(((i*151+y*3+time*10)%1050)-50,y,24+(i%3)*18,theme==='pixel'?2:1);}
  polygon([[0,460],[112,423],[198,441],[246,465],[332,451],[415,470],[522,462],[671,470],[800,438],[877,440],[960,467],[960,540],[0,540]],theme==='pixel'?'#172f39':'#23404a');
  polygon([[0,481],[175,454],[358,483],[570,482],[850,453],[960,481],[960,540],[0,540]],theme==='pixel'?'#23504c':'#395950');
  if(theme==='origami')polygon([[175,454],[358,483],[0,540],[0,481]],'#2c4948');
  const effectiveClock=['review','intermission','results'].includes(game.phase)?12+(game.phase==='review'?game.clock:3.2):game.clock;
  const glow=game.phase!=='arming'&&game.phase!=='checkin'&&game.shots.some(s=>s.round===game.round&&effectiveClock>=s.burstAt&&effectiveClock-s.burstAt<1.2);
  for(const a of actors){if(!present(a.npcId))continue;a.action={type:glow?'celebrate':'observe',t:(time+a.npcId*.1)%1.8,duration:1.8};drawAnimatedCharacter(ctx,a,theme,profile(a.npcId).color,true,time,.65);}
  for(let lane=0;lane<3;lane++){const x=FIREWORKS_LANES[lane]*960;polygon([[x-32,509],[x,496],[x+32,509],[x,522]],'#35554e');ctx.fillStyle='#c5a571';ctx.fillRect(x-18,492,36,6);ctx.fillStyle='#203d41';ctx.fillRect(x-14,498,5,17);ctx.fillRect(x+9,498,5,17);ctx.fillStyle='#71959a';ctx.fillRect(x-6,475,12,19);drawItem(ctx,'firework',theme,x,475,31,-.10);}
  const aim=game.configs[selected],unfired=!game.shots.some(s=>s.round===game.round&&s.index===selected);
  if(['arming','performing'].includes(game.phase)){
   for(const t of act.targets){const x=t.x*960,y=t.y*540,shot=game.shots.find(s=>s.round===game.round&&s.index===t.index),lit=game.phase==='performing'&&Math.abs(game.clock-t.at)<=act.window;ctx.strokeStyle=color(t.color).color;ctx.globalAlpha=lit?.9:.28;ctx.lineWidth=lit?3:1;ctx.setLineDash(theme==='pixel'?[4,4]:[3,7]);ctx.beginPath();ctx.ellipse(x,y,act.radius*960,act.radius*540,0,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.globalAlpha=1;ctx.fillStyle=color(t.color).color;ctx.font='600 15px '+family;ctx.textAlign='center';ctx.fillText((t.index+1)+' · '+shape(t.shape).name,x,y-act.radius*540-14);if(shot&&game.clock>=shot.burstAt)ctx.fillText(shot.hit?'合拍命中':'再接再厉',x,y+act.radius*540+18);}
   if(aim&&unfired){const p=fireworksBurst(game,aim,game.clock),x=aim.x*960,y=aim.y*540,end={x:p.x*960,y:p.y*540};ctx.strokeStyle='#f5e6b1';ctx.lineWidth=1;ctx.setLineDash([3,5]);ctx.beginPath();ctx.moveTo(FIREWORKS_LANES[aim.lane]*960,490);ctx.quadraticCurveTo((FIREWORKS_LANES[aim.lane]*960+x)/2,y+90,end.x,end.y);ctx.stroke();ctx.setLineDash([]);ctx.strokeStyle='#f7eed6';ctx.beginPath();ctx.moveTo(x-11,y);ctx.lineTo(x+11,y);ctx.moveTo(x,y-11);ctx.lineTo(x,y+11);ctx.stroke();point(end.x,end.y,4,'#ffe6a5',.8);}
  }
  for(const shot of game.shots.filter(s=>s.round===game.round)){const t=act.targets[shot.index],age=effectiveClock-shot.at,col=color(shot.config.color).color;
   if(age>=0&&age<t.flight){for(let tail=12;tail>=0;tail--){const q0=clamp((age-tail*.025)/t.flight,0,1),x=(FIREWORKS_LANES[shot.config.lane]+(shot.point.x-FIREWORKS_LANES[shot.config.lane])*q0)*960,y=(.87+(shot.point.y-.87)*q0-Math.sin(q0*Math.PI)*.03)*540;point(x,y,tail?2.4:4.3,tail?'#efd49a':'#fff1d1',1-tail/15);}}
   const burstAge=effectiveClock-shot.burstAt;if(burstAge<0||burstAge>2.9)continue;
   const key=shot.round+':'+shot.index;if(!bursts.has(key)){bursts.add(key);sound('firework');}
   const radius=75*(1-Math.exp(-burstAge*2.1)),fade=clamp(1-burstAge/2.9,0,1);
   for(let i=0;i<72;i++){let angle=i/72*Math.PI*2,speed=1;if(shot.config.shape==='star')speed=.42+.58*Math.abs(Math.cos(angle*2.5));else if(shot.config.shape==='willow')speed=.65+.25*Math.sin(i*2.6);else speed=.7+.3*Math.sin(i*2.3)**2;
    const x=shot.point.x*960+Math.cos(angle)*radius*speed,y=shot.point.y*540+Math.sin(angle)*radius*speed+(shot.config.shape==='willow'?burstAge*burstAge*20:burstAge*burstAge*7),alpha=fade*(.55+.45*Math.sin(i*3.1+burstAge*6)**2);
    point(x,y,theme==='pixel'?2+i%3:2.2+(i%4)*.55,i%7===0?'#fff2c8':col,alpha);
    if(shot.config.shape==='willow'&&burstAge>.25){ctx.strokeStyle=col;ctx.globalAlpha=alpha*.45;ctx.lineWidth=theme==='pixel'?1.5:1;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-3*Math.cos(angle),y-10-burstAge*7);ctx.stroke();ctx.globalAlpha=1;}
   }
   point(shot.point.x*960,shot.point.y*540,Math.max(0,15*(1-burstAge/.35)),'#fff4df',clamp(1-burstAge/.35,0,1));
   for(let ripple=0;ripple<4;ripple++){ctx.globalAlpha=fade*.18;ctx.fillStyle=col;ctx.fillRect(shot.point.x*960-40-ripple*10,383+ripple*11+Math.sin(time*2+ripple)*2,80+ripple*20,2);ctx.globalAlpha=1;}
  }
 }
 function paint(){
  const a=currentFireworksAct(game),summary=fireworksSummary(game),starting=['checkin','intermission'].includes(game.phase),arming=game.phase==='arming',playing=game.phase==='performing',finished=game.phase==='results';
  const play=root.querySelector('.fireworks-play');play.dataset.phase=game.phase;if(lastPhase!==game.phase){lastPhase=game.phase;root.closest('.modal-body')?.scrollTo({top:0});}
  text(q('fireworksStatus'),transport?(arming?'正在记录 · 编排和瞄准仍可调整':'正在记录 · 本幕计时暂停，海风与星空继续'):paused?'本场已暂停，烟花和演出进度保留':game.status);text(q('fireworksRound'),(game.round+1)+' / 3');text(q('fireworksStock'),(6-game.shots.length)+'枚未发射');
  const hits=game.shots.filter(s=>s.hit&&(s.round<game.round||!playing||game.clock>=s.burstAt)).length;text(q('fireworksHits'),hits+' / 6');text(q('fireworksAct'),a.name);const wind=fireworksWind(game);text(q('fireworksWind'),(wind<0?'← 向左':'向右 →')+' · '+(Math.abs(wind)<.013?'轻风':'阵风'));
  text(q('fireworksClock'),arming?'编排剩余 '+Math.max(0,60-game.clock).toFixed(0)+'秒':playing?'演出 '+game.clock.toFixed(1)+' / 12秒':game.phase==='review'?'伙伴回看这一幕':finished?'三幕已完成':'等待伙伴实际赴约');text(q('fireworksPhase'),transport?'记录本场进度':paused?'暂停中':arming?'编排':playing?'演出':'');
  const ck=JSON.stringify([game.round,game.configs.map(c=>c?[c.lane,c.color,c.shape]:null),selected,game.shots.length,game.phase]);if(ck!==configKey){
   configKey=ck;q('fireworksBrief').innerHTML='<small>ACT '+(game.round+1)+' / '+esc(a.name)+'</small>'+a.targets.map(t=>'<p><b>第'+(t.index+1)+'枚</b> · '+laneNames[t.lane]+' · <span style="color:'+color(t.color).color+'">'+color(t.color).name+'</span> · '+shape(t.shape).name+'<small>绽放 '+t.at.toFixed(1)+'秒 · 飞行'+t.flight.toFixed(1)+'秒</small></p>').join('');
   q('fireworksConfigs').innerHTML=game.configs.map((c,i)=>{const fired=game.shots.some(s=>s.round===game.round&&s.index===i);return'<article class="fireworks-shell '+(selected===i?'selected':'')+'"><button class="fireworks-shell-title" data-fireworks-select="'+i+'">'+itemMarkup('firework',theme,'fireworks-shell-art')+'<strong>第'+(i+1)+'枚</strong><span>'+ (fired?'已发射':selected===i?'正在瞄准':'点击调整')+'</span></button><div class="fireworks-choices">'+FIREWORKS_COLORS.map(k=>'<button data-fireworks-config="'+i+'|color:'+k.id+'" aria-pressed="'+(c?.color===k.id)+'"><i class="fireworks-color-chip" style="--shell-color:'+k.color+'"></i>'+k.name+'</button>').join('')+'</div><div class="fireworks-choices">'+FIREWORKS_SHAPES.map(k=>'<button data-fireworks-config="'+i+'|shape:'+k.id+'" aria-pressed="'+(c?.shape===k.id)+'"><i class="fireworks-shape-glyph">'+glyphs[k.id]+'</i>'+k.name+'</button>').join('')+'</div><div class="fireworks-choices">'+laneNames.map((k,j)=>'<button data-fireworks-config="'+i+'|lane:'+j+'" aria-pressed="'+(c?.lane===j)+'">'+k+'</button>').join('')+'</div></article>';}).join('');
   q('fireworksTimeline').innerHTML='<div class="fireworks-timeline-track"><i id="fireworksPlayhead"></i>'+a.targets.map(t=>'<span class="fireworks-beat" data-fireworks-beat="'+t.index+'" style="left:'+(t.at/12*100)+'%;width:'+(a.window*2/12*100)+'%"><b>'+ (t.index+1)+'</b></span>').join('')+'</div><small>提前发射，让绽放落在亮拍</small>';
  }
  q('fireworksPlayhead').style.left=(playing?Math.min(100,game.clock/12*100):game.phase==='review'||finished?100:0)+'%';
  root.querySelectorAll('[data-fireworks-config]').forEach(b=>b.disabled=paused||!arming);root.querySelectorAll('[data-fireworks-select]').forEach(b=>{const i=Number(b.dataset.fireworksSelect);b.disabled=paused||(transport&&!arming)||!['arming','performing'].includes(game.phase)||game.shots.some(s=>s.round===game.round&&s.index===i);});
  for(let i=0;i<2;i++){const fired=game.shots.some(s=>s.round===game.round&&s.index===i);q('fireworksLaunch'+i).disabled=locked()||!playing||fired||game.clock>9.5||!ready();q('fireworksLaunch'+i).classList.toggle('fired',fired);root.querySelector('[data-fireworks-beat="'+i+'"]')?.classList.toggle('lit',playing&&Math.abs(game.clock-a.targets[i].at)<=a.window);}
  q('fireworksStart').classList.toggle('hidden',!starting);q('fireworksStart').disabled=locked()||!ready();text(q('fireworksStart'),!ready()?'等伙伴实际到齐':game.phase==='checkin'?'大家已到齐 · 编排第一幕':'编排下一幕');
  q('fireworksSubmit').classList.toggle('hidden',!arming);q('fireworksSubmit').disabled=locked()||!ready()||!game.configs.every(Boolean)||game.configs[0]?.lane===game.configs[1]?.lane;
  const rk=JSON.stringify(game.reports);if(rk!==reportKey){reportKey=rk;q('fireworksReports').innerHTML=game.reports.map(r=>'<article><small>'+esc(game.level.rounds[r.index].name)+'</small><strong>'+r.quality+'<em> / 100</em></strong><p>实际发射 '+r.fired+'/2 · 合拍命中 '+r.hits+'/2</p></article>').join('');}
  q('fireworksResults').classList.toggle('hidden',!finished);if(finished&&!q('fireworksResults').childElementCount)q('fireworksResults').innerHTML='<img src="/assets/fireworks-orbit-'+theme+'-v90.png" alt="SR星潮留影灯"/><div><small>A NIGHT TO KEEP</small><h3>'+ (summary.passed?'六朵星光，把今晚留给了彼此':'收好这一次的烟花编排')+'</h3><p>品质 '+summary.quality+'/100 · 合拍命中 '+summary.hits+'/6 · 收益 '+summary.reward+'岛币</p><p>实际发射 '+summary.fired+'枚，归还 '+(6-summary.fired)+'枚与海风旗。</p><p>'+ (summary.passed?'本场达到SR星潮留影灯条件，到收藏册陈列于烟花工坊庭院。':'六枚全发射、至少五枚合拍命中且品质75分可得稀有纪念品；实际品质收益仍会结算。')+'</p></div>';
  q('fireworksClaim').classList.toggle('hidden',!finished);q('fireworksClaim').disabled=transport;q('fireworksCancel').disabled=transport;q('fireworksPause').classList.toggle('hidden',finished);text(q('fireworksPause'),paused?'继续本场':'暂停本场');
  if(game.effect?.id!==effect){effect=game.effect?.id||0;if(game.effect?.type==='launch')sound('trail');if(game.effect?.type==='result')sound('victory');}
 }
 function configure(i,item){if(paused||game.phase!=='arming')return;emit({action:{type:'configure',index:i,item}});selected=i;paint();}
 function launch(i){if(locked()||game.phase!=='performing'||!ready())return;emit({action:{type:'launch',index:i}});selected=1-i;controls.saveOutcome();paint();}
 root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.fireworksConfig){const [i,item]=b.dataset.fireworksConfig.split('|');configure(Number(i),item);}else if(b.dataset.fireworksSelect!==undefined){selected=Number(b.dataset.fireworksSelect);paint();}});
 q('fireworksStart').onclick=()=>{if(locked()||!ready())return;emit({action:{type:'start'}});for(let i=0;i<2;i++)emit({action:{type:'configure',index:i,item:'lane:'+(i*2)}});selected=0;controls.saveOutcome();paint();};
 q('fireworksSubmit').onclick=()=>{if(locked()||game.phase!=='arming'||!ready())return;emit({action:{type:'submit'}});controls.saveOutcome();paint();};
 for(let i=0;i<2;i++)q('fireworksLaunch'+i).onclick=()=>launch(i);
 q('fireworksPause').onclick=()=>{paused=!paused;last=0;controls.saveOutcome();paint();};q('fireworksClaim').onclick=()=>{if(!transport&&game.phase==='results')controls.claim();};
 q('fireworksCancel').onclick=()=>{if(transport)return;if(!quitting){quitting=true;paused=true;controls.saveOutcome();text(q('fireworksCancel'),'确认结束 · 只归还未发射烟花');paint();return;}controls.exit();};
 function aim(x,y){if(paused||(transport&&game.phase!=='arming')||!['arming','performing'].includes(game.phase)||!game.configs[selected]||game.shots.some(s=>s.round===game.round&&s.index===selected))return;emit({action:{type:'aim',index:selected,x:clamp(x,.08,.92),y:clamp(y,.16,.56)}});paint();}
 function pointer(e){const r=canvas.getBoundingClientRect();aim((e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height);}
 canvas.onpointerdown=e=>{canvas.setPointerCapture(e.pointerId);pointer(e);};canvas.onpointermove=e=>{if(e.buttons&&performance.now()-aimAt>60){aimAt=performance.now();pointer(e);}};canvas.onpointerup=e=>{pointer(e);canvas.releasePointerCapture(e.pointerId);};
 function pause(){paused=true;last=0;controls.saveOutcome();paint();}
 const visibility=()=>{if(document.hidden)pause();},key=e=>{if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)||e.repeat)return;if(['1','2',' '].includes(e.key)){e.preventDefault();launch(e.key===' '?selected:Number(e.key)-1);}else if(e.key.startsWith('Arrow')){e.preventDefault();const c=game.configs[selected];if(c){const step=e.shiftKey?.018:.006;aim(c.x+(e.key==='ArrowLeft'?-step:e.key==='ArrowRight'?step:0),c.y+(e.key==='ArrowUp'?-step:e.key==='ArrowDown'?step:0));}}};
 window.addEventListener('blur',pause);document.addEventListener('visibilitychange',visibility);window.addEventListener('keydown',key);
 function tick(ts){if(ended)return;const dt=last?Math.min(.05,Math.max(0,(ts-last)/1000)):0;last=ts;if(dt&&!paused&&!transport&&['arming','performing','review'].includes(game.phase))emit({dt});paint();draw(ts);frame=requestAnimationFrame(tick);}
 paint();frame=requestAnimationFrame(tick);
 return{inspect:()=>({kind:'fireworks-party',game,paused,transport,selected,stagePeople:actors.map(a=>({npcId:a.npcId,x:a.x,y:a.y,action:a.action?.type}))}),setTransportPaused(v){transport=v;last=0;paint();},destroy(){if(ended)return;ended=true;cancelAnimationFrame(frame);window.removeEventListener('blur',pause);document.removeEventListener('visibilitychange',visibility);window.removeEventListener('keydown',key);controls.saveOutcome();}};
}
