import {lanWonderMarkup} from './lanWonderUI.js';
import {lanEconomyForm,updateLanEconomyPreview,lanEconomyCard} from './lanEconomyUI.js';
import {neutralCraftGame} from './craftGameReplay.js';import {mountRoomGame} from './roomGames.js';import {ITEM_BY_ID,RECIPE_BY_ID,CATALOG_ITEMS} from './contentCatalog.js';import {GARMENTS} from './equipmentRules.js';import {itemMarkup} from './artStore.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),phases={preparing:'筹备中',live:'正在举办',completed:'已圆满结束',cancelled:'已取消',expired:'已到期'};
export function createLanActivitiesUI(api){
 const root=document.getElementById('lanActivities'),modal=document.getElementById('lanEventModal');let context=null,doc=null,key='',poll=null,refreshing=false,flight=0,engine=null,playing=null,trace=[],timer=null,uiTimer=null,stopping=false,signature='';
 const cache=()=>context?'hd-lan:'+context.me.id+':pending-event-command':'',pending=()=>{try{return JSON.parse(localStorage.getItem(cache())||'null')}catch{return null}};
 async function request(body){const r=await fetch('/api/lan/activities'+(body?'/action':''),{method:body?'POST':'GET',headers:{'X-HD-Island':context.me.id,...body?{'Content-Type':'application/json'}:{}},body:body?JSON.stringify(body):undefined,cache:'no-store',signal:AbortSignal.timeout(15000)}),data=await r.json();if(!r.ok)throw Object.assign(Error(data.error||'活动服务暂缓'),{status:r.status,code:data.code});return data;}
 async function command(args){if(flight)throw Error('活动操作正在确认');const old=pending();if(old&&old.requestId!==args.requestId)throw Error('先核对上次活动操作，再继续');const body=old||{...args,requestId:crypto.randomUUID()},storageKey=cache();if(!old)localStorage.setItem(storageKey,JSON.stringify(body));flight++;try{const r=await request(body);doc=r.view;localStorage.removeItem(storageKey);if(body.operation==='finish'&&!r.replayed){const e=doc.events.find(e=>e.id===body.eventId);if(e?.wonder?.milestone&&e.owner===context.me.id)showWonder(e);}return r;}catch(e){if(e.code&&e.status<500)localStorage.removeItem(storageKey);throw e;}finally{flight--;}}
 const act=fn=>async e=>{e?.preventDefault();try{await fn();render(true);}catch(e){api.toast(e.message);const status=document.getElementById('lanEventStatus');if(status)status.textContent=e.message;render();}};
 const chosen=id=>doc?.events.find(e=>e.id===id),bind=(selector,fn)=>root.querySelectorAll(selector).forEach(b=>b.onclick=act(()=>fn(b)));
 const date=t=>new Date(t).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'});
 function showWonder(e){if(!e?.wonder?.milestone)return;modal.dataset.previousTheme=document.body.dataset.theme;document.body.dataset.theme=e.theme;modal.innerHTML='<div class="modal-overlay"><section class="modal lan-wonder-dialog" role="dialog" aria-modal="true" aria-label="群岛灯塔纪念"><header class="modal-head"><div><h2>把远方，留在岛上</h2><small>本场相聚已结算 · 主办岛的纪念</small></div><button id="lanWonderClose" class="close" aria-label="收起群岛纪念">×</button></header><div class="modal-body">'+lanWonderMarkup(e)+'</div><footer class="modal-footer"><button class="primary" id="lanWonderRemember">收好这份纪念</button></footer></section></div>';document.getElementById('lanWonderClose').onclick=stopEngine;document.getElementById('lanWonderRemember').onclick=stopEngine;document.getElementById('lanWonderRemember').focus();}
 function render(force=false){if(!context||!doc)return;const s=JSON.stringify({doc:{...doc,at:undefined},ready:doc.events.map(e=>doc.at>=e.startsAt),room:context.room&&{id:context.room.id,revision:context.room.revision},pending:pending()?.requestId});if(!force&&signature===s)return;signature=s;const openDetails=[...root.querySelectorAll('details')].map(x=>x.open);const fields=[...root.querySelectorAll('input,select,textarea')].filter(e=>e.id).map(e=>[e.id,e.value,e.checked,e===document.activeElement]);const owner=context.room?.owner===context.me.id,users=context.users.filter(u=>u.id!==context.me.id);
 const featured=doc.events.find(e=>e.owner===context.me.id&&e.phase==='completed'&&e.wonder?.milestone);
 root.innerHTML=(featured?'<div class="lan-wonder-featured">'+lanWonderMarkup(featured,{button:true})+'</div>':'')+'<div class="lan-section-heading"><div><small>AN INVITATION, A LITTLE PREPARATION</small><h2>下一场相聚，由你来邀请。</h2><p>携物与穿着在入席时核对。完成真实挑战，留下活动印章与口碑。</p></div><button id="lanEventRefresh">查看新邀请</button></div>'+
 (pending()?'<section class="lan-card lan-event-recovery"><b>上次活动操作待核对</b><button class="primary" id="lanEventRetry">按原请求核对</button></section>':'')+
 (owner?'<details class="lan-card lan-event-compose"><summary>为会客房筹备一场活动</summary><form id="lanEventPublish"><div class="lan-fields"><label>活动名字<input id="lanEventTitle" minlength="2" maxlength="40" value="海风里的相聚" required></label><label>主题<select id="lanEventKind">'+doc.kinds.map(k=>'<option value="'+k.id+'">'+esc(k.name)+'</option>').join('')+'</select></label><label>准备时间<select id="lanEventPrepare"><option value="300">5分钟</option><option value="60">1分钟</option><option value="900">15分钟</option><option value="3600">1小时</option></select></label><label>挑战难度<select id="lanEventDifficulty"><option value="1">轻松</option><option value="2">标准</option><option value="3">挑战</option></select></label><label>目标品质<input id="lanEventQuality" type="number" min="55" max="95" value="70" required></label><label>主题穿着<select id="lanEventGarment"><option value="">自在穿着</option>'+Object.values(GARMENTS).map(g=>'<option value="'+g.id+'">'+esc(g.name)+'</option>').join('')+'</select></label></div><label>邀请寄语<textarea id="lanEventBrief" maxlength="240" rows="2" placeholder="写一句欢迎的话，也可以说明玩法与礼仪。"></textarea></label><fieldset><legend>给谁寄邀请 · 最多'+(context.room.maxPlayers-1)+'位朋友</legend><div class="lan-invitees">'+users.map(u=>'<label><input type="checkbox" id="lanInvite_'+u.id+'" data-lan-invite="'+u.id+'">'+esc(u.profile.name)+' · '+esc(u.profile.islandName)+'</label>').join('')+'</div></fieldset>'+lanEconomyForm()+'<fieldset><legend id="lanCarryLegend">携带要求 · 入席核对，不扣除物品</legend><div class="lan-event-item-fields">'+[0,1,2].map(n=>'<div><select id="lanRequire_'+n+'" aria-label="携带物品'+(n+1)+'"><option value="">不指定物品</option>'+CATALOG_ITEMS.map(x=>'<option value="'+x.id+'">'+esc(x.name)+'</option>').join('')+'</select><input id="lanQuantity_'+n+'" type="number" min="1" max="10" value="1" aria-label="所需数量"></div>').join('')+'</div></fieldset><p id="lanEventStatus" role="status"></p><button class="primary" type="submit">寄出活动邀请</button></form></details>':'')+
 '<div class="lan-event-grid">'+(doc.events.length?doc.events.map(e=>{const own=e.owner===context.me.id,m=e.participants.find(x=>x.id===context.me.id),active=['preparing','live'].includes(e.phase),accepted=m?.response==='accepted',completed=e.results.find(r=>r.accountId===context.me.id);return'<article class="lan-card lan-event-card" data-event="'+e.id+'"><div class="lan-event-banner">'+itemMarkup(RECIPE_BY_ID[e.recipeId].item,e.theme)+'<div><small>'+phases[e.phase]+' · '+esc(doc.kinds.find(k=>k.id===e.kind)?.name)+'</small><h3>'+esc(e.title)+'</h3><p>'+esc(e.ownerName)+' · '+esc(e.islandName)+'</p></div></div><p>'+esc(e.brief)+'</p><p class="lan-event-date">最早开场 '+date(e.startsAt)+'<br>邀请与活动有效至 '+date(e.expiresAt)+'</p><div class="lan-event-requirements">'+(e.requirements.items.length?e.requirements.items.map(x=>'<span>'+itemMarkup(x.item,e.theme)+esc(ITEM_BY_ID[x.item].name)+' ×'+x.quantity+'</span>').join(''):'<span>轻装赴约 · 不要求携物</span>')+(e.requirements.garment?'<span>'+itemMarkup(e.requirements.garment,e.theme)+'穿着 '+esc(GARMENTS[e.requirements.garment].name)+'</span>':'<span>穿着自由</span>')+'</div>'+lanEconomyCard(e,context.me.id)+'<ul class="lan-event-guests">'+e.participants.map(x=>'<li><b>'+esc(x.name)+'</b><span>'+(x.completed?'挑战完成 · 品质'+x.result.quality:x.response==='declined'?'婉拒邀请':x.checkedIn?'准备已核对':x.response==='accepted'?'已答应 · 准备中':'等待答复')+'</span></li>').join('')+'</ul><div class="lan-event-buttons">'+
 (e.invited&&!own&&active&&!accepted?'<button class="primary" data-event-accept="'+e.id+'">答应赴约</button><button data-event-decline="'+e.id+'">这次不便参加</button>':'')+
 (accepted&&active&&context.room?.id!==e.roomId?'<button class="primary" data-event-arrive="'+e.id+'">从码头前往主办岛</button>':'')+
 (accepted&&active&&!completed?'<button data-event-check="'+e.id+'">核对携物与穿着</button>':'')+
 (own&&e.phase==='preparing'?'<button class="primary" data-event-start="'+e.id+'" '+(doc.at<e.startsAt?'disabled':'')+'>'+(doc.at<e.startsAt?'留出准备时间':'邀请朋友开场')+'</button>':'')+
 (accepted&&e.phase==='live'&&!completed?'<button class="primary" data-event-play="'+e.id+'">'+(e.trial?'继续活动挑战':'进入活动挑战')+'</button>':'')+
 (own&&e.phase==='live'?'<button data-event-finish="'+e.id+'">结束并结算活动</button>':'')+
 (own&&['preparing','live','expired'].includes(e.phase)?'<button data-event-cancel="'+e.id+'">取消本场</button>':'')+
 (e.trial?'<button data-event-abandon="'+e.id+'">结束自己的本局</button>':'')+'</div>'+
 (e.phase==='completed'&&completed&&!own&&!e.myReview?'<form class="lan-event-rate" data-event-rate="'+e.id+'"><label>这次体验<select id="lanStars_'+e.id+'"><option value="5">★★★★★ 很喜欢</option><option value="4">★★★★☆ 喜欢</option><option value="3">★★★☆☆ 普通</option><option value="2">★★☆☆☆ 需改进</option><option value="1">★☆☆☆☆ 不满意</option></select></label><textarea id="lanComment_'+e.id+'" rows="2" maxlength="200" placeholder="留下给主办方的建议"></textarea><button class="primary" type="submit">留下真实参与评价</button></form>':'')+
 (e.reviews.length?'<div class="lan-event-reviews">'+e.reviews.map(r=>'<p><b>'+esc(r.name)+' · '+'★'.repeat(r.stars)+'</b>'+esc(r.comment||'感谢这次相聚。')+'</p>').join('')+'</div>':'')+
 (e.phase==='completed'?'<p class="lan-event-stamp">相聚印章 · '+e.results.filter(r=>r.accountId!==e.owner).length+'位朋友完成挑战</p>':'')+'</article>';}).join(''):'<article class="lan-card"><h3>第一封邀请，还在等你。</h3><p>在自己的会客房发布活动，或等待朋友寄来邀请。先回自己的小岛采集、制作与换装，再赴约。</p></article>')+'</div>'+
 '<section class="lan-card lan-host-book"><h3>岛主口碑与订阅</h3><p>订阅后会在这里收到该岛主新发布的活动。评价仅计入实际完成挑战的受邀朋友。</p><div class="lan-host-grid">'+users.map(u=>{const h=doc.hosts.find(h=>h.id===u.id);return'<article><b>'+esc(u.profile.name)+'</b><small>'+esc(u.profile.islandName)+' · 举办'+(h?.hosted||0)+'场</small><p>'+(h?.rating===null||h?.rating===undefined?'等待第一份真实评价':h.rating+' / 5 · '+h.ratingCount+'份评价')+'</p><button data-event-subscribe="'+u.id+'" data-subscribed="'+(h?.subscribed?'true':'false')+'">'+(h?.subscribed?'取消订阅':'订阅新活动')+'</button></article>';}).join('')+'</div></section><p class="lan-event-boundary">活动成绩、物资转交与岛币结算由本机服务保存。共同筹办中完成才交付与发奖，取消或到期退款；普通相聚只核验携物。实际多设备局域网验收仍待完成。</p>';
 bind('[data-event-wonder]',b=>showWonder(chosen(b.dataset.eventWonder)));document.getElementById('lanEventRefresh').onclick=act(refresh);document.getElementById('lanEventRetry')?.addEventListener('click',act(async()=>{await command(pending());if(playing){const id=playing;stopEngine(false);mount(id);}api.toast('上次活动操作已核对');}));
 document.getElementById('lanEventPublish')?.addEventListener('submit',act(async()=>{const val=id=>document.getElementById(id).value,items=[0,1,2].filter(n=>val('lanRequire_'+n)).map(n=>({item:val('lanRequire_'+n),quantity:Number(val('lanQuantity_'+n))}));await command({operation:'publish',roomId:context.room.id,title:val('lanEventTitle'),kind:val('lanEventKind'),brief:val('lanEventBrief')||doc.kinds.find(k=>k.id===val('lanEventKind')).brief,prepareSeconds:Number(val('lanEventPrepare')),difficulty:Number(val('lanEventDifficulty')),minQuality:Number(val('lanEventQuality')),economyMode:val('lanEconomyMode'),deliveryMode:val('lanEconomyMode')==='funded'?val('lanDeliveryMode'):'bring',requirements:{items,garment:val('lanEventGarment')||null},invitees:[...root.querySelectorAll('[data-lan-invite]:checked')].map(x=>x.dataset.lanInvite)});api.toast('活动邀请已寄出');}));
 bind('[data-event-accept]',b=>command({operation:'respond',eventId:b.dataset.eventAccept,response:'accepted'}));bind('[data-event-decline]',b=>command({operation:'respond',eventId:b.dataset.eventDecline,response:'declined'}));bind('[data-event-arrive]',async b=>{await command({operation:'arrive',eventId:b.dataset.eventArrive});api.toast('已靠泊，沿栈桥进入主办岛。');});bind('[data-event-check]',async b=>{await command({operation:'checkin',eventId:b.dataset.eventCheck});api.toast(chosen(b.dataset.eventCheck)?.economy.mode==='funded'?'入席准备已预留，结束后按规则交付与退款':'携物与穿着已核对，留在各自背包');});
 for(const op of ['start','finish','cancel'])bind('[data-event-'+op+']',async b=>{const id=b.getAttribute('data-event-'+op);try{return await command({operation:op,eventId:id,expectedRevision:chosen(id).revision});}catch(error){if(error.code!=='lan_event_revision')throw error;await refresh();return command({operation:op,eventId:id,expectedRevision:chosen(id).revision});}});
 bind('[data-event-play]',async b=>{const id=b.dataset.eventPlay;if(!chosen(id).trial)await command({operation:'trial_begin',eventId:id});mount(id);});
 bind('[data-event-abandon]',async b=>{const id=b.dataset.eventAbandon;await command({operation:'trial_cancel',eventId:id,runId:chosen(id).trial.runId});if(playing===id)stopEngine(false);});
 bind('[data-event-subscribe]',b=>command({operation:'subscribe',hostId:b.dataset.eventSubscribe,subscribed:b.dataset.subscribed!=='true'}));
 root.querySelectorAll('[data-event-rate]').forEach(form=>form.onsubmit=act(()=>command({operation:'rate',eventId:form.dataset.eventRate,stars:Number(document.getElementById('lanStars_'+form.dataset.eventRate).value),comment:document.getElementById('lanComment_'+form.dataset.eventRate).value})));
 root.querySelectorAll('details').forEach((x,n)=>x.open=openDetails[n]||false);for(const[id,value,checked,focused]of fields){const el=document.getElementById(id);if(el){el.value=value;el.checked=checked;if(focused)el.focus({preventScroll:true});}}
 updateLanEconomyPreview(root,doc,context.me.profile.theme);for(const el of root.querySelectorAll('#lanEconomyMode,#lanDeliveryMode,#lanEventKind,[data-lan-invite]'))el.addEventListener('change',()=>updateLanEconomyPreview(root,doc,context.me.profile.theme));
 }
 async function refresh(){if(!context||refreshing||flight||playing)return;refreshing=true;try{doc=(await request()).view;render();}catch(e){api.toast(e.message);}finally{refreshing=false;}}
 async function flush(){if(!playing||!trace.length||flight)return false;const e=chosen(playing),t=e?.trial;if(!t)return false;engine?.setTransportPaused(true);const old=pending();if(old&&(old.operation!=='trial_checkpoint'||old.eventId!==playing))return false;const events=old?old.events:trace.slice(0,2048);try{await command(old||{operation:'trial_checkpoint',eventId:playing,runId:t.runId,batch:t.nextBatch,events});trace.splice(0,events.length);engine?.setTransportPaused(false);return true;}catch(e){api.toast('活动进度待核对：'+e.message);return false;}}
 function mount(id){const e=chosen(id),t=e?.trial;if(!t)return;stopEngine(false);playing=id;trace=[{neutral:true}];const style=document.body.dataset.theme;modal.dataset.theme=e.theme;document.body.dataset.theme=e.theme;modal.dataset.previousTheme=style;modal.innerHTML='<div class="modal-overlay"><section class="modal game-modal cocreation-modal lan-event-game" role="dialog" aria-modal="true" aria-label="'+esc(e.title)+'"><header class="modal-head"><div><h2>'+esc(e.title)+'</h2><small>'+esc(e.ownerName)+'的邀请 · 目标品质 '+e.minQuality+'</small></div><button id="lanEventClose" class="close" aria-label="收起并保留活动进度">×</button></header><div class="modal-body"><p>'+esc(e.brief)+'</p><div id="lanEventGameRoot"></div><p class="lan-event-game-note">'+(e.economy.mode==='funded'?'完成挑战获2岛币，品质达到90获3岛币；主办方结束活动后从已预留预算发奖，按约定转交物资。':'此成绩留作真实参与凭证，不产生额外物品；制作请回自己的小岛。')+'</p></div><footer class="modal-footer"><button id="lanEventSuspend">收起并保留进度</button><button class="primary" id="lanEventClaim" disabled>保存活动成绩</button></footer></section></div>';
 engine=mountRoomGame(document.getElementById('lanEventGameRoot'),t.building,finish,{theme:e.theme,avatar:context.me.profile.avatar,standalone:true,recipe:RECIPE_BY_ID[t.recipeId],mode:String(t.difficulty),level:t.game.level,resumeGame:neutralCraftGame(structuredClone(t.game)),onGameEvent:x=>trace.push(x),onOutcome:flush,onExit:suspend,onRestart:()=>api.toast('收起本局后，可结束旧关卡再重试。'),readBest:()=>({score:0,stars:0}),writeBest:()=>{}});
 document.getElementById('lanEventClose').onclick=suspend;document.getElementById('lanEventSuspend').onclick=suspend;document.getElementById('lanEventClaim').onclick=finish;timer=setInterval(flush,5000);uiTimer=setInterval(()=>{if(!playing)return;const b=modal.querySelector('[data-action="claim"],.activity-finish');if(b){b.textContent='保存活动成绩';document.getElementById('lanEventClaim').disabled=b.disabled;}modal.querySelectorAll('[data-action="difficulty"],[data-difficulty]').forEach(b=>b.disabled=true);modal.querySelectorAll('[data-action="restart"]').forEach(b=>{b.disabled=true;b.textContent='本局结束后可返回活动';});for(const small of modal.querySelectorAll('.wk-result-card small'))if(small.textContent.includes('成绩已保存到此浏览器'))small.textContent='确认后，成绩保存到本机联机活动档案。';},250);
 }
 async function finish(){if(!playing||flight)return;engine?.setTransportPaused(true);while(trace.length)if(!await flush())return;const id=playing,t=chosen(id)?.trial;try{const r=await command({operation:'trial_finish',eventId:id,runId:t.runId});stopEngine(false);render(true);api.toast(r.receipt.outcome==='completed'?'活动挑战完成 · 品质'+r.receipt.result.quality:'练习已记录，可以在本场剩余次数内再试');}catch(e){api.toast(e.message);}}
 async function suspend(){if(flight){api.toast('进度正在确认，请稍候收起');return;}engine?.setTransportPaused(true);trace.push({neutral:true});while(trace.length)if(!await flush()){stopEngine(false);render(true);return;}stopEngine(false);render(true);}
 function stopEngine(){if(stopping)return;stopping=true;clearInterval(timer);clearInterval(uiTimer);timer=uiTimer=null;engine?.destroy();engine=null;playing=null;trace=[];if(modal.dataset.previousTheme)document.body.dataset.theme=modal.dataset.previousTheme;modal.innerHTML='';stopping=false;}
 function clear(){clearInterval(poll);poll=null;stopEngine();context=null;doc=null;key='';signature='';root.innerHTML='';}
 function setContext(v){if(key&&key!==v.me.id)clear();context=v;if(key===v.me.id)return;key=v.me.id;refresh();poll=setInterval(refresh,2000);}
 window.addEventListener('pagehide',()=>{engine?.destroy();clearInterval(timer);clearInterval(uiTimer);clearInterval(poll);});
 return{setContext,clear,busy:()=>flight>0||!!playing||!!pending(),inspect:()=>({doc,flight,playing,trace:trace.length,pending:pending(),game:engine?.inspect()})};
}
