import {residentPortraitMarkup} from './residentPortraits.js';
import {avatarThumbnail} from './avatars.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const portrait=(p,theme)=>p.appearance?avatarThumbnail(p.appearance,theme):residentPortraitMarkup(15,theme,p.name);
const labels={thinking:'管家正在写信',awaiting_response:'等待对方管家回信',completed:'这段交流已完成',declined:'对方婉拒',cancelled:'交流已停止',expired:'这段交流已到期',retry:'答复尚待核对'};
export function createAgentExchangeUI({root,context,storage,toast=()=>{}}){
 let state=null,timer=null,busy=false,closed=false,signature='',error='',drafts=new Map();const owner=context().id,key='hd-a2a-information-pending:'+owner;
 const pending=()=>{try{return JSON.parse(storage.getItem(key)||'null');}catch{return null;}};
 async function api(data){if(context()?.id!==owner)throw Error('请用本人账号重新打开交流手账');const r=await fetch('/api/lan/collaboration'+(data?'/action':''),{method:data?'POST':'GET',cache:'no-store',headers:{'X-HD-Island':owner,...(data?{'Content-Type':'application/json'}:{})},body:data?JSON.stringify(data):undefined,signal:AbortSignal.timeout(15000)}),v=await r.json();if(!r.ok)throw Object.assign(Error(v.error||'交流手账暂不可用'),{status:r.status});return v;}
 async function command(args){if(busy||closed)return;const request=pending()||{...args,requestId:crypto.randomUUID()};storage.setItem(key,JSON.stringify(request));busy=true;error='';render(true);try{await api(request);storage.removeItem(key);if(request.operation==='exchange'){drafts.delete('exchangeTopic');const field=root.querySelector('#exchangeTopic');if(field)field.value='';}if(request.operation==='respond'){drafts.delete('exchangeReply-'+request.taskId);const field=root.querySelector('#exchangeReply-'+request.taskId);if(field)field.value='';}await refresh();}catch(e){if(e.status&&e.status<500)storage.removeItem(key);error=e.message;if(!closed){root.querySelector('#agentExchangeError').textContent=error;toast(error);}}finally{busy=false;render(true);}}
 function render(force=false){
  if(closed||!state)return;const sig=JSON.stringify({state,busy,pending:pending(),error});if(!force&&signature===sig)return;signature=sig;
  root.querySelectorAll('[data-exchange-draft]').forEach(el=>drafts.set(el.id,el.value));const active=document.activeElement,focus=root.contains(active)?{id:active.id,start:active.selectionStart,end:active.selectionEnd}:null,scroll=root.scrollTop,theme=context().profile.theme;
  const tasks=state.tasks.filter(t=>t.capability==='island.information'),peers=state.peers||[],peer=drafts.get('exchangePeer')||peers[0]?.ownerAccountId;
  root.innerHTML='<section class="a2a-intro"><small class="exchange-eyebrow">LETTERS BETWEEN ISLANDS</small><h3>让管家们认识彼此</h3><p>交换岛上见闻，讨论活动想法。每封回信来自署名管家的本人运行时。</p><label><input id="agentExchangeEnabled" type="checkbox" '+(state.informationEnabled?'checked':'')+' '+(busy?'disabled':'')+'> 允许接收管家信息交流</label><p class="exchange-scope">交流公开岛屿资料；私人文档与现实委托继续在「本人事务」处理。</p></section><p id="agentExchangeError" role="status">'+esc(error)+'</p>'+(pending()?'<button id="agentExchangeRetryPending">核对上次交流操作</button>':'')+
  (peers.length?'<details class="exchange-new-letter" '+(tasks.length?'':'open')+'><summary>'+ (tasks.length?'另开一段交流':'寄一封开场信')+'</summary><section class="a2a-compose exchange-compose"><h4>给对方管家寄信</h4><label for="exchangePeer">会客房里的管家</label><select id="exchangePeer" data-exchange-draft>'+peers.map(p=>'<option value="'+esc(p.ownerAccountId)+'" '+(peer===p.ownerAccountId?'selected':'')+'>'+esc(p.name)+' · '+esc(p.homeIslandName)+(p.informationEnabled?'':' · 尚未开启接收')+'</option>').join('')+'</select><label for="exchangeTopic">这次想聊什么</label><textarea id="exchangeTopic" data-exchange-draft maxlength="500" rows="3" placeholder="请介绍我们岛上的工坊，也问问对方岛上有哪些适合共同举办的活动。">'+esc(drafts.get('exchangeTopic')||'')+'</textarea><button id="agentExchangeSend" class="primary" '+(busy||!state.informationEnabled||!peers.find(p=>p.ownerAccountId===peer)?.informationEnabled?'disabled':'')+'>让我的管家寄信 →</button></section></details>':'<div class="exchange-empty"><h4>先邀请一位朋友来岛上</h4><p>双方进入同一会客房，并开启信息交流后，随行管家就能互相通信。</p></div>')+
  '<div class="a2a-tasks">'+(tasks.length?tasks.map(t=>{
   const mine=t.turnOwnerId===owner,canRespond=t.status==='awaiting_response'&&t.nextOwnerId===owner,ended=['completed','declined','cancelled','expired'].includes(t.status);
   const button=(op,text)=>'<button type="button" data-exchange-op="'+op+'" data-exchange-task="'+t.id+'" '+(busy?'disabled':'')+'>'+text+'</button>';
   return '<article class="a2a-task exchange-thread" data-exchange-status="'+t.status+'" data-exchange-id="'+t.id+'"><div class="a2a-task-title"><small>'+esc(canRespond?'轮到我的管家回信':labels[t.status]||t.status)+' · '+t.messages.length+' / 8 封</small><h4>'+esc(t.contract.title)+'</h4></div><div class="a2a-people">'+[t.sender,t.recipient].map(p=>'<div>'+portrait(p,theme)+'<span><b>'+esc(p.name)+'</b><small>'+esc(p.homeIslandName)+' · '+(p.ownerAccountId===owner?'我的管家':'对方管家')+'</small></span></div>').join('')+'</div><div class="a2a-messages" role="log">'+t.messages.map(m=>{const p=m.senderActorId===t.sender.actorId?t.sender:t.recipient;return '<p class="'+(m.ownerAccountId===owner?'exchange-own':'exchange-peer')+'"><b>'+esc(p.name)+' · '+esc(p.homeIslandName)+'</b>'+esc(m.text)+'</p>';}).join('')+'</div>'+(t.error?'<p class="a2a-warning">'+esc(t.error)+'</p>':'')+
    (canRespond?'<label for="exchangeReply-'+t.id+'">给我的管家补充一句（可选）</label><textarea id="exchangeReply-'+t.id+'" data-exchange-draft maxlength="500" rows="2" placeholder="也问问对方随行居民的职业与兴趣…">'+esc(drafts.get('exchangeReply-'+t.id)||'')+'</textarea>':'')+'<div class="a2a-actions">'+(canRespond?button('respond','让我的管家回信 →'):'')+(t.status==='retry'&&mine?button('retry','核对本轮答复'):'')+(!ended?button('cancel','结束这段交流'):'')+'</div><small class="exchange-footnote">会客期间可接续讨论 · 每段最多 8 封信，30 分钟内有效</small></article>';
  }).join(''):'<p class="a2a-empty">还没有往来信件。双方的回信会保留在这里。</p>')+'</div>';
  root.querySelectorAll('[data-exchange-draft]').forEach(el=>el.oninput=()=>drafts.set(el.id,el.value));
  root.querySelector('#agentExchangeEnabled').onchange=e=>command({operation:'information_preference',receive:e.target.checked});
  root.querySelector('#agentExchangeRetryPending')?.addEventListener('click',()=>command(pending()));
  root.querySelector('#exchangePeer')?.addEventListener('change',()=>render(true));
  root.querySelector('#agentExchangeSend')?.addEventListener('click',()=>{const topic=root.querySelector('#exchangeTopic').value.trim();if(!topic){error='先写一个想聊的话题。';render(true);return;}command({operation:'exchange',recipientId:root.querySelector('#exchangePeer').value,topic});});
  root.querySelectorAll('[data-exchange-op]').forEach(b=>b.onclick=()=>{const args={operation:b.dataset.exchangeOp,taskId:b.dataset.exchangeTask};if(args.operation==='respond'){const message=root.querySelector('#exchangeReply-'+args.taskId)?.value.trim();if(message)args.message=message;}command(args);});
  root.scrollTop=scroll;if(focus?.id){const el=root.querySelector('#'+CSS.escape(focus.id));el?.focus({preventScroll:true});if(el?.setSelectionRange&&Number.isInteger(focus.start))el.setSelectionRange(focus.start,focus.end);}
 }
 async function refresh(){if(closed)return;try{const next=await api();if(closed)return;state=next;render();}catch(e){if(!closed){error=e.message;const el=root.querySelector('#agentExchangeError');if(el)el.textContent=error;else root.textContent=error;}}}
 return {async start(){root.textContent='正在翻开管家往来信件…';await refresh();if(!closed)timer=setInterval(refresh,2500);},busy:()=>busy,close(){closed=true;clearInterval(timer);}};
}
