import {drawGuestWorkstation} from './guestWorkArt.js';
import {WORLD,worldSlots,worldWalkableForTheme,setWorldTheme} from './world.js';import {drawOuterSea,drawIsland,drawHarbor} from './harbor.js';import {drawAnimatedCharacter} from './characters.js';
const layers=new Map();async function image(url){const im=new Image();im.src=url;await im.decode();return im;}
async function layer(theme){if(layers.has(theme))return layers.get(theme);const loading=(async()=>{const [map,houses]=await Promise.all([image('/assets/island-'+theme+'-v9.png'),image('/assets/buildings-'+theme+'-front-v2.png')]),canvas=document.createElement('canvas');canvas.width=houses.naturalWidth;canvas.height=houses.naturalHeight;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(houses,0,0);const pixels=ctx.getImageData(0,0,canvas.width,canvas.height).data,bounds=[];for(let id=0;id<25;id++){const left=Math.round(id%5*canvas.width/5),top=Math.round(Math.floor(id/5)*canvas.height/5),right=Math.round((id%5+1)*canvas.width/5),bottom=Math.round((Math.floor(id/5)+1)*canvas.height/5);let x0=right,x1=-1,y0=bottom,y1=-1;for(let y=top;y<bottom;y++)for(let x=left;x<right;x++)if(pixels[(y*canvas.width+x)*4+3]>70){x0=Math.min(x0,x);x1=Math.max(x1,x);y0=Math.min(y0,y);y1=Math.max(y1,y);}bounds.push(x1>=x0?{x:x0,y:y0,w:x1-x0+1,h:y1-y0+1}:null);}return{map,houses,bounds};})();layers.set(theme,loading);try{return await loading}catch(e){layers.delete(theme);throw e;}}
function passable(theme,a,b){for(let i=0;i<=8;i++)if(!worldWalkableForTheme(theme,a.x+(b.x-a.x)*i/8,a.y+(b.y-a.y)*i/8))return false;return true;}
export function createLanMap(canvas,{view,move,toast}){
 const ctx=canvas.getContext('2d'),members=new Map();let current=view,theme=view.room.theme,art=null,alive=true,frame=0,zoom=1,camera={x:WORLD.width/2,y:WORLD.height/2},drag=null,clickMoved=false,cssW=1,cssH=1,scale=1,density=1,loaded=false,viewAt=performance.now(),last=performance.now();setWorldTheme(theme);layer(theme).then(a=>{if(alive){art=a;loaded=true;}}).catch(()=>toast('地图素材暂未加载，请重新进入会客房'));
 function resize(){const r=canvas.getBoundingClientRect();cssW=Math.max(1,r.width);cssH=Math.max(1,r.height);density=Math.min(2,devicePixelRatio||1);canvas.width=Math.round(cssW*density);canvas.height=Math.round(cssH*density);scale=Math.max(cssW/WORLD.width,cssH/WORLD.height)*zoom;clamp();}
 function clamp(){const w=cssW/scale/2,h=cssH/scale/2;camera.x=Math.max(w,Math.min(WORLD.width-w,camera.x));camera.y=Math.max(h,Math.min(WORLD.height-h,camera.y));}
 let labelBoxes=[];
 function label(member,a){const mult=theme==='pixel'?.24:.32,anchorX=cssW/2+(a.x-camera.x)*scale,anchorY=cssH/2+(a.y-camera.y-96*mult-10)*scale,name=member.profile.name+(member.id===current.me.id?' · 你':'');ctx.save();ctx.setTransform(density,0,0,density,0,0);ctx.font=(theme==='pixel'?'12px FusionPixel,monospace':'12px Microsoft YaHei,sans-serif');ctx.textAlign='center';const width=ctx.measureText(name).width+12;let x=anchorX,y=anchorY;const candidates=[[0,0],[0,-24],[-width*.8,-8],[width*.8,-8],[0,-48],[-width,-32],[width,-32],[0,-72]];for(const[dx,dy]of candidates){const px=Math.max(width/2+3,Math.min(cssW-width/2-3,anchorX+dx)),py=Math.max(20,anchorY+dy),box={x:px-width/2,y:py-16,w:width,h:20};if(!labelBoxes.some(b=>box.x<b.x+b.w+3&&box.x+box.w+3>b.x&&box.y<b.y+b.h+3&&box.y+box.h+3>b.y)){x=px;y=py;break;}}labelBoxes.push({x:x-width/2,y:y-16,w:width,h:20});if(Math.abs(x-anchorX)>1||Math.abs(y-anchorY)>1){ctx.strokeStyle='#466c5777';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x,y+4);ctx.lineTo(anchorX,anchorY+4);ctx.stroke();}ctx.fillStyle=member.id===current.me.id?'#f9e8bddf':'#fffaecdf';ctx.fillRect(x-width/2,y-16,width,20);ctx.strokeStyle='#55786199';ctx.strokeRect(x-width/2,y-16,width,20);ctx.fillStyle='#345346';ctx.fillText(name,x,y-2);ctx.restore();}
 function people(){return [...(current.room.residents||[]).map(c=>({id:c.actorId,npcId:c.npcId,kind:c.kind,profile:{name:c.name,avatar:c.appearance},position:c.position,speech:c.speech,work:c.work,ownerAccountId:c.ownerAccountId})),...current.room.members.flatMap(m=>[m,...(m.companions||[]).map(c=>({id:c.actorId,npcId:c.npcId,kind:c.kind,profile:{name:c.name,avatar:c.appearance},position:c.position,speech:c.speech,work:c.work,ownerAccountId:m.id}))])];}
 function actors(dt){const out=[];for(const m of people()){let a=members.get(m.id);if(!a){a={x:m.position.x,y:m.position.y,facing8:null,phase:0,appearance:m.profile.avatar,npcId:m.npcId};members.set(m.id,a);}const p=m.position;let target={x:p.x,y:p.y},travel=p.online?Math.min(.6,Math.max(0,(performance.now()-viewAt)/1000))*(p.speed||80):0;for(const next of p.route||[]){const dx=next.x-target.x,dy=next.y-target.y,len=Math.hypot(dx,dy),step=Math.min(travel,len);if(len){const dest={x:target.x+dx/len*step,y:target.y+dy/len*step};if(!passable(theme,target,dest))break;target=dest;}travel-=step;if(travel<=0)break;}
 const d=Math.hypot(target.x-a.x,target.y-a.y),moving=p.online&&(p.walking||(p.route||[]).length>0);if(d>80||!passable(theme,a,target)){a.x=target.x;a.y=target.y;}else{const t=Math.min(1,dt*14);a.x+=(target.x-a.x)*t;a.y+=(target.y-a.y)*t;}if(d>1&&moving)a.direction=Math.atan2(target.y-a.y,target.x-a.x);else a.direction=p.direction;a.appearance=m.profile.avatar;a.walking=moving;a.walkMix=(a.walkMix||0)+((moving?1:0)-(a.walkMix||0))*Math.min(1,dt*12);a.phase+=dt*12;const speechTime=Date.now()-(m.speech?.at||0),talking=!!m.speech&&speechTime>=0&&speechTime<m.speech.lines.length*3500;const working=m.work?.phase==='working'&&p.online;if(working){if(a.workKey!==m.work.id){a.workKey=m.work.id;a.workVisual=m.work.elapsed||0;}a.workVisual+=dt;}else a.workKey=null;a.action=talking?{type:'talk',t:speechTime/1000,duration:m.speech.lines.length*3.5}:working?{type:m.work.action,guestWork:true,t:a.workVisual,duration:m.work.duration,roomId:m.work.buildingId,output:m.work.output}:null;a.speech=talking?(m.speech.lines.find(l=>l.actorId===m.id&&speechTime>=l.start&&speechTime<l.start+3500)?.text||''):'';out.push({member:m,actor:a});}for(const id of members.keys())if(!people().some(m=>m.id===id))members.delete(id);return out;}
 function speech(member,a){
  const at=Date.now()-(member.speech?.at||0),line=member.speech?.lines.find(l=>l.actorId===member.id&&at>=l.start&&at<l.start+3500);if(!line)return;
  ctx.save();ctx.setTransform(density,0,0,density,0,0);ctx.font=theme==='pixel'?'16px FusionPixel,monospace':'16px Microsoft YaHei,sans-serif';
  const w=Math.min(270,cssW-16),rows=[];let row='';for(const ch of line.text){if(row&&ctx.measureText(row+ch).width>w-24){rows.push(row);row='';}row+=ch;}if(row)rows.push(row);
  const h=rows.length*23+42,x=Math.max(8,Math.min(cssW-w-8,cssW/2+(a.x-camera.x)*scale-w/2)),y=Math.max(8,cssH/2+(a.y-camera.y-60)*scale-h);
  ctx.fillStyle='#fff8ea';ctx.strokeStyle='#587760';ctx.lineWidth=theme==='pixel'?3:1;ctx.fillRect(x,y,w,h);ctx.strokeRect(x,y,w,h);
  ctx.fillStyle='#667653';ctx.textAlign='left';ctx.fillText(member.profile.name,x+12,y+22);ctx.fillStyle='#344e42';rows.forEach((r,i)=>ctx.fillText(r,x+12,y+46+i*23));ctx.restore();
 }
 function tick(at){if(!alive)return;const dt=Math.min(.05,(at-last)/1000);last=at;ctx.setTransform(density,0,0,density,0,0);ctx.clearRect(0,0,cssW,cssH);ctx.fillStyle='#66b4bd';ctx.fillRect(0,0,cssW,cssH);ctx.translate(cssW/2,cssH/2);ctx.scale(scale,scale);ctx.translate(-camera.x,-camera.y);ctx.imageSmoothingEnabled=theme!=='pixel';if(art){drawOuterSea(ctx,art.map,theme,at/1000);drawIsland(ctx,art.map,theme);drawHarbor(ctx,theme,at/1000);}const entities=[...worldSlots(theme).map(s=>({y:s.y,slot:s})),...actors(dt).map(x=>({y:x.actor.y,...x}))];for(const e of entities.sort((a,b)=>a.y-b.y)){if(e.slot&&art){const s=e.slot,b=art.bounds[s.id];if(b){const w=Math.min(128,s.w+8),h=Math.min(112,w*b.h/b.w);ctx.drawImage(art.houses,b.x,b.y,b.w,b.h,s.x-w/2,s.y-h/2,w,h);}}else if(e.actor){ctx.save();if(!e.member.position.online)ctx.globalAlpha=.5;drawGuestWorkstation(ctx,e.member,e.actor,theme);drawAnimatedCharacter(ctx,e.actor,theme,'#d9bd78',Number.isInteger(e.member.npcId),at/1000,theme==='pixel'?.24:.32);ctx.restore();}}labelBoxes=[];for(const m of people()){const a=members.get(m.id);if(a)label(m,a);}for(const m of people()){const a=members.get(m.id);if(a)speech(m,a);}frame=requestAnimationFrame(tick);}
 function point(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top};}
 const down=e=>{drag={...point(e),cx:camera.x,cy:camera.y};clickMoved=false;canvas.setPointerCapture(e.pointerId);};
 const motion=e=>{if(!drag)return;const p=point(e),dx=p.x-drag.x,dy=p.y-drag.y;if(Math.hypot(dx,dy)>5)clickMoved=true;if(clickMoved){camera.x=drag.cx-dx/scale;camera.y=drag.cy-dy/scale;clamp();}};
 const up=e=>{if(!drag)return;const p=point(e);if(!clickMoved){const x=camera.x+(p.x-cssW/2)/scale,y=camera.y+(p.y-cssH/2)/scale;if(worldWalkableForTheme(theme,x,y))move(x,y);else toast('请点击道路或栈桥，建筑地块暂不用于同行寻路。');}drag=null;};
 const wheel=e=>{e.preventDefault();zoomBy(e.deltaY<0?1.12:1/1.12);};
 function zoomBy(f){zoom=Math.max(1,Math.min(3,zoom*f));resize();const el=document.getElementById('lanZoomValue');if(el)el.textContent=Math.round(zoom*100)+'%';}
 const observer=new ResizeObserver(resize);observer.observe(canvas);canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',motion);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',()=>drag=null);canvas.addEventListener('wheel',wheel,{passive:false});resize();frame=requestAnimationFrame(tick);
 return{roomId:view.room.id,setView(v){current=v;viewAt=performance.now();},reattach(){resize();const e=document.getElementById('lanZoomValue');if(e)e.textContent=Math.round(zoom*100)+'%';},zoomBy,reset(){zoom=1;camera={x:WORLD.width/2,y:WORLD.height/2};resize();const e=document.getElementById('lanZoomValue');if(e)e.textContent='100%';},inspect:()=>({loaded,theme,roomId:current.room.id,zoom,camera:{...camera},scale,cssW,cssH,members:[...members].map(([id,a])=>({id,x:a.x,y:a.y,direction:a.direction,appearance:a.appearance,action:a.action?{...a.action}:null,work:people().find(m=>m.id===id)?.work||null}))}),destroy(){alive=false;cancelAnimationFrame(frame);observer.disconnect();canvas.removeEventListener('pointerdown',down);canvas.removeEventListener('pointermove',motion);canvas.removeEventListener('pointerup',up);canvas.removeEventListener('wheel',wheel);}};
}
