import {createCollaborationUI} from './lanCollaborationUI.js';
import {createAgentExchangeUI} from './lanAgentExchangeUI.js';
import {hudIllustration} from './uiArt.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function createPersonalStewardUI({context,toast=()=>{},storage=localStorage}){
 let panel=null,timer=null,view=null,busy=false,requestBody=null,signature='',returnFocus=null,collaboration=null,exchange=null,tab='own',selectedSession=null;
 const pendingKey=()=> 'hd-personal-steward:'+context().id;
 function keepPending(){if(requestBody)storage.setItem(pendingKey(),JSON.stringify(requestBody));else storage.removeItem(pendingKey());}
 const css=document.createElement('link');css.rel='stylesheet';css.href='/src/lan-steward-v65.css';document.head.append(css);
 async function api(path='',data){const c=context();if(!c)throw Error('请先登录自己的小岛');const r=await fetch('/api/lan/steward'+path,{method:data?'POST':'GET',cache:'no-store',headers:{'X-HD-Island':c.id,...(data?{'Content-Type':'application/json'}:{})},body:data?JSON.stringify(data):undefined,signal:AbortSignal.timeout(12000)});const result=await r.json();if(!r.ok)throw Error(result.error||'暂时无法核对管家手账');return result;}
 function paintSelection(){
  if(!panel)return;const root=panel.querySelector('#personalResumeContext'),c=context();
  if(selectedSession?.ownerId!==c?.id||selectedSession?.theme!==c?.profile.theme)selectedSession=null;
  const html=selectedSession?'<div class="steward-resume-note"><b>接着这项工作继续</b><p>'+esc(selectedSession.title.slice(0,80))+'</p><small>会带入此前读取的内容和工具结果；下一步仍按当前文件核对。</small><button class="secondary" type="button" id="personalResumeCancel">仅用普通对话</button></div>':'';
  if(root&&root.innerHTML!==html)root.innerHTML=html;
  const blocked=busy||!!requestBody||view?.jobs.some(j=>j.status==='running');
  panel.querySelectorAll('[data-personal-resume]').forEach(b=>b.disabled=!!blocked);
  const cancel=panel.querySelector('#personalResumeCancel');if(cancel){cancel.disabled=!!blocked;cancel.onclick=()=>{if(blocked)return;selectedSession=null;paintSelection();};}
 }
 function render(){
  if(!panel||!view)return;paintSelection();
  panel.querySelector('header h2').textContent=(view.butler?.name||'你的管家')+' · 同行手账';
  const key=JSON.stringify(view.jobs);if(key===signature)return;signature=key;
  const log=panel.querySelector('#personalStewardLog'),bottom=log.scrollHeight-log.scrollTop-log.clientHeight<60;
  log.innerHTML=view.jobs.length?view.jobs.map(j=>'<article class="personal-letter user"><small>你 · '+(j.location==='visit'?'会客途中':'原岛')+'</small><p>'+esc(j.message)+'</p></article><article class="personal-letter assistant"><small>你的管家 · '+esc(({running:'正在处理',completed:'Hermes 已回复',failed:'未完成',unconfirmed:'结果待核对'})[j.status])+'</small><p>'+esc(j.result?.answer||j.error||'任务已经登记，刷新页面后仍可继续查看。')+'</p>'+(j.result?.operations?.length?'<details><summary>实际执行记录 · '+j.result.operations.length+' 步</summary>'+j.result.operations.map(o=>'<p>'+esc(o.tool)+' · '+esc(o.status)+'<br>'+esc(o.path)+'</p>').join('')+'</details>':'')+(j.status==='completed'&&j.result?.session?.canResume?'<button type="button" class="secondary" data-personal-resume="'+esc(j.id)+'">继续这项工作 →</button>':'')+(j.result?.artifacts?.length?'<div class="personal-artifacts">'+j.result.artifacts.map(a=>'<a href="/api/workbench/'+view.theme+'/artifact/'+encodeURIComponent(a.id)+'/download" data-artifact="'+esc(a.id)+'">'+esc(a.name||'下载文档成果')+'</a>').join('')+'</div>':'')+'</article>').join(''):'<div class="personal-welcome"><h3>换一座岛，也继续刚才的话题。</h3><p>你的对话与文档成果随账号保留。可以交代一件具体的事，或问问已有委托的进展。</p></div>';
  if(bottom)log.scrollTop=log.scrollHeight;
  panel.querySelectorAll('[data-personal-resume]').forEach(b=>b.onclick=()=>{if(busy||requestBody)return;const j=view.jobs.find(j=>j.id===b.dataset.personalResume);if(!j?.result?.session?.canResume)return;selectedSession={id:j.result.session.id,ownerId:context().id,theme:view.theme,title:j.message};paintSelection();panel.querySelector('textarea').focus();});paintSelection();
  panel.querySelectorAll('[data-artifact]').forEach(el=>el.onclick=async e=>{e.preventDefault();try{const r=await fetch(el.href,{headers:{'X-HD-Island':context().id}});if(!r.ok)throw Error('成果暂时无法下载');const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=el.textContent;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}catch(e){toast(e.message)}});
 }
 async function refresh(){if(!panel||tab!=='own')return;const current=panel;try{view=await api('?theme='+context().profile.theme);if(panel!==current)return;if(selectedSession){const next=view.jobs.findLast(j=>j.resumeSessionId===selectedSession.id&&j.status==='completed'&&j.result?.session?.canResume);if(next)selectedSession.id=next.result.session.id;}if(requestBody&&view.jobs.some(j=>j.id===requestBody.requestId)){const input=panel.querySelector('textarea');if(input.value===requestBody.message)input.value='';requestBody=null;keepPending();}render();const status=panel.querySelector('#personalStewardStatus');status.textContent=view.status.hermes.configured?'Hermes · DeepSeek Flash · 本人工作区':'Hermes 尚未就绪 · 委托结果将明确显示';panel.querySelector('#personalWorkdir').textContent=view.documents;panel.querySelector('#personalStewardSend').disabled=busy||view.jobs.some(j=>j.status==='running');}catch(e){if(panel===current)panel.querySelector('#personalStewardStatus').textContent=e.message;}}
 async function send(e){e.preventDefault();if(busy)return;const input=panel.querySelector('textarea'),message=input.value.trim();if(!requestBody&&!message)return;busy=true;const current=panel,c=context();requestBody??={requestId:crypto.randomUUID(),theme:c.profile.theme,message,...(selectedSession&&selectedSession.ownerId===c.id&&selectedSession.theme===c.profile.theme?{resumeSessionId:selectedSession.id}:{})};keepPending();
  panel.querySelector('#personalStewardSend').disabled=true;
  try{await api('',requestBody);if(panel!==current||context()?.id!==c.id)return;requestBody=null;keepPending();input.value='';await refresh();}
  catch(e){if(panel===current)panel.querySelector('#personalStewardStatus').textContent=e.message+'；点击寄出可按原委托核对。';}
  finally{busy=false;if(panel)panel.querySelector('#personalStewardSend').disabled=view?.jobs.some(j=>j.status==='running')||false;paintSelection();}
 }
 function close(){if(busy||collaboration?.busy()||exchange?.busy()){toast('正在登记委托，请稍候');return;}clearInterval(timer);collaboration?.close();collaboration=null;exchange?.close();exchange=null;panel?.remove();panel=null;returnFocus?.focus();}
 async function open(){if(panel)return;const c=context();if(!c)return;try{requestBody=JSON.parse(storage.getItem(pendingKey())||'null');}catch{requestBody=null;}returnFocus=document.activeElement;tab='own';signature='';view=null;panel=document.createElement('div');panel.className='personal-steward-overlay';panel.dataset.theme=c.profile.theme;
  panel.innerHTML='<section class="personal-steward-panel" role="dialog" aria-modal="true" aria-label="随行管家"><header>'+hudIllustration('steward',c.profile.theme)+'<div><small>PERSONAL COMPANION</small><h2>一路同行的管家</h2></div><button id="personalStewardClose" aria-label="关闭管家">×</button></header><nav class="personal-steward-tabs"><button type="button" id="personalOwnTab" aria-selected="true">本人事务</button><button type="button" id="personalCooperateTab" aria-selected="false">活动协作</button><button type="button" id="personalExchangeTab" aria-selected="false">管家交流</button></nav><div class="personal-steward-meta"><span id="personalStewardStatus">正在翻开手账…</span><details><summary>我的文档工作区</summary><p id="personalWorkdir"></p><p>当前可读写这个账号的独立工作区。访客自己的电脑尚未绑定；私人对话和文档不会发到会客聊天。</p></details></div><div id="personalStewardLog" role="log" aria-live="polite"></div><form id="personalStewardForm"><div class="personal-compose-fields"><div id="personalResumeContext"></div><label for="personalStewardMessage">写给你的管家</label><textarea id="personalStewardMessage" maxlength="1000" rows="3" placeholder="继续刚才的话题，或让我在工作区整理一份文档…"></textarea></div><div class="personal-compose-actions"><small>回复和文档操作均保留记录</small><button id="personalStewardSend" class="primary">寄出 →</button></div></form><div id="personalCollaboration" hidden></div><div id="personalAgentExchange" hidden></div></section>';
  document.body.append(panel);
  const switchTab=async next=>{if(busy||collaboration?.busy()||exchange?.busy())return;tab=next;for(const el of panel.querySelectorAll('.personal-steward-meta,#personalStewardLog,#personalStewardForm'))el.hidden=next!=='own';panel.querySelector('#personalCollaboration').hidden=next!=='cooperate';panel.querySelector('#personalAgentExchange').hidden=next!=='exchange';panel.querySelector('#personalOwnTab').setAttribute('aria-selected',String(next==='own'));panel.querySelector('#personalCooperateTab').setAttribute('aria-selected',String(next==='cooperate'));panel.querySelector('#personalExchangeTab').setAttribute('aria-selected',String(next==='exchange'));exchange?.close();exchange=null;collaboration?.close();collaboration=null;if(next==='cooperate'){collaboration=createCollaborationUI({root:panel.querySelector('#personalCollaboration'),context,storage,toast});await collaboration.start();}else if(next==='exchange'){exchange=createAgentExchangeUI({root:panel.querySelector('#personalAgentExchange'),context,storage,toast});await exchange.start();}else await refresh();};
  panel.querySelector('#personalOwnTab').onclick=()=>switchTab('own');panel.querySelector('#personalCooperateTab').onclick=()=>switchTab('cooperate');panel.querySelector('#personalExchangeTab').onclick=()=>switchTab('exchange');
  panel.querySelector('#personalStewardClose').onclick=close;panel.querySelector('form').onsubmit=send;panel.addEventListener('keydown',e=>{if(e.key==='Escape'){e.stopPropagation();close();}});panel.querySelector('#personalStewardClose').focus();if(requestBody){panel.querySelector('textarea').value=requestBody.message;panel.querySelector('#personalStewardStatus').textContent='上次委托等待核对，寄出会复用原编号';}await refresh();if(panel)timer=setInterval(refresh,2500);
 }
 return {open,close,busy:()=>busy,clear:()=>{busy=false;requestBody=null;selectedSession=null;close();}};
}
