import {createLanSocialUI} from './lanSocialUI.js';
import {createPersonalStewardUI} from './lanStewardUI.js';
import {travelPreparationMarkup,memberCompanionsMarkup} from './lanTravelUI.js';
import {createLanActivitiesUI} from './lanActivitiesUI.js';
import {AVATARS} from './avatarCatalog.js';import {avatarThumbnail,avatarPortrait} from './avatars.js';import {artReady} from './artStore.js';import {scopedLanStorage} from './lanStorage.js';import {createLanMap} from './lanMap.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let view=null,mode='login',flight=0,poll=null,map=null,signature='',lastError='',refreshing=false;const rawStorage=localStorage,root=document.getElementById('lanRoot'),bar=document.getElementById('lanAccountBar');
const storage=()=>view?.me&&scopedLanStorage(rawStorage,view.me.id),pending=()=>{try{return JSON.parse(storage()?.getItem('pending-room-command')||'null')}catch{return null}};
function toast(s){const el=document.getElementById('lanToast');el.textContent=s;el.classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('visible'),3500);}
async function request(path,data){const headers=data?{'Content-Type':'application/json'}:{};if(view?.me&&path!=='login'&&path!=='register')headers['X-HD-Island']=view.me.id;const r=await fetch('/api/lan/'+path,{method:data?'POST':'GET',headers,body:data?JSON.stringify(data):undefined,cache:'no-store',signal:AbortSignal.timeout(12000)}),body=await r.json();if(!r.ok)throw Object.assign(Error(body.error||'暂时无法连接会客厅'),{status:r.status,code:body.code});return body;}
async function command(args){if(flight)throw Error('上一项操作正在确认');const old=pending();if(old&&args.requestId!==old.requestId)throw Error('请先核对上一次操作');const body=old||{...args,requestId:crypto.randomUUID()},cache=storage();if(!old)cache.setItem('pending-room-command',JSON.stringify(body));flight++;try{const r=await request('action',body);cache.removeItem('pending-room-command');view=r.view;render(true);return r;}catch(e){lastError=e.message;if(e.code&&e.status<500)cache.removeItem('pending-room-command');throw e;}finally{flight--;}}
const act=fn=>async e=>{e?.preventDefault();try{await fn()}catch(e){toast(e.message);const status=document.getElementById('lanFormStatus');if(status)status.textContent=e.message;render();}};
const personalSteward=createPersonalStewardUI({context:()=>view?.me,toast});
const activityUI=createLanActivitiesUI({context:()=>view,toast});
const socialUI=createLanSocialUI({context:()=>view});
function auth(tab='login'){socialUI.clear();personalSteward.clear();activityUI.clear();mode=tab;view=null;map?.destroy();map=null;stopPoll();signature='';bar.innerHTML='';document.body.dataset.theme='origami';root.innerHTML='<div class="lan-auth-grid"><section class="lan-card lan-welcome"><small>COME AS AN ISLANDER</small><h2>一起在小岛走走。</h2><p>带上自己的名字和小岛，分享一个午后的故事。主办方可以先开两人房，再添两把椅子。</p>'+avatarPortrait('female_0','origami')+'<ol><li>创建自己的岛主身份</li><li>用口令加入朋友的会客房</li><li>走在同一座岛上，再回自己的岛制作</li></ol></section><section class="lan-card"><div class="lan-tabs"><button id="lanLoginTab" class="'+(tab==='login'?'active':'')+'">回到我的小岛</button><button id="lanRegisterTab" class="'+(tab==='register'?'active':'')+'">初次来到这里</button></div><form id="lanAuthForm"><label>登录名<input id="lanLogin" autocomplete="username" minlength="3" maxlength="24" required placeholder="英文、数字、下划线"></label><label>密码<input id="lanPassword" type="password" autocomplete="'+(tab==='register'?'new-password':'current-password')+'" minlength="8" maxlength="128" required></label>'+
 (tab==='register'?'<div class="lan-fields"><label>岛主名字<input id="lanName" minlength="2" maxlength="24" required placeholder="你想让朋友怎样称呼你"></label><label>小岛名字<input id="lanIsland" minlength="2" maxlength="32" required placeholder="给你的岛取个名字"></label><label>画风<select id="lanTheme"><option value="origami">折纸</option><option value="pixel">像素</option></select></label><label>形象<select id="lanAvatar">'+AVATARS.map(a=>'<option value="'+a.id+'">'+esc(a.gender+' · '+a.name)+'</option>').join('')+'</select></label></div><div id="lanAvatarPreview" class="lan-avatar-preview"></div><label>主办方加入码<input id="lanEnrollment" minlength="8" maxlength="80" required autocomplete="off"></label>':'')+
 '<p class="lan-form-status" id="lanFormStatus" role="status"></p><button class="primary" type="submit" id="lanAuthSubmit">'+(tab==='register'?'建立我的小岛身份':'进入会客厅')+'</button></form><p class="lan-auth-note">这里用于会客、同行与聊天。每位岛主的采集、制作与共创存档分别保留；可以发布携物与主题穿着要求、保留准备时间、完成活动挑战，并留下真实参与评价。</p></section></div>';
 document.getElementById('lanLoginTab').onclick=()=>auth('login');document.getElementById('lanRegisterTab').onclick=()=>auth('register');const input=id=>document.getElementById(id).value;
 if(tab==='register'){const preview=()=>document.getElementById('lanAvatarPreview').innerHTML=avatarThumbnail(input('lanAvatar'),input('lanTheme'));document.getElementById('lanTheme').onchange=preview;document.getElementById('lanAvatar').onchange=preview;preview();}
 document.getElementById('lanAuthForm').onsubmit=async e=>{e.preventDefault();const button=document.getElementById('lanAuthSubmit');button.disabled=true;try{const args={login:input('lanLogin'),password:input('lanPassword')};if(tab==='register')Object.assign(args,{name:input('lanName'),islandName:input('lanIsland'),avatar:input('lanAvatar'),theme:input('lanTheme'),enrollmentKey:input('lanEnrollment')});const r=await request(tab,args);view=r.view;render(true);startPoll();}catch(e){document.getElementById('lanFormStatus').textContent=e.message;}finally{if(button.isConnected)button.disabled=false;}};
}
function render(force=false){if(!view)return;activityUI.setContext(view);socialUI.setContext(view);const v=view,r=v.room,key=JSON.stringify({travel:v.travel,me:v.me,rooms:v.rooms,room:r&&{id:r.id,revision:r.revision,chat:r.chat.at(-1)?.id,members:r.members.map(m=>[m.id,m.profile,m.position.online])},pending:pending()?.requestId});map?.setView(v);if(!force&&key===signature)return;signature=key;const travelExpanded=!!root.querySelector('#lanTravelChoices')?.open;const fields=[...root.querySelectorAll('input,select,textarea')].filter(e=>e.id&&e.type!=='password').map(e=>[e.id,e.value,e===document.activeElement]);document.body.dataset.theme=r?.theme||v.me.profile.theme;bar.innerHTML='<b>'+esc(v.me.profile.name)+' · '+esc(v.me.profile.islandName)+'</b><a class="lan-button" href="/play" id="lanMyIsland">回自己的小岛</a><button id="lanStewardOpen">随行管家</button><button id="lanLogout">退出身份</button>';if(r)document.getElementById('lanMyIsland').onclick=e=>{e.preventDefault();toast('请先结束会客或回会客厅，同行队伍会一起返回原岛');};document.getElementById('lanStewardOpen').onclick=()=>personalSteward.open();document.getElementById('lanLogout').onclick=act(async()=>{if(flight||pending()||activityUI.busy()||personalSteward.busy())throw Error('请先核对正在确认的操作');await request('logout',{});auth();});
 if(!r){map?.destroy();map=null;mode='lobby';root.innerHTML=travelPreparationMarkup(v)+(pending()?'<section class="lan-card"><h3>上次操作结果待核对</h3><p>重新连接后按原请求确认，不会多开一间房或重复聊天。</p><button class="primary" id="lanRetry">核对上次操作</button></section>':'')+'<div class="lan-lobby-grid"><section class="lan-card"><small>HOST A QUIET AFTERNOON</small><h2>在我的岛会客</h2><form id="lanCreateForm"><label>会客房名字<input id="lanRoomTitle" minlength="2" maxlength="40" value="'+esc(v.me.profile.islandName+'的午后')+'" required></label><label>座位<select id="lanCapacity"><option value="2">两位岛主</option><option value="4">四位岛主</option></select></label><button class="primary" type="submit">布置会客房</button></form><hr><form id="lanJoinForm"><label>朋友的邀请口令<input id="lanJoinCode" autocomplete="off" maxlength="12" required placeholder="12位邀请口令"></label><button type="submit">前往朋友的小岛</button></form><p id="lanFormStatus" class="lan-form-status"></p></section><section class="lan-card"><div class="lan-space-between"><h2>正在会客的小岛</h2><button id="lanRefresh">刷新</button></div><div class="lan-room-list">'+(v.rooms.length?v.rooms.map(r=>'<article class="lan-room-summary"><small>'+(r.theme==='pixel'?'像素':'折纸')+' · '+r.count+' / '+r.maxPlayers+' 席</small><h3>'+esc(r.title)+'</h3><p>'+esc(r.owner.profile.name)+' · '+esc(r.owner.profile.islandName)+'</p><p>向主办岛主获取邀请口令，再入席。</p></article>').join(''):'<p class="lan-empty">海风正好。开一间会客房，邀请第一位朋友来坐坐。</p>')+'</div><div class="lan-link-row"><a class="lan-button primary" href="/play">去自己的小岛采集与制作</a></div></section></div>';
 document.getElementById('lanCreateForm').onsubmit=act(()=>command({operation:'room_create',title:document.getElementById('lanRoomTitle').value,maxPlayers:Number(document.getElementById('lanCapacity').value)}));document.getElementById('lanJoinForm').onsubmit=act(()=>command({operation:'room_join',code:document.getElementById('lanJoinCode').value,entry:'harbor'}));document.getElementById('lanRefresh').onclick=act(refresh);
 }else{mode='room';const owner=r.owner===v.me.id,oldCanvas=root.querySelector('#lanMapCanvas'),reuse=map&&map.roomId===r.id;const mapParent=oldCanvas?.parentElement;
 root.innerHTML=(new URLSearchParams(location.search).get('resume')==='travel'?'<section class="lan-card" id="lanTravelResume" role="status"><h3>你的同行队伍还在岛上</h3><p>已恢复原来的行程与角色。结束会客或回会客厅后，可以回到自己的小岛继续采集与制作。</p></section>':'')+(pending()?'<section class="lan-card"><h3>操作待核对</h3><button class="primary" id="lanRetry">核对上次操作</button></section>':'')+'<div class="lan-room-layout"><section class="lan-card lan-map-panel"><div class="lan-map-heading"><div><h2>'+esc(r.title)+'</h2><p>'+r.members.length+' / '+r.maxPlayers+' 位岛主 · '+(r.theme==='pixel'?'像素岛':'折纸岛')+'</p></div><span id="lanConnection">海风传信 · 已连接</span></div><div class="lan-map-stage" id="lanMapStage"><canvas id="lanMapCanvas" aria-label="点击道路，与朋友在会客小岛同行"></canvas><div class="lan-map-tools"><button id="lanZoomOut" aria-label="缩小">−</button><span id="lanZoomValue">100%</span><button id="lanZoomIn" aria-label="放大">+</button><button id="lanZoomReset">全岛</button></div></div><p class="lan-map-note">点击道路自动绕开建筑。拖动画面、滚轮缩放；这是同行会客地图。临时伙伴可在双方认可后参加客岛共同试作；日常采集与制作请回自己的小岛。</p></section><aside class="lan-room-sidebar"><section class="lan-card"><small>INVITE A FRIEND</small><h3>你的岛上，还有空椅子。</h3><p class="lan-room-code" id="lanInviteCode">'+esc(r.code)+'</p><button id="lanCopyCode">复制邀请口令</button><div class="lan-room-actions">'+(owner?(r.maxPlayers===2?'<button id="lanExpand">再添两把椅子</button>':'')+'<button id="lanCloseRoom">结束会客</button>':'<button id="lanLeaveRoom">回会客厅</button>')+'</div></section><section class="lan-card"><h3>已入席的岛主</h3><div class="lan-members">'+r.members.map(m=>'<article class="lan-member">'+avatarThumbnail(m.profile.avatar,r.theme)+'<div><b>'+esc(m.profile.name)+(m.id===v.me.id?' · 你':'')+'</b><small>'+esc(m.profile.islandName)+' · '+(m.id===r.owner?'主办岛主':m.position.online?'在岛上':'暂时离线')+'</small></div>'+memberCompanionsMarkup(m,r.theme)+'</article>').join('')+'</div></section><section class="lan-card"><h3>海风里的聊天</h3><div class="lan-chat-list" id="lanChatList">'+(r.chat.length?r.chat.map(x=>'<p><b>'+esc(x.name)+'</b>'+esc(x.message)+'</p>').join(''):'<p>给朋友留一句欢迎的话吧。</p>')+'</div><form class="lan-chat-form" id="lanChatForm"><input id="lanChatText" aria-label="聊天内容" maxlength="240" required placeholder="写给岛上的朋友"><button type="submit">发送</button></form></section></aside></div>';
 if(reuse){const canvas=root.querySelector('#lanMapCanvas');canvas.replaceWith(oldCanvas);map.reattach(root.querySelector('#lanMapStage'));map.setView(v);}else{map?.destroy();map=createLanMap(root.querySelector('#lanMapCanvas'),{view:v,move:(x,y)=>act(()=>command({operation:'room_move',roomId:view.room.id,x,y}))(),toast});}
 document.getElementById('lanCopyCode').onclick=act(async()=>{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(r.code);toast('邀请口令已复制');}else{const range=document.createRange();range.selectNodeContents(document.getElementById('lanInviteCode'));const sel=getSelection();sel.removeAllRanges();sel.addRange(range);toast('已选中口令，请复制后分享给朋友');}});
 document.getElementById('lanExpand')?.addEventListener('click',act(()=>command({operation:'room_resize',roomId:view.room.id,expectedRevision:view.room.revision,maxPlayers:4})));document.getElementById('lanCloseRoom')?.addEventListener('click',act(()=>command({operation:'room_close',roomId:view.room.id,expectedRevision:view.room.revision})));document.getElementById('lanLeaveRoom')?.addEventListener('click',act(()=>command({operation:'room_leave',roomId:view.room.id,expectedRevision:view.room.revision})));document.getElementById('lanChatForm').onsubmit=act(async()=>{const input=document.getElementById('lanChatText');await command({operation:'room_chat',roomId:view.room.id,message:input.value});const next=document.getElementById('lanChatText');if(next)next.value='';});document.getElementById('lanChatList').scrollTop=document.getElementById('lanChatList').scrollHeight;
 document.getElementById('lanZoomIn').onclick=()=>map.zoomBy(1.2);document.getElementById('lanZoomOut').onclick=()=>map.zoomBy(1/1.2);document.getElementById('lanZoomReset').onclick=()=>map.reset();
 }
 if(travelExpanded&&root.querySelector('#lanTravelChoices'))root.querySelector('#lanTravelChoices').open=true;root.querySelectorAll('[data-travel-npc]').forEach(b=>b.onclick=act(()=>command({operation:b.dataset.travelOperation,npcId:Number(b.dataset.travelNpc)})));
 const retry=document.getElementById('lanRetry');if(retry)retry.onclick=act(async()=>{await command(pending());toast('上次会客操作已核对');});for(const[id,value,focused]of fields){const el=document.getElementById(id);if(el){el.value=value;if(focused)el.focus({preventScroll:true});}}
}
async function refresh(){if(refreshing||flight)return;refreshing=true;try{const r=await request('view');view=r.view;lastError='';render();}catch(e){lastError=e.message;if(e.code==='lan_scope_changed'){location.reload();return;}if(e.status===401){auth();return;}const status=document.getElementById('lanConnection');if(status)status.textContent='连接暂缓 · 稍后重试';}finally{refreshing=false;}}
function startPoll(){stopPoll();poll=setInterval(refresh,500);}function stopPoll(){clearInterval(poll);poll=null;}
if(new URLSearchParams(location.search).has('qa'))window.lanInspect=()=>({activities:activityUI.inspect(),view,mode,flight,pending:pending(),lastError,map:map?.inspect()});
await artReady;await refresh();if(view)startPoll();else auth();
window.addEventListener('pagehide',()=>{stopPoll();map?.destroy();activityUI.clear();socialUI.destroy();});

window.hdLanPane={traveling:()=>!!view?.room,busy:()=>flight>0||activityUI.busy()||!!pending()};if(new URLSearchParams(location.search).has('embedded')){document.body.classList.add('lan-embedded');window.addEventListener('keydown',e=>{if(e.key==='Escape'&&!window.hdLanPane.busy())parent.postMessage({type:'hd-lan-return'},location.origin);});}
