import {validCooperationSnapshot} from './cooperationEvidence.js';
import{PARTY_TAGS,THEME_GUESTS}from'./partyPlanning.js';
import{ITEM_BY_ID}from'./contentCatalog.js';
import{eventRequests,eventCost,validatePartyProposal,partyInputSignature,partyDraftStamp}from'./partyPlanning.js';
import{availableQuantity,nextOperationId,commitResources}from'./resourceLedger.js';
import{createProject,syncProjects,controlProject}from'./projectPlans.js';
import{relationshipInvitation}from'./residentStories.js';
import{trackJourney}from'./journey.js';
import {validStewardPartyMetadata,validStewardPartyReceipts} from './partyReceipts.js';
export function hydrateNightParty(s){return s.nightParty??={version:1,draft:null,history:[]};}
export function nightSnapshot(s){const f=structuredClone(hydrateNightParty(s));delete f.composer;return f;}
export function createNightEvent(s,input={}){const f=hydrateNightParty(s);if(f.draft||s.partySession)return{ok:false,reason:'先结束当前夜集或取消筹备'};const checked=validatePartyProposal(s,{name:'星灯夜集',...input,template:'night'});if(!checked.ok)return checked;f.draft={id:nextOperationId(s,'night').replace(':','-'),...checked.proposal,version:1,createdDay:s.day,invites:{},inviteGifts:{},revisions:[],projectId:null,projectIds:[],source:'player',runId:null,proposalId:null};s.partyInvites={};return{ok:true,event:f.draft};}
export function updateNightEvent(s,input){const f=hydrateNightParty(s),d=f.draft;if(!d||s.partySession)return{ok:false,reason:'夜集方案不能在开场后改动'};const checked=validatePartyProposal(s,{...input,template:'night'});if(!checked.ok)return checked;const change=partyInputSignature(d)!==partyInputSignature(checked.proposal),before=partyDraftStamp(d);Object.assign(d,checked.proposal,{source:'player',runId:null,proposalId:null});if(change){d.version++;d.invites={};s.partyInvites={};d.revisions.push({version:d.version,day:s.day,before});d.revisions=d.revisions.slice(-20);if(d.projectId){const p=s.workProjects?.find(p=>p.id===d.projectId);if(p&&['preparing','paused','ready'].includes(p.status))controlProject(s,p.id,'cancel');d.projectId=null;}}return{ok:true,event:d,reinvite:change};}
export function nightNeeds(s){const d=hydrateNightParty(s).draft;if(!d)return null;const cost={...eventCost(d)};for(const r of eventRequests(d))if(!d.inviteGifts[r.id]?.delivered?.[r.item])cost[r.item]=(cost[r.item]||0)+r.quantity;return{cost,missing:Object.fromEntries(Object.entries(cost).map(([id,n])=>[id,Math.max(0,n-availableQuantity(s,id,d.projectId?'project:'+d.projectId:null))]).filter(([,n])=>n))};}
export function releaseNightPlan(s,d){if(!d.projectId)return;syncProjects(s,{server:true});const p=s.workProjects?.find(p=>p.id===d.projectId);if(p?.status==='ready')controlProject(s,p.id,'finish');}
export function createNightPlan(s){const d=hydrateNightParty(s).draft;if(!d)return{ok:false,reason:'先发布夜集方案'};const p=s.workProjects?.find(p=>p.id===d.projectId);if(p&&['preparing','paused','ready'].includes(p.status))return{ok:true,replayed:true,project:p};const targets={...nightNeeds(s).cost};delete targets.coins;const r=createProject(s,{id:nextOperationId(s,'night-supplies').replace(':','-'),title:d.name+' · 物资筹备',targets,source:d.source==='hermes'?'hermes':'player',runId:d.runId||null});if(r.ok){d.projectId=r.project.id;d.projectIds=[...new Set([...d.projectIds,r.project.id])];}return r;}
export function inviteNightNpc(s,id){const d=hydrateNightParty(s).draft,r=d&&eventRequests(d).find(r=>r.id===id);if(!r)return{ok:false,reason:'这位居民不在当前夜集的邀请名单'};if(d.invites[id]?.version===d.version)return{ok:true,replayed:true};const willing=relationshipInvitation(s,id,eventRequests(d).map(r=>r.id));if(!willing.ready)return{ok:false,reason:willing.reason};releaseNightPlan(s,d);const prior=d.inviteGifts[id];if(!prior?.delivered?.[r.item]){const paid=commitResources(s,{id:'night-gift:'+d.id+':'+id+':'+r.item,cost:{[r.item]:r.quantity},category:'party_invite',note:'夜集邀请物资'});if(!paid.ok)return{ok:false,reason:'约好的物资还未准备好，或已留给其他筹备'};d.inviteGifts[id]={delivered:{...(prior?.delivered||{}),[r.item]:r.quantity},day:s.day,affinityGranted:true};s.npcAffinity??={};s.npcAffinity[id]=Math.min(100,(s.npcAffinity[id]??20)+1);}d.invites[id]={version:d.version,day:s.day};s.partyInvites??={};s.partyInvites[id]=true;trackJourney(s,'invite');return{ok:true,npcId:id,version:d.version};}
export function nightReadiness(s){const d=hydrateNightParty(s).draft;if(!d)return{ready:false,reason:'先发布夜集方案'};const people=eventRequests(d);const waiting=people.find(r=>d.invites[r.id]?.version!==d.version);if(waiting)return{ready:false,reason:'先亲自对话邀请所有关键居民'};const block=people.map(r=>relationshipInvitation(s,r.id,people.map(p=>p.id))).find(r=>!r.ready);if(block)return{ready:false,reason:block.reason};if(s.fireworksParty?.session?.phase==='running'||s.coutureParty?.session?.phase==='running'||s.partySession||['checkin','running'].includes(s.fishingParty?.session?.phase))return{ready:false,reason:'先结束正在进行的活动'};if(s.lastPartyDay===s.day)return{ready:false,reason:'今天的承办机会已经使用'};const cost=eventCost(d);const owner=d.projectId?'project:'+d.projectId:null;if(Object.entries(cost).some(([id,n])=>availableQuantity(s,id,owner)<n))return{ready:false,reason:'还需要备齐本场实际投入'};return{ready:true,event:d};}
export function cancelNightDraft(s){const f=hydrateNightParty(s),d=f.draft;if(!d||s.partySession)return{ok:false,reason:'当前夜集不能取消筹备'};if(d.projectId){const p=s.workProjects?.find(p=>p.id===d.projectId);if(p&&['preparing','paused','ready'].includes(p.status))controlProject(s,p.id,'cancel');}f.history.push({...d,phase:'cancelled',endedDay:s.day,paid:0});f.history=f.history.slice(-20);f.draft=null;s.partyInvites={};return{ok:true,text:'筹备已取消，已送出的邀请物品留给居民；其他物资保留。'};}
export function completeNightDraft(s,t,outcome,reward,score){const f=hydrateNightParty(s),d=f.draft;if(!t.design||d?.id!==t.design.id)return;const result={...structuredClone(t.design),eventId:t.eventId,entryReceiptId:t.entryReceiptId??null,outfit:t.outfit,phase:outcome,endedDay:s.day,paid:reward,score};f.history.push(result);f.history=f.history.slice(-20);f.draft=null;s.partyInvites={};}
const record=v=>v&&typeof v==='object'&&!Array.isArray(v),positive=v=>Number.isSafeInteger(v)&&v>0,id=v=>typeof v==='string'&&/^[a-zA-Z0-9_-]{1,100}$/.test(v),npc=v=>/^(?:[0-9]|1[0-5])$/.test(v);
function validNightDesign(d){
 if(!record(d)||!validCooperationSnapshot(d.cooperation)||!validStewardPartyMetadata(d)||!id(d.id)||d.template!=='night'||!positive(d.version)||!positive(d.createdDay)||typeof d.name!=='string'||!d.name.trim()||d.name.length>24||typeof d.description!=='string'||d.description.length>200||!['normal','easy'].includes(d.difficulty)||!Array.isArray(d.tags)||d.tags.length>2||new Set(d.tags).size!==d.tags.length||d.tags.some(t=>!PARTY_TAGS.some(p=>p.id===t))||typeof d.fireworks!=='boolean'||typeof d.guestReason!=='string'||d.guestReason.length>180||d.guestId!==null&&!THEME_GUESTS.some(g=>g.id===d.guestId&&g.tags.some(t=>d.tags.includes(t))))return false;
 const invited=new Set(eventRequests(d).map(r=>String(r.id)));
 if(!record(d.invites)||Object.entries(d.invites).some(([n,v])=>!invited.has(n)||!record(v)||!positive(v.version)||v.version>d.version||!positive(v.day)))return false;
 if(!record(d.inviteGifts)||Object.entries(d.inviteGifts).some(([n,v])=>!npc(n)||!record(v)||!positive(v.day)||v.affinityGranted!==true||!record(v.delivered)||!Object.keys(v.delivered).length||Object.entries(v.delivered).some(([item,count])=>!ITEM_BY_ID[item]||!positive(count)||count>99)))return false;
 return (d.projectId===null||id(d.projectId))&&Array.isArray(d.projectIds)&&d.projectIds.length<=40&&new Set(d.projectIds).size===d.projectIds.length&&d.projectIds.every(id)&&(!d.projectId||d.projectIds.includes(d.projectId))&&Array.isArray(d.revisions)&&d.revisions.length<=20&&d.revisions.every(r=>record(r)&&positive(r.version)&&r.version<=d.version&&positive(r.day)&&typeof r.before==='string'&&r.before.length<=1000);
}
export function validNightParty(s){const f=s.nightParty;if(f===undefined)return true;return !!(record(f)&&validStewardPartyReceipts(f,'night')&&f.version===1&&(f.draft===null||validNightDesign(f.draft))&&Array.isArray(f.history)&&f.history.length<=20&&f.history.every(h=>validNightDesign(h)&&['finished','cancelled'].includes(h.phase)&&positive(h.endedDay)&&Number.isSafeInteger(h.paid)&&h.paid>=0&&(h.phase!=='finished'||Number.isInteger(h.score)&&h.score>=0&&h.score<=4)));}
