import {worldFetch as fetch} from './worldSession.js';
import {wonderRewardMarkup} from './wonderRewardUI.js';
import {cooperationMarkup} from './cooperationUI.js';
import {modalNavigationToken} from './modalNavigation.js';
import{hydrateNightParty,nightNeeds,nightReadiness}from'./nightPartyPlanning.js';
import{eventRequests,eventCost,partyDraftStamp,PARTY_TAGS}from'./partyPlanning.js';
import{mountPartyDesigner}from'./partyDesigner.js';import{itemMarkup,artReady}from'./artStore.js';import{ITEM_BY_ID}from'./contentCatalog.js';import{availableQuantity}from'./resourceLedger.js';import{relationshipInvitation}from'./residentStories.js';import{esc}from'./journeyUI.js';
export function createNightPartyUI({state,theme,profile,portrait,openModal,toast,persist,command,back,start,collections=()=>{}}){
let busy=false;const capture=()=>({theme:theme(),slot:state().saveSlot}),live=c=>theme()===c.theme&&state().saveSlot===c.slot;const q=id=>document.getElementById(id);
const args=()=>{const d=hydrateNightParty(state()).draft;return{eventId:d?.id||null,eventVersion:d?.version||null,eventStamp:partyDraftStamp(d)};};
async function ensure(){await command('night_enable');}
async function call(op,extra={}){if(busy)throw Error('先等本次操作确认');busy=true;try{return(await command(op,{...args(),...extra})).receipt?.details;}finally{busy=false;}}
async function open(){const c=capture(),navigation=modalNavigationToken();try{await ensure();if(!live(c)||!navigation.current())return;const s=state(),d=hydrateNightParty(s).draft;if(s.partySession){start();return;}openModal(d?.name||'星灯夜集手账','给相聚一个主题，亲自邀请，再沿道路赴约。','<div id="nightBoard"></div>','<button class="secondary" id="nightBack">返回派对</button>');q('nightBack').onclick=back;paint(true);}catch(e){toast(e.message);}}
function paint(){if(busy)return;const root=q('nightBoard');if(!root)return;const s=state(),f=hydrateNightParty(s),d=f.draft,n=d?nightNeeds(s):null,r=d?nightReadiness(s):null;
const featured=f.history.slice().reverse().find(h=>h.phase==='finished'&&wonderRewardMarkup(s,h,theme())),featuredId=featured&&(featured.eventId||featured.id);
root.innerHTML=(featured?'<section class="fishing-prep wonder-featured-result"><small>本场相聚 · 已完成</small><h4>'+esc(featured.name)+'</h4><p>精准 '+featured.score+'/4 · 收入 '+featured.paid+' 岛币</p>'+wonderRewardMarkup(s,featured,theme())+'<button class="primary" id="nightCollections">查看收藏 · 陈列本场纪念品</button></section>':'')+'<section class="fishing-hero"><div><small>THE STARLIGHT GATHERING</small><h3>四盏星灯<br>今夜一起放飞</h3><p>先送达约好的物品，等大家收尾工作、各自站定，再把今晚的心愿一起放飞。</p><span>广场相聚 · 20–28 岛币 · 主题穿着 +2 · 烟花 +3</span></div><div class="night-hero-art">'+itemMarkup('lantern',theme(),'night-symbol')+'</div></section>'+
(!d?'<section class="fishing-create"><h4>发起一场有主题的夜集</h4><p>阿岚与露露是关键居民。可以再请一位符合主题的嘉宾。每人通过对话提出具体条件，确认后才参加。</p><button class="primary" id="nightBasic">发布基础夜集</button><button class="secondary" id="nightDesign">设计主题与嘉宾</button></section>':
'<section class="fishing-prep"><h4>'+esc(d.name)+' · 第 '+d.version+' 版</h4><p>'+esc(d.description||'一起把认真准备的星灯，放进海岛夜空。')+'</p><div class="party-preview-people">'+eventRequests(d).map(p=>'<article><div class="party-preview-portrait">'+portrait(p.id)+'</div><div><b>'+esc(profile(p.id).name)+'</b><small>'+esc(p.role)+'</small><span>'+itemMarkup(p.item,theme(),'fishing-item')+esc(ITEM_BY_ID[p.item].name)+' ×'+p.quantity+(d.inviteGifts[p.id]?.delivered?.[p.item]?' · 已送达':' · 待送达')+'</span><button class="secondary" data-night-invite="'+p.id+'">'+(d.invites[p.id]?.version===d.version?'已确认本版 · 查看约定':'前往对话邀请')+'</button></div></article>').join('')+'</div><h5>本场实际投入</h5><div class="material-costs">'+Object.entries(eventCost(d)).map(([id,num])=>'<span>'+(id==='coins'?'组织费 8 岛币':itemMarkup(id,theme(),'fishing-item')+esc(ITEM_BY_ID[id].name)+' ×'+num)+'</span>').join('')+'</div><p class="hint" id="nightReady">'+esc(r.reason||'物资与当前版本同意都已准备好，可以开场。')+'</p><p>'+(d.projectId?'筹备编号 '+esc(d.projectId)+' · 已预留物资由服务端核对':'可让管家按实际配方，把物资缺口派给对应职业的居民。')+'</p><div class="night-party-actions"><button class="primary" id="nightStart" '+(!r.ready?'disabled':'')+'>开场 · 四盏星灯</button><button class="secondary" id="nightPlan">请管家筹备物资</button><button class="secondary" id="nightDesign">修改主题方案</button><button class="secondary" id="nightCancelDraft">取消筹备</button></div><p class="mini-explain">修改主题、难度、嘉宾或烟花会产生新版本，必须重新确认参加；同一物品已送达后不会再次扣除。仅改名称保留同意。</p></section>')+
(f.history.length?'<section class="fishing-prep"><h4>岛上相聚的记忆</h4>'+f.history.slice(-8).reverse().map(h=>'<article><p>'+esc(h.name)+' · 第 '+(h.endedDay||h.createdDay)+' 天 · '+(h.phase==='finished'?'精准 '+h.score+'/4 · 收入 '+h.paid+' 岛币':h.phase==='cancelled'?'已结束，保留已有物资':'已记录')+'</p>'+((h.eventId||h.id)===featuredId?'':wonderRewardMarkup(s,h,theme()))+cooperationMarkup(s,h,theme())+'</article>').join('')+(featured?'':'<button class="secondary" id="nightCollections">查看纪念 · 去收藏册陈列</button>')+'</section>':'');
if(q('nightCollections'))q('nightCollections').onclick=collections;
if(q('nightBasic'))q('nightBasic').onclick=async()=>{try{await call('night_create',{proposal:{template:'night',name:'星灯夜集',tags:['stars'],difficulty:'normal',guestId:null,description:'',fireworks:false}});open();}catch(e){toast(e.message);}};
q('nightDesign').onclick=design;
if(d){root.querySelectorAll('[data-night-invite]').forEach(b=>b.onclick=()=>invite(Number(b.dataset.nightInvite)));q('nightPlan').onclick=async()=>{try{const a=await call('night_plan');toast(a.text);open();}catch(e){toast(e.message);}};q('nightCancelDraft').onclick=async()=>{try{const a=await call('night_cancel');toast(a.text);open();}catch(e){toast(e.message);}};q('nightStart').onclick=()=>start(d);}
}
async function design(){const c=capture(),navigation=modalNavigationToken();try{await ensure();if(!live(c)||!navigation.current())return;openModal('为星灯夜集写一封邀请','主题与嘉宾会产生真实筹备和对话约定。','<div id="nightDesigner"></div>');mountPartyDesigner(q('nightDesigner'),{state,theme,profile,portrait,persist,toast,template:'night',getPartyState:hydrateNightParty,onPublished:open,publish:async(p,expected)=>call(expected.expectedId?'night_update':'night_create',{proposal:p,eventId:expected.expectedId,eventVersion:expected.expectedVersion,eventStamp:expected.expectedStamp}),request:async(input,expected)=>{persist();const response=await fetch('/api/parties/'+theme()+'/suggest',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId:crypto.randomUUID(),worldKey:state().saveSlot,input,...expected}),signal:AbortSignal.timeout(30000)});const data=await response.json();if(!response.ok)throw Error(data.error||'主题建议暂时不可用');return data;}});}catch(e){toast(e.message);}}
async function invite(id){const c=capture(),navigation=modalNavigationToken();try{await ensure();if(!live(c)||!navigation.current())return;let d=hydrateNightParty(state()).draft;if(!d){await call('night_create',{proposal:{template:'night',name:'星灯夜集',description:'',tags:['stars'],difficulty:'normal',guestId:null,fireworks:false}});d=hydrateNightParty(state()).draft;}const p=eventRequests(d).find(p=>p.id===id);if(!p){toast('这位居民不在当前夜集的邀请名单');return;}const gift=!!d.inviteGifts[id]?.delivered?.[p.item],confirmed=d.invites[id]?.version===d.version,w=relationshipInvitation(state(),id,eventRequests(d).map(r=>r.id));openModal(profile(id).name+' · 夜集之约',d.name+' · 第 '+d.version+' 版','<div class="conversation-stage"><aside class="character-stage">'+portrait(id)+'</aside><article class="conversation-body"><blockquote class="dialogue-bubble">'+esc(confirmed?'我已经答应参加这版夜集。收好手边的工作，就到广场的专属位置等你。':p.request)+'</blockquote><p>'+itemMarkup(p.item,theme(),'fishing-item')+esc(ITEM_BY_ID[p.item].name)+' ×'+p.quantity+' · '+(gift?'已送达，重新确认不再扣除':'实际送达后确认参加')+'</p><p>'+esc(w.ready?'确认参加当前版本以后，才会在开场时赴约。':w.reason)+'</p></article></div>','<button class="secondary" id="nightInviteBack">返回手账</button><button class="primary" id="nightInviteConfirm" '+(confirmed||!w.ready||!gift&&availableQuantity(state(),p.item,d.projectId?'project:'+d.projectId:null)<p.quantity?'disabled':'')+'>'+(confirmed?'本版已确认':gift?'确认参加新版本':'送达物品并邀请')+'</button>');q('nightInviteBack').onclick=open;const inviteButton=q('nightInviteConfirm');inviteButton.onclick=async()=>{try{if(!live(c)||!inviteButton.isConnected)return;inviteButton.disabled=true;await call('night_invite',{npcId:id,eventId:d.id,eventVersion:d.version,eventStamp:partyDraftStamp(d)});if(!live(c)||!inviteButton.isConnected)return;toast(profile(id).name+'确认参加当前版本');open();}catch(e){if(live(c)&&inviteButton.isConnected){toast(e.message);invite(id);}}};}catch(e){toast(e.message);}}
artReady.then(()=>paint()).catch(()=>{});
return{open,design,invite,paint,inspect:()=>({busy,draft:hydrateNightParty(state()).draft})};
}
