const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>new Date(v).toLocaleString('zh-CN',{hour12:false});
export function createPortfolioUI({theme,openModal,toast,root=()=>document.getElementById('modalRoot'),api='/api/portfolio',headers=()=>({}),name=()=>'',scope=()=>''}){
 let data=null,edit=null,tab='gallery',session=0,busy=false,pending=null,cache=null,inflight=null,epoch=0;
 const cacheKey=()=>api+'|'+JSON.stringify(headers())+'|'+scope();
 const remember=value=>{cache={key:cacheKey(),value,at:Date.now()};};
 async function request(path='',body){const r=await fetch(api+path,{method:body?'POST':'GET',headers:{...headers(),...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,cache:'no-store',signal:AbortSignal.timeout(30000)}),d=await r.json();if(!r.ok)throw Object.assign(Error(d.error||'会客馆暂时无法连接'),{code:d.code});if(body){epoch++;remember(d);}return d;}
 async function load(force=false){const key=cacheKey();if(!force&&cache?.key===key&&Date.now()-cache.at<30000)return cache.value;if(inflight?.key===key)return inflight.promise;const version=epoch,promise=request().then(value=>{if(cacheKey()===key&&version===epoch)remember(value);return version===epoch?value:cache?.key===key?cache.value:value;}).finally(()=>{if(inflight?.promise===promise)inflight=null;});inflight={key,promise};return promise;}
 async function preload(){try{const d=await load();const urls=['/assets/gallery-'+skin()+'.png',...(d.published?.projects||[]).flatMap(p=>p.files).map(id=>d.assets.find(a=>a.id===id)).filter(a=>a?.type.startsWith('image/')).slice(0,3).map(fileURL)];for(const url of urls){const im=new Image();im.decoding='async';im.src=url;im.decode().catch(()=>{});}return true;}catch{return false;}}
 const skin=()=>theme()==='origami'?'origami':'pixel';
 const icon=kind=>'<img decoding="async" class="portfolio-ui-icon" src="/assets/ui-hud-v59/'+skin()+'-'+kind+'.png" alt="" aria-hidden="true">';
 const fileURL=a=>api+'/file/'+a.id;
 const asset=id=>data.assets.find(a=>a.id===id);
 function project(p){return '<article class="portfolio-project"><div class="portfolio-project-art">'+(p.files.map(asset).filter(a=>a?.type.startsWith('image/')).slice(0,1).map(a=>'<img decoding="async" loading="lazy" src="'+fileURL(a)+'" alt="'+esc(a.name)+'">').join('')||'<div class="portfolio-frame-empty">'+icon('build')+'<small>项目展位</small></div>')+'</div><div class="portfolio-project-copy"><small class="portfolio-section-label">'+icon('build')+' PROJECT ARCHIVE · 项目档案</small><h3>'+esc(p.title)+'</h3><p class="portfolio-prose">'+esc(p.summary)+'</p>'+p.files.map(asset).filter(Boolean).map(a=>'<a class="portfolio-file" href="'+fileURL(a)+'?download=1" target="_blank" rel="noopener">'+icon('recipes')+'<span>'+esc(a.name)+'</span><small>'+Math.ceil(a.size/1024)+' KiB ↗</small></a>').join('')+(p.url?'<a class="portfolio-link" href="'+esc(p.url)+'" target="_blank" rel="noopener noreferrer">访问项目 ↗</a>':'')+'</div></article>';}
 function exhibition(p){const pictures=(p?.projects||[]).flatMap(project=>project.files.map(id=>({asset:asset(id),title:project.title}))).filter(a=>a.asset?.type.startsWith('image/')).slice(0,3);return '<section class="portfolio-room" aria-label="会客馆内部展厅"><div class="portfolio-room-art" role="img" aria-label="'+(skin()==='pixel'?'像素':'折纸')+'风海岛展馆内部"><span class="portfolio-gallery-plaque">ISLANDER’S GALLERY · 海风展馆</span></div><div class="portfolio-welcome"><span class="portfolio-section-label">'+icon('role')+' 来我的岛，读一段故事</span><h3>'+esc(p?.name||'岛主会客馆')+'</h3><p>'+esc(p?.headline||'每一段经历，都有自己的展位。')+'</p><div class="portfolio-room-frames">'+[0,1,2].map(i=>'<figure class="portfolio-room-frame">'+(pictures[i]?'<img decoding="async" loading="lazy" src="'+fileURL(pictures[i].asset)+'" alt="'+esc(pictures[i].asset.name)+'">':'<div class="portfolio-frame-empty">'+icon('build')+'</div>')+'<figcaption>'+esc(pictures[i]?.title||'待布置展位')+'</figcaption></figure>').join('')+'</div><small class="portfolio-welcome-note">'+(p?'从一个想法，到一段值得分享的经历。':'收藏经历，陈列作品，留住相遇。')+'</small></div></section>';}
 function preview(p){if(!p)return exhibition(null)+'<div class="portfolio-empty"><h3>展馆正在布展</h3><p>岛主发布资料后，个人介绍、过往经历和项目会出现在这里。你现在就可以在留言板留下问候。</p></div>';if(tab==='experiences')return '<section class="portfolio-timeline"><header class="portfolio-section-heading">'+icon('recipes')+'<div><small>CHAPTERS OF A LIFE</small><h3>走过的路，都在这里</h3><p>人生、学习与工作的片段，汇成这座岛的故事。</p></div></header>'+(p.experiences.length?p.experiences.map((e,i)=>'<article><div class="portfolio-period"><small>CHAPTER '+String(i+1).padStart(2,'0')+'</small><time>'+esc(e.period)+'</time></div><div class="portfolio-timeline-card"><small class="portfolio-section-label">'+icon(e.title.startsWith('教育')?'recipes':e.title.startsWith('就业')?'workshop':'role')+esc(e.title.includes('｜')?e.title.split('｜')[0]:'人生经历')+'</small><h3>'+esc(e.title.includes('｜')?e.title.slice(e.title.indexOf('｜')+1):e.title)+'</h3><p class="portfolio-prose">'+esc(e.description)+'</p></div></article>').join(''):'<p class="portfolio-empty">经历展墙还在布置。</p>')+'</section>';if(tab==='projects')return '<div class="portfolio-projects"><header class="portfolio-section-heading">'+icon('build')+'<div><small>THINGS WE MAKE</small><h3>把想法，做成看得见的作品</h3></div></header>'+(p.projects.map(project).join('')||'<p class="portfolio-empty">项目展位等待上新。</p>')+'</div>';return exhibition(p)+'<div class="portfolio-overview">'+[['experiences','recipes',p.experiences.length,'段过往经历'],['projects','build',p.projects.length,'个历史项目'],['guestbook','lan',data.messages.length,'封海风来信']].map(([id,art,count,label])=>'<button data-tab="'+id+'">'+icon(art)+'<b>'+count+'</b><span>'+label+'<small>翻开看看 →</small></span></button>').join('')+'</div><section class="portfolio-biography"><small class="portfolio-section-label">'+icon('role')+' ABOUT THE ISLANDER · 关于岛主</small><h3>'+esc(p.name)+'</h3><p class="portfolio-prose">'+esc(p.bio||'欢迎来岛上坐坐。')+'</p></section>';}
 function board(){return '<section class="portfolio-board"><header>'+icon('lan')+'<small>LETTERS FROM THE SHORE</small><h3>给岛主留一封信</h3><p>你的岛主名字与留言时间会显示在留言板上。</p></header><form id="portfolioMessageForm"><textarea id="portfolioMessage" maxlength="1000" required placeholder="写下问候、建议，或下次合作的想法…" aria-label="给岛主留言"></textarea><button class="primary" type="submit">投递留言</button></form><div class="portfolio-letters">'+(data.messages.slice().reverse().map(m=>'<article class="portfolio-letter '+(m.hidden?'portfolio-hidden':'')+'"><header><b>'+esc(m.name)+'</b><time>'+date(m.at)+'</time>'+(m.hidden?'<span>已隐藏</span>':'')+'</header><p class="portfolio-prose">'+esc(m.text)+'</p>'+(m.reply?'<blockquote><b>岛主回复</b><p class="portfolio-prose">'+esc(m.reply)+'</p></blockquote>':'')+(data.canEdit?'<details><summary>回复与管理</summary><textarea data-reply="'+m.id+'" maxlength="1000" aria-label="岛主回复">'+esc(m.reply)+'</textarea><button data-moderate="'+m.id+'" data-hide="'+m.hidden+'">保存回复</button><button data-moderate="'+m.id+'" data-hide="'+!m.hidden+'">'+(m.hidden?'恢复展示':'隐藏留言')+'</button></details>':'')+'</article>').join('')||'<p class="portfolio-empty">还没有来信。留一句问候吧。</p>')+'</div></section>';}
 const field=(label,key,value,max,area=false)=>'<label>'+label+(area?'<textarea':'<input')+' data-field="'+key+'" maxlength="'+max+'"'+(area?'>'+esc(value)+'</textarea>':' value="'+esc(value)+'">')+'</label>';
 function editor(){return '<form id="portfolioEditor"><div class="portfolio-edit-intro"><h3>布置我的展馆</h3><p>先保存草稿，再发布给访客。已发布展馆保持上一次的公开内容。</p></div><div class="portfolio-fields">'+field('展示名字','name',edit.name,40)+field('一句话介绍','headline',edit.headline,120)+field('关于我','bio',edit.bio,6000,true)+'</div><section><header class="portfolio-edit-heading"><h3>经历展墙</h3><button type="button" id="portfolioAddExperience">＋ 添加经历</button></header><div id="portfolioExperiences">'+edit.experiences.map((e,i)=>'<article class="portfolio-edit-card" data-experience="'+i+'">'+field('时间 / 阶段','period',e.period,60)+field('经历标题','title',e.title,100)+field('经历描述','description',e.description,2000,true)+'<button type="button" data-remove-experience="'+i+'">移除这段经历</button></article>').join('')+'</div></section><section><header class="portfolio-edit-heading"><h3>历史项目</h3><button type="button" id="portfolioAddProject">＋ 添加项目</button></header><div id="portfolioProjects">'+edit.projects.map((p,i)=>'<article class="portfolio-edit-card" data-project="'+i+'">'+field('项目名字','title',p.title,100)+field('项目介绍','summary',p.summary,3000,true)+field('项目链接（可选）','url',p.url,1000)+'<div class="portfolio-upload-row"><label>上传图片 / PDF / 文本 <input type="file" data-upload="'+i+'" accept=".png,.jpg,.jpeg,.webp,.pdf,.txt"></label><small>单件 8 MiB · 展馆总计 64 MiB</small></div><div class="portfolio-file-choices">'+data.assets.map(a=>'<label><input type="checkbox" data-project-file="'+i+'" value="'+a.id+'" '+(p.files.includes(a.id)?'checked':'')+'> '+esc(a.name)+'</label>').join('')+'</div><button type="button" data-remove-project="'+i+'">移除这个项目</button></article>').join('')+'</div></section><button class="primary" type="submit" id="portfolioSaveDraft">保存私有草稿</button></form>';}
 function collect(){if(tab!=='edit'||!root()?.querySelector('#portfolioEditor'))return;const host=root();const vals=node=>Object.fromEntries([...node.querySelectorAll('[data-field]')].map(e=>[e.dataset.field,e.value]));const intro=vals(host.querySelector('.portfolio-fields'));edit={...edit,...intro,experiences:edit.experiences.map((e,i)=>({...e,...vals(host.querySelector('[data-experience="'+i+'"]'))})),projects:edit.projects.map((p,i)=>({...p,...vals(host.querySelector('[data-project="'+i+'"]')),files:[...host.querySelectorAll('[data-project-file="'+i+'"]:checked')].map(e=>e.value)}))};}
 function active(host){return host?.isConnected&&root()?.contains(host);}
 function status(text){const e=root()?.querySelector('#portfolioStatus');if(e)e.textContent=text;}
 async function perform(operation,extra={}){if(busy)return;const host=root()?.querySelector('.portfolio-modal');busy=true;host?.classList.add('portfolio-busy');status('正在保存…');const i={operation,requestId:crypto.randomUUID(),revision:data.revision,...extra};pending={i,host};try{const next=await request('/action',i);if(active(host)){data=next;pending=null;if(operation==='save')edit=structuredClone(data.draft);render();status(operation==='publish'?'展馆已发布，访客现在可以看到这些资料。':operation==='unpublish'?'展馆资料已撤下。':operation==='save'?'草稿已保存在本机，尚未公开。':'已保存。');}}catch(e){if(active(host)){status(e.message);const button=root().querySelector('#portfolioRetry');button.hidden=false;button.textContent=e.code==='portfolio_conflict'?'重新读取最新资料':'核对并重试';button.onclick=async()=>{if(e.code==='portfolio_conflict'){await open(tab,true);}else{busy=false;await retry();}};}}finally{busy=false;host?.classList.remove('portfolio-busy');}}
 async function retry(){if(!pending)return;const{host,i}=pending;busy=true;try{const next=await request('/action',i);if(active(host)){data=next;pending=null;render();status('已核对并保存。');}}catch(e){status(e.message)}finally{busy=false}}
 function render(){
 const p=data.published;openModal('岛主会客馆','个人经历 · 历史项目 · 海风来信','<div class="portfolio-shell"><nav class="portfolio-tabs" aria-label="会客馆展区">'+[['gallery','会客厅','role'],['experiences','经历展墙','recipes'],['projects','项目展厅','build'],['guestbook','留言板','lan'],...(data.canEdit?[['edit','布展编辑','admin']]:[])].map(([id,title,art])=>'<button data-tab="'+id+'" aria-pressed="'+(tab===id)+'" class="'+(tab===id?'active':'')+'">'+icon(art)+'<span>'+title+'</span></button>').join('')+'</nav><div class="portfolio-publication"><span>'+(!p?'尚未发布资料':tab==='edit'?'正在编辑私有草稿':'公开展馆 · '+date(p.publishedAt))+'</span>'+(data.canEdit?'<span>附件 '+(data.quota.used/1024/1024).toFixed(1)+' / 64 MiB</span>':'')+'</div><div class="portfolio-content">'+(tab==='edit'?editor():tab==='guestbook'?board():preview(p))+'</div></div><p id="portfolioStatus" role="status" aria-live="polite"></p><button id="portfolioRetry" class="secondary" hidden>重新读取资料</button>',data.canEdit?'<button class="secondary" id="portfolioReload">重新读取</button>'+(p?'<button class="secondary" id="portfolioUnpublish">撤下公开资料</button>':'')+'<button class="primary" id="portfolioPublish">'+(p?'发布最新草稿':'发布展馆资料')+'</button>':'<span>欢迎参观 · 仅展示岛主主动发布的资料</span>');
 const host=root().querySelector('.modal');host.classList.add('portfolio-modal');host.dataset.portfolioTheme=skin();host.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{if(busy)return;collect();tab=b.dataset.tab;if(tab==='edit'&&!edit){edit=structuredClone(data.draft);edit.name||=name();}render();});
 host.querySelector('#portfolioReload')?.addEventListener('click',()=>open(tab,true));host.querySelector('#portfolioPublish')?.addEventListener('click',()=>{if(tab==='edit'){collect();if(JSON.stringify(edit)!==JSON.stringify(data.draft)){status('请先保存草稿，再发布展馆。');return;}}perform('publish');});host.querySelector('#portfolioUnpublish')?.addEventListener('click',()=>perform('unpublish'));
 host.querySelector('#portfolioEditor')?.addEventListener('submit',e=>{e.preventDefault();collect();perform('save',{draft:edit});});
 host.querySelector('#portfolioAddExperience')?.addEventListener('click',()=>{if(busy)return;collect();if(edit.experiences.length>=30){status('最多 30 条经历');return;}edit.experiences.push({id:crypto.randomUUID(),period:'',title:'',description:''});render();});
 host.querySelector('#portfolioAddProject')?.addEventListener('click',()=>{if(busy)return;collect();if(edit.projects.length>=24){status('最多 24 个项目');return;}edit.projects.push({id:crypto.randomUUID(),title:'',summary:'',url:'',files:[]});render();});
 for(const type of ['experience','project'])host.querySelectorAll('[data-remove-'+type+']').forEach(b=>b.onclick=()=>{if(busy)return;collect();edit[type==='experience'?'experiences':'projects'].splice(Number(b.dataset[type==='experience'?'removeExperience':'removeProject']),1);render();});
 host.querySelectorAll('[data-upload]').forEach(input=>input.onchange=async()=>{const file=input.files[0];if(!file||busy)return;collect();if(file.size>8*1024*1024){status('每个附件最大 8 MiB');return;}busy=true;host.classList.add('portfolio-busy');status('正在上传附件…');try{let type=file.type||(/\.txt$/i.test(file.name)?'text/plain':'');const base64=await new Promise((r,j)=>{const reader=new FileReader();reader.onload=()=>r(String(reader.result).split(',')[1]);reader.onerror=j;reader.readAsDataURL(file);});const next=await request('/upload',{name:file.name,type,base64});if(active(host)){data=next;const p=edit.projects[Number(input.dataset.upload)];if(p.files.length<8)p.files.push(next.uploadedId);render();status('附件已上传；保存草稿后即可预览，发布后访客可见。');}}catch(e){if(active(host))status(e.message)}finally{busy=false;host.classList.remove('portfolio-busy');}});
 host.querySelector('#portfolioMessageForm')?.addEventListener('submit',e=>{e.preventDefault();perform('message',{message:host.querySelector('#portfolioMessage').value});});host.querySelectorAll('[data-moderate]').forEach(b=>b.onclick=()=>perform('moderate',{messageId:b.dataset.moderate,hidden:b.dataset.hide==='true',reply:host.querySelector('[data-reply="'+b.dataset.moderate+'"]').value}));
 }
 async function open(initial='gallery',force=false){
  const token=++session,key=cacheKey();tab=initial;edit=null;pending=null;
  const cached=!force&&cache?.key===key?cache.value:null;
  if(cached){data=cached;if(tab==='edit'&&data.canEdit){edit=structuredClone(data.draft);edit.name||=name();}else if(tab==='edit')tab='gallery';render();}
  else{openModal('岛主会客馆','个人经历 · 历史项目 · 海风来信','<div class="portfolio-empty" role="status"><h3>欢迎来到海风展馆</h3><p>正在读取展览资料…</p></div>');const host=root()?.querySelector('.modal');host?.classList.add('portfolio-modal');if(host)host.dataset.portfolioTheme=skin();}
  const host=root()?.querySelector('.modal');
  try{const next=await load(force);if(token!==session||key!==cacheKey()||!active(host))return;
   // Background refresh must not destroy a visitor's typed message or draft.
   if(cached)return;
   data=next;if(tab==='edit'&&data.canEdit){edit=structuredClone(data.draft);edit.name||=name();}else if(tab==='edit')tab='gallery';render();
  }catch(e){if(active(host)){if(cached)status('暂时无法更新；当前显示上次读取的资料。');else{host.querySelector('.modal-body').textContent=e.message;toast?.(e.message);}}}
 }
 return{open,preload,inspect:()=>({tab,revision:data?.revision,canEdit:data?.canEdit,busy,published:!!data?.published,cached:cache?.key===cacheKey()})};
}

