import {RECRUIT_CANDIDATES} from './recruitmentCatalog.js';
import {AVATARS} from './avatarCatalog.js';
import {avatarPortrait} from './avatars.js';
import {esc} from './journeyUI.js';
export function createCandidateLibrary({openModal,theme,world,records,save,refresh,back,toast}){
 let selected=null,working=false,captured=null,message='';const key=()=> 'hd-candidate-management:'+captured.theme+':'+captured.world;
 const pending=()=>{try{return JSON.parse(localStorage.getItem(key()))}catch{return null}},live=()=>captured?.theme===theme()&&captured?.world===world()&&!!document.getElementById('candidateLibrary');
 async function commit(body,replay=false){if(working||!live())return;const old=pending();if(old&&!replay){message='上次修改尚待确认，请先点击核对上次修改。';render();return;}const scope=captured,journalKey=key();working=true;message='正在保存候选档案…';const root=document.getElementById('candidateLibrary');root.querySelectorAll('button').forEach(b=>b.disabled=true);root.querySelector('[role=status]').textContent=message;
 try{localStorage.setItem(journalKey,JSON.stringify(body));await save(body);localStorage.removeItem(journalKey);if(captured!==scope||!live())return;await refresh();if(captured!==scope||!live())return;message='档案已保存，旧聘约记录保持原样。';toast(message);}
 catch(e){if(e.status>=400&&e.status<500&&![401,403,408,429].includes(e.status))localStorage.removeItem(journalKey);if(captured===scope)message=e.message||'暂时无法保存，请核对上次修改。';}
 finally{working=false;if(live())render();}
 }
 function render(){
  if(!live())return;const root=document.getElementById('candidateLibrary'),rows=records();if(!rows.some(r=>r.profile.id===selected))selected=rows[0]?.profile.id;const row=rows.find(r=>r.profile.id===selected),p=row?.profile;
  root.innerHTML='<div class="candidate-library-heading"><h3>候选档案库</h3><p>可同时保留三位待选伙伴。归档后可恢复；正在履约的伙伴需先完成交接。</p></div><p class="recruit-library-status" role="status">'+esc(message)+'</p>'+(pending()?'<button id="candidateManageRetry" class="primary">核对上次修改</button>':'')+
  '<div class="candidate-library-grid"><nav aria-label="自建候选档案">'+rows.map(r=>'<button type="button" data-library-candidate="'+esc(r.profile.id)+'" aria-pressed="'+(r.profile.id===selected)+'">'+avatarPortrait(r.profile.appearance,theme(),'recruit-candidate-art')+'<span><b>'+esc(r.profile.name)+'</b><small>'+esc(r.profile.job)+'</small><em>'+(r.archived?'已归档':'可供选择')+' · 第 '+r.version+' 版</em></span></button>').join('')+'</nav>'+
  (row?'<section><form id="candidateEditForm" class="recruit-custom"><div class="candidate-library-portrait">'+avatarPortrait(p.appearance,theme(),'recruit-custom-art')+'<span>'+(row.archived?'已归档，可恢复':'下次招聘将使用这份档案')+'</span></div><div class="recruit-custom-grid"><label>姓名<input name="name" required maxlength="16" value="'+esc(p.name)+'"></label><label>职业<select name="roleId">'+RECRUIT_CANDIDATES.map(c=>'<option value="'+c.id+'" '+((p.roleId||'mai')===c.id?'selected':'')+'>'+esc(c.job)+'</option>').join('')+'</select></label><label class="wide">形象<select name="appearance">'+AVATARS.map(a=>'<option value="'+a.id+'" '+(p.appearance===a.id?'selected':'')+'>'+esc(a.name)+'</option>').join('')+'</select></label><label class="wide">性格<textarea name="personality" maxlength="160" rows="3" required>'+esc(p.personality)+'</textarea></label><label class="wide">来历<textarea name="backstory" maxlength="200" rows="3" required>'+esc(p.backstory)+'</textarea></label></div><div class="candidate-library-actions"><button type="submit" class="primary">保存候选档案</button><button type="button" id="candidateArchive" class="secondary">'+(row.archived?'恢复为待选伙伴':'归档这位候选')+'</button></div></form>'+
  '<details class="recruit-record"><summary>最近的档案变化</summary>'+((row.edits||[]).slice(-6).reverse().map(e=>'<p>第 '+e.day+' 天 · '+({edit:'编辑档案',archive:'归档',restore:'恢复'})[e.action]+' · '+esc(e.before.profile.name)+' → '+esc(e.after.profile.name)+'</p>').join('')||'<p>尚未修改过这份档案。</p>')+'</details></section>':'<p>还没有自建伙伴，可以返回招聘手账创建。</p>')+'</div>';
  root.querySelectorAll('[data-library-candidate]').forEach(b=>b.onclick=()=>{if(!working){selected=b.dataset.libraryCandidate;message='';render();}});
  const form=root.querySelector('form');if(form){form.onsubmit=e=>{e.preventDefault();commit({id:p.id,requestId:crypto.randomUUID(),expectedVersion:row.version,action:'edit',input:Object.fromEntries(new FormData(form))});};form.elements.appearance.onchange=()=>{form.querySelector('.candidate-library-portrait').firstElementChild.outerHTML=avatarPortrait(form.elements.appearance.value,theme(),'recruit-custom-art');};root.querySelector('#candidateArchive').onclick=()=>commit({id:p.id,requestId:crypto.randomUUID(),expectedVersion:row.version,action:row.archived?'restore':'archive'});}
  const retry=root.querySelector('#candidateManageRetry');if(retry)retry.onclick=()=>commit(pending(),true);
 }
 async function open(){const scope=captured={theme:theme(),world:world()};message='';await refresh();if(captured!==scope||scope.theme!==theme()||scope.world!==world())return;openModal('伙伴档案库','编辑未来的候选安排，保留已经发生的故事。','<div id="candidateLibrary"></div>','<button class="secondary" id="candidateLibraryRefresh">读取最新档案</button><button class="secondary" id="candidateLibraryBack">返回招聘手账</button>');document.querySelector('#modalRoot .modal').classList.add('recruitment-modal');document.getElementById('candidateLibraryBack').onclick=()=>{if(!working)back();};document.getElementById('candidateLibraryRefresh').onclick=async()=>{if(working)return;await refresh();message='已读取服务端最新档案。';render();};render();}
 return{open};
}
