import {worldFetch as fetch} from './worldSession.js';
import {routineFor,recordSocialOutcome,residentLifeSummary} from './residentLife.js';
import {chooseResidentCooperation,cooperationPlanFor,cooperationFarmAvailable} from './residentCooperation.js';
import {facilityServicePoint,functionalUnit} from './functionalFacilities.js';
import {outdoorSpot} from './outdoorOccupancy.js';
import {advanceResidentStories,restoreResidentStories,recordResidentConversation,claimResidentStory,recordResidentStoryWork,interruptResidentStory} from './residentStories.js';
import {nextPresentationOperationId} from './resourceLedger.js';
import {partyPlanningContext,partyPlanningContexts} from './partyPlanning.js';
import {applyStewardParty} from './fishingParty.js';
import {syncProjects,createProject,controlProject,assignProjectStep} from './projectPlans.js';
import {availableQuantity,releaseResources} from './resourceLedger.js';
import {queueTask,nextTask,beginTaskStep,recordTaskStep,controlTask,restoreTasks,taskOwner} from './taskBoard.js';
import {journeyBrief} from './journey.js';
import {NPC_CADENCE} from './npcCadence.js';
import {groundedConversation} from './conversationFallback.js';
import {planRecipeAssignment,planAssignedTask} from './craftPlanning.js';
import {ALL_RECIPES,RECIPE_BY_ID,recipeGate,ITEM_BY_ID} from './contentCatalog.js';
import {CROPS} from './farming.js';
import {acquireRoomSpot,promoteRoomSpot,releaseRoomSpot,releaseRoomGroup} from './sceneOccupancy.js';
import {BUILDINGS,RESIDENTS,SLOTS,HARBOR,findPath,worldWalkable,nearestWalkable} from './world.js';
import {ROOMS,roomWalkable} from './rooms.js';
import {hydrateTown,CAREERS,RECIPES,career,needs,relationship,purposeOptions,choosePurpose,mealOptions,availableMealQuantity,destination,commitWork,applyRelationshipEvent} from './townSimulation.js';
export function createResidentRuntime({npcs,getState,profile,followPath,onChange,onEvent,farmRemote=null,fieldRemote=null,residentRemote=null,partyRemote=null,recruitmentRemote=null,planningRemote=null}){
 let projectAt=0,storyAt=0,time=0,batchAt=1,stewardAt=4,batchBusy=false,stewardBusy=false,epoch=0,uiAt=0,serial=0,conversationAt=0;
 const meetings=new Map(),controllers=new Set(),farmReservations=new Map(),mineReservations=new Map(),facilityClaims=new Map();
 const health={deepseek:'等待连接',hermes:'等待连接',lastError:''};const state=()=>getState();
 function remember(i,text){const s=state();s.npcMemory[i]??=[];s.npcMemory[i].push({day:s.day,text});s.npcMemory[i]=s.npcMemory[i].slice(-16)}
 function syncPresence(){state().npcPresence=npcs.filter(n=>n.visible!==false).map(n=>({id:n.npcId,x:n.x,y:n.y,inside:n.inside,buildingId:n.intent?.buildingId??meetings.get(n.meeting)?.buildingId,facilityId:n.intent?.facilityId||null,mealFood:n.intent?.mealClaimActive&&!n.intent?.serverResidentTicket?n.intent.foodId:null,mealOrder:n.intent?.mealClaimOrder??null,meeting:!!n.meeting,assignment:!!n.assignment,partyControlled:!!n.partyControlled,recruitControlled:!!n.recruitControlled}));}
 function person(i){const n=npcs[i],r=profile(i),s=state(),known=new Map((r.relationships||[]).map(x=>[x.target,{...x,...relationship(s,i,x.target)}]));for(const [j,rel] of Object.entries(s.npcRelations[i]||{}))if(rel.interactions>0)known.set(Number(j),{target:Number(j),...rel});const relationships=[...known.values()].sort((a,b)=>b.interactions-a.interactions).slice(0,5).map(x=>({...x,name:profile(x.target).name}));const c=career(i,s);return {...r,relationships,memories:(s.npcMemory[i]||[]).map(m=>m.text),life:residentLifeSummary(s,i,r),needs:needs(i,s),career:{title:CAREERS[i].title,phase:c.phase,history:c.history.slice(-4)},commitments:(s.residentStories?.episodes||[]).filter(e=>['scheduled','meeting','working'].includes(e.status)&&e.people.includes(i)).slice(-3).map(e=>({id:e.id,title:e.title,partnerId:e.people.find(j=>j!==i),dueDay:e.dueDay,stage:e.stage,item:cooperationPlanFor(e,i)?.resource,activity:e.demand?.name||null})),options:purposeOptions(i,s,r,time),status:n.status||'开始今日生活',lastGoal:n.lastGoal,assignment:n.assignment,availableForConversation:!n.partyControlled&&needs(i,s).energy>30&&needs(i,s).hunger>30&&!n.meeting&&!n.assignment&&time>(n.manualUntil||0)&&time>(n.socialCooldown||0)}}
 function context(){const s=state();return {theme:s.placementBook?.theme||null,saveSlot:s.saveSlot,projects:(s.workProjects||[]).filter(p=>['preparing','ready','paused'].includes(p.status)).map(p=>({id:p.id,title:p.title,status:p.status,targets:p.targets,held:p.held})),journey:journeyBrief(s),day:s.day,built:BUILDINGS.map(b=>({...b,...s.facilities[b.id],occupancy:s.npcPresence?.filter(n=>n.inside===b.id||n.buildingId===b.id).length||0})),inventory:Object.fromEntries(Object.keys(s.inventory).map(id=>[id,availableQuantity(s,id)])),inventoryTotals:s.inventory,taskBoard:(s.agentTaskLedger||[]).filter(t=>['queued','running','waiting','paused'].includes(t.status)).map(t=>({id:t.id,projectId:t.projectId||null,npcId:t.npcId,intent:t.intent,status:t.status,quantity:t.quantity,completed:t.completed,targetItem:t.targetItem})),recipes:ALL_RECIPES.filter(r=>recipeGate(r,s).ready).map(r=>r.id),tasks:s.tasks,events:s.events.slice(0,5),executions:s.agentExecutions.slice(-6),economy:{gross:s.economy.gross,arrivals:s.economy.arrivals,rating:s.economy.rating},residents:npcs.slice(0,15).map((_,i)=>person(i))}}
 async function post(route,body){const controller=new AbortController();controllers.add(controller);const timer=setTimeout(()=>controller.abort(),route==='/api/hermes/command'?245000:route.includes('hermes')?95000:65000);try{const response=await fetch(route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:controller.signal});const data=await response.json();if(!response.ok){const error=Error(data.error||'服务暂时不可用');error.code=data.code;error.retryAfter=Number(data.retryAfter)||0;throw error;}return data}finally{clearTimeout(timer);controllers.delete(controller)}}
 function walk(n,p,after){const start=nearestWalkable(Math.round(n.x/24)*24,Math.round(n.y/24)*24);if(Math.hypot(start.x-n.x,start.y-n.y)>18)Object.assign(n,start);const end=nearestWalkable(p.x,p.y);n.path=findPath(n,end,worldWalkable);const arrival=n.path.at(-1)||end;n.after=()=>after(arrival);if(!n.path.length){if(Math.hypot(n.x-end.x,n.y-end.y)<40){n.after=null;after(arrival);return true}n.status='寻找可达入口：'+(n.intent?.reason||'');n.target=null;n.intent=null;n.after=null;n.think=4;return false}return true}
 function spot(base,id){return outdoorSpot(base,id,npcs)}
 function releasePlot(n){if(n.intent)n.intent.mealClaimActive=false;if(n.intent?.facilityId&&facilityClaims.get(n.intent.facilityId)===n.npcId)facilityClaims.delete(n.intent.facilityId);if(n.intent?.mineIndex!=null)mineReservations.delete(n.intent.mineIndex);if(n.intent?.farmIndex!=null&&farmReservations.get(n.intent.farmIndex)===n.npcId)farmReservations.delete(n.intent.farmIndex)}
 function exitRoom(n,delay=NPC_CADENCE.betweenPurposesSeconds){releaseRoomSpot('npc-'+n.npcId);n.roomQueued=false;if(!n.inside&&n.inside!==0){n.intent=null;n.think=delay;return}const bid=n.inside,a=n.indoorActor;a.action=null;const end={x:500,y:585};a.path=findPath(a,end,(x,y)=>roomWalkable(bid,x,y),20);a.after=()=>{n.inside=null;n.indoorActor=null;n.intent=null;n.think=delay};if(!a.path.length)a.after()}
 function finish(n,d){if(d.serverResidentTicket&&!d.serverResidentFinished){const t=d.serverResidentTicket;n.action=null;n.status='正在确认居民成果';residentRemote.finish(t).then(r=>{d.serverResidentFinished=true;d.serverResidentReceipt=r.receipt;finish(n,d)}).catch(e=>{n.status=e.message;residentRemote.cancel(t).catch(()=>{}).finally(()=>{releasePlot(n);exitRoom(n);onChange()})});return}if(d.serverFieldTicket&&!d.serverFieldFinished){const t=d.serverFieldTicket;n.action=null;n.status='正在确认矿洞交付';fieldRemote.finish(t).then(()=>{d.serverFieldFinished=true;finish(n,d)}).catch(e=>{n.status=e.message;fieldRemote.cancel(t).catch(()=>{}).finally(()=>{releasePlot(n);exitRoom(n);onChange()})});return}if(d.serverFarmTicket&&!d.serverFarmFinished){const t=d.serverFarmTicket;n.action=null;n.status='正在确认田间交付';farmRemote.finish(t).then(()=>{d.serverFarmFinished=true;finish(n,d)}).catch(e=>{n.status=e.message;farmRemote.cancel(t).catch(()=>{}).finally(()=>{releasePlot(n);exitRoom(n);onChange()})});return}const s=state();if(d.projectId&&!d.serverFarmFinished&&!d.serverFieldFinished&&!d.serverResidentFinished){syncProjectActors();const t=s.agentTaskLedger.find(t=>t.id===d.assignmentId);if(!t||t.status!=='running'||t.npcId!==n.npcId||t.operationId!==d.operationId){stopAssignment(n);onChange();return}}let result;if(d.serverResidentFinished)result=d.serverResidentReceipt.text;else if(!d.serverFarmFinished&&!d.serverFieldFinished&&d.farmIndex!=null&&(s.plots[d.farmIndex]?.playerTended||s.plots[d.farmIndex]?.stage!==d.expectedStage)){result='这块田的进度已经变化，重新安排农活'}else result=commitWork(n.npcId,d,s,time);if(d.storyId){const storyResult=recordResidentStoryWork(s,d.storyId,n.npcId,d.operationId);if(storyResult.ok&&storyResult.episode.status==='resolved')onEvent(storyResult.episode.timeline.at(-1).text);}releasePlot(n);remember(n.npcId,result);n.lastGoal=d.goal;n.status=result;n.speech='';n.action=null;
  if(d.assignmentId&&n.assignment?.id===d.assignmentId){
   const receipt=s.taskActionReceipts?.[d.operationId],progress=d.serverFarmFinished||d.serverFieldFinished||d.serverResidentFinished?{done:s.agentTaskLedger.find(t=>t.id===d.assignmentId)?.status==='done'}:recordTaskStep(s,d.assignmentId,{operationId:d.operationId,result,delta:receipt?.delta||{},preparing:!!d.preparing});
   if(progress.done){s.agentExecutions.push(profile(n.npcId).name+'：'+result);s.agentExecutions=s.agentExecutions.slice(-30);n.assignment=null;onEvent(profile(n.npcId).name+'完成管家分工：'+result)}
  }else if(d.action==='work')onEvent(profile(n.npcId).name+'：'+result);
  exitRoom(n);syncProjectActors();onChange();
 }
 function refreshAssignment(n,d){
  if(!d.assignmentId)return true;
  const t=state().agentTaskLedger?.find(t=>t.id===d.assignmentId);
  if(!t?.command||t.npcId!==n.npcId||t.blocked||!['queued','running','waiting'].includes(t.status)||(t.dependsOn||[]).some(id=>state().agentTaskLedger.find(x=>x.id===id)?.status!=='done')){stopAssignment(n);return false;}
  const current=planAssignedTask(state(),t);
  if(d.goal!==current.goal||(d.buildingId??null)!==current.buildingId){
   releasePlot(n);n.queuedDecision=null;exitRoom(n,0);n.status='物资安排已更新，前往下一处工位';onChange();return false;
  }
  Object.assign(d,current);return true;
 }
 function act(n,d){if(!refreshAssignment(n,d))return;if(d.action==='eat'&&!d.facilityId&&!d.serverResidentTicket&&(d.foodId==='rations'?needs(n.npcId,state()).rations<1:availableMealQuantity(state(),d.foodId,n.npcId)<1)){syncPresence();const alternative=mealOptions(n.npcId,state(),profile(n.npcId),time).find(o=>o.action==='eat'&&o.buildingId===d.buildingId);if(alternative){Object.assign(d,alternative,{source:'local',speech:'',mealClaimActive:alternative.foodId!=='rations',mealClaimOrder:++serial});n.aiSource='local';syncPresence();}else{releasePlot(n);exitRoom(n,0);n.status='餐点余量已变化，重新安排用餐';onChange();return;}}if(d.projectId){syncProjectActors();const t=state().agentTaskLedger.find(t=>t.id===d.assignmentId);if(!t||!['queued','running'].includes(t.status)||t.npcId!==n.npcId){stopAssignment(n);return}}let type=d.action==='rest'?'rest':d.action==='eat'?'eat':d.action==='visit'?(routineFor(n.npcId,d)?.animation||'observe'):d.buildingId!=null?ROOMS[d.buildingId].action:({farm:'hoe',mine:'pickaxe',forest:'axe',dock:'fish',plaza:'observe'})[d.goal];
  if(d.resource&&d.action==='work'){const source=ITEM_BY_ID[d.resource]?.source;if(source==='shore'||source==='greenhouse'||source==='forest'&&!['wood','bamboo','hardwood','twig','bark'].includes(d.resource))type='gather';}
  if(d.goal==='farm'&&d.action==='work'){const s=state();const ids=s.plots.map((p,i)=>({i,stage:p.stage})).filter(p=>!s.plots[p.i].playerTended&&!(p.i===0&&!s.journey?.completed?.harvest)&&!farmReservations.has(p.i)&&!farmRemote?.occupied(p.i)&&cooperationFarmAvailable(s,p.i,n.npcId,d.storyId)&&(!CROPS[d.resource]||p.stage<2||(s.plots[p.i].crop||'wheat')===d.resource)&&p.stage!==3&&(p.stage!==1||availableQuantity(s,'seed',d.resourceOwner)>0)).sort((a,b)=>({4:0,2:1,1:2,0:3})[a.stage]-({4:0,2:1,1:2,0:3})[b.stage]);const p=ids[0];if(p){if(!s.farmControl&&p.stage<=1&&CROPS[d.resource])s.plots[p.i].crop=d.resource;d.farmIndex=p.i;d.expectedStage=p.stage;farmReservations.set(p.i,n.npcId);type=({0:'hoe',1:'sow',2:'water',4:'harvest'})[p.stage]}else{type='observe';d.noFarmTask=true;}}
  if(d.goal==='mine'){d.mineIndex=state().oreNodes.findIndex((p,i)=>p.hp>0&&!mineReservations.has(i)&&!fieldRemote?.occupied(i));if(d.mineIndex>=0)mineReservations.set(d.mineIndex,n.npcId);else type='observe';}
  // Assigned field work waits for its actual plot/node; it cannot fall through to a resident observation lease.
  if((d.assignmentId||d.storyId)&&((d.goal==='farm'&&d.noFarmTask)||(d.goal==='mine'&&d.mineIndex<0))){releasePlot(n);exitRoom(n);n.status=d.goal==='farm'?'等待可作业的农田，保留原分工':'等待可开采的矿脉，保留原分工';n.think=4;return;}
  if(d.assignmentId){if(state().planningControl?.enabled){delete d.operationId;}else{d.operationId=beginTaskStep(state(),d.assignmentId);if(!d.operationId){exitRoom(n);return}onChange()}}else if(d.storyId){d.operationId=nextPresentationOperationId(state(),'story-work');if(!claimResidentStory(state(),d.storyId,n.npcId,d.operationId,'work',d)){exitRoom(n);return}onChange()}
  const animateFarm=ticket=>{if(ticket){if(ticket.kind==='resident'){d.serverResidentTicket=ticket;type=ticket.action;}else if(ticket.kind==='field')d.serverFieldTicket=ticket;else d.serverFarmTicket=ticket;d.operationId=ticket.operationId;}
  n.action={type,leisure:!!routineFor(n.npcId,d),equipment:ticket?{tool:ticket.tool,duration:ticket.duration}:null,roomId:d.buildingId,t:0,duration:ticket?.duration|| (d.action==='work'&&!d.assignmentId?Math.max(NPC_CADENCE.workSeconds,d.duration||10):d.duration||10),onDone:()=>finish(n,d)};n.direction=d.facilityCenter?Math.atan2(d.facilityCenter.y-n.y,d.facilityCenter.x-n.x):d.buildingId==null?0:-Math.PI/2;if(n.indoorActor){n.indoorActor.action=n.action;const f=ROOMS[d.buildingId].primary;n.indoorActor.direction=Math.atan2(f.y+f.h/2-n.indoorActor.y,f.x+f.w/2-n.indoorActor.x);}n.status=d.reason+' · '+(d.buildingId!=null?BUILDINGS[d.buildingId].name:d.goal);if(d.speech){n.speech=d.speech;n.speechUntil=time+5}};
  if(fieldRemote&&d.goal==='mine'&&d.action==='work'&&d.mineIndex>=0){const life=epoch;n.status='准备矿洞作业';fieldRemote.begin(n,d).then(t=>{if(!t)return;if(life!==epoch||n.intent!==d){fieldRemote.cancel(t).catch(()=>{});return}animateFarm(t)}).catch(e=>{n.status=e.message;if(d.storyId&&!e.pendingAction)interruptResidentStory(state(),d.storyId,d.operationId);releasePlot(n);exitRoom(n);onChange()});return}
  if(farmRemote&&d.farmIndex!=null&&!d.noFarmTask){const life=epoch;n.status='准备田间作业';farmRemote.begin(n,d,type).then(t=>{if(!t)return;if(life!==epoch||n.intent!==d){farmRemote.cancel(t).catch(()=>{});return}animateFarm(t)}).catch(e=>{n.status=e.message;if(d.storyId&&!e.pendingAction)interruptResidentStory(state(),d.storyId,d.operationId);releasePlot(n);exitRoom(n);onChange()});return}
  if(residentRemote){const life=epoch;d.serverTime=time;n.status='准备居民作业';residentRemote.begin(n,d).then(t=>{if(!t)return;if(life!==epoch||n.intent!==d){residentRemote.cancel(t).catch(()=>{});return}animateFarm(t)}).catch(e=>{n.status=e.message;if(d.storyId&&!e.pendingAction)interruptResidentStory(state(),d.storyId,d.operationId);releasePlot(n);exitRoom(n,e.code==='resident_food'&&!e.pendingAction?0:undefined);onChange()});return}
  animateFarm(null);
 }
 function enterRoom(n,d){const bid=d.buildingId,token='npc-'+n.npcId,claim=acquireRoomSpot(bid,token,d.action==='work'?'work':'visitor');if(!claim){n.status='室内客满，稍后再进入';n.think=4;return}const a={npcId:n.npcId,x:500+(n.npcId%5-2)*35,y:585,face:1,phase:0,path:[],walkMix:0};if(!roomWalkable(bid,a.x,a.y))a.x=500;n.inside=bid;n.indoorActor=a;n.roomQueued=claim.role==='queue';a.path=findPath(a,claim.point,(x,y)=>roomWalkable(bid,x,y),20);a.after=()=>{if(n.roomQueued)n.status='等候'+ROOMS[bid].station+'空出工位';else act(n,d)};if(!a.path.length)a.after()}
 function begin(n,d){if(n.partyControlled||n.recruitControlled)return;if(d.goal==='dock'&&d.buildingId==null&&['checkin','running'].includes(state().fishingParty?.session?.phase)){n.think=5;n.status='钓位正举办大会，稍后再去码头';return}if(d.action==='social'){const b=npcs[d.partnerId];if(time>(n.socialCooldown||0)&&!n.assignment&&n.npcId<15&&b&&b!==n&&!b.partyControlled&&!b.recruitControlled&&b.npcId<15&&needs(b.npcId,state()).energy>30&&needs(b.npcId,state()).hunger>30&&!b.meeting&&!b.assignment&&time>(b.manualUntil||0)&&time>(b.socialCooldown||0)){meet(n,b,d);return}d=choosePurpose(n.npcId,state(),profile(n.npcId),time,{allowSocial:false})}
  if(d.action==='eat'&&!d.facilityId&&d.foodId!=='rations'){d.mealClaimActive=true;d.mealClaimOrder=++serial;}
  if(d.facilityId){const p=state().placedItems?.find(p=>p.id===d.facilityId),u=functionalUnit(state(),d.facilityId);if(!p||u?.phase!=='ready'||!u.servings||facilityClaims.has(d.facilityId)){n.think=3;return;}facilityClaims.set(d.facilityId,n.npcId);d.operationId=nextPresentationOperationId(state(),'npc-tea');d.facilityPoint=facilityServicePoint(p);d.facilityCenter={x:p.x,y:p.y};}
  n.intent=d;n.aiSource=d.source||'local';n.status=d.reason;n.lastGoal=d.goal;const target=d.facilityId?nearestWalkable(d.facilityPoint.x,d.facilityPoint.y):d.goal==='dock'&&d.buildingId==null?(HARBOR.activities.find(p=>npcs.every(other=>other===n||other.inside!=null||Math.hypot((other.target?.x??other.x)-p.x,(other.target?.y??other.y)-p.y)>25))||HARBOR.activities[n.npcId%HARBOR.activities.length]):spot(destination(d),n.npcId);if(!target){releasePlot(n);n.intent=null;n.target=null;n.think=3;n.status='等候室外作业空间，稍后继续';return;}n.target=target;if(!walk(n,target,()=>{n.target=null;if(d.buildingId!=null)enterRoom(n,d);else act(n,d)}))releasePlot({...n,intent:d});
 }
 function next(n){syncPresence();const pending=nextTask(state(),n.npcId);n.assignment=pending?{...pending.command,npcId:pending.npcId,projectId:pending.projectId,resourceOwner:pending.resourceOwner,targetItem:pending.targetItem}:null;const options=purposeOptions(n.npcId,state(),profile(n.npcId),time);let d=n.queuedDecision;n.queuedDecision=null;if(d){const current=options.find(o=>o.purposeId===d.purposeId)||(d.purposeId?.startsWith('career:')?options.find(o=>o.purposeId.startsWith('career:')):null);d=current?{...current,id:n.npcId,source:d.source,speech:d.buildingId===current.buildingId?d.speech:'',reason:current.reason}:null;if(d&&options[0]?.purposeId.startsWith('need:')&&options[0].score>95&&d.score<90)d=null;if(d?.buildingId!=null&&(state().npcPresence||[]).filter(x=>x.id!==n.npcId&&(x.inside===d.buildingId||x.buildingId===d.buildingId)).length>=4&&d.action!=='work')d=null;}if(n.assignment&&needs(n.npcId,state()).energy>=20&&needs(n.npcId,state()).hunger>=30){d={...planAssignedTask(state(),pending),duration:12,source:'hermes',assignmentId:pending.id,projectId:pending.projectId,activity:'station'}}if(d?.recipeId&&!d.assignmentId&&!d.projectId&&RECIPE_BY_ID[d.recipeId])d=planRecipeAssignment(RECIPE_BY_ID[d.recipeId],state(),d);
 if(!d)d=choosePurpose(n.npcId,state(),profile(n.npcId),time);begin(n,d)}
 function meet(a,b,d){if(a.partyControlled||b.partyControlled||a.recruitControlled||b.recruitControlled)return;const operationId=nextPresentationOperationId(state(),'npc-talk');if(d.storyId&&!claimResidentStory(state(),d.storyId,a.npcId,operationId,'talk')){a.think=4;return}const cooperationPlan=d.socialType==='negotiate'?chooseResidentCooperation(state(),[a.npcId,b.npcId],{careers:CAREERS,options:Object.fromEntries([a,b].map(n=>[n.npcId,purposeOptions(n.npcId,state(),profile(n.npcId),time).find(o=>o.purposeId?.startsWith('career:'))]))}):null;const id=++serial,m={id,cooperationPlan,operationId,storyId:d.storyId||null,ids:[a.npcId,b.npcId],phase:'waiting',topic:d.reason,goal:d.goal,buildingId:d.buildingId,type:d.socialType||'friendship',socialTopicKey:d.socialTopic?.key||null,clock:0,lines:null,changes:[],source:'pending',summary:'',epoch};meetings.set(id,m);onChange();for(const n of [a,b]){n.meeting=id;n.queuedDecision=null;n.status='约'+profile(n===a?b.npcId:a.npcId).name+'谈一谈：'+d.reason;n.aiSource=d.source||'local'}
  if(time<conversationAt){Object.assign(m,groundedConversation(m.ids,state(),profile,m.type,time,m.cooperationPlan));return}
  conversationAt=time+NPC_CADENCE.conversationSeconds;
  post('/api/npc/interact',{...context(),residents:m.ids.map(i=>person(i)),topic:m.topic,socialType:m.type}).then(data=>{if(m.epoch!==epoch)return;Object.assign(m,{lines:data.lines,source:data.source,changes:data.changes||[],summary:data.summary||m.topic,type:data.type||m.type,emotions:data.emotions||[]})}).catch(e=>{if(m.epoch!==epoch)return;Object.assign(m,groundedConversation(m.ids,state(),profile,m.type,time,m.cooperationPlan));conversationAt=Math.max(conversationAt,time+(e.message.includes('402')?NPC_CADENCE.providerFailureSeconds:e.code==='automatic_budget_exhausted'?Math.min(e.retryAfter||NPC_CADENCE.conversationSeconds,NPC_CADENCE.conversationSeconds):e.retryAfter||NPC_CADENCE.conversationSeconds));if(!['automatic_cooldown','automatic_paused','automatic_budget_exhausted'].includes(e.code))health.lastError=e.message});
 }
 function endMeeting(m){for(const change of m.changes)applyRelationshipEvent(state(),change,m.summary);for(const n of m.ids.map(i=>npcs[i])){const other=m.ids.find(i=>i!==n.npcId),rel=relationship(state(),n.npcId,other);rel.interactions++;rel.lastEvent=m.summary;needs(n.npcId,state()).social=Math.min(100,needs(n.npcId,state()).social+25);needs(n.npcId,state()).mood=m.emotions?.find(e=>e.id===n.npcId)?.mood||'平静';remember(n.npcId,'与'+profile(other).name+'：'+m.summary+'；'+m.lines.filter(l=>l.speaker===other).map(l=>l.text).join(' / '));n.meeting=null;n.action=null;n.speech='';n.think=NPC_CADENCE.betweenPurposesSeconds;n.socialCooldown=time+NPC_CADENCE.socialCooldownSeconds;const history=career(n.npcId,state());history.socialAfter=time+NPC_CADENCE.socialCooldownSeconds;history.history.push({day:state().day,daySeconds:state().economy?.daySeconds||0,time,goal:m.goal,buildingId:m.buildingId,action:'social',result:m.summary,source:m.source});history.history=history.history.slice(-16);}
  const row={id:m.operationId,storyId:m.storyId,day:state().day,time,participants:m.ids,topic:m.topic,socialTopicKey:m.socialTopicKey,lines:m.lines,type:m.type,summary:m.summary,changes:m.changes,source:m.source};state().npcConversations.push(row);state().npcConversations=state().npcConversations.slice(-50);recordSocialOutcome(state(),row);const options=Object.fromEntries(m.ids.map(id=>[id,purposeOptions(id,state(),profile(id),time).find(o=>o.purposeId?.startsWith('career:'))]));const plan=m.cooperationPlan||chooseResidentCooperation(state(),m.ids,{careers:CAREERS,options});recordResidentConversation(state(),row,plan||{unavailable:true});onEvent(m.ids.map(i=>profile(i).name).join('与')+'：'+m.summary);meetings.delete(m.id);onChange();
 }
 function advanceMeetings(dt){for(const m of meetings.values()){const [a,b]=m.ids.map(i=>npcs[i]);m.clock+=dt;if(m.phase==='waiting'&&!a.action&&!b.action&&a.inside==null&&b.inside==null){m.phase='approaching';m.clock=0;const center=spot(destination(m),a.npcId);m.arrived={};for(const [n,dx] of [[a,-16],[b,16]]){n.after=null;n.path=[];const target=nearestWalkable(center.x+dx,center.y);n.target=target;const reachable=walk(n,target,arrival=>{n.target=null;m.arrived[n.npcId]=Math.hypot(n.x-arrival.x,n.y-arrival.y)<40;});if(!reachable)m.clock=76;}}
   if(m.phase==='approaching'&&m.arrived?.[a.npcId]&&m.arrived?.[b.npcId]&&Math.hypot(a.x-b.x,a.y-b.y)<=85&&m.lines){m.phase='speaking';m.clock=0;for(const n of [a,b]){n.action={type:'talk',t:0,duration:m.lines.length*3.7};n.status=({dispute:'分歧与争执',reconcile:'尝试和解',confession:'表达心意',negotiate:'商量分工',friendship:'分享生活'})[m.type]||'交谈';n.aiSource=m.source}}
   if(m.phase==='speaking'){const l=m.lines[Math.min(m.lines.length-1,Math.floor(m.clock/3.7))];for(const n of [a,b]){const other=n===a?b:a;n.direction=Math.atan2(other.y-n.y,other.x-n.x);n.face=other.x<n.x?-1:1;n.speech=l.speaker===n.npcId?l.text:'';n.speechUntil=time+1;n.action.t=m.clock}if(m.clock>=m.lines.length*3.7)endMeeting(m)}else if(m.clock>75){if(m.storyId)interruptResidentStory(state(),m.storyId,m.operationId);for(const n of [a,b]){n.meeting=null;if(m.phase==='approaching'){n.path=[];n.after=null;}n.target=null;n.queuedDecision=null;n.socialCooldown=time+30;career(n.npcId,state()).socialAfter=time+30;n.think=NPC_CADENCE.betweenPurposesSeconds;remember(n.npcId,'约谈未能及时开始，先完成手上的生活安排')}meetings.delete(m.id)}
  }}
 async function batch(){batchBusy=true;const captured=epoch,versions=npcs.map((_,i)=>profile(i).version||0);health.deepseek='思考职业与生活安排';try{const data=await post('/api/npc/tick',context());if(captured!==epoch||window.hdLanOverlayOpen)return;for(const d of data.decisions){const n=npcs[d.id];if(!n||n.partyControlled||n.recruitControlled||(profile(d.id).version||0)!==versions[d.id])continue;n.queuedDecision=d;if(!n.path.length&&!n.action&&!n.meeting&&n.inside==null)n.think=Math.max(1,n.think)}health.deepseek='已连接 · '+data.decisions.length+' 位居民';health.lastError=''}catch(e){if(captured===epoch){health.deepseek=e.message.includes('402')?'余额不足 · 本地职业规划':'本地职业规划 · 自动重试';batchAt=Math.max(batchAt,time+(e.message.includes('402')?NPC_CADENCE.providerFailureSeconds:e.code==='automatic_budget_exhausted'?Math.min(e.retryAfter||NPC_CADENCE.planSeconds,NPC_CADENCE.planSeconds):e.retryAfter||NPC_CADENCE.planSeconds));if(e.code==='automatic_cooldown')health.deepseek='低频规划 · 沿用当前安排';if(e.code==='automatic_paused')health.deepseek='自动模型暂停 · 本地职业生活';if(e.code==='automatic_budget_exhausted')health.deepseek='今日自动额度已用完 · 本地职业生活';if(!['automatic_cooldown','automatic_paused','automatic_budget_exhausted'].includes(e.code))health.lastError=e.message}}finally{batchBusy=false;onChange()}}
 async function acceptCommands(data,manual=false){if(data.recruitmentOffers?.length&&recruitmentRemote)await recruitmentRemote(data.recruitmentOffers);data.partyResults=[];for(const p of data.parties||[])data.partyResults.push(manual?(partyRemote?await partyRemote(p,data.runId):applyStewardParty(state(),p,data.runId)):{ok:false,title:p.name,reason:'自动巡查不能发布新活动'});const planned=planningRemote&&((data.plans||[]).length||(data.commands||[]).length)?await planningRemote('batch',{plans:data.plans||[],commands:data.commands||[],runId:data.runId||null}):null;if(planned){data.commandResults=planned.commands.map((result,index)=>({...result,id:result.id||(data.commands||[])[index]?.id||null}));const rejected=data.commandResults.filter(r=>!r.ok);if(rejected.length)data.answer=String(data.answer||'')+'\n未登记的分工：'+rejected.map(r=>r.reason||'当前条件不满足').join('；')+'。';data.commands=(data.commands||[]).filter(c=>data.commandResults.some(r=>r.id===c.id&&r.ok));}data.planResults=planned?planned.planResults:(data.plans||[]).map(plan=>{const result=createProject(state(),{...plan,source:'hermes',runId:data.runId});return {id:result.project?.id||plan.id,title:plan.title,ok:result.ok,reason:result.reason||null}});syncProjectActors();let accepted=0;for(const c of data.commands||[]){
 const n=npcs[c.npcId];if(!n)continue;const bid=c.buildingId??({workshop:0,tea:1,gallery:11})[c.goal];
 const targetItem=RECIPE_BY_ID[c.recipeId]?.item||c.resource||({forest:'wood',mine:'ore',farm:'wheat',dock:'fish'})[c.goal]||RECIPES[bid]?.item||null;
 const queued=planned?planned.commands.find(x=>x.id===c.id)||{ok:false}:queueTask(state(),c,{name:profile(c.npcId).name,targetItem});if(!queued.ok||queued.replayed)continue;
 accepted++;if(n.partyControlled||n.recruitControlled){remember(c.npcId,'收到管家分工，当前活动结束后继续：'+c.intent);continue}if(!n.assignment)n.assignment={...c,targetItem};n.queuedDecision=null;
 if(!n.action&&!n.meeting&&n.inside==null){n.path=[];n.after=null;n.think=0}remember(c.npcId,'收到管家分工：'+c.intent)}
 if(accepted)onEvent('管家已派出 '+accepted+' 项准备任务。');health.hermes=data.source==='hermes'?'已连接 · Hermes工具':data.errorCode==='automatic_cooldown'?'低频巡查 · 沿用当前安排':data.errorCode==='provider_balance'?'余额不足 · 本地手账':'本地手账 · 模型待恢复';health.lastError=data.providerError||'';if(data.source!=='hermes')stewardAt=Math.max(stewardAt,time+Math.max(NPC_CADENCE.stewardSeconds,data.errorCode==='provider_balance'?NPC_CADENCE.providerFailureSeconds:data.retryAfter||0));onChange()}
 async function steward(message,retryModel=false,history=[],options={}){if(stewardBusy)throw Error('管家正在处理上一轮任务');stewardBusy=true;const captured=epoch;health.hermes='观察经营与调度';try{const data=await post(message?'/api/hermes/command':'/api/hermes/plan',{...context(),...(message?{party:partyPlanningContext(state()),partyTemplates:partyPlanningContexts(state())}:{}),message,requestId:options.requestId||crypto.randomUUID(),retryModel,history:message?history:[],includeWorkProject:!!message&&options.includeWorkProject===true,resumeSessionId:message?options.resumeSessionId:undefined});if(captured===epoch&&(!globalThis.window?.hdLanOverlayOpen||!!message))await acceptCommands(data,!!message);return data}catch(e){if(captured===epoch){health.hermes=e.code==='automatic_cooldown'?'低频巡查 · 沿用当前安排':e.code==='automatic_paused'?'自动巡查暂停 · 手动委托可用':e.code==='automatic_budget_exhausted'?'今日自动额度已用完 · 手动委托可用':'连接重试中';if(!message)stewardAt=Math.max(stewardAt,time+(e.code==='automatic_budget_exhausted'?Math.min(e.retryAfter||NPC_CADENCE.stewardSeconds,NPC_CADENCE.stewardSeconds):e.retryAfter||NPC_CADENCE.stewardSeconds));if(!['automatic_cooldown','automatic_paused','automatic_budget_exhausted'].includes(e.code))health.lastError=e.message}throw e}finally{stewardBusy=false;onChange()}}
 function reset(){storyAt=0;epoch++;if(!state().planningControl?.enabled)restoreTasks(state());for(const owner of Object.keys(state().resourceLedger?.reservations||{}))if(owner.startsWith('player:'))releaseResources(state(),owner);for(const c of controllers)c.abort();controllers.clear();meetings.clear();farmReservations.clear();mineReservations.clear();facilityClaims.clear();releaseRoomGroup('npc-');hydrateTown(state());restoreResidentStories(state());health.deepseek='等待连接';health.hermes='等待连接';batchAt=Math.max(batchAt,time+1);stewardAt=Math.max(stewardAt,time+4);conversationAt=Math.max(conversationAt,time);for(const [i,n] of npcs.entries()){const c=career(i,state()),step=CAREERS[i].route[c.phase%CAREERS[i].route.length],p=destination(typeof step==='number'?{buildingId:step}:{goal:step});Object.assign(n,nearestWalkable(p.x+(i%3-1)*18,p.y),{path:[],after:null,action:null,meeting:null,assignment:null,roomQueued:false,inside:null,indoorActor:null,intent:null,target:null,queuedDecision:null,think:1+i*1.7,lastGoal:null,status:CAREERS[i].title,speech:'',aiSource:'local'})}onChange()}
 function update(dt,now){time=now;if(time>=storyAt){storyAt=time+1;if(advanceResidentStories(state()))onChange();}if(time>=projectAt){projectAt=time+1;syncProjectActors()}syncPresence();for(const n of npcs){if(n.recruitControlled||n.partyControlled)continue;const need=needs(n.npcId,state());need.energy=Math.max(0,need.energy-dt*.04);need.hunger=Math.max(0,need.hunger-dt*.12);need.social=Math.max(0,need.social-dt*.09);if(n.speechUntil<time)n.speech='';if(n.meeting&&meetings.get(n.meeting)?.phase==='speaking'){n.walkMix=(n.walkMix||0)*Math.exp(-dt*10);continue}if(n.indoorActor?.path.length){followPath(n.indoorActor,dt,108);continue}if(n.roomQueued){const claim=promoteRoomSpot('npc-'+n.npcId);if(claim){n.roomQueued=false;const a=n.indoorActor,bid=n.inside;a.path=findPath(a,claim.point,(x,y)=>roomWalkable(bid,x,y),20);a.after=()=>act(n,n.intent);if(!a.path.length)a.after()}continue}if(n.action){n.action.t+=dt;n.walkMix=(n.walkMix||0)*Math.exp(-dt*10);if(n.action.t>=n.action.duration){const done=n.action.onDone;n.action=null;done?.()}}else if(n.path.length)followPath(n,dt,55+(n.npcId%3)*2);else if(n.inside==null&&!n.meeting&&time>(n.manualUntil||0)){n.think-=dt;if(need.hunger<42||need.energy<38)n.think=0;if(n.think<=0)next(n)}}advanceMeetings(dt);if(time>=batchAt&&!batchBusy){batchAt=time+NPC_CADENCE.planSeconds;batch()}if(time>=stewardAt&&!stewardBusy){stewardAt=time+NPC_CADENCE.stewardSeconds;steward().catch(()=>{})}if(time>=uiAt){uiAt=time+2;onChange()}}
 async function manageTask(id,action){const outcome=planningRemote?await planningRemote('task-control',{id,action}):controlTask(state(),id,action);if(!outcome.ok)return outcome;const n=npcs[outcome.task.npcId];if(n?.assignment?.id===id&&action!=='resume')stopAssignment(n);if(n&&action==='resume')n.think=0;onChange();return outcome}
 function stopAssignment(n){if(n.intent?.serverResidentTicket&&!n.intent.serverResidentFinished)residentRemote?.cancel(n.intent.serverResidentTicket).catch(()=>{});if(n.intent?.serverFieldTicket&&!n.intent.serverFieldFinished)fieldRemote?.cancel(n.intent.serverFieldTicket).catch(()=>{});if(n.intent?.serverFarmTicket&&!n.intent.serverFarmFinished)farmRemote?.cancel(n.intent.serverFarmTicket).catch(()=>{});if(n.intent?.storyId)interruptResidentStory(state(),n.intent.storyId,n.intent.operationId);if(n.meeting){const m=meetings.get(n.meeting);if(m?.storyId)interruptResidentStory(state(),m.storyId,m.operationId);if(m){for(const id of m.ids){const other=npcs[id];other.meeting=null;if(m.phase==='speaking')other.action=null;if(m.phase==='approaching'){other.path=[];other.after=null;other.target=null;}other.speech='';other.think=20;other.socialCooldown=time+30;}meetings.delete(m.id);}}releasePlot(n);n.assignment=null;n.path=[];n.after=null;n.action=null;n.target=null;n.queuedDecision=null;if(n.indoorActor){n.indoorActor.action=null;n.indoorActor.after=null;n.indoorActor.path=[]}exitRoom(n);n.think=0}
 function syncProjectActors(){syncProjects(state());for(const n of npcs){if(n.partyControlled)continue;const id=n.assignment?.id||n.intent?.assignmentId,t=state().agentTaskLedger?.find(t=>t.id===id);if(t?.projectId&&(!['queued','running'].includes(t.status)||t.npcId!==n.npcId))stopAssignment(n)}}
 async function manageProject(id,action,npcId){const result=planningRemote?await planningRemote(action==='assign'?'assign':'control',{id,action,npcId}):action==='assign'?assignProjectStep(state(),id,npcId):controlProject(state(),id,action);if(result.ok){if(action==='assign'){const n=npcs[result.previousNpcId];if(n?.assignment?.id===id||n?.intent?.assignmentId===id)stopAssignment(n)}syncProjectActors();for(const n of npcs)if(!n.action&&!n.path.length)n.think=0;onChange()}return result}
 async function createPreparation(project){const result=planningRemote?await planningRemote('create',{project}):createProject(state(),project);if(result.ok){syncProjectActors();onChange()}return result}
 reset();return {update,reset,steward,createPreparation,health,recheckAutomatic:()=>{batchAt=time+1;stewardAt=time+4;conversationAt=time},person,meetings,manageTask,manageProject,releaseActor:stopAssignment,syncProjects:syncProjectActors,claimFarm:(i,owner='player')=>{if(farmReservations.has(i)&&farmReservations.get(i)!==owner)return false;farmReservations.set(i,owner);return true},releaseFarm:(i,owner='player')=>{if(farmReservations.get(i)===owner)farmReservations.delete(i)},cadence:NPC_CADENCE,refresh:()=>{syncPresence()}};
}
