import test from 'node:test';import assert from 'node:assert/strict';
import {createState,SLOTS,HARBOR,findPath,setWorldTheme,worldWalkable} from '../src/world.js';
import {ROOMS,roomWalkable} from '../src/rooms.js';
import {hydrateTown,purposeOptions,commitWork,career,needs,applyRelationshipEvent,assessIsland,TOURISTS,settleVisit} from '../src/townSimulation.js';
test('both themes keep all parcel entrances connected to ferry gate',()=>{for(const t of ['pixel','origami']){setWorldTheme(t);assert.ok(worldWalkable(HARBOR.gate.x,HARBOR.gate.y));for(const s of SLOTS)assert.ok(findPath(HARBOR.gate,s.entry).length,t+' '+s.id)}setWorldTheme('pixel');for(const r of ROOMS)assert.ok(findPath({x:500,y:585},r.primary.entry,(x,y)=>roomWalkable(r.id,x,y),20).length||Math.hypot(500-r.primary.entry.x,585-r.primary.entry.y)<40,'room '+r.id)});
test('career sources missing material and advances only after real craft',()=>{const s=hydrateTown(createState());career(1,s).phase=1;s.inventory.ore=0;const p=purposeOptions(1,s,{relationships:[]})[0];assert.equal(p.goal,'mine');commitWork(1,p,s,10);assert.equal(career(1,s).phase,1);s.inventory.ore=1;s.inventory.wood=2;const d=purposeOptions(1,s,{relationships:[]})[0];assert.equal(d.buildingId,0);commitWork(1,d,s,20);assert.equal(s.inventory.lantern,1);assert.equal(s.inventory.wood,0);assert.equal(career(1,s).phase,2);needs(1,s).energy=10;assert.equal(purposeOptions(1,s,{relationships:[]})[0].action,'rest');});
test('relationship outcomes preserve negative tension and bounded changes',()=>{const s=hydrateTown(createState());const a=applyRelationshipEvent(s,{from:0,to:1,affinity:-50,trust:-20,tension:50},'物资分配分歧');assert.equal(a.affinity,-6);assert.equal(a.trust,-4);assert.equal(a.tension,6);const b=applyRelationshipEvent(s,{from:0,to:1,affinity:3,trust:2,tension:-3},'商量分工');assert.equal(b.tension,3);assert.equal(b.lastEvent,'商量分工')});
test('tourists assess facilities and purchases debit stock and budget exactly once',()=>{const s=hydrateTown(createState());s.inventory.bouquet=1;let low=assessIsland(s,TOURISTS[0]).score;for(const f of Object.values(s.facilities))f.quality=90;assert.ok(assessIsland(s,TOURISTS[0]).score>low);const g={name:'乔安',budget:24};const coins=s.coins;assert.equal(settleVisit(s,g,3,'test-sale',10).paid,5);assert.equal(s.inventory.bouquet,0);assert.equal(g.budget,19);assert.equal(s.coins,coins+3);assert.equal(settleVisit(s,g,3,'test-sale',11).paid,0);assert.equal(s.coins,coins+3);s.buildings={};assert.equal(assessIsland(s,TOURISTS[0]).accepted,false)});

test('shared inventory cannot become negative or count failed production as progress',()=>{const s=hydrateTown(createState());s.plots[0].stage=1;s.inventory.seed=0;commitWork(0,{goal:'farm',buildingId:null,action:'work',farmIndex:0,purposeId:'career:0'},s,0);assert.equal(s.inventory.seed,0);assert.equal(s.plots[0].stage,1);career(1,s).phase=1;s.inventory.ore=0;s.inventory.wood=0;commitWork(1,{goal:'workshop',buildingId:0,action:'work',purposeId:'career:1'},s,0);assert.equal(s.inventory.lantern,0);assert.equal(career(1,s).phase,1)});
