import {chromium} from 'playwright-core';import assert from 'node:assert/strict';import {writeFile} from 'node:fs/promises';
import {createState} from '../src/world.js';import {hydrateTown} from '../src/townSimulation.js';
const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const report=[];
try{for(const [port,theme] of [[4173,'pixel'],[4174,'origami']]){
 const page=await browser.newPage({viewport:{width:1440,height:950}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/api/npc/**',r=>r.fulfill({status:503,contentType:'application/json',body:'{"error":"isolated UI verification"}'}));
 const initial=hydrateTown(createState());initial.inventory.wood=50;initial.inventory.stone=50;initial.inventory.lantern=1;initial.inventory.wheat=5;initial.partyInvites={0:true,2:true};initial.facilities[0].condition=70;
 await page.goto('http://127.0.0.1:'+port+'/?qa=1&rev=life-v10');await page.evaluate(([theme,s])=>localStorage.setItem('hyper-dimension-'+theme+'-v3',JSON.stringify(s)),[theme,initial]);await page.reload();await page.waitForFunction(()=>window.islandInspect);
 await page.locator('#businessBtn').click();const scroll=await page.locator('.modal').evaluate(el=>({overflow:el.scrollHeight>el.clientHeight,thumb:getComputedStyle(el,'::-webkit-scrollbar-thumb').backgroundColor,background:getComputedStyle(el,'::-webkit-scrollbar-thumb').backgroundImage,width:getComputedStyle(el,'::-webkit-scrollbar').width,color:getComputedStyle(el).scrollbarColor}));
 assert.ok(scroll.overflow);assert.equal(scroll.width,'14px');assert.notEqual(scroll.background,'none');assert.equal(scroll.color,'auto');
 await page.screenshot({path:'qa/v10-business-'+theme+'.png'});
 const before=await page.evaluate(()=>window.islandInspect());await page.locator('[data-supply="seeds"]').click();let after=await page.evaluate(()=>window.islandInspect());assert.equal(after.coins,before.coins-18);assert.equal(after.inventory.seed,before.inventory.seed+5);
 await page.locator('[data-manage="0"]').click();const upgradeBefore=await page.evaluate(()=>window.islandInspect());await page.locator('#upgradeFacility').click();after=await page.evaluate(()=>window.islandInspect());assert.equal(after.coins,upgradeBefore.coins-80);assert.equal(after.facilities[0].upgrades,1);assert.equal(await page.locator('#upgradeFacility').isDisabled(),true);
 await page.locator('#closeModal').click();await page.locator('#partyBtn').click();await page.locator('#hostParty').click();const escrow=await page.evaluate(()=>window.islandInspect());assert.equal(escrow.inventory.lantern,0);assert.ok(escrow.partySession);assert.equal(escrow.coins,after.coins-8);
 await page.reload();await page.locator('#partyBtn').click();assert.equal((await page.evaluate(()=>window.islandInspect())).coins,escrow.coins);
 for(let i=0;i<4;i++)await page.locator('#launchLantern').click();await page.waitForTimeout(2600);const settled=await page.evaluate(()=>window.islandInspect());assert.equal(settled.partySession,null);assert.equal(settled.economy.cashLedger.filter(x=>x.category==='party'&&x.income>0).length,1);assert.equal(settled.economy.cashLedger.filter(x=>x.category==='party'&&x.cost>0).length,1);assert.ok(Object.values(settled.inventory).every(n=>n>=0));
 await page.locator('#partyBtn').click();assert.equal(await page.locator('#hostParty').isDisabled(),true);await page.locator('#closeModal').click();
 await page.locator('#stewardBtn').click();await page.locator('#hermesInput').fill('帮我准备灯笼');await page.locator('#hermesSend').click();await page.waitForFunction(()=>document.querySelector('#hermesSend')&&!document.querySelector('#hermesSend').disabled,{},{timeout:100000});
 const answer=await page.locator('#hermesAnswer').innerText(),source=await page.locator('#hermesAnswer').getAttribute('data-source');assert.notEqual(source,null);assert.ok(!answer.includes('incomplete response'));if(source==='local'){assert.ok(answer.includes('未派发新任务'));assert.ok(answer.includes('HTTP 402')||answer.includes('上一轮模型请求')||answer.includes('服务暂时不可用'));}
 await page.screenshot({path:'qa/v10-steward-'+theme+'.png'});assert.deepEqual(errors,[]);report.push({theme,scroll,coins:settled.coins,source,answer,pageErrors:errors});console.log('PASS',theme,'themed scroll, supplies, upgrades, party escrow/reload/daily cap, real butler UI');await page.close();
}await writeFile('qa/v10-ui.json',JSON.stringify(report,null,2));}finally{await browser.close()}
