import test from 'node:test';import assert from 'node:assert/strict';import {followPath,followPendingPath} from '../src/movement.js';import {setWorldTheme,HARBOR} from '../src/world.js';import {arrivalRoute,boardingRoute} from '../src/harborNavigation.js';
const distance=points=>points.slice(1).reduce((n,p,i)=>n+Math.hypot(p.x-points[i].x,p.y-points[i].y),0);
function traverse(points,fps){let count=0,elapsed=0;const actor={...points[0],path:structuredClone(points),after:()=>count++};while(!count&&elapsed<60){const before={x:actor.x,y:actor.y};followPath(actor,1/fps,86);elapsed+=1/fps;assert(Math.hypot(actor.x-before.x,actor.y-before.y)<=86/fps+1e-7,'A frame must never exceed its walking distance');}assert.equal(count,1);assert(elapsed>=Math.ceil(distance(points)/86*1000)/1000,'Arrival must not precede the authoritative earliest transfer time');assert(elapsed<distance(points)/86+(points.length+1)/fps);return elapsed;}
test('Both theme gangways respect speed and server transfer time at 30, 60, 165 and 240 FPS',()=>{for(const theme of ['pixel','origami']){setWorldTheme(theme);for(const fps of [30,60,165,240])traverse(arrivalRoute(),fps);}});
test('Every return queue follows the same speed budget through its full boarding route',()=>{for(const theme of ['pixel','origami']){setWorldTheme(theme);for(let q=0;q<HARBOR.waiting.length;q++)for(const fps of [60,165,240])traverse(boardingRoute(q),fps);}});
test('A close waypoint does not snap beyond the frame distance',()=>{const a={x:0,y:0,path:[{x:1.9,y:0}]};followPath(a,1/165,86);assert.equal(a.path.length,1);assert(Math.abs(a.x-86/165)<1e-9);});
test('Zero elapsed time preserves a nonzero remaining step',()=>{const a={x:0,y:0,path:[{x:1,y:0}],after:()=>assert.fail('Paused movement must not arrive')};followPath(a,0,86);assert.equal(a.x,0);assert.equal(a.path.length,1);});
test('The final short step sets correct facing and calls arrival once',()=>{let count=0;const a={x:0,y:0,path:[{x:-.5,y:.5}],after:()=>count++};followPath(a,.02,86);assert.equal(a.x,-.5);assert.equal(a.y,.5);assert.equal(a.direction,3*Math.PI/4);assert.equal(count,1);followPath(a,.02,86);assert.equal(count,1);});
test('Pending receipts retain the final callback until confirmed simulation resumes',()=>{let count=0;const a={x:0,y:0,path:[{x:1.9,y:0}],after:()=>count++};for(let i=0;i<30;i++)followPendingPath(a,1/165,86);assert.equal(a.x,1.9);assert.equal(count,0);assert.equal(a.path.length,1);followPath(a,1/165,86);assert.equal(count,1);assert.equal(a.path.length,0);followPath(a,1/165,86);assert.equal(count,1);});

