import test from 'node:test';import assert from 'node:assert/strict';import {mkdir,mkdtemp,readFile} from 'node:fs/promises';import {join,resolve} from 'node:path';import {randomUUID} from 'node:crypto';
import {createSaveStore} from '../server/saveStore.mjs';import {createRecruitmentStore} from '../server/recruitmentStore.mjs';import {hydrateTown} from '../src/townSimulation.js';import {createZeroState} from '../src/freshStart.js';import {prepareRecruitment} from '../src/recruitment.js';import {assertResourceState} from '../server/resourceAuthority.mjs';import {availableQuantity} from '../src/resourceLedger.js';import {proof} from './v72-recruitment-fixture.mjs';
const out=resolve('qa/v106/request-rules');await mkdir(out,{recursive:true});
async function fixture(theme){const directory=await mkdtemp(join(out,theme+'-')),state=hydrateTown(createZeroState());state.freshStartPending=false;state.coins=40;const store=createSaveStore({directory});await store.open(theme,{legacyState:state});await store.openClient(theme);const current=()=>store.current(theme),call=async(operation,args={})=>{const d=await current();return store.action(theme,{kind:'commerce',operation,requestId:randomUUID(),expectedVersion:d.version,day:d.state.day,...args});};for(const op of ['enable','hire_enable','plan_enable'])await call(op);await call('plan_create',{project:{id:'native-hire-plan',title:'准备木料',targets:{wood:50}}});return {theme,directory,store,current,call,other:()=>createSaveStore({directory}),prepare:args=>call('hire_prepare',{contractId:randomUUID(),projectId:'native-hire-plan',candidateId:'mai',mode:'hire',source:'user',recallId:null,...args})};}
async function bound(f){const prepared=await f.prepare(),id=prepared.document.state.recruitment.pending.id,registry=createRecruitmentStore({directory:f.directory});const c=(await registry.start(f.theme,await f.current(),{requestId:id,projectId:'native-hire-plan',candidateId:'mai',source:'user'})).contract;await registry.complete(f.theme,id,c.attempt,proof(c.context));await registry.activate(f.theme,await f.current(),id);await f.call('hire_bind',{contractId:id});let d=await f.current(),s=structuredClone(d.state);Object.assign(s.recruitment.active,{phase:'working',hasArrived:true,position:{x:780,y:465,inside:null,direction:0}});await f.store.save(f.theme,{state:s,expectedVersion:d.version});await f.call('plan_control',{projectId:'native-hire-plan',control:'pause'});return {id,registry};}
for(const theme of ['pixel','origami']){
test(theme+' protected native salary preparation persists once and survives lost response/restart',async()=>{const f=await fixture(theme),r=await f.prepare(),s=r.document.state,id=s.recruitment.pending.id;assertResourceState(s,r.document.actions);assert.equal(s.coins,40);assert.equal(availableQuantity(s,'coins'),32);assert.equal(s.resourceLedger.reservations['hire:'+id].items.coins,8);assert.equal(r.receipt.cashDelta,0);const replay=await f.other().action(theme,{...r.ticket,operation:'hire_prepare',kind:'commerce',contractId:id,projectId:'native-hire-plan',candidateId:'mai',mode:'hire',source:'user',recallId:null,day:s.day,expectedVersion:'response-lost'});assert(replay.replayed);assert.equal(replay.document.version,r.document.version);assert.deepEqual(replay.document.state.resourceLedger,s.resourceLedger);});
test(theme+' browser cannot fabricate a salary hold and rejected save preserves exact bytes',async()=>{const f=await fixture(theme),d=await f.current(),file=join(f.directory,theme,'current.json'),before=await readFile(file),s=structuredClone(d.state);assert(prepareRecruitment(s,randomUUID(),'native-hire-plan').ok);await assert.rejects(f.store.save(theme,{state:s,expectedVersion:d.version}),e=>e.code==='resource_state_conflict');assert.deepEqual(await readFile(file),before);});
test(theme+' failed or cancelled preparation releases only its own wages and pays nothing',async()=>{const f=await fixture(theme),r=await f.prepare(),id=r.document.state.recruitment.pending.id;await f.call('hire_release',{contractId:randomUUID()});assert.equal(availableQuantity((await f.current()).state,'coins'),32);const released=await f.call('hire_release',{contractId:id});assert.equal(released.document.state.coins,40);assert.equal(availableQuantity(released.document.state,'coins'),40);assert.equal(released.document.state.recruitment.pending,null);assertResourceState(released.document.state,released.document.actions);const again=await f.call('hire_release',{contractId:id});assert.equal(again.receipt.cashDelta,0);assert.deepEqual(again.document.state.resourceLedger,released.document.state.resourceLedger);});
test(theme+' same application cannot change partner/project or occupy a second population slot',async()=>{const f=await fixture(theme),r=await f.prepare(),id=r.document.state.recruitment.pending.id,d=await f.current();await assert.rejects(f.prepare({contractId:id,candidateId:'yan'}),e=>e.code==='hire_request_changed');await assert.rejects(f.prepare(),e=>e.code==='hire_funds');await assert.rejects(f.prepare({projectId:'missing'}),e=>e.code==='hire_no_work');assert.equal((await f.current()).version,d.version);});
test(theme+' protected renewal reserves an additional wage and releases it without touching old contract',async()=>{const f=await fixture(theme),old=await bound(f);await f.call('plan_create',{project:{id:'renew-wood',title:'继续备料',targets:{wood:50}}});const id=randomUUID(),r=await f.call('hire_renew_prepare',{contractId:old.id,renewalId:id,projectId:'renew-wood'});assertResourceState(r.document.state,r.document.actions);assert.equal(r.document.state.coins,40);assert.equal(availableQuantity(r.document.state,'coins'),24);assert.equal(r.document.state.recruitment.renewal.id,id);await assert.rejects(f.call('hire_release',{contractId:old.id}),e=>e.code==='hire_busy');const released=await f.call('hire_renew_release',{contractId:old.id,renewalId:id});assert.equal(availableQuantity(released.document.state,'coins'),32);assert.equal(released.document.state.resourceLedger.reservations['hire:'+old.id].items.coins,8);assert.equal(released.document.state.recruitment.renewal,null);assert.equal(released.document.state.recruitment.active.id,old.id);assertResourceState(released.document.state,released.document.actions);});
}
