import test from 'node:test';
import assert from 'node:assert/strict';
import {createZeroState} from '../src/freshStart.js';
import {RESIDENTS} from '../src/world.js';
import {hydrateTown,relationship,commitWork,needs,choosePurpose,purposeOptions,applyRelationshipEvent} from '../src/townSimulation.js';
import {groundedConversation} from '../src/conversationFallback.js';
import {workApproachTopic,SOCIAL_TOPIC_COOLDOWN} from '../src/residentSocialTopics.js';
import {recordSocialOutcome,socialBoundary,validResidentLife} from '../src/residentLife.js';
import {recordResidentConversation,claimResidentStory} from '../src/residentStories.js';
import {nextPresentationOperationId} from '../src/resourceLedger.js';
import {validateState} from '../server/saveStore.mjs';
const people=[1,13],profile=i=>RESIDENTS[i],fresh=()=>{const s=hydrateTown(createZeroState());s.freshStartPending=false;return s};
function record(s,d,extra={}){const row={id:nextPresentationOperationId(s,'npc-talk'),participants:people,day:s.day,time:s.economy.daySeconds,...d,...extra};for(const c of row.changes)applyRelationshipEvent(s,c,row.summary);for(const id of people)relationship(s,id,people.find(i=>i!==id)).interactions++;s.npcConversations.push(row);assert(recordSocialOutcome(s,row));return row;}
function work(s,id){return commitWork(id,{goal:'forest',resource:id===1?'wood':'fiber',action:'work',operationId:nextPresentationOperationId(s,'npc-work')},s,30);}
function ready(){const s=fresh();record(s,groundedConversation(people,s,profile,'friendship',10));for(const id of people){work(s,id);needs(id,s).social=20;}return s;}
test('personality alone and stated plans cannot invent a grievance or completed work',()=>{const s=fresh();for(const id of people)relationship(s,id,people.find(j=>j!==id)).interactions=1;assert.equal(workApproachTopic(s,...people,...people.map(profile)),null);for(const id of people)s.npcCareers[id]={phase:0,history:[{action:'work',result:'想做一把椅子'}]};assert.equal(workApproachTopic(s,...people,...people.map(profile)),null);work(s,1);assert.equal(workApproachTopic(s,...people,...people.map(profile)),null);const d=groundedConversation(people,s,profile,'dispute',100);assert.equal(d.type,'friendship');assert(d.changes.every(c=>c.affinity>=0));});
test('a first real exchange and completed work enable a specific differing approach without spending stock',()=>{const s=ready(),before=JSON.stringify(s.inventory),t=workApproachTopic(s,...people,...people.map(profile));assert(t);assert.equal(t.careful,1);assert.equal(t.exploratory,13);assert(t.facts.every(f=>s.taskActionReceipts[f.receiptId]?.npcId===f.id));const d=choosePurpose(1,s,profile(1),100);assert.equal(d.partnerId,13);assert.equal(d.socialType,'dispute');assert.equal(d.socialTopic.key,'work-approach');assert(d.reason.includes('采集'));const talk=groundedConversation(people,s,profile,'dispute',100);assert.equal(talk.type,'dispute');assert(talk.changes.some(c=>c.affinity<0&&c.tension>0));assert(talk.changes.some(c=>c.trust>0));assert.equal(JSON.stringify(s.inventory),before);assert(!talk.lines.some(l=>/上次的分歧|承诺交付/.test(l.text)));});
test('trust can accommodate different methods without manufactured conflict or rewards',()=>{const s=ready();for(const id of people)relationship(s,id,people.find(i=>i!==id)).trust=10;const before=JSON.stringify(s.inventory),d=groundedConversation(people,s,profile,'dispute',100);assert.equal(d.type,'friendship');assert(d.summary.includes('不同偏好'));assert(d.changes.every(c=>c.tension===0));assert.equal(JSON.stringify(s.inventory),before);});
test('completed topic persists across reload, respects three effective days and expires without invented history',()=>{const s=ready();s.economy.daySeconds=340;const d=groundedConversation(people,s,profile,'dispute',350),row=record(s,d);assert(socialBoundary(s,...people));assert.equal(s.residentLife.topics[0].until,340+SOCIAL_TOPIC_COOLDOWN);const saved=JSON.stringify(s);assert.equal(recordSocialOutcome(s,row),false);assert.equal(JSON.stringify(s),saved);const restored=JSON.parse(saved);validateState(restored);restored.day=2;restored.economy.daySeconds=341;assert.equal(socialBoundary(restored,...people),null);for(const id of people)work(restored,id);assert.equal(workApproachTopic(restored,...people,...people.map(profile)),null);restored.day=4;for(const id of people)work(restored,id);assert(workApproachTopic(restored,...people,...people.map(profile)));const bad=structuredClone(restored);bad.residentLife.topics[0].until=Infinity;assert(!validResidentLife(bad));assert.throws(()=>validateState(bad));});
test('hunger, busy partners, similar or changed personalities and absent shared interests prevent inappropriate topics',()=>{const s=ready();needs(1,s).hunger=10;assert.notEqual(choosePurpose(1,s,profile(1),100).action,'social');needs(1,s).hunger=90;s.npcPresence=[{id:13,assignment:true}];assert(!purposeOptions(1,s,profile(1),100).some(o=>o.partnerId===13));assert.equal(workApproachTopic(s,1,13,profile(1),{...profile(13),personality:'细心而谨慎'}),null);assert.equal(workApproachTopic(s,1,13,profile(1),{...profile(13),interest:['no-shared-interest']}),null);s.day=3;assert.equal(workApproachTopic(s,...people,...people.map(profile)),null);});
test('mild disagreement waits the entire boundary then real reconciliation advances the recorded story',()=>{const s=ready();s.economy.daySeconds=340;const row=record(s,groundedConversation(people,s,profile,'dispute',350));const e=recordResidentConversation(s,row,{goal:'forest',buildingId:null,resource:'wood'}).episode;assert.equal(e.kind,'conflict');assert(relationship(s,1,13).tension<12);s.day=e.dueDay;s.economy.daySeconds=0;assert(!purposeOptions(1,s,profile(1),900).some(o=>o.storyId===e.id));s.economy.daySeconds=341;const option=purposeOptions(1,s,profile(1),1241).find(o=>o.storyId===e.id);assert.equal(option.socialType,'reconcile');const id=nextPresentationOperationId(s,'npc-talk');assert(claimResidentStory(s,e.id,1,id,'talk'));const result=groundedConversation(people,s,profile,'reconcile',1241);assert.equal(result.type,'reconcile');assert(result.changes.some(c=>c.tension<0));const done=record(s,result,{id,storyId:e.id});assert(recordResidentConversation(s,done).ok);assert.equal(e.stage,'work');assert.equal(e.status,'scheduled');assert.equal(socialBoundary(s,...people),null);assert(Object.keys(e.contributions).length===0,'agreement does not manufacture delivered materials');});
test('one-sided hurt cannot be overwritten by the other resident wanting reconciliation',()=>{const s=ready();relationship(s,1,13).tension=2;relationship(s,13,1).affinity=-20;const d=groundedConversation(people,s,profile,'reconcile',100);assert.equal(d.type,'reconcile');assert(d.summary.includes('暂未和解'));assert(d.changes.every(c=>c.tension>=0));});
