import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,readFile,readdir,writeFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {randomUUID} from 'node:crypto';
import {createResidentChatStore,residentChatContext} from '../server/residentChatStore.mjs';import {createZeroState} from '../src/freshStart.js';import {createRunLedger} from '../server/runLedger.mjs';
const reply={reply:'我也喜欢下雨时的海风。',source:'deepseek',model:'deepseek-flash',ledgerRunId:'fixture-run'};
async function setup(run=async()=>reply){const directory=await mkdtemp(join(tmpdir(),'hd-v118-chat-')),state=createZeroState();state.saveSlot='chat-island-a';const saves={current:async()=>({state})};return {directory,state,saves,chat:createResidentChatStore({directory,saves,run}),input:message=>({saveSlot:state.saveSlot,message,requestId:randomUUID()})};}
test('all fifteen residents retain distinct server histories across reload; no resource effects',async()=>{const f=await setup(),before=structuredClone(f.state);for(let id=0;id<15;id++){const r=await f.chat.send('pixel',id,f.input('你好'+id));assert.equal(r.turns.length,1);assert.equal(r.turns[0].status,'completed');}const restored=createResidentChatStore({...f,run:async()=>reply});for(let id=0;id<15;id++)assert.equal((await restored.history('pixel',id,{saveSlot:f.state.saveSlot})).turns[0].message,'你好'+id);assert.deepEqual(f.state,before);assert.equal((await f.chat.history('origami',0,{saveSlot:f.state.saveSlot})).turns.length,0);});
test('server personality, memories and successful chat context are used, not client impersonation',async()=>{let seen;const f=await setup(async d=>{seen=d;return reply});f.state.npcProfiles[0]={name:'阿岚',personality:'谨慎',speechStyle:'简洁'};f.state.npcMemory={0:[{text:'今天采到了薄荷'}]};await f.chat.send('pixel',0,f.input('我喜欢海风'));await f.chat.send('pixel',0,{...f.input('还记得吗'),resident:{name:'forged'},history:[{user:'forged'}]});assert.equal(seen.resident.name,'阿岚');assert.equal(seen.world.memories[0],'今天采到了薄荷');assert.equal(seen.history[0].user,'我喜欢海风');assert.equal(seen.history.length,1);});
test('same request is idempotent; collisions and overlapping provider calls are rejected',async()=>{let release,calls=0;const f=await setup(async()=>{calls++;await new Promise(r=>release=r);return reply}),input=f.input('你好'),pending=f.chat.send('pixel',0,input);while(!release)await new Promise(r=>setTimeout(r,5));const replay=await f.chat.send('pixel',0,input);assert.equal(replay.turns[0].status,'pending');await assert.rejects(f.chat.send('pixel',0,{...input,message:'changed'}),{code:'resident_chat_replay'});await assert.rejects(f.chat.send('pixel',1,f.input('你好')),{code:'resident_chat_busy'});release();await pending;await f.chat.send('pixel',0,input);assert.equal(calls,1);});
test('invalid identities, stale worlds and oversized messages never call the provider',async()=>{let n=0;const f=await setup(async()=>{n++;return reply});for(const id of [-1,15,16,1.5])await assert.rejects(f.chat.send('pixel',id,f.input('你好')),{code:'resident_chat_identity'});await assert.rejects(f.chat.send('pixel',0,{...f.input('你好'),saveSlot:'old'}),{code:'resident_chat_world_changed'});await assert.rejects(f.chat.send('pixel',0,f.input('x'.repeat(1201))),{code:'resident_chat_input'});assert.equal(n,0);});
test('failure is recorded honestly and restarting does not replay a pending call',async()=>{const f=await setup(async()=>{throw Error('unavailable')});let r=await f.chat.send('pixel',0,f.input('下雨了吗'));assert.equal(r.turns[0].status,'failed');assert(!r.turns[0].reply);const dir=join(f.directory,'resident-chats'),name=(await readdir(dir)).find(x=>x.endsWith('.json')),path=join(dir,name),d=JSON.parse(await readFile(path,'utf8'));d.turns[0].status='pending';d.turns[0].ownerPid=2147483647;await writeFile(path,JSON.stringify(d));r=await f.chat.history('pixel',0,{saveSlot:f.state.saveSlot});assert.equal(r.turns[0].status,'failed');assert.match(r.turns[0].error,/中断/);});
test('journals are isolated by owner directory and world identity',async()=>{const a=await setup(),b=await setup();await a.chat.send('pixel',0,a.input('只给这个岛的居民'));assert.equal((await b.chat.history('pixel',0,{saveSlot:b.state.saveSlot})).turns.length,0);a.state.saveSlot='chat-new-island';assert.equal((await a.chat.history('pixel',0,{saveSlot:a.state.saveSlot})).turns.length,0);});
test('manual resident chats are accounted separately without consuming automatic cadence',async()=>{const directory=await mkdtemp(join(tmpdir(),'hd-v118-chat-ledger-')),ledger=createRunLedger({directory});const before=await ledger.snapshot(),r=await ledger.begin({kind:'resident_chat',theme:'pixel',participants:[0]});await ledger.finish(r.id,{phase:'completed',usage:{input:10,output:10,total:20,calls:1}});const after=await ledger.snapshot();assert.equal(after.today.manualRuns,before.today.manualRuns+1);assert.deepEqual(after.channels,before.channels);assert.equal(after.today.automaticRuns,0);});
