import {loadRuntimeEnvironment} from '../server/runtimeConfig.mjs';
import {centralClockProviderFromEnvironment} from '../server/environmentService.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import{mkdtemp,readFile,realpath}from'node:fs/promises';import{join,resolve}from'node:path';import{tmpdir}from'node:os';
import{DEFAULT_CLOCK,validEnvironmentClock,environmentAt}from'../src/environmentClock.js';import{createEnvironmentClient}from'../src/environmentClient.js';import{createEnvironmentService}from'../server/environmentService.mjs';import{buildEnvironmentGeometry}from'../src/environmentGeometry.js';import{createLanHttpServer}from'../server/lanServer.mjs';
const clock={...DEFAULT_CLOCK,clockId:'clock-test',epochMs:1000000,phaseAtEpoch:0};
test('all four seasons rotate on the shared clock, including boundaries and rate; not the economy date',()=>{for(let n=0;n<8;n++){const s=environmentAt(clock,clock.epochMs+n*clock.seasonDays*clock.dayLengthMs);assert.equal(s.season,['spring','summer','autumn','winter'][n%4]);}assert.equal(environmentAt({...clock,rate:2},clock.epochMs+3.5*clock.dayLengthMs).season,'summer');assert.equal(environmentAt(clock,clock.epochMs-1).season,'winter');});
test('dawn, daylight, dusk and readable night are continuous and periodic',()=>{for(const [hour,period]of [[3,'night'],[6,'dawn'],[12,'day'],[18,'dusk'],[22,'night']]){const e=environmentAt({...clock,phaseAtEpoch:hour/24},clock.epochMs);assert.equal(e.period,period);assert(Number.isFinite(e.night));assert.equal(e.clockText,String(hour).padStart(2,'0')+':00');}assert.equal(environmentAt(clock,clock.epochMs+clock.dayLengthMs).hour,0);assert.equal(environmentAt({...clock,phaseAtEpoch:.5},clock.epochMs).daylight,1);});
test('protocol rejects invalid durations, unsupported seasons, revisions and malformed values',()=>{for(const patch of [{dayLengthMs:0},{seasonDays:0},{seasonDays:1000},{rate:Infinity},{epochMs:NaN},{revision:0},{source:'browser'},{clockId:'../private'}])assert(!validEnvironmentClock({...clock,...patch}));});
test('client interpolation uses monotonic elapsed time, caches failures and rejects stale revisions',async()=>{let at=0,fail=false;const c=createEnvironmentClient({now:()=>at,wallNow:()=>clock.epochMs,fetchClock:async()=>{if(fail)throw Error('network down');return{clock,serverNowMs:clock.epochMs,synchronization:'synced'};}});await c.refresh();at=450000;assert.equal(c.sample().hour,12);fail=true;await c.refresh();at=675000;assert.equal(c.sample().hour,18);assert(c.sample().error);assert.throws(()=>c.accept({clock:{...clock,revision:0},serverNowMs:clock.epochMs}));});
test('central revisions are atomic, preserved across restart and cannot silently rewrite one revision',async()=>{const directory=await mkdtemp(join(tmpdir(),'hd-clock-'));let at=clock.epochMs;const s=await createEnvironmentService({directory,now:()=>at,centralClockProvider:null});const before=s.view().clock;assert.equal(before.source,'local');const central={...clock,source:'central',revision:2,secret:'must not persist'};await s.synchronize(central);await assert.rejects(()=>s.synchronize({...central,revision:1}));await assert.rejects(()=>s.synchronize({...central,seasonDays:8}));const disk=JSON.parse(await readFile(s.file,'utf8'));assert.equal(disk.secret,undefined);const reopened=await createEnvironmentService({directory,now:()=>at,centralClockProvider:null});assert.deepEqual(reopened.view().clock,disk);await s.close();await reopened.close();});
test('provider outages keep the last synchronized clock; no request waits for central polling',async()=>{const directory=await mkdtemp(join(tmpdir(),'hd-clock-provider-'));let broken=false;const s=await createEnvironmentService({directory,now:()=>clock.epochMs,centralClockProvider:async()=>{if(broken)throw Error('upstream down');return{clock:{...clock,source:'central'}};}});await s.refresh();const before=s.view().clock;broken=true;await s.refresh();assert.deepEqual(s.view().clock,before);assert.equal(s.view().synchronization,'unavailable');await s.close();});
test('connected-ocean mask never includes isolated blue roofs, crystals or land',()=>{const w=24,h=20,data=new Uint8ClampedArray(w*h*4);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const land=x>=4&&x<20&&y>=4&&y<16,n=(y*w+x)*4;data.set(land?[90,150,60,255]:[12,160,205,255],n);}for(let y=8;y<11;y++)for(let x=10;x<13;x++)data.set([30,170,230,255],(y*w+x)*4);const f=buildEnvironmentGeometry(data,w,h,1);assert(f.isWater(1,1));assert(!f.isWater(6,6));assert(!f.isWater(11,9));assert(f.coast.length>=1);assert(f.coast.flat().every(p=>Number.isFinite(p.nx)&&Number.isFinite(p.ny)));});
test('LAN clock endpoint is read-only shared metadata, never personal state',async()=>{const directory=await realpath(await mkdtemp(join(tmpdir(),'hd-clock-api-'))),s=await createLanHttpServer({directory,port:0,enrollmentKey:'CLOCK-TEST',environmentClockProvider:null}),base='http://127.0.0.1:'+s.port;try{const a=await(await fetch(base+'/api/world/environment')).json(),b=await(await fetch(base+'/api/world/environment')).json();assert.deepEqual(a.clock,b.clock);assert(validEnvironmentClock(a.clock));assert.equal((await fetch(base+'/api/world/environment',{method:'POST'})).status,405);assert.deepEqual(s.environmentService.view().clock,a.clock);assert(!JSON.stringify(a).includes('account'));}finally{await s.close();}});

test('concurrent first boot publishes one complete clock before other readers can open it',async()=>{for(let round=0;round<4;round++){const directory=await mkdtemp(join(tmpdir(),'hd-clock-race-'));const services=await Promise.all(Array.from({length:12},()=>createEnvironmentService({directory,centralClockProvider:null})));const clocks=services.map(s=>s.view().clock);assert(clocks.every(c=>JSON.stringify(c)===JSON.stringify(clocks[0])));assert.deepEqual(JSON.parse(await readFile(services[0].file,'utf8')),clocks[0]);await Promise.all(services.map(s=>s.close()));}});

test('independent services cannot overwrite a newer persisted central revision with stale cached state',async()=>{const directory=await mkdtemp(join(tmpdir(),'hd-clock-shared-revision-'));const a=await createEnvironmentService({directory,centralClockProvider:null}),b=await createEnvironmentService({directory,centralClockProvider:null});await a.synchronize({...clock,revision:3});await assert.rejects(b.synchronize({...clock,revision:2}),/stale_environment_clock/);assert.equal(JSON.parse(await readFile(a.file,'utf8')).revision,3);await Promise.allSettled([a.synchronize({...clock,revision:10}),b.synchronize({...clock,revision:9})]);assert.equal(JSON.parse(await readFile(a.file,'utf8')).revision,10);await a.close();await b.close();});

test('private deployment clock settings are loaded literally and metadata directory is resolved',()=>{const environment={};const c=loadRuntimeEnvironment({root:'/fixture',environment,read:()=>"HD_WORLD_CLOCK_URL=https://clock.example.test/world\nHD_WORLD_CLOCK_TOKEN=fixture-private-token\nHD_ENVIRONMENT_DIR=data/shared-clock\n",exists:()=>false,platform:'linux'});assert.equal(environment.HD_WORLD_CLOCK_URL,'https://clock.example.test/world');assert.equal(environment.HD_WORLD_CLOCK_TOKEN,'fixture-private-token');assert.equal(environment.HD_ENVIRONMENT_DIR,resolve('/fixture','data/shared-clock'));assert(c.loadedFields.includes('HD_WORLD_CLOCK_TOKEN'));assert.throws(()=>centralClockProviderFromEnvironment({HD_WORLD_CLOCK_URL:'https://user:password@clock.example.test/'}));});
