import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,readdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {spawn} from 'node:child_process';
import {atomicJSON} from '../server/atomicJson.mjs';
import {createStewardRequestStore} from '../server/stewardRequestStore.mjs';
const seed={worldKey:'fictional-world-one',requestId:'fixture-request-one',message:'整理虚构简报并保存文件',includeWorkProject:false};
const fixture=async()=>{const directory=await mkdtemp(join(tmpdir(),'hd-steward-receipt-'));return{directory,store:createStewardRequestStore({directory,waitMs:3000})};};
const result={source:'hermes',answer:'已保存并回读虚构文件。',operations:[{tool:'document_create',status:'done'}],artifacts:[{id:'capture-'+ 'a'.repeat(32),name:'fictional-note.txt'}],commands:[],plans:[]};
test('lost HTTP response replay and a reopened service never perform the document operation twice',async()=>{const f=await fixture();let calls=0;const file=join(f.directory,'fictional-note.txt');const run=async()=>{calls++;await writeFile(file,'version one',{flag:'wx'});return result;};const first=await f.store.run(seed,run);const reopened=createStewardRequestStore({directory:f.directory});const replay=await reopened.run({...seed,theme:'origami',day:99,history:[{content:'context changed'}]},run);assert.equal(calls,1);assert.equal(await readFile(file,'utf8'),'version one');assert.deepEqual(replay.artifacts,first.artifacts);assert.equal(replay.receiptReplay,true);assert.equal((await reopened.get(seed.worldKey,seed.requestId)).status,'completed');});
test('same id cannot change the message, project disclosure or resumed session',async()=>{const f=await fixture();await f.store.run(seed,async()=>result);for(const change of [{message:'换一份文档'},{includeWorkProject:true},{resumeSessionId:'session-new'}])await assert.rejects(f.store.run({...seed,...change},()=>{throw Error('must not execute');}),e=>e.code==='steward_request_replay');});
test('two store instances wait for one claimed execution and expose only this world receipt',async()=>{const f=await fixture();let release,entered;const gate=new Promise(r=>release=r),started=new Promise(r=>entered=r);let calls=0;const first=f.store.run(seed,async()=>{calls++;entered();await gate;return result;});await started;const other=createStewardRequestStore({directory:f.directory});assert.equal((await other.get(seed.worldKey,seed.requestId)).status,'running');assert.equal(await other.get('another-world',seed.requestId),null);const second=other.run(seed,()=>{calls++;return result;});release();const [a,b]=await Promise.all([first,second]);assert.equal(calls,1);assert.deepEqual(a.artifacts,b.artifacts);});
const moduleUrl=new URL('../server/stewardRequestStore.mjs',import.meta.url).href;
function processRun(directory,mode='normal'){const code=`import {writeFile} from 'node:fs/promises';import{join}from'node:path';const{createStewardRequestStore}=await import(process.argv[2]);const store=createStewardRequestStore({directory:process.argv[1],waitMs:5000});const r=await store.run(${JSON.stringify(seed)},async()=>{await writeFile(join(process.argv[1],'one-operation.txt'),'only once',{flag:'wx'});console.log('tool-written');${mode==='crash'?'await new Promise(()=>setInterval(()=>{},1000));':'await new Promise(r=>setTimeout(r,700));'}return ${JSON.stringify(result)}});console.log(JSON.stringify({source:r.source,replay:!!r.receiptReplay}));`;
 const child=spawn(process.execPath,['--input-type=module','-e',code,directory,moduleUrl],{windowsHide:true,stdio:['ignore','pipe','pipe']});let output='',error='';child.stdout.on('data',b=>output+=b);child.stderr.on('data',b=>error+=b);const done=new Promise((resolve,reject)=>{child.once('error',reject);child.once('exit',code=>resolve({code,output,error}));});return{child,done,output:()=>output};}
test('two real processes competing for one request write exactly one file',async()=>{const f=await fixture();const a=processRun(f.directory),b=processRun(f.directory);const rows=await Promise.all([a.done,b.done]);assert(rows.every(r=>r.code===0),JSON.stringify(rows));assert.equal(rows.filter(r=>r.output.includes('tool-written')).length,1);assert.equal(await readFile(join(f.directory,'one-operation.txt'),'utf8'),'only once');assert.equal((await f.store.get(seed.worldKey,seed.requestId)).status,'completed');});
test('a stopped process after a tool write is unconfirmed and cannot be silently rerun',async()=>{const f=await fixture(),p=processRun(f.directory,'crash');for(let i=0;i<100&&!p.output().includes('tool-written');i++)await new Promise(r=>setTimeout(r,20));assert(p.output().includes('tool-written'));assert.equal(p.child.exitCode,null);assert.equal((await f.store.get(seed.worldKey,seed.requestId)).status,'running');p.child.kill();await p.done;const stored=await f.store.get(seed.worldKey,seed.requestId);assert.equal(stored.status,'unconfirmed');let calls=0;await assert.rejects(f.store.run(seed,async()=>{calls++;return result;}),e=>e.code==='steward_request_unconfirmed');assert.equal(calls,0);assert.equal(await readFile(join(f.directory,'one-operation.txt'),'utf8'),'only once');});
test('a tool exception leaves a durable unconfirmed receipt, including after reload',async()=>{const f=await fixture();await assert.rejects(f.store.run(seed,async()=>{throw Error('fixture tool interrupted')}),e=>e.code==='steward_request_unconfirmed');const next=createStewardRequestStore({directory:f.directory});assert.equal((await next.get(seed.worldKey,seed.requestId)).status,'unconfirmed');await assert.rejects(next.run(seed,async()=>result),e=>e.code==='steward_request_unconfirmed');});
test('corrupt receipt and invalid identifiers cannot start a replacement operation',async()=>{const f=await fixture();await f.store.run(seed,async()=>result);const dir=join(f.directory,'steward-requests',(await readdir(join(f.directory,'steward-requests')))[0]),file=join(dir,(await readdir(dir)).find(n=>n.endsWith('.json')));await writeFile(file,'{"schema":1}');await assert.rejects(f.store.run(seed,async()=>result),e=>e.code==='steward_receipt_corrupt');await assert.rejects(f.store.run({...seed,requestId:'../../other'},async()=>result),e=>e.code==='steward_request_invalid');});

test('a failed final receipt write preserves the original claim without allowing a second execution',async()=>{const f=await fixture();let writes=0,calls=0;const store=createStewardRequestStore({directory:f.directory,writeJSON:async(file,value)=>{if(++writes===2)throw Error('fixture disk unavailable');return atomicJSON(file,value);}});await assert.rejects(store.run(seed,async()=>{calls++;await writeFile(join(f.directory,'saved-before-receipt.txt'),'already saved');return result;}),e=>e.code==='steward_receipt_unavailable');assert.equal((await store.get(seed.worldKey,seed.requestId)).status,'unconfirmed');await assert.rejects(f.store.run(seed,async()=>{calls++;return result;}),e=>e.code==='steward_request_unconfirmed');assert.equal(calls,1);assert.equal(await readFile(join(f.directory,'saved-before-receipt.txt'),'utf8'),'already saved');});
