import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,realpath} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {randomUUID} from 'node:crypto';
import {createLanHttpServer} from '../server/lanServer.mjs';import {createLanCollaborationStore} from '../server/lanCollaborationStore.mjs';import {islandExchangeContext} from '../server/islandExchangeContext.mjs';
async function fixture({gate=async()=>{},decision='share'}={}){
 const directory=await mkdtemp(join(await realpath(tmpdir()),'hd-v137-info-')),calls=[];let clock=1800000000000;
 const runtime=({ownerId})=>({documents:'fictional-private-workspace',async call(method,p){if(method==='status')return {hermes:{configured:true}};assert.equal(method,'a2a');assert.equal(p.stage,'exchange');calls.push({ownerId,p});await gate();return {source:'hermes',ledgerRunId:'run-'+randomUUID(),runId:'provider-'+randomUUID(),reply:{decision,message:p.sharedContext.islandName+'的管家向对方介绍了岛上的真实设施。'}};},async close(){}});
 let service=await createLanHttpServer({directory,port:0,enrollmentKey:'INFORMATION-FIXTURE',agentRuntimeFactory:runtime,now:()=>clock});const users=[];
 try{for(let n=0;n<3;n++){const theme=n===1?'origami':'pixel',a=await service.identities.register({login:'exchange_'+n,password:'fixture-password',name:'虚构岛主'+n,islandName:'虚构岛屿'+n,avatar:n===1?'female_2':'male_1',theme});await service.tenants.open(a.token,theme,{});users.push({...a,id:a.view.me.id,theme});}
 const room=(await service.identities.action(users[0].token,{operation:'room_create',requestId:randomUUID(),title:'管家会客验证',maxPlayers:4})).view.room;await service.identities.action(users[1].token,{operation:'room_join',requestId:randomUUID(),code:room.code});
 const f={directory,users,room,calls,get service(){return service;},call:(n,operation,args={})=>service.collaboration.action(users[n].token,{operation,requestId:randomUUID(),...args}),view:n=>service.collaboration.view(users[n].token),advance:ms=>clock+=ms,restart:async()=>{await service.close();service=await createLanHttpServer({directory,port:0,enrollmentKey:'INFORMATION-FIXTURE',agentRuntimeFactory:runtime,now:()=>clock});},close:()=>service.close()};return f;
 }catch(e){await service.close();throw e;}
}
async function until(f,id,status){for(let k=0;k<100;k++){const t=(await f.view(0)).tasks.find(t=>t.id===id);if(t?.status===status)return t;if(t?.status==='retry'&&status!=='retry')throw Error(t.error);await new Promise(r=>setTimeout(r,15));}throw Error('No '+status);}
async function enabled(f){for(let n=0;n<2;n++)await f.call(n,'information_preference',{receive:true});}
const topic='请介绍我们的工坊，并问问对方随行居民的职业。';
test('two authenticated owners exchange real canonical contexts with linked, durable and idempotent messages',async()=>{const f=await fixture();try{
 const zero0=await f.service.tenants.readIslandForServer(f.users[0].id,'pixel'),zero1=await f.service.tenants.readIslandForServer(f.users[1].id,'origami');await enabled(f);
 const body={operation:'exchange',recipientId:f.users[1].id,topic,requestId:randomUUID()},r=await f.service.collaboration.action(f.users[0].token,body);let t=await until(f,r.taskId,'awaiting_response');assert.equal(f.calls.length,1);assert.equal(f.calls[0].ownerId,f.users[0].id);assert.equal(f.calls[0].p.sharedContext.islandName,'虚构岛屿0');assert.equal(t.messages[0].homeWorldKey,zero0.state.saveSlot);
 assert((await f.service.collaboration.action(f.users[0].token,body)).replayed);assert.equal(f.calls.length,1);await assert.rejects(f.service.collaboration.action(f.users[0].token,{...body,topic:'改变主题'}),e=>e.code==='a2a_replay');
 await assert.rejects(f.call(0,'respond',{taskId:t.id}),e=>e.code==='a2a_stage');await f.call(1,'respond',{taskId:t.id,message:'我方管家，请介绍自己的岛屿。'});t=await until(f,t.id,'awaiting_response');for(let k=0;k<100&&t.messages.length<2;k++){await new Promise(r=>setTimeout(r,15));t=(await f.view(0)).tasks[0];}assert.equal(t.messages.length,2);assert.equal(f.calls[1].ownerId,f.users[1].id);assert.equal(f.calls[1].p.sharedContext.islandName,'虚构岛屿1');assert.equal(t.messages[1].parentRunId,t.messages[0].ledgerRunId);assert.equal(t.messages[1].homeWorldKey,zero1.state.saveSlot);
 assert.deepEqual((await f.view(1)).tasks[0],t);assert.equal((await f.view(2)).tasks.length,0);await assert.rejects(f.call(2,'respond',{taskId:t.id}),e=>e.code==='a2a_forbidden');await assert.rejects(f.call(1,'execute',{taskId:t.id}),e=>e.code==='a2a_stage');
 await f.restart();assert.deepEqual((await f.view(1)).tasks[0].messages,t.messages);assert.equal(f.calls.length,2);for(const [n,before] of [[0,zero0],[1,zero1]]){const after=await f.service.tenants.readIslandForServer(f.users[n].id,f.users[n].theme);assert.deepEqual(after.state.inventory,before.state.inventory);assert.equal(after.state.coins,before.state.coins);}
 }finally{await f.close();}});
test('information consent is independent of activity consent and requires actual same-room stewards',async()=>{const f=await fixture();try{
 await f.call(0,'preference',{receive:true});await f.call(1,'preference',{receive:true});await assert.rejects(f.call(0,'exchange',{recipientId:f.users[1].id,topic}),e=>e.code==='a2a_consent');await enabled(f);await f.call(0,'preference',{receive:false});assert.equal((await f.view(0)).informationEnabled,true);assert.equal((await f.view(0)).enabled,false);
 await f.call(2,'information_preference',{receive:true});await assert.rejects(f.call(0,'exchange',{recipientId:f.users[2].id,topic}),e=>e.code==='a2a_room');const r=await f.call(0,'exchange',{recipientId:f.users[1].id,topic});await until(f,r.taskId,'awaiting_response');await assert.rejects(f.call(0,'exchange',{recipientId:f.users[1].id,topic:'第二个话题'}),e=>e.code==='a2a_duplicate');await f.call(1,'information_preference',{receive:false});assert.equal((await f.view(0)).tasks[0].status,'cancelled');assert.equal((await f.view(1)).enabled,true);
 }finally{await f.close();}});
test('leaving, expiry and a late model reply cannot reopen an information conversation',async()=>{let release,entered,once=true;const gate=new Promise(r=>release=r),ready=new Promise(r=>entered=r);const f=await fixture({gate:async()=>{if(once){once=false;entered();await gate;}}});try{
 await enabled(f);const r=await f.call(0,'exchange',{recipientId:f.users[1].id,topic});await ready;await f.call(1,'information_preference',{receive:false});assert.equal((await f.view(0)).tasks[0].status,'cancelled');release();await f.service.collaboration.close();assert.equal((await f.view(0)).tasks[0].messages.length,0);
 }finally{release();await f.close();}
 const next=await fixture();try{await enabled(next);const r=await next.call(0,'exchange',{recipientId:next.users[1].id,topic});await until(next,r.taskId,'awaiting_response');next.advance(1800001);assert.equal((await next.view(0)).tasks[0].status,'expired');await assert.rejects(next.call(1,'respond',{taskId:r.taskId}),e=>e.code==='a2a_ended');}finally{await next.close();}});
test('public context excludes private real-life content, conversations and credentials',()=>{const state={day:3,buildings:{0:0,1:1},facilities:{0:{quality:82}},coins:999,inventory:{wood:9},npcMemory:{0:'PRIVATE_MEMORY'},agentExecutions:['PRIVATE_JOB'],workProject:{brief:'PRIVATE_PROJECT'},portfolio:{biography:'PRIVATE_BIO'},DEEPSEEK_API_KEY:'PRIVATE_KEY'};const person={name:'虚构管家',homeIslandName:'虚构岛屿',homeTheme:'pixel',personality:'沉稳',job:'管家'};const data=islandExchangeContext(state,person,[{name:'虚构园丁',job:'园艺',kind:'ai',interest:['花卉'],secret:'PRIVATE_COMPANION'}]);assert.equal(data.buildings.length,2);assert.equal(data.buildings[0].quality,82);assert.equal(data.companions[0].name,'虚构园丁');assert(!JSON.stringify(data).includes('PRIVATE_'));assert(!('coins' in data));assert(!('inventory' in data));});
test('interrupted coordinator recovers only the original owner turn and ignores its old reply',async()=>{let release,entered,once=true;const gate=new Promise(r=>release=r),ready=new Promise(r=>entered=r);const f=await fixture({gate:async()=>{if(once){once=false;entered();await gate;}}});let replacement;try{
 await enabled(f);const r=await f.call(0,'exchange',{recipientId:f.users[1].id,topic});await ready;replacement=createLanCollaborationStore({directory:f.directory,identities:f.service.identities,tenants:f.service.tenants,activities:f.service.activities,agents:f.service.agents});assert.equal((await replacement.view(f.users[0].token)).tasks[0].status,'retry');release();await f.service.collaboration.close();assert.equal((await replacement.view(f.users[0].token)).tasks[0].messages.length,0);await assert.rejects(replacement.action(f.users[1].token,{operation:'retry',taskId:r.taskId,requestId:randomUUID()}),e=>e.code==='a2a_stage');await replacement.action(f.users[0].token,{operation:'retry',taskId:r.taskId,requestId:randomUUID()});await replacement.close();assert.equal((await replacement.view(f.users[0].token)).tasks[0].messages.length,1);
 }finally{release();await replacement?.close();await f.close();}});
