import test from 'node:test';import assert from 'node:assert/strict';
import {mkdir,mkdtemp,readFile,writeFile} from 'node:fs/promises';import {resolve} from 'node:path';import {randomUUID} from 'node:crypto';
import {createLanHttpServer} from '../server/lanServer.mjs';import {createDeviceBridgeClient,normalizeBridgeServer} from '../server/deviceBridgeClient.mjs';
async function fixture(){
 await mkdir('qa/v138',{recursive:true});const dir=await mkdtemp(resolve('qa/v138/bridge-'));let time=1800000000000;const serverCalls=[],deviceCalls=[];
 const status={hermes:{configured:true,model:'deepseek-flash'},deepseek:{configured:true,model:'deepseek-flash'}};
 const localFactory=({ownerId})=>({documents:'SERVER-WORKSPACE',async call(method,args){serverCalls.push({ownerId,method,args});if(method==='status')return structuredClone(status);return {source:'hermes',answer:'server fixture',ownerId};},async close(){}});
 let service=await createLanHttpServer({directory:resolve(dir,'data'),port:0,enrollmentKey:'BRIDGE-FIXTURE',agentRuntimeFactory:localFactory,now:()=>time});const users=[];
 for(let i=0;i<2;i++){const u=await service.identities.register({login:'device_'+i,password:'fixture-password',name:'虚构设备岛主'+i,islandName:'原机验证岛'+i,theme:i?'origami':'pixel',avatar:'male_1'});await service.tenants.open(u.token,i?'origami':'pixel',{});users.push({...u,id:u.view.me.id,theme:i?'origami':'pixel'});}
 const clients=[];
 const api=async(i,path,input)=>{const r=await fetch('http://127.0.0.1:'+service.port+path,{method:input?'POST':'GET',headers:{Cookie:'hd_lan_session='+users[i].token,'X-HD-Island':users[i].id,...(input?{'Content-Type':'application/json'}:{})},body:input?JSON.stringify(input):undefined});return {status:r.status,data:await r.json()};};
 async function pair(i,{fetchImpl=fetch,approve=true}={}){
  const p=await api(i,'/api/lan/bridge/pair',{});assert.equal(p.status,200);const workspace=resolve(dir,'documents-'+i),directory=resolve(dir,'client-'+i);await mkdir(workspace,{recursive:true});
  const runtimeFactory=({ownerId,documentRoot})=>({documents:documentRoot,async call(method,args){if(method==='status')return structuredClone(status);deviceCalls.push({ownerId,method,args,documentRoot});if(method==='command'){await writeFile(resolve(documentRoot,'result.txt'),'实际文件写入 '+args.message);return {source:'hermes',answer:'原机完成 '+args.message,ledgerRunId:'fixture-'+randomUUID(),operations:[{tool:'write',status:'completed',path:resolve(documentRoot,'result.txt')}]};}if(method==='a2a')return {source:'hermes',ledgerRunId:'fixture-'+randomUUID(),runId:'fixture-'+randomUUID(),reply:{decision:'share',message:'原机管家介绍 '+args.sharedContext.islandName}};return {source:'hermes',method};},async close(){}});
  const client=await createDeviceBridgeClient({server:'http://127.0.0.1:'+service.port,workspace,directory,pairCode:p.data.code,name:'原机-'+i,runtimeFactory,fetchImpl,heartbeatMs:60000});clients.push(client);
  if(approve){const a=await api(i,'/api/lan/bridge/approve',{deviceId:client.info.deviceId,verification:client.info.verification});assert.equal(a.status,200);}
  return {client,workspace,directory,runtimeFactory,code:p.data.code,fetchImpl};
 }
 return {dir,users,api,pair,serverCalls,deviceCalls,get service(){return service;},advance:ms=>time+=ms,async restart(){const port=service.port;await service.close();service=await createLanHttpServer({directory:resolve(dir,'data'),port,enrollmentKey:'BRIDGE-FIXTURE',agentRuntimeFactory:localFactory,now:()=>time});},async close(){for(const c of clients)await c.close();await service.close();}};
}
async function completed(f,i,id){for(let n=0;n<100;n++){const v=await f.service.agents.view(f.users[i].token,f.users[i].theme),j=v.jobs.find(j=>j.id===id);if(j?.status==='completed')return j;if(j?.status==='unconfirmed')throw Error(j.error);await new Promise(r=>setTimeout(r,10));}throw Error('No completed command');}
test('pairing requires the owning island approval; credentials stay hashed and foreign owners cannot bind or revoke',async()=>{const f=await fixture();try{const p=await f.pair(0,{approve:false});assert.equal((await p.client.tick()).phase,'awaiting-owner-approval');const foreign=await f.api(1,'/api/lan/bridge/approve',{deviceId:p.client.info.deviceId,verification:p.client.info.verification});assert.equal(foreign.status,403);assert.equal((await f.api(0,'/api/lan/bridge/approve',{deviceId:p.client.info.deviceId,verification:'000000'})).status,409);assert.equal((await f.api(0,'/api/lan/bridge/approve',{deviceId:p.client.info.deviceId,verification:p.client.info.verification})).status,200);assert.equal((await f.api(1,'/api/lan/bridge/revoke',{deviceId:p.client.info.deviceId})).status,403);const credentials=JSON.parse(await readFile(resolve(p.directory,'client.json'),'utf8')),registry=await readFile(resolve(f.dir,'data/_lan/device-bridge/registry.json'),'utf8');assert(!registry.includes(credentials.secret));assert(!registry.includes(p.code));assert.equal((await f.api(1,'/api/lan/bridge')).data.bound,null);}finally{await f.close();}});
test('bound steward uses the original workspace while visiting, carries private history and keeps server NPC decisions separate',async()=>{const f=await fixture();try{const p=await f.pair(1);await f.service.agents.automatic(f.users[1].token,'plans',{theme:'origami',saveSlot:(await f.service.tenants.readIslandForServer(f.users[1].id,'origami')).state.saveSlot});const room=await f.service.identities.action(f.users[0].token,{operation:'room_create',requestId:randomUUID(),title:'原机访客验证',maxPlayers:2});await f.service.identities.action(f.users[1].token,{operation:'room_join',requestId:randomUUID(),code:room.view.room.code});const input={theme:'origami',requestId:randomUUID(),message:'访客文档便笺'};await f.service.agents.submit(f.users[1].token,input);assert.equal((await p.client.tick()).phase,'completed');const done=await completed(f,1,input.requestId);assert.equal(done.location,'visit');assert.equal(await readFile(resolve(p.workspace,'result.txt'),'utf8'),'实际文件写入 '+input.message);assert.equal(f.serverCalls.filter(c=>c.method==='command').length,0);assert.equal(f.deviceCalls[0].ownerId,f.users[1].id);const view=await f.service.agents.view(f.users[1].token,'origami');assert.equal(view.documents,p.workspace);assert.equal(view.capabilities.deviceBridge,true);assert(view.status.deviceBridge.online);assert(!JSON.stringify(await f.service.identities.view(f.users[0].token)).includes(input.message));assert(!JSON.stringify(await f.service.agents.view(f.users[0].token,'pixel')).includes(input.message));assert(f.serverCalls.some(c=>c.method==='plans'));assert(!f.deviceCalls.some(c=>c.method==='plans'));}finally{await f.close();}});
test('missing completion acknowledgement and duplicate command never repeat original file tools',async()=>{const f=await fixture();try{let drop=true;const p=await f.pair(0,{fetchImpl:async(url,args)=>{const response=await fetch(url,args);if(url.endsWith('/complete')&&drop){drop=false;await response.arrayBuffer();throw Error('lost completion acknowledgement');}return response;}}),input={theme:'pixel',requestId:randomUUID(),message:'只执行一次'};await f.service.agents.submit(f.users[0].token,input);await assert.rejects(p.client.tick(),/lost completion/);await completed(f,0,input.requestId);await f.service.agents.submit(f.users[0].token,input);assert.equal((await p.client.tick()).phase,'idle');assert.equal(f.deviceCalls.filter(c=>c.method==='command').length,1);await assert.rejects(f.service.agents.submit(f.users[0].token,{...input,message:'改写原请求'}),e=>e.code==='lan_agent_replay');}finally{await f.close();}});
test('original-device A2A messages use this owner actor and require no file tool authority',async()=>{const f=await fixture();try{const p=await f.pair(1),room=await f.service.identities.action(f.users[0].token,{operation:'room_create',requestId:randomUUID(),title:'原机通信',maxPlayers:2});await f.service.identities.action(f.users[1].token,{operation:'room_join',requestId:randomUUID(),code:room.view.room.code});for(const u of f.users)await f.service.collaboration.action(u.token,{operation:'information_preference',requestId:randomUUID(),receive:true});const r=await f.service.collaboration.action(f.users[1].token,{operation:'exchange',requestId:randomUUID(),recipientId:f.users[0].id,topic:'分享我的岛屿设施'});await p.client.tick();let t;for(let n=0;n<100;n++){await p.client.tick();t=(await f.service.collaboration.view(f.users[0].token)).tasks.find(t=>t.id===r.taskId);if(t?.status==='awaiting_response')break;await new Promise(r=>setTimeout(r,10));}assert.equal(t.status,'awaiting_response');assert.match(t.messages[0].text,/原机验证岛1/);assert.equal(t.messages[0].ownerAccountId,f.users[1].id);assert.equal(f.deviceCalls.filter(c=>c.method==='a2a').length,1);assert.equal(f.deviceCalls.filter(c=>c.method==='command').length,0);}finally{await f.close();}});
test('offline and revoked devices never silently move document work to the game server',async()=>{const f=await fixture();try{const p=await f.pair(0);f.advance(50000);await f.service.agents.submit(f.users[0].token,{theme:'pixel',requestId:randomUUID(),message:'离线不能操作'});await new Promise(r=>setTimeout(r,20));assert.equal(f.serverCalls.filter(c=>c.method==='command').length,0);assert.equal((await f.service.agents.status(f.users[0].token)).originalDevice.online,false);const v=await f.service.agents.view(f.users[0].token,'pixel');assert.equal(v.jobs.at(-1).status,'unconfirmed');assert.match(v.jobs.at(-1).error,/原机离线/);await f.api(0,'/api/lan/bridge/revoke',{deviceId:p.client.info.deviceId});await assert.rejects(p.client.tick(),e=>e.code==='bridge_revoked');}finally{await f.close();}});
test('transport accepts loopback HTTP, requires HTTPS for arbitrary devices and rejects URL credentials',()=>{assert.equal(normalizeBridgeServer('http://127.0.0.1:4175/'),'http://127.0.0.1:4175');assert.throws(()=>normalizeBridgeServer('http://remote.example'),e=>e.code==='bridge_transport');assert.throws(()=>normalizeBridgeServer('https://username:password@remote.example'));assert.equal(normalizeBridgeServer('https://remote.example'),'https://remote.example');assert.equal(normalizeBridgeServer('http://192.168.1.9',{allowInsecureLAN:true}),'http://192.168.1.9');});

test('server and device reconnect recover an already written original result without executing again',async()=>{const f=await fixture();let recovered;try{let block=true;const p=await f.pair(0,{fetchImpl:async(url,args)=>{if(url.endsWith('/complete')&&block)throw Error('completion did not reach server');return fetch(url,args);}}),input={theme:'pixel',requestId:randomUUID(),message:'重启前已经写好'};await f.service.agents.submit(f.users[0].token,input);await assert.rejects(p.client.tick(),/did not reach/);assert.equal(f.deviceCalls.filter(c=>c.method==='command').length,1);await p.client.close();await f.restart();block=false;recovered=await createDeviceBridgeClient({server:'http://127.0.0.1:'+f.service.port,workspace:p.workspace,directory:p.directory,runtimeFactory:p.runtimeFactory,fetchImpl:p.fetchImpl,heartbeatMs:60000});assert.equal((await recovered.tick()).phase,'completed');const done=await completed(f,0,input.requestId);assert.equal(done.recoveredFromOriginalDevice,true);assert.match(done.result.answer,/重启前已经写好/);assert.equal(f.deviceCalls.filter(c=>c.method==='command').length,1);await f.service.agents.submit(f.users[0].token,input);assert.equal((await recovered.tick()).phase,'idle');}finally{await recovered?.close();await f.close();}});
test('a foreign device credential cannot claim or complete another owners job',async()=>{const f=await fixture();try{const a=await f.pair(0),b=await f.pair(1),input={theme:'pixel',requestId:randomUUID(),message:'不能让另一原机接管'};await f.service.agents.submit(f.users[0].token,input);const ca=JSON.parse(await readFile(resolve(a.directory,'client.json'),'utf8')),cb=JSON.parse(await readFile(resolve(b.directory,'client.json'),'utf8'));const next=await f.service.bridge.next(ca.secret);assert(next.job);await assert.rejects(f.service.bridge.claim(cb.secret,{jobId:next.job.id,fingerprint:next.job.fingerprint}),e=>e.code==='bridge_owner');await assert.rejects(f.service.bridge.complete(cb.secret,{jobId:next.job.id,fingerprint:next.job.fingerprint,result:{source:'hermes'}}),e=>e.code==='bridge_owner');await a.client.tick();await completed(f,0,input.requestId);assert.equal(f.deviceCalls.filter(c=>c.method==='command').length,1);}finally{await f.close();}});

test('a new pairing code cannot silently reuse an already bound client record',async()=>{const f=await fixture();try{const p=await f.pair(0);await p.client.close();const next=await f.api(0,'/api/lan/bridge/pair',{});await assert.rejects(createDeviceBridgeClient({server:'http://127.0.0.1:'+f.service.port,workspace:p.workspace,directory:p.directory,pairCode:next.data.code,runtimeFactory:p.runtimeFactory}),e=>e.code==='bridge_client_config');}finally{await f.close();}});
