import assert from 'node:assert/strict';import {writeFile,mkdir} from 'node:fs/promises';import {resolve} from 'node:path';import {standardFixture,sendParams} from './fixtures/a2a-standard.mjs';
const sdkUrl=process.env.HD_TEST_A2A_SDK;if(!sdkUrl)throw Error('Set HD_TEST_A2A_SDK to the installed official @a2a-js/sdk 1.3.0 client module URL');
const {ClientFactory}=await import(sdkUrl),{Message,TaskState,ListTasksRequest}=await import(new URL('../index.js',sdkUrl).href),out=resolve(process.env.HD_QA_OUT||'qa/v158/official-sdk');await mkdir(out,{recursive:true});
const report={client:'@a2a-js/sdk 1.3.0',scope:'Actual official client against HTTP service; fictional accounts and mock runtime. No physical-device or real-model claim.',checks:[]};let f;
try{
 f=await standardFixture();await f.enable();const factory=new ClientFactory(),host=await factory.createFromUrl(f.base),guest=await factory.createFromUrl(f.base),outsider=await factory.createFromUrl(f.base),options=n=>({serviceParameters:{Authorization:'Bearer '+f.users[n].token},signal:AbortSignal.timeout(20000)});
 const card=await host.getAgentCard(options(0));assert.equal(card.capabilities.extensions[0].params.peers.length,1);
 const p=sendParams(f);delete p.message.metadata;p.message=Message.fromJSON(p.message);const sent=await host.sendMessage(p,options(0)),task=sent;assert.equal(task.status.state,TaskState.TASK_STATE_INPUT_REQUIRED);assert.equal(task.history[0].messageId,p.message.messageId);report.checks.push('Discovery and plain-text send selected the sole same-room steward');
 const follow=sendParams(f,{taskId:task.id,text:'请介绍来访岛居民与设施。'});delete follow.message.metadata;follow.message=Message.fromJSON(follow.message);const replied=await guest.sendMessage(follow,options(1));assert.equal(replied.history.length,4);assert.equal(f.calls.length,2);assert.deepEqual((await guest.sendMessage(follow,options(1))),replied);assert.equal(f.calls.length,2);report.checks.push('Both owners replied; replay did not invoke the runtime again');
 const read=await host.getTask({id:task.id,historyLength:1},options(0));assert.equal(read.history.length,1);const listed=await host.listTasks(ListTasksRequest.fromJSON({contextId:f.room.id,historyLength:0}),options(0));assert.equal(listed.totalSize,1);assert.equal(listed.tasks[0].history.length,0);assert.equal((await outsider.listTasks(ListTasksRequest.fromJSON({}),options(2))).tasks.length,0);await assert.rejects(outsider.getTask({id:task.id},options(2)));report.checks.push('Get/List, bounded history and third-owner isolation');
 assert.equal((await host.cancelTask({id:task.id},options(0))).status.state,TaskState.TASK_STATE_CANCELED);await f.restart();const restored=await (await factory.createFromUrl(f.base)).getTask({id:task.id},options(0));assert.equal(restored.status.state,TaskState.TASK_STATE_CANCELED);assert.equal(restored.history.length,4);report.checks.push('Cancel and persisted history survived restart');report.passed=true;
}catch(e){report.passed=false;report.failure=e.message;process.exitCode=1;console.error(e.stack);}finally{await f?.close();await writeFile(resolve(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));}
