import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {standardFixture,sendParams,successful} from './fixtures/a2a-standard.mjs';import {A2A_EXTENSION} from '../server/a2aGateway.mjs';
const ext=task=>task.metadata[A2A_EXTENSION];
test('standard discovery, owner authentication, version negotiation and text-only boundary',async()=>{const f=await standardFixture();try{
 const response=await fetch(f.base+'/.well-known/agent-card.json'),card=await response.json();assert.equal(response.status,200);assert.deepEqual(card.supportedInterfaces,[{url:f.base+'/api/lan/a2a',protocolBinding:'JSONRPC',protocolVersion:'1.0'}]);assert.equal(card.capabilities.streaming,false);assert.equal(card.capabilities.extendedAgentCard,true);assert.equal(card.securitySchemes.ownerCookie.apiKeySecurityScheme.name,'hd_lan_session');assert(!JSON.stringify(card).includes(f.users[0].id));
 const cookieRequest=await fetch(f.base+'/api/lan/a2a',{method:'POST',headers:{'Content-Type':'application/json','A2A-Version':'1.0',Cookie:'hd_lan_session='+f.users[0].token},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'ListTasks',params:{}})});assert.equal(cookieRequest.status,200);assert.equal((await cookieRequest.json()).result.totalSize,0);
 const missing=await fetch(f.base+'/api/lan/a2a',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});assert.equal(missing.status,401);assert.match(missing.headers.get('www-authenticate'),/Bearer/);
 const {data:old}=await f.rpc(0,'ListTasks',{}, {'A2A-Version':'0.3'});assert.equal(old.error.code,-32009);
 const {data:absent}=await f.rpc(0,'ListTasks',{}, {'A2A-Version':''});assert.equal(absent.error.code,-32009);
 const {data:extended}=await f.rpc(0,'GetExtendedAgentCard');const params=extended.result.capabilities.extensions[0].params;assert.equal(params.ownerId,f.users[0].id);assert.equal(params.peers.length,1);assert.equal(params.peers[0].recipientId,f.users[1].id);assert(!JSON.stringify(extended).includes('PRIVATE_'));
 const cookie=await f.rpc(0,'ListTasks',{}, {Authorization:'',Cookie:'hd_lan_session='+f.users[0].token});assert.equal(cookie.response.status,401,'Malformed explicit bearer cannot fall back to a cookie');
 const csrf=await f.rpc(0,'ListTasks',{}, {Origin:'https://unrelated.invalid'});assert.equal(csrf.response.status,403);
 const p=sendParams(f);p.message.parts=[{url:'file:///private/document.txt'}];assert.equal((await f.rpc(0,'SendMessage',p)).data.error.code,-32005);assert.equal(f.calls.length,0);
 assert.equal((await f.rpc(0,'SendStreamingMessage')).data.error.code,-32004);assert.equal((await f.rpc(0,'CreateTaskPushNotificationConfig')).data.error.code,-32003);
 }finally{await f.close();}});
test('official wire messages preserve input IDs, both owner turns, private isolation and replay after restart',async()=>{const f=await standardFixture();try{
 await f.enable();const p=sendParams(f),first=(await successful(f,0,'SendMessage',p)).task;assert.equal(first.status.state,'TASK_STATE_INPUT_REQUIRED');assert.equal(first.contextId,f.room.id);assert.equal(first.history[0].messageId,p.message.messageId);assert.equal(first.history[0].role,'ROLE_USER');assert.equal(first.history[1].role,'ROLE_AGENT');assert(!JSON.stringify(first).includes('homeWorldKey'));assert(!JSON.stringify(first).includes('PRIVATE_'));assert.equal(f.calls.length,1);
 const r=sendParams(f,{taskId:first.id,text:'请介绍来访岛自己的设施。'}),reply=(await successful(f,1,'SendMessage',r)).task;assert.equal(reply.history.length,4);assert.equal(reply.history[2].messageId,r.message.messageId);assert.equal(ext(reply).nextAction,null);assert.equal(f.calls.length,2);assert.equal(f.calls[1].ownerId,f.users[1].id);
 const again=(await successful(f,1,'SendMessage',r)).task;assert.deepEqual(again,reply);assert.equal(f.calls.length,2);assert.equal((await f.rpc(1,'SendMessage',{...r,message:{...r.message,parts:[{text:'changed'}]}})).data.error.code,-32602);
 assert.equal((await f.rpc(2,'GetTask',{id:first.id})).data.error.code,-32001);assert.equal((await successful(f,2,'ListTasks')).tasks.length,0);
 assert.equal((await f.rpc(0,'GetTask',{id:first.id,historyLength:-1})).data.error.code,-32602);assert(!('history' in await successful(f,0,'GetTask',{id:first.id,historyLength:0})));assert.equal((await successful(f,0,'GetTask',{id:first.id,historyLength:1})).history.length,1);
 const wrong=sendParams(f,{taskId:first.id,contextId:randomUUID()});assert.equal((await f.rpc(0,'SendMessage',wrong)).data.error.code,-32602);
 await f.restart();assert.deepEqual((await successful(f,1,'SendMessage',r)).task,reply);assert.equal(f.calls.length,2);
 }finally{await f.close();}});
test('blocking waits for the runtime reply; nonblocking reports working; cancel rejects late replies',async()=>{let release,entered;const hold=new Promise(r=>release=r),ready=new Promise(r=>entered=r);const f=await standardFixture({gate:async()=>{entered();await hold;}});try{
 await f.enable();let completed=false;const pending=successful(f,0,'SendMessage',sendParams(f)).then(r=>{completed=true;return r;});await ready;await new Promise(r=>setTimeout(r,30));assert.equal(completed,false);const listed=await successful(f,0,'ListTasks');assert.equal(listed.tasks[0].status.state,'TASK_STATE_WORKING');const cancelled=await successful(f,0,'CancelTask',{id:listed.tasks[0].id});assert.equal(cancelled.status.state,'TASK_STATE_CANCELED');release();const response=await pending;assert.equal(response.task.status.state,'TASK_STATE_CANCELED');await f.service.collaboration.close();assert.equal((await successful(f,0,'GetTask',{id:cancelled.id})).history.length,1);assert.equal((await successful(f,0,'CancelTask',{id:cancelled.id})).status.state,'TASK_STATE_CANCELED');
 }finally{release();await f.close();}
 let release2,entered2;const hold2=new Promise(r=>release2=r),ready2=new Promise(r=>entered2=r),next=await standardFixture({gate:()=>{entered2();return hold2;}});try{await next.enable();const p=sendParams(next,{configuration:{returnImmediately:true}}),r=(await successful(next,0,'SendMessage',p)).task;assert.equal(r.status.state,'TASK_STATE_WORKING');assert.equal((await successful(next,0,'SendMessage',p)).task.id,r.id);await ready2;assert.equal(next.calls.length,1);await successful(next,0,'CancelTask',{id:r.id});}finally{release2();await next.close();}});
test('canonical same-room consent remains mandatory and expiration is a terminal task',async()=>{const f=await standardFixture();try{
 assert.equal((await f.rpc(0,'SendMessage',sendParams(f))).data.error.code,-32602);await f.enable();assert.equal((await f.rpc(0,'SendMessage',sendParams(f,{recipient:2}))).data.error.code,-32602);
 const t=(await successful(f,0,'SendMessage',sendParams(f))).task;f.advance(1800001);const expired=await successful(f,0,'GetTask',{id:t.id});assert.equal(expired.status.state,'TASK_STATE_FAILED');assert.equal((await f.rpc(0,'CancelTask',{id:t.id})).data.error.code,-32002);
 }finally{await f.close();}});
test('stable cursor pagination is owner/query scoped and history obeys the requested bound',async()=>{const f=await standardFixture();try{
 await f.enable();const ids=[];for(let i=0;i<3;i++){const t=(await successful(f,0,'SendMessage',sendParams(f,{text:'话题 '+i}))).task;ids.push(t.id);await successful(f,0,'CancelTask',{id:t.id});}
 const first=await successful(f,0,'ListTasks',{pageSize:1,status:'TASK_STATE_CANCELED',historyLength:0});assert.equal(first.totalSize,3);assert(first.nextPageToken);assert.equal(first.tasks.length,1);assert(!first.tasks[0].history);const second=await successful(f,0,'ListTasks',{pageSize:1,status:'TASK_STATE_CANCELED',pageToken:first.nextPageToken});assert.notEqual(second.tasks[0].id,first.tasks[0].id);
 assert.equal((await f.rpc(1,'ListTasks',{pageSize:1,status:'TASK_STATE_CANCELED',pageToken:first.nextPageToken})).data.error.code,-32602);assert.equal((await f.rpc(0,'ListTasks',{pageSize:101})).data.error.code,-32602);assert.equal((await successful(f,0,'ListTasks',{statusTimestampAfter:'2020-01-01T00:00:00Z'})).totalSize,3);
 }finally{await f.close();}});
test('event preparation requires the invited owner explicit execution and retains one protected reservation',async()=>{const f=await standardFixture({event:true});try{
 await f.enable('preference');const host=f.users[0],guest=f.users[1],before=(await f.service.tenants.readIslandForServer(guest.id,guest.theme)).state;
 const offer=(await successful(f,0,'SendMessage',sendParams(f,{capability:'event.checkin'}))).task;assert.equal(ext(offer).status,'offered');const review=(await successful(f,1,'SendMessage',sendParams(f,{taskId:offer.id}))).task;assert.equal(ext(review).nextAction,'execute');
 assert.equal((await f.rpc(1,'SendMessage',sendParams(f,{taskId:offer.id,text:'I agree'}))).data.error.code,-32602,'Text alone cannot reserve resources');assert.equal((await f.rpc(0,'SendMessage',sendParams(f,{taskId:offer.id,action:'execute'}))).data.error.code,-32602);
 const execute=sendParams(f,{taskId:offer.id,action:'execute',text:'确认约定的入场物资预留。'}),receipt=(await successful(f,1,'SendMessage',execute)).task;assert.equal(ext(receipt).status,'executed');assert.equal(ext(receipt).receipt.verified,true);const after=(await f.service.tenants.readIslandForServer(guest.id,guest.theme)).state;assert.deepEqual((await successful(f,1,'SendMessage',execute)).task,receipt);assert.deepEqual((await f.service.tenants.readIslandForServer(guest.id,guest.theme)).state.inventory,after.inventory);assert.equal(after.inventory.wood,before.inventory.wood-2);assert.equal(after.lanEconomyControl.holds['event:'+f.eventId+':entry:'+guest.id].cost.wood,2);
 const confirmed=(await successful(f,0,'SendMessage',sendParams(f,{taskId:offer.id}))).task;assert.equal(confirmed.status.state,'TASK_STATE_COMPLETED');assert.equal(f.calls.length,3);assert.deepEqual(f.calls.map(c=>c.ownerId),[host.id,guest.id,host.id]);assert.equal((await f.rpc(0,'CancelTask',{id:offer.id})).data.error.code,-32002);
 }finally{await f.close();}});
import {createDeviceBridgeClient} from '../server/deviceBridgeClient.mjs';import {mkdir} from 'node:fs/promises';import {resolve} from 'node:path';
test('standard transport routes a bound visiting steward to its device and rejects device credentials as owner credentials',async()=>{const f=await standardFixture();let client;const deviceCalls=[];try{
 await f.enable();const pairing=await f.service.bridge.pair(f.users[1].token,{}),workspace=resolve(f.directory,'device-documents');await mkdir(workspace,{recursive:true});
 client=await createDeviceBridgeClient({server:f.base,workspace,directory:resolve(f.directory,'device-state'),pairCode:pairing.code,name:'测试原机',heartbeatMs:60000,runtimeFactory:({ownerId})=>({documents:workspace,async call(method,args){if(method==='status')return {hermes:{configured:true,model:'deepseek-flash'},deepseek:{configured:true,model:'deepseek-flash'}};deviceCalls.push({ownerId,method});assert.equal(method,'a2a');return {source:'hermes',ledgerRunId:'device-'+randomUUID(),runId:'provider-'+randomUUID(),reply:{decision:'share',message:args.sharedContext.islandName+'的原机管家在标准接口中回信。'}};},async close(){}})});
 await f.service.bridge.approve(f.users[1].token,{deviceId:client.info.deviceId,verification:client.info.verification});
 const started=(await successful(f,1,'SendMessage',sendParams(f,{recipient:0,configuration:{returnImmediately:true}}))).task;let task;
 for(let n=0;n<100;n++){await client.tick();task=await successful(f,1,'GetTask',{id:started.id});if(task.status.state==='TASK_STATE_INPUT_REQUIRED')break;await new Promise(r=>setTimeout(r,15));}
 assert.equal(task.status.state,'TASK_STATE_INPUT_REQUIRED');assert.equal(deviceCalls.length,1);assert.equal(deviceCalls[0].ownerId,f.users[1].id);assert.equal(f.calls.length,0,'The bound owner cannot fall back to the server runtime');
 const {readFile}=await import('node:fs/promises'),credential=JSON.parse(await readFile(resolve(f.directory,'device-state/client.json'),'utf8'));assert.equal((await f.rpc(1,'ListTasks',{}, {Authorization:'Bearer '+credential.secret})).response.status,401);
 }finally{await client?.close();await f.close();}});
