import test from 'node:test';import assert from 'node:assert/strict';
import {mkdir,mkdtemp} from 'node:fs/promises';import {resolve} from 'node:path';import {randomUUID} from 'node:crypto';
import {createSaveStore} from '../server/saveStore.mjs';import {createZeroState} from '../src/freshStart.js';import {hydrateTown} from '../src/townSimulation.js';
import {CROPS,soilCharges,harvestAmount} from '../src/farming.js';import {availableQuantity,reserveResources} from '../src/resourceLedger.js';import {itemUse} from '../src/contentCatalog.js';import {itemPurpose} from '../src/itemPurpose.js';import {validFarmTicket} from '../server/farmActions.mjs';
await mkdir('qa/v159',{recursive:true});
async function fixture(edit=()=>{}){const directory=await mkdtemp(resolve('qa/v159/soil-'));let clock=1000000;const store=createSaveStore({directory,now:()=>clock}),s=hydrateTown(createZeroState());s.freshStartPending=false;s.inventory.seed=3;s.inventory.c14_8=1;s.plots[0]={stage:2,growth:0,crop:'wheat',playerTended:true};edit(s);const {document}=await store.open('pixel',{legacyState:s});return {store,directory,document,advance:n=>clock+=n,other:()=>createSaveStore({directory,now:()=>clock})};}
const begin=(d,step='fertilize',extra={})=>({kind:'farm',operation:'begin',requestId:randomUUID(),index:0,step,expectedVersion:d.version,expectedSequence:d.actions?.sequence||0,epoch:d.actions?.epoch||null,...extra});
const finish=(r,operation='finish')=>({kind:'farm',operation,requestId:r.ticket.requestId,epoch:r.ticket.epoch,sequence:r.ticket.sequence,expectedVersion:r.document.version});
async function work(f,d,step,extra={}){const r=await f.store.action('pixel',begin(d,step,extra));f.advance(Math.ceil(r.ticket.duration*1000));return f.store.action('pixel',finish(r));}
async function grow(f,d,seconds){for(let left=seconds;left>0;){const delta=Math.min(15,left);f.advance(delta*1000);d=(await f.store.save('pixel',{state:d.state,expectedVersion:d.version,saveId:randomUUID(),activeSeconds:delta})).document;left-=delta;}return d;}
test('fertilizer is reserved, animated for 2.5 seconds and charged exactly once through disk restart',async()=>{const f=await fixture(),r=await f.store.action('pixel',{...begin(f.document),duration:0,fertility:999,gain:{wheat:999}});assert.equal(r.ticket.duration,2.5);assert(validFarmTicket(r.ticket));assert.equal(availableQuantity(r.document.state,'c14_8'),0);assert.equal(soilCharges(r.document.state.plots[0]),0);await assert.rejects(f.store.action('pixel',finish(r)),e=>e.code==='action_early');f.advance(2500);const done=await f.other().action('pixel',finish(r));assert.deepEqual(done.receipt.cost,{c14_8:1});assert.deepEqual(done.receipt.gain,{});assert.equal(done.document.state.inventory.c14_8,0);assert.equal(done.document.state.plots[0].stage,2);assert.equal(done.document.state.plots[0].growth,0);assert.equal(soilCharges(done.document.state.plots[0]),3);const again=await f.other().action('pixel',finish(r));assert(again.replayed);assert.equal(again.document.state.inventory.c14_8,0);assert.equal(again.document.actions.receipts.length,1);});
test('reserved fertilizer is unavailable to farming; cancel returns the bag without granting nutrition',async()=>{const f=await fixture(s=>reserveResources(s,'another-task',{c14_8:1},{purpose:'另一份委托'}));await assert.rejects(f.store.action('pixel',begin(f.document)),e=>e.code==='farm_materials');assert.equal((await f.store.current('pixel')).state.inventory.c14_8,1);const f2=await fixture(),r=await f2.store.action('pixel',begin(f2.document)),cancel=await f2.store.action('pixel',finish(r,'cancel'));assert.equal(cancel.document.state.inventory.c14_8,1);assert.equal(soilCharges(cancel.document.state.plots[0]),0);assert.equal(availableQuantity(cancel.document.state,'c14_8'),1);const late=await f2.other().action('pixel',finish(r));assert.equal(late.receipt.outcome,'cancelled');assert.equal(soilCharges(late.document.state.plots[0]),0);});
test('three harvests each gain one, consume one charge and keep full growth time; fourth returns to base yield',async()=>{const f=await fixture();let d=(await work(f,f.document,'fertilize')).document;let expected=0;for(let cycle=0;cycle<4;cycle++){if(cycle){d=(await work(f,d,'hoe')).document;d=(await work(f,d,'sow',{crop:'wheat'})).document;}d=(await work(f,d,'water')).document;d=await grow(f,d,179);assert.equal(d.state.plots[0].stage,3);d=await grow(f,d,1);assert.equal(d.state.plots[0].stage,4);assert.equal(d.state.plots[0].growth,180);const r=await work(f,d,'harvest');d=r.document;const amount=cycle<3?3:2;expected+=amount;assert.equal(r.receipt.gain.wheat,amount);assert.equal(d.state.inventory.wheat,expected);assert.equal(d.state.economy.playerGoods.wheat,expected);assert.equal(soilCharges(d.state.plots[0]),Math.max(0,2-cycle));}assert.equal(d.state.inventory.c14_8,0);assert.equal(expected,11);});
test('each of the eleven crops has bounded extra yield, and NPC harvest consumes nutrition without player credit',async()=>{for(const [crop,c]of Object.entries(CROPS)){const f=await fixture(s=>{s.plots[1]={stage:4,growth:c.seconds,crop,fertility:3};});const r=await work(f,f.document,'harvest',{actor:'npc',actorId:1,index:1});assert.equal(r.document.state.inventory[c.item],c.yield+1,crop);assert.equal(soilCharges(r.document.state.plots[1]),2);assert.equal(r.receipt.gain[c.item],c.yield+1);assert.equal(r.document.state.economy.playerGoods[c.item]||0,0);}});
test('empty, mature, already-fed and automated actors cannot apply fertilizer; untrusted autosave cannot add nutrition',async()=>{for(const stage of [0,1,4]){const f=await fixture(s=>s.plots[0].stage=stage);await assert.rejects(f.store.action('pixel',begin(f.document)),e=>e.code==='farm_soil');}const f=await fixture(s=>s.plots[0].fertility=2);await assert.rejects(f.store.action('pixel',begin(f.document)),e=>e.code==='farm_soil');const f2=await fixture(s=>delete s.plots[0].playerTended);await assert.rejects(f2.store.action('pixel',begin(f2.document,'fertilize',{actor:'npc',actorId:1})),e=>e.code==='farm_soil');const r=await f2.store.action('pixel',{kind:'farm',operation:'enable',requestId:randomUUID(),expectedVersion:f2.document.version});const changed=structuredClone(r.document.state);changed.plots[0].fertility=3;await assert.rejects(f2.store.save('pixel',{state:changed,expectedVersion:r.document.version}),e=>e.code==='farm_state_conflict');});
test('growing plants retain their elapsed growth when fertilized; soil bonus cannot exceed the catalog limit',async()=>{const f=await fixture(s=>s.plots[0]={stage:3,growth:60,crop:'tomato',playerTended:true});const done=await work(f,f.document,'fertilize');assert.equal(done.document.state.plots[0].growth,60);assert.equal(CROPS.tomato.seconds,300);assert.equal(harvestAmount(done.document.state.plots[0]),4);assert.equal(soilCharges({fertility:999}),0);});
test('item use opens real farm care without consuming a bag or producing a decoration',async()=>{const f=await fixture(),s=f.document.state,before=structuredClone(s.inventory);const r=itemUse('c14_8',s);assert.equal(r.route,'farmCare');assert.deepEqual(s.inventory,before);assert.equal(s.placedItems.length,0);assert.equal(itemPurpose('c14_8',s).primary.action,'前往农田施肥');});

// Default shelves protect a first useful item, while explicit player settings remain authoritative.
import {ALL_RECIPES} from '../src/contentCatalog.js';
import {shopItemOffer,configureShopfront} from '../src/shopfronts.js';
import {visitQuote} from '../src/townSimulation.js';
test('automatic shelves preserve each nonfood first copy, still sell surplus and foods',()=>{const s=hydrateTown(createZeroState());for(const r of ALL_RECIPES){s.inventory[r.item]=1;assert.equal(shopItemOffer(s,r.item).available,r.category==='food'?1:0,r.item);s.inventory[r.item]=2;assert.equal(shopItemOffer(s,r.item).available,r.category==='food'?2:1,r.item);}});
test('explicit zero shelf floor can sell the first nonfood item and survives disk reload',async()=>{const f=await fixture(),d=f.document;{const s=structuredClone(d.state);s.inventory.c14_8=1;assert.notEqual(visitQuote(s,{name:'visitor',budget:100},14).item,'c14_8');const r=configureShopfront(s,{buildingId:14,listing:[{item:'c14_8',keep:0}],expectedShopRevision:0});assert(r.ok);assert.equal(shopItemOffer(s,'c14_8').available,1);assert.equal(visitQuote(s,{name:'visitor',budget:100},14).item,'c14_8');}const enabled=await f.store.action('pixel',{kind:'commerce',operation:'enable',requestId:randomUUID(),day:d.state.day,expectedVersion:d.version});const r=await f.store.action('pixel',{kind:'commerce',operation:'shopfront',requestId:randomUUID(),day:d.state.day,buildingId:14,listing:[{item:'c14_8',keep:0}],expectedShopRevision:0,expectedVersion:enabled.document.version});assert.equal(shopItemOffer(r.document.state,'c14_8').available,1);assert.equal(shopItemOffer((await f.other().current('pixel')).state,'c14_8').available,1);});
