import {chromium} from 'playwright-core';
import {completeCoutureClients} from './couture-ui-helper.mjs';
import {spawn} from 'node:child_process';
import {mkdir,mkdtemp,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import assert from 'node:assert/strict';
import {createState} from '../src/world.js';
import {hydrateTown} from '../src/townSimulation.js';
import {createProject,assignProjectStep} from '../src/projectPlans.js';
await mkdir('qa/v27',{recursive:true});
const directory=await mkdtemp(resolve('qa/v27/browser-storage-')),port=4197,base='http://127.0.0.1:'+port;
const server=spawn(process.execPath,['server.mjs','--port='+port,'--theme=origami'],{cwd:resolve('.'),env:{...process.env,HD_SAVE_DIR:directory},windowsHide:true,stdio:['ignore','pipe','pipe']});
let logs='',browser;server.stdout.on('data',b=>logs+=b);server.stderr.on('data',b=>logs+=b);
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const until=async fn=>{for(let i=0;i<150;i++){if(await fn())return;await wait(100)}throw Error('condition timed out')};
const report={directory,checks:[],errors:[]};
const api=async(theme,op='',body)=>{const r=await fetch(base+'/api/saves/'+theme+(op?'/'+op:''),{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const value=await r.json();assert(r.ok,JSON.stringify(value));return value};
try{
 await until(async()=>{try{return (await fetch(base+'/api/status')).ok}catch{return false}});
 browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
 for(const theme of ['pixel','origami']){
  const s=hydrateTown(createState());s.inventory.cotton=2;s.inventory.flax=1;s.inventory.fiber=1;s.inventory.outfit=0;
  const {project:p}=createProject(s,{id:'player-couture',title:'为夜集做一套衣服',targets:{outfit:1}});
  assignProjectStep(s,p.id+':outfit',-1);
  await api(theme,'open',{legacyState:s,clientId:'v27-fixture'});
  const context=await browser.newContext({viewport:{width:1440,height:950}});
  await context.route('**/api/**',route=>route.request().url().includes('/api/saves/')?route.continue():route.fulfill({status:503,contentType:'application/json',body:'{"error":"isolated QA"}'}));
  const page=await context.newPage();page.on('pageerror',e=>report.errors.push({theme,message:e.message,stack:e.stack}));
  await page.goto(base+'/?qa=1&theme='+theme);
  const inspect=()=>page.evaluate(()=>window.islandInspect());
  const openPlans=async()=>{await page.locator('#stewardBtn').click();await page.locator('#stewardProjects').click()};
  await openPlans();assert.match(await page.locator('.project-card').textContent(),/我来接管/);
  await page.waitForFunction(()=>window.islandInspect().contentArts.loaded.every(x=>x.ready));
  await page.screenshot({path:'qa/v27/'+theme+'-plan.png'});
  await page.locator('[data-plan-do="player-couture:outfit"]').click();
  await page.locator('.workshop-game').waitFor({timeout:30000});
  assert((await inspect()).resourceLedger.reservations['project:player-couture']);
  await page.locator('#closeModal').click();
  assert((await inspect()).resourceLedger.reservations['project:player-couture'],'closing a project workbench retains plan materials');
  assert.equal((await inspect()).agentTaskLedger.find(t=>t.id==='player-couture:outfit').status,'queued');
  await openPlans();await page.locator('[data-plan-do="player-couture:outfit"]').click();await page.locator('.workshop-game').waitFor({timeout:30000});
  await page.locator('[data-action="start"]').click();await completeCoutureClients(page);
  await page.locator('[data-action="claim"]').waitFor();await page.locator('[data-action="claim"]').click();
  await until(async()=>(await inspect()).workProjects[0].status==='ready');
  assert.equal((await inspect()).inventory.outfit,1);
  await page.locator('#closeModal').click();await openPlans();
  assert.match(await page.locator('.project-card').textContent(),/物资齐备/);
  await page.locator('[data-plan-action="finish"]').click();
  assert.equal((await inspect()).resourceLedger.reservations['project:player-couture'],undefined);
  report.checks.push({theme,flow:'player takeover uses reserved ingredients; closing keeps reservation; real couture play and action makes exactly one outfit; finish releases stock'});
  if(!await page.locator('#planTitle').isVisible())await page.locator('.plan-builder summary').click();
  await page.locator('#planTitle').fill('实际筹备与改派');await page.locator('#planCreate').click();
  const current=(await inspect()).workProjects.at(-1);
  const step=(await inspect()).agentTaskLedger.find(t=>t.projectId===current.id&&t.remaining>0);
  assert(step);await page.locator('[data-plan-assignee="'+step.id+'"]').selectOption('-1');
  assert.equal((await inspect()).agentTaskLedger.find(t=>t.id===step.id).npcId,-1);
  await page.locator('[data-plan="'+current.id+'"][data-plan-action="pause"]').click();
  await page.locator('#closeModal').click();await page.locator('#saveStatus').click();await page.locator('#saveNow').click();
  await until(async()=>(await api(theme)).document.state.workProjects?.at(-1)?.status==='paused');
  await page.reload();await openPlans();assert.equal((await inspect()).workProjects.at(-1).status,'paused');
  await page.locator('[data-plan="'+current.id+'"][data-plan-action="resume"]').click();
  await page.setViewportSize({width:390,height:780});
  await page.locator('.modal-body').evaluate(el=>el.scrollTop=el.scrollHeight);
  assert.equal(await page.locator('.modal-body').evaluate(el=>el.scrollWidth>el.clientWidth+1),false);
  assert(await page.locator('#closeModal').isVisible());
  await page.screenshot({path:'qa/v27/'+theme+'-plan-compact.png'});
  await page.locator('[data-plan="'+current.id+'"][data-plan-action="cancel"]').click();
  assert.equal((await inspect()).resourceLedger.reservations['project:'+current.id],undefined);
  report.checks.push({theme,flow:'create, reassign, pause, real server save/reload, resume, mobile layout, cancel'});
  await context.close();
 }
 assert.deepEqual(report.errors,[]);report.passed=true;
}catch(e){report.failure=e.stack;throw e}finally{
 await browser?.close();server.kill();await writeFile('qa/v27/browser-report.json',JSON.stringify(report,null,2));
 if(!report.passed)await writeFile('qa/v27/browser-failure.log',logs+'\n'+JSON.stringify(report.errors,null,2));
}
console.log(JSON.stringify(report));
