import {hydratePlacements,decorate} from '../src/placements.js';import {hydrateFunctionalFacilities,functionalCommand,tickFunctionalFacilities,functionalUnit} from '../src/functionalFacilities.js';
import test from 'node:test';import assert from 'node:assert/strict';import {mkdir,mkdtemp} from 'node:fs/promises';import {resolve} from 'node:path';import {randomUUID} from 'node:crypto';
import {createSaveStore} from '../server/saveStore.mjs';import {createZeroState} from '../src/freshStart.js';import {hydrateTown} from '../src/townSimulation.js';import {ALL_RECIPES,RAW_MATERIALS} from '../src/contentCatalog.js';import {newActionBook} from '../server/playerActions.mjs';import {applyResidentCommand} from '../server/residentActions.mjs';import {availableQuantity,reserveResources,nextOperationId,commitResources} from '../src/resourceLedger.js';import {queueTask,beginTaskStep,controlTask,restoreTasks,taskOwner} from '../src/taskBoard.js';import {BUILDINGS} from '../src/world.js';import {recordResidentConversation,claimResidentStory} from '../src/residentStories.js';
await mkdir('qa/v50',{recursive:true});
const fresh=()=>{const s=hydrateTown(createZeroState());s.freshStartPending=false;return s};
async function fixture(edit=()=>{}){let clock=1000000;const directory=await mkdtemp(resolve('qa/v50/resident-')),store=createSaveStore({directory,now:()=>clock}),s=fresh();edit(s);return {store,directory,document:(await store.open('pixel',{legacyState:s})).document,advance:n=>clock+=n,other:()=>createSaveStore({directory,now:()=>clock})};}
const begin=(d,intent={goal:'forest',buildingId:null,action:'work',resource:'wood'},actorId=5)=>({kind:'resident',operation:'begin',actorId,intent,gameTime:100,requestId:randomUUID(),expectedVersion:d.version,expectedSequence:d.actions?.sequence||0,epoch:d.actions?.epoch||null});
const identity=(r,operation)=>({kind:'resident',operation,requestId:r.ticket.requestId,epoch:r.ticket.epoch,sequence:r.ticket.sequence,expectedVersion:r.document.version});
const finish=async(f,r)=>{f.advance(r.ticket.duration*1000);return f.store.action('pixel',identity(r,'finish'))};
const stock=(s,r)=>{for(const [id,n]of Object.entries(r.cost))s.inventory[id]=n;s.facilities[r.building].quality=90;s.research??={};s.research[r.building]=99};
test('NPC forest gather has a twenty-second floor and a unique actual production receipt, no player credit',async()=>{const f=await fixture(),r=await f.store.action('pixel',begin(f.document));assert.equal(r.ticket.duration,20);await assert.rejects(f.store.action('pixel',identity(r,'finish')),e=>e.code==='action_early');const done=await finish(f,r);assert.deepEqual(done.receipt.gain,{wood:2});assert.equal(done.document.state.economy.playerGoods.wood||0,0);assert.equal(done.document.state.npcCareers[5].history.at(-1).time,120);assert((await f.other().action('pixel',identity(r,'finish'))).replayed);assert.equal((await f.store.current('pixel')).state.inventory.wood,2)});
test('all 300 NPC recipes derive catalog cost, one actual output and craft history without client supplied gains',()=>{for(const r of ALL_RECIPES){const s=fresh(),b=newActionBook();stock(s,r);const intent={goal:BUILDINGS[r.building].kind,buildingId:r.building,action:'work',recipeId:r.id},start=applyResidentCommand(s,b,{...begin({actions:b}),actorId:1,intent},1000000);assert.equal(start.ticket.mode,'craft',r.id);assert.deepEqual(start.ticket.cost,r.cost);const done=applyResidentCommand(s,b,{kind:'resident',operation:'finish',requestId:start.ticket.requestId,epoch:b.epoch,sequence:b.sequence,gain:{coins:999},quality:100},1020000);assert.deepEqual(done.receipt.gain,{[r.item]:1},r.id);assert.deepEqual(done.receipt.cost,r.cost,r.id);assert.equal(s.craftHistory[r.id],1);for(const id of Object.keys(r.cost))assert.equal(s.inventory[id],0,r.id+':'+id);assert.equal(s.coins,0)}});
test('recipe materials are reserved at entry and another consumer cannot spend them',async()=>{const recipe=ALL_RECIPES.find(r=>r.item==='lantern'),f=await fixture(s=>stock(s,recipe)),r=await f.store.action('pixel',begin(f.document,{goal:'workshop',buildingId:0,action:'work',recipeId:recipe.id},1));for(const id of Object.keys(recipe.cost))assert.equal(availableQuantity(r.document.state,id),0);assert.equal(commitResources(r.document.state,{cost:recipe.cost}).ok,false);const done=await finish(f,r);assert.equal(done.document.state.inventory.lantern,1);assert.equal(done.document.state.npcCareers[1].completed,1)});
test('maintenance stays maintenance when materials arrive during the same operation',async()=>{const rcp=ALL_RECIPES.find(r=>r.item==='lantern'),f=await fixture(),r=await f.store.action('pixel',begin(f.document,{goal:'workshop',buildingId:0,action:'work',recipeId:rcp.id},1));assert.equal(r.ticket.mode,'maintenance');const changed=structuredClone(r.document.state);stock(changed,rcp);const saved=await f.store.save('pixel',{state:changed,expectedVersion:r.document.version});f.advance(20000);const done=await f.store.action('pixel',{...identity(r,'finish'),expectedVersion:saved.document.version});assert.deepEqual(done.receipt.gain,{});assert.equal(done.document.state.inventory.lantern,0);assert(done.receipt.text.includes('维护'));for(const [id,n]of Object.entries(rcp.cost))assert.equal(done.document.state.inventory[id],n)});
test('locked or mismatched recipes never create a product and cannot switch the replay identity',async()=>{const rcp=ALL_RECIPES.find(r=>r.tier===2),f=await fixture(s=>{for(const [id,n]of Object.entries(rcp.cost))s.inventory[id]=n}),body=begin(f.document,{goal:BUILDINGS[rcp.building].kind,buildingId:rcp.building,action:'work',recipeId:rcp.id},1),r=await f.store.action('pixel',body);assert.equal(r.ticket.mode,'maintenance');await assert.rejects(f.store.action('pixel',{...body,intent:{...body.intent,recipeId:'lantern'}}),e=>e.code==='action_id_conflict');const done=await finish(f,r);assert.equal(done.document.state.inventory[rcp.item],0);await assert.rejects(f.store.action('pixel',begin(done.document,{goal:'x',buildingId:(rcp.building+1)%25,action:'work',recipeId:rcp.id})),e=>e.code==='resident_invalid')});
test('all valid forest shore fishing and greenhouse materials preserve their actual NPC yields',()=>{for(const raw of RAW_MATERIALS.filter(x=>['forest','shore','fishing','greenhouse'].includes(x.source))){const s=fresh(),b=newActionBook(),intent={goal:raw.source==='forest'?'forest':['shore','fishing'].includes(raw.source)?'dock':BUILDINGS[14].kind,buildingId:raw.source==='greenhouse'?14:null,resource:raw.id,action:'work'},r=applyResidentCommand(s,b,{...begin({actions:b}),intent},1000000),d=applyResidentCommand(s,b,{kind:'resident',operation:'finish',requestId:r.ticket.requestId,epoch:b.epoch,sequence:b.sequence},1020000);assert.equal(d.receipt.gain[raw.id],raw.source==='forest'?2:1,raw.id);const gather=['shore','greenhouse'].includes(raw.source)||raw.source==='forest'&&!['wood','bamboo','hardwood','twig','bark'].includes(raw.id);assert.equal(r.ticket.action,gather?'gather':raw.source==='fishing'?'fish':'axe',raw.id+' action');}const s=fresh(),b=newActionBook();assert.throws(()=>applyResidentCommand(s,b,{...begin({actions:b}),intent:{goal:'forest',buildingId:null,action:'work',resource:'ore'}},1000000),e=>e.code==='resident_invalid')});
test('nursery seed collection and herb seed top-up preserve their limits',async()=>{const f=await fixture(),r=await f.store.action('pixel',begin(f.document,{goal:BUILDINGS[14].kind,buildingId:14,action:'work',resource:'seed'})),done=await finish(f,r);assert.deepEqual(done.receipt.gain,{seed:1});const g=await fixture(s=>s.inventory.seed=4),h=await g.store.action('pixel',begin(g.document,{goal:BUILDINGS[14].kind,buildingId:14,action:'work',resource:'herb'})),harvest=await finish(g,h);assert.deepEqual(harvest.receipt.gain,{herb:1});assert.equal(harvest.document.state.inventory.seed,4)});
test('NPC eating reserves exactly one food and rest/visit/rations apply once at their actual floors',async()=>{const f=await fixture(s=>{s.inventory.bread=1;s.npcNeeds[6]={energy:20,hunger:10,social:10,rations:2,mood:'平静'}}),r=await f.store.action('pixel',begin(f.document,{goal:'bakery',buildingId:17,action:'eat',foodId:'bread'},6));assert.equal(availableQuantity(r.document.state,'bread'),0);const done=await finish(f,r);assert.deepEqual(done.receipt.cost,{bread:1});assert.equal(done.document.state.npcNeeds[6].hunger,48);let z=await f.store.action('pixel',begin(done.document,{goal:'home',buildingId:19,action:'rest'},6));assert.equal(z.ticket.duration,14);let d=await finish(f,z);assert.equal(d.document.state.npcNeeds[6].energy,69);z=await f.store.action('pixel',begin(d.document,{goal:'camp',buildingId:22,action:'eat',foodId:'rations'},6));assert.equal(z.ticket.duration,9);d=await finish(f,z);assert.equal(d.document.state.npcNeeds[6].rations,1);z=await f.store.action('pixel',begin(d.document,{goal:'park',buildingId:5,action:'visit'},6));d=await finish(f,z);assert.equal(d.document.state.npcCareers[6].personalAfter,177);assert.equal(d.document.state.npcNeeds[6].social,16)});
test('same NPC cannot overlap across farm mine and resident jobs while different actors/player can coexist',async()=>{const f=await fixture(),r=await f.store.action('pixel',begin(f.document));await assert.rejects(f.store.action('pixel',begin(r.document)),e=>e.code==='npc_action_active');await assert.rejects(f.store.action('pixel',{kind:'field',operation:'begin',field:'mine',itemId:'stone',index:0,actor:'npc',actorId:5,requestId:randomUUID(),epoch:r.document.actions.epoch,expectedVersion:r.document.version,expectedSequence:r.document.actions.sequence}),e=>e.code==='npc_action_active');const p=await f.store.action('pixel',{operation:'begin',itemId:'wood',requestId:randomUUID(),epoch:r.document.actions.epoch,expectedVersion:r.document.version,expectedSequence:r.document.actions.sequence});f.advance(20000);const done=await f.store.action('pixel',{...identity(r,'finish'),expectedVersion:p.document.version});assert.equal(done.document.state.inventory.wood,2);assert.equal(done.document.actions.active.requestId,p.ticket.requestId)});
test('job mirror and recipe reservations cannot be replaced through autosave',async()=>{const rcp=ALL_RECIPES.find(r=>r.item==='lantern'),f=await fixture(s=>stock(s,rcp)),r=await f.store.action('pixel',begin(f.document,{goal:'workshop',buildingId:0,action:'work',recipeId:rcp.id})),state=structuredClone(r.document.state);state.residentControl.leases=[];await assert.rejects(f.store.save('pixel',{state,expectedVersion:r.document.version}),e=>e.code==='resident_state_conflict');state.residentControl=r.document.state.residentControl;delete state.resourceLedger.reservations[r.ticket.owner];await assert.rejects(f.store.save('pixel',{state,expectedVersion:r.document.version}),e=>e.code==='action_hold_conflict')});
test('real task recipe holds transfer at entry and cancellation restores only unused assigned stock',async()=>{const rcp=ALL_RECIPES.find(r=>r.item==='lantern'),f=await fixture(s=>{stock(s,rcp);queueTask(s,{id:'resident-craft',npcId:1,goal:'workshop',buildingId:0,recipeId:rcp.id,quantity:1},{targetItem:rcp.item});beginTaskStep(s,'resident-craft');reserveResources(s,taskOwner('resident-craft'),rcp.cost)}),t=f.document.state.agentTaskLedger[0],r=await f.store.action('pixel',begin(f.document,{goal:'workshop',buildingId:0,action:'work',recipeId:rcp.id,assignmentId:t.id,operationId:t.operationId},1));assert.deepEqual(r.ticket.sourceTransfer,rcp.cost);assert.equal(r.document.state.resourceLedger.reservations[taskOwner(t.id)],undefined);const d=await f.store.action('pixel',identity(r,'cancel'));assert.deepEqual(d.document.state.resourceLedger.reservations[taskOwner(t.id)].items,rcp.cost);assert.equal(d.document.state.agentTaskLedger[0].status,'queued');assert.equal(d.document.state.inventory.lantern,0)});
test('real task delivery records one actual product and pause blocks late output',async()=>{const rcp=ALL_RECIPES.find(r=>r.item==='lantern'),f=await fixture(s=>{stock(s,rcp);queueTask(s,{id:'actual-resident',npcId:1,goal:'workshop',buildingId:0,recipeId:rcp.id,quantity:1},{targetItem:rcp.item});beginTaskStep(s,'actual-resident')}),t=f.document.state.agentTaskLedger[0],r=await f.store.action('pixel',begin(f.document,{goal:'workshop',buildingId:0,action:'work',recipeId:rcp.id,assignmentId:t.id,operationId:t.operationId},1));restoreTasks(r.document.state);assert.equal(r.document.state.agentTaskLedger[0].status,'running');const d=await finish(f,r);assert.equal(d.document.state.agentTaskLedger[0].status,'done');assert.equal(d.document.state.agentTaskLedger[0].evidence.length,1);const g=await fixture(s=>{queueTask(s,{id:'paused',npcId:5,goal:'forest',quantity:1},{targetItem:'wood'});beginTaskStep(s,'paused')}),task=g.document.state.agentTaskLedger[0],n=await g.store.action('pixel',begin(g.document,{goal:'forest',buildingId:null,action:'work',resource:'wood',assignmentId:task.id,operationId:task.operationId}));const changed=structuredClone(n.document.state);controlTask(changed,task.id,'pause');const saved=await g.store.save('pixel',{state:changed,expectedVersion:n.document.version});g.advance(20000);await assert.rejects(g.store.action('pixel',{...identity(n,'finish'),expectedVersion:saved.document.version}),e=>e.code==='resident_task_changed');assert.equal((await g.store.current('pixel')).state.inventory.wood,0)});
test('actual forest story contribution records original story and cannot be replayed as another operation',async()=>{const f=await fixture(s=>{const row={id:nextOperationId(s,'npc-talk'),day:s.day,time:0,participants:[0,5],type:'negotiate',changes:[],summary:'约定木材',source:'local',lines:[{speaker:0,text:'备料'},{speaker:5,text:'好'}]};s.npcConversations.push(row);const e=recordResidentConversation(s,row,{goal:'forest',buildingId:null,resource:'wood'}).episode;s.day=2;claimResidentStory(s,e.id,5,nextOperationId(s,'story-work'),'work')}),e=f.document.state.residentStories.episodes[0],r=await f.store.action('pixel',begin(f.document,{goal:'forest',buildingId:null,action:'work',resource:'wood',storyId:e.id,operationId:e.inFlight[5].operationId})),d=await finish(f,r);assert.equal(d.document.state.residentStories.episodes[0].contributions[5].amount,2);assert.equal(d.document.state.taskActionReceipts[r.ticket.operationId].storyId,e.id)});
test('parallel processes settle one actual NPC product and expired work still cancels',async()=>{const f=await fixture(),r=await f.store.action('pixel',begin(f.document));f.advance(20000);const a=await Promise.all([f.store.action('pixel',identity(r,'finish')),f.other().action('pixel',identity(r,'finish'))]);assert.equal(a.filter(x=>!x.replayed).length,1);assert.equal((await f.store.current('pixel')).state.inventory.wood,2);const n=await f.store.action('pixel',begin(a[0].document));f.advance(1800001);await assert.rejects(f.store.action('pixel',identity(n,'finish')),e=>e.code==='action_expired');assert.equal((await f.store.action('pixel',identity(n,'cancel'))).receipt.outcome,'cancelled')});
test('restore/import/reset remove jobs return unused stock and invalidate earlier epochs',async()=>{const f=await fixture(),r=await f.store.action('pixel',begin(f.document)),backup=await f.store.backup('pixel',{expectedVersion:r.document.version}),restored=await f.store.restore('pixel',{id:backup.id,expectedVersion:r.document.version});assert.equal(restored.document.state.residentControl,undefined);await assert.rejects(f.store.action('pixel',{...identity(r,'finish'),expectedVersion:restored.document.version}),e=>e.code==='action_stale');const n=await f.store.action('pixel',begin(restored.document)),imported=await f.store.import('pixel',{data:n.document,expectedVersion:n.document.version});assert.equal(imported.document.state.residentControl,undefined);const reset=await f.store.restart('pixel',{requestId:'resident-zero-restart',expectedVersion:imported.document.version});assert.equal(reset.document.state.inventory.wood||0,0);assert.equal(reset.document.actions.resident,undefined)});
test('a recruited NPC cannot create unassigned work outside an active contract',async()=>{const f=await fixture();await assert.rejects(f.store.action('pixel',begin(f.document,undefined,16)),e=>e.code==='resident_task_changed')});

for(const theme of ['pixel','origami'])test(theme+' actual tea facility serves one cup only after the resident action and excludes simultaneous users',()=>{
 const s=fresh();hydratePlacements(s,theme);hydrateFunctionalFacilities(s);s.inventory.c1_9=1;s.inventory.tea=3;s.inventory.wood=1;
 const placed=decorate(s,{commandId:'resident-tea-place',action:'place',item:'c1_9',x:800,y:560,rotation:0},{theme});assert(placed.ok);
 hydrateFunctionalFacilities(s);assert(functionalCommand(s,{commandId:'resident-tea-load',displayId:placed.id,action:'load',expectedRevision:s.functionalFacilities.revision}).ok);tickFunctionalFacilities(s,12);
 const b=newActionBook(),intent={goal:'tea',buildingId:null,action:'eat',facilityId:placed.id},r=applyResidentCommand(s,b,{...begin({actions:b}),intent},1000000);
 assert.throws(()=>applyResidentCommand(s,b,{...begin({actions:b}),actorId:6,intent},1000000),e=>e.code==='resident_facility_occupied');assert.throws(()=>applyResidentCommand(s,b,{kind:'resident',operation:'finish',requestId:r.ticket.requestId,epoch:b.epoch,sequence:b.sequence},1009999),e=>e.code==='action_early');assert.equal(functionalUnit(s,placed.id).servings,3);
 const d=applyResidentCommand(s,b,{kind:'resident',operation:'finish',requestId:r.ticket.requestId,epoch:b.epoch,sequence:b.sequence},1010000);assert.equal(functionalUnit(s,placed.id).servings,2);assert.equal(functionalUnit(s,placed.id).delivered,1);assert.deepEqual(d.receipt.cost,{});assert.equal(s.npcNeeds[5].mood,'温暖');
});
test('active recruited partners can rest between assigned work and cannot complete after requesting leave',()=>{
 const s=fresh(),b=newActionBook();s.recruitment={active:{phase:'working',leaveRequested:false}};s.npcNeeds[16]={energy:10,hunger:80,social:80,rations:2,mood:'平静'};
 const r=applyResidentCommand(s,b,{...begin({actions:b}),actorId:16,intent:{goal:'home',buildingId:19,action:'rest'}},1000000);assert.equal(r.ticket.duration,14);
 s.recruitment.active.leaveRequested=true;assert.throws(()=>applyResidentCommand(s,b,{kind:'resident',operation:'finish',requestId:r.ticket.requestId,epoch:b.epoch,sequence:b.sequence},1014000),e=>e.code==='resident_task_changed');assert.equal(s.npcNeeds[16].energy,10);
 s.recruitment.active.leaveRequested=false;applyResidentCommand(s,b,{kind:'resident',operation:'finish',requestId:r.ticket.requestId,epoch:b.epoch,sequence:b.sequence},1014000);assert.equal(s.npcNeeds[16].energy,52);
});
