import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {createSaveStore} from '../server/saveStore.mjs';
import {createZeroState} from '../src/freshStart.js';
import {hydrateTown,RECIPES,purposeOptions} from '../src/townSimulation.js';
import {ALL_RECIPES} from '../src/contentCatalog.js';
import {commitResources,reserveResources} from '../src/resourceLedger.js';
import {validActionBook} from '../server/playerActions.mjs';
async function fixture(theme='pixel',modify=()=>{}){
 let time=100000;const directory=await mkdtemp(join(tmpdir(),'hd-v51-')),store=createSaveStore({directory,now:()=>time}),s=hydrateTown(createZeroState());s.freshStartPending=false;s.coins=100;
 for(const r of Object.values(RECIPES))s.inventory[r.item]=4;modify(s);
 await store.open(theme,{legacyState:s});const current=()=>store.current(theme),call=async(operation,args={})=>store.action(theme,{kind:'visitor',operation,requestId:randomUUID(),expectedVersion:(await current()).version,...args});
 await call('enable',{theme});const advance=async seconds=>{while(seconds>0){const dt=Math.min(seconds,15),doc=await current();time+=dt*1000;await store.save(theme,{state:structuredClone(doc.state),expectedVersion:doc.version,activeSeconds:dt,saveId:randomUUID()});seconds-=dt;}};
 const first=async()=>{await advance(20);return call('arrive');},land=async id=>{time=Math.max(time,(await current()).actions.visitor.guests[id].landReadyAt);return call('land',{guestId:id});},begin=async id=>{const g=(await current()).actions.visitor.guests[id];return call('begin',{guestId:id,stop:g.stop,buildingId:g.itinerary[g.stop]});},finish=async t=>{time=Math.max(time,t.readyAt);return call('finish',{requestId:t.requestId,epoch:t.epoch,sequence:t.sequence});},cancel=t=>call('cancel',{requestId:t.requestId,epoch:t.epoch,sequence:t.sequence});
 return {theme,directory,store,current,call,advance,first,land,begin,finish,cancel,setTime:t=>time=t,getTime:()=>time};
}
test('enable preserves earned counters, derives actual theme, gives no free boats, stock or cash',async()=>{const f=await fixture('origami',s=>{s.economy.tripCounter=3;s.economy.arrivals=7;s.economy.reviews=4;s.economy.rating=4.1;});const doc=await f.current();assert.equal(doc.actions.visitor.theme,'origami');assert.equal(doc.state.coins,100);assert.equal(doc.state.economy.arrivals,7);assert.equal(doc.state.economy.reviews,4);await assert.rejects(f.call('arrive'),e=>e.code==='visitor_early');const a=await f.first();assert.equal(a.document.state.economy.tripCounter,4);assert(a.receipt.accepted.every(g=>g.skin>=6));assert(validActionBook(a.document.actions));});
test('visitor-only clock is wall bounded, offline does not award trips, and same autosave cannot advance twice',async()=>{const f=await fixture(),doc=await f.current(),body={state:structuredClone(doc.state),expectedVersion:doc.version,activeSeconds:15,saveId:randomUUID()};f.setTime(f.getTime()+1000);const one=await f.store.save(f.theme,body);assert.equal(one.document.actions.visitor.activeSeconds,1);f.setTime(f.getTime()+100000);const replay=await f.store.save(f.theme,body);assert(replay.replayed);assert.equal(replay.document.actions.visitor.activeSeconds,1);await assert.rejects(f.store.save(f.theme,{...body,activeSeconds:14}),e=>e.code==='save_id_conflict');assert.equal((await f.current()).state.economy.tripCounter,0);await assert.rejects(f.store.save(f.theme,{state:replay.document.state,expectedVersion:replay.document.version,activeSeconds:16}),e=>e.code==='visitor_clock');});
test('arrival decisions use actual quality, products, capacity and catalogue identity',async()=>{const f=await fixture('pixel',s=>{for(const b of Object.values(s.facilities))b.quality=0;});const r=await f.first();assert.equal(r.receipt.accepted.length,0);assert.equal(r.receipt.declined.length,2);assert.equal(r.document.state.economy.declined,2);const again=await f.store.action(f.theme,{kind:'visitor',operation:'arrive',requestId:r.ticket.requestId,expectedVersion:'old'});assert(again.replayed);assert.equal(again.document.state.economy.tripCounter,1);await assert.rejects(f.call('arrive'),e=>e.code==='visitor_early');});
for(const theme of['pixel','origami'])test(theme+' actual itinerary, twelve-second service, one material/net/rating and dock departure guards',async()=>{const f=await fixture(theme),a=await f.first(),g=a.receipt.accepted[0];assert(g);await assert.rejects(f.call('land',{guestId:g.id}),e=>e.code==='visitor_early');await f.land(g.id);for(let stop=0;stop<g.itinerary.length;stop++){const b=await f.begin(g.id),t=b.ticket,coins=b.document.state.coins,stock=t.quote.item?b.document.state.inventory[t.quote.item]:null;assert.equal(t.duration,12);await assert.rejects(f.call('finish',{requestId:t.requestId,epoch:t.epoch,sequence:t.sequence}),e=>e.code==='visitor_early');const r=await f.finish(t);assert.equal(r.document.state.coins,coins+(t.quote.net||0));if(t.quote.item)assert.equal(r.document.state.inventory[t.quote.item],stock-1);assert.equal(r.receipt.guest.stop,stop+1);const repeat=await f.store.action(theme,{kind:'visitor',operation:'finish',requestId:t.requestId,epoch:t.epoch,sequence:t.sequence,expectedVersion:'stale'});assert(repeat.replayed);assert.equal(repeat.document.state.coins,r.document.state.coins);}
const review=await f.call('review',{guestId:g.id,queue:0}),count=review.document.state.economy.reviews;assert.equal(count,1);const twice=await f.call('review',{guestId:g.id,queue:0});assert.equal(twice.document.state.economy.reviews,count);await assert.rejects(f.call('depart',{guestId:g.id}),e=>e.code==='visitor_early');f.setTime(twice.document.actions.visitor.guests[g.id].boardReadyAt);const end=await f.call('depart',{guestId:g.id});assert(!end.document.actions.visitor.guests[g.id]);assert.equal(end.document.actions.visitor.history.length,1);assert(validActionBook(end.document.actions));});
test('same request cannot change tourist, stop, venue or candidate quote',async()=>{const f=await fixture(),a=await f.first(),g=a.receipt.accepted[0];await f.land(g.id);await assert.rejects(f.call('begin',{guestId:g.id,stop:0,buildingId:20,paid:999}),e=>e.code==='visitor_itinerary');const b=await f.begin(g.id),t=b.ticket;await assert.rejects(f.store.action(f.theme,{kind:'visitor',operation:'begin',requestId:t.requestId,guestId:g.id,stop:1,buildingId:g.itinerary[1],expectedVersion:b.document.version}),e=>e.code==='action_id_conflict');assert.equal((await f.current()).state.coins,100);});
test('last shop product is reserved; another guest, meal and generic spend cannot steal it',async()=>{const f=await fixture('pixel',s=>{s.facilities[1].quality=55;s.inventory.tea=1;for(const r of ALL_RECIPES.filter(r=>r.building===1&&r.item!=='tea'))s.inventory[r.item]=0;});await f.first();await f.advance(90);const a=await f.call('arrive'),guests=a.receipt.accepted;assert.equal(guests.length,2);assert(guests.every(g=>g.itinerary[0]===1));await f.land(guests[0].id);await f.land(guests[1].id);const first=await f.begin(guests[0].id);assert.equal(first.ticket.quote.item,'tea');const snapshot=structuredClone(first.document.state);assert(!commitResources(snapshot,{cost:{tea:1}}).ok);await assert.rejects(f.store.action(f.theme,{kind:'resident',operation:'begin',actorId:6,requestId:randomUUID(),intent:{goal:'tea',buildingId:1,action:'eat',foodId:'tea'},epoch:first.document.actions.epoch,expectedSequence:first.document.actions.sequence,expectedVersion:first.document.version}),e=>e.code==='resident_food');const second=await f.begin(guests[1].id);assert.equal(second.ticket.quote.paid,0);await f.cancel(first.ticket);const result=await f.finish(second.ticket);assert.equal(result.receipt.paid,0);assert.equal(result.document.state.inventory.tea,1);assert.equal(result.document.state.coins,100);});
test('selection and price freeze during service; new premium stock is not substituted',async()=>{const f=await fixture(),a=await f.first(),g=a.receipt.accepted[0];await f.land(g.id);const b=await f.begin(g.id),t=b.ticket,doc=await f.current(),newRecipe=ALL_RECIPES.filter(r=>r.building===t.buildingId&&r.item!==t.quote.item).at(-1);assert(t.quote.item&&newRecipe);const state=structuredClone(doc.state);state.inventory[newRecipe.item]=2;state.facilities[t.buildingId].quality=95;await f.store.save(f.theme,{state,expectedVersion:doc.version});const done=await f.finish(t);assert.equal(done.receipt.paid,t.quote.paid);assert.equal(done.document.state.inventory[newRecipe.item],2);assert.equal(done.document.state.economy.ledger.at(-1).item,t.quote.item);});
test('autosave cannot rewrite visitor mirror, counts, gross, review or held product',async()=>{const f=await fixture(),a=await f.first();await f.land(a.receipt.accepted[0].id);const b=await f.begin(a.receipt.accepted[0].id);for(const mutate of[s=>s.economy.arrivals++,s=>s.economy.rating=5,s=>s.economy.gross=999,s=>s.visitorControl.guests[0].budget=999,s=>delete s.resourceLedger.reservations[b.ticket.owner]]){const state=structuredClone(b.document.state);mutate(state);await assert.rejects(f.store.save(f.theme,{state,expectedVersion:b.document.version}),e=>['visitor_state_conflict','action_hold_conflict'].includes(e.code));}assert(validActionBook((await f.current()).actions));});
test('capacity includes onboard guests and incompletely visited guests cannot review early',async()=>{const f=await fixture(),first=await f.first();for(let i=0;i<3;i++){await f.advance(90);await f.call('arrive');}const doc=await f.current();assert.equal(Object.keys(doc.actions.visitor.guests).length,6);assert.equal(doc.state.economy.declined,2);const g=first.receipt.accepted[0];await f.land(g.id);await assert.rejects(f.call('review',{guestId:g.id,queue:0}),e=>e.code==='visitor_itinerary');await f.advance(220);const done=await f.call('review',{guestId:g.id,queue:0});assert.equal(done.receipt.rating,1);assert.equal(done.document.state.economy.reviews,1);});
test('expired service can only cancel its own hold and resume same unpaid stop',async()=>{const f=await fixture(),a=await f.first(),g=a.receipt.accepted[0];await f.land(g.id);const b=await f.begin(g.id),stock=b.document.state.inventory[b.ticket.quote.item];f.setTime(b.ticket.expiresAt+1);await assert.rejects(f.call('finish',{requestId:b.ticket.requestId,epoch:b.ticket.epoch,sequence:b.ticket.sequence}),e=>e.code==='visitor_expired');const c=await f.cancel(b.ticket);assert.equal(c.document.state.inventory[b.ticket.quote.item],stock);assert.equal(c.document.actions.visitor.guests[g.id].stop,0);assert.equal(c.document.actions.visitor.guests[g.id].phase,'landed');assert(!c.document.state.resourceLedger.reservations[b.ticket.owner]);});
test('two store instances finishing the same service get one unique transaction',async()=>{const f=await fixture(),a=await f.first(),g=a.receipt.accepted[0];await f.land(g.id);const b=await f.begin(g.id);f.setTime(b.ticket.readyAt);const store2=createSaveStore({directory:f.directory,now:f.getTime}),body={kind:'visitor',operation:'finish',requestId:b.ticket.requestId,epoch:b.ticket.epoch,sequence:b.ticket.sequence,expectedVersion:b.document.version};const result=await Promise.all([f.store.action(f.theme,body),store2.action(f.theme,body)]);assert.equal(result.filter(r=>r.replayed).length,1);const end=await f.current();assert.equal(end.state.economy.ledger.length,1);assert.equal(end.actions.receipts.filter(r=>r.ticket.requestId===b.ticket.requestId).length,1);});
test('restore/import/restart release pending visitor goods and invalidate old leases',async()=>{const f=await fixture(),a=await f.first(),g=a.receipt.accepted[0];await f.land(g.id);const b=await f.begin(g.id),backup=await f.store.backup(f.theme,{expectedVersion:b.document.version});const restored=await f.store.restore(f.theme,{id:backup.id,expectedVersion:b.document.version});assert(!restored.document.state.visitorControl);assert.equal(Object.keys(restored.document.state.resourceLedger.reservations).length,0);await assert.rejects(f.store.action(f.theme,{kind:'visitor',operation:'finish',requestId:b.ticket.requestId,epoch:b.ticket.epoch,sequence:b.ticket.sequence,expectedVersion:restored.document.version}),e=>e.code==='visitor_not_enabled');const imported=await f.store.import(f.theme,{data:b.document,expectedVersion:restored.document.version});assert(!imported.document.state.visitorControl);assert.equal(imported.document.state.economy.active,0);const fresh=await f.store.restart(f.theme,{requestId:randomUUID(),expectedVersion:imported.document.version});assert.equal(fresh.document.state.coins,0);assert(!fresh.document.actions.visitor);});
test('visitor and farm clocks share visible time without double-counting a lost save response',async()=>{const f=await fixture();await f.store.action(f.theme,{kind:'farm',operation:'enable',requestId:randomUUID(),expectedVersion:(await f.current()).version});const doc=await f.current();f.setTime(f.getTime()+5000);const body={state:doc.state,expectedVersion:doc.version,saveId:randomUUID(),activeSeconds:5},saved=await f.store.save(f.theme,body),replayed=await f.store.save(f.theme,body);assert.equal(saved.document.actions.visitor.activeSeconds,5);assert.equal(saved.document.actions.farm.activeSeconds,5);assert.equal(replayed.document.actions.visitor.activeSeconds,5);assert(replayed.replayed);});

test('invalid legacy visitor counters refuse migration without clearing earned revenue or overwriting the save',async()=>{const directory=await mkdtemp(join(tmpdir(),'hd-v51-legacy-')),store=createSaveStore({directory}),s=hydrateTown(createZeroState());s.freshStartPending=false;s.coins=93;s.economy.gross=80;s.economy.guestSerial='broken';const opened=await store.open('pixel',{legacyState:s});await assert.rejects(store.action('pixel',{kind:'visitor',operation:'enable',requestId:randomUUID(),expectedVersion:opened.document.version}),e=>e.code==='visitor_legacy_invalid');const current=await store.current('pixel');assert.equal(current.version,opened.document.version);assert.equal(current.state.coins,93);assert.equal(current.state.economy.gross,80);assert(!current.actions?.visitor);});

test('autonomous recipe seed shortage routes to the greenhouse nursery instead of attempting to sow the seed item as a crop',()=>{const s=hydrateTown(createZeroState());s.npcCareers[0]={phase:1,completed:0,history:[],lastResult:''};const d=purposeOptions(0,s,{relationships:[]},0).find(d=>d.purposeId==='career:1');assert.equal(d.resource,'seed');assert.equal(d.buildingId,14);assert.equal(d.goal,'workshop');assert.equal(s.inventory.seed,0);});
