import {trackJourney,hydrateJourney} from '../src/journey.js';import {refreshAchievements} from '../src/achievements.js';
import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {randomUUID} from 'node:crypto';
import {createSaveStore} from '../server/saveStore.mjs';import {createZeroState} from '../src/freshStart.js';import {hydrateTown} from '../src/townSimulation.js';import {reserveResources} from '../src/resourceLedger.js';import {townDailyBudget,townOrders,reserveParty,completeParty} from '../src/economy.js';import {validActionBook} from '../server/playerActions.mjs';
import {chooseSpecialization,acceptSpecializationCommission,specializationOffer,trackSpecialization} from '../src/specialization.js';import {ALL_RECIPES,commitRecipe} from '../src/contentCatalog.js';import {nextOperationId} from '../src/resourceLedger.js';
async function fixture(theme='pixel',edit=()=>{}){let time=100000;const directory=await mkdtemp(join(tmpdir(),'hd-v52-')),store=createSaveStore({directory,now:()=>time}),s=hydrateTown(createZeroState());s.freshStartPending=false;s.coins=200;edit(s);await store.open(theme,{legacyState:s});const current=()=>store.current(theme),call=async(operation,args={})=>{const d=await current();return store.action(theme,{kind:'commerce',operation,requestId:randomUUID(),day:d.state.day,expectedVersion:d.version,...args});};await call('enable');const save=async(seconds=0,edit=()=>{})=>{const d=await current(),s=structuredClone(d.state);edit(s);time+=seconds*1000;return store.save(theme,{state:s,expectedVersion:d.version,saveId:randomUUID(),activeSeconds:seconds});};return{theme,directory,store,current,call,save,setTime:t=>time=t,time:()=>time};}
test('enable retains cash, day and partial day and neither grants stock nor offline income',async()=>{const f=await fixture('origami',s=>{s.day=3;s.economy.daySeconds=415;s.economy.orderIncome=18;});const d=await f.current();assert.equal(d.state.day,3);assert.equal(d.state.coins,200);assert.equal(d.state.economy.daySeconds,415);assert.equal(d.actions.commerce.snapshot.orderIncome,18);f.setTime(999999);await f.save(0);assert.equal((await f.current()).state.economy.daySeconds,415);assert(validActionBook(d.actions));});
for(const theme of ['pixel','origami'])test(theme+' effective 900-second day settles actual budget once and same save cannot advance twice',async()=>{const f=await fixture(theme,s=>{s.economy.daySeconds=899;s.economy.budgetPolicyStartsDay=1;});const d=await f.current(),budget=townDailyBudget(d.state).total;f.setTime(f.time()+1000);const body={state:d.state,expectedVersion:d.version,saveId:randomUUID(),activeSeconds:1},r=await f.store.save(theme,body);assert.equal(r.document.state.day,2);assert.equal(r.document.state.economy.daySeconds,0);assert.equal(r.document.state.coins,200-budget);assert.equal(r.document.state.economy.townDays.length,1);assert(r.document.state.economy.cashReceipts['town-day-1']);const again=await f.store.save(theme,body);assert(again.replayed);assert.equal(again.document.state.day,2);assert.equal(again.document.state.economy.townDays.length,1);});
test('insufficient cash keeps reserve and records reduced operating payment without offline debt',async()=>{const f=await fixture('pixel',s=>{s.coins=25;s.economy.daySeconds=899;s.economy.budgetPolicyStartsDay=1;});await f.save(1);const d=await f.current();assert.equal(d.state.coins,20);assert.equal(d.state.economy.townDays[0].paid,5);assert(d.state.economy.townDays[0].deferred>0);assert.equal(d.state.economy.cashLedger.filter(r=>r.category==='town').length,1);});
test('server rejects client date, phase, daily payment, policy and order-income changes',async()=>{const f=await fixture();for(const edit of[s=>s.day++,s=>s.economy.daySeconds=800,s=>s.economy.townDays.push({day:1,paid:0}),s=>s.economy.orderIncome=999,s=>s.economy.cashReceipts['town-order-1-0']=true,s=>s.economy.budgetPolicyVersion=12,s=>s.commerceControl.day=2])await assert.rejects(f.save(0,edit),e=>e.code==='commerce_state_conflict');});
test('daily clock is wall bounded and no arbitrary seconds can mint days',async()=>{const f=await fixture(),d=await f.current();f.setTime(f.time()+1000);const r=await f.store.save(f.theme,{state:d.state,expectedVersion:d.version,saveId:randomUUID(),activeSeconds:15});assert.equal(r.document.actions.commerce.activeSeconds,1);assert.equal(r.document.state.economy.daySeconds,1);await assert.rejects(f.save(16),e=>e.code==='commerce_clock');});
test('three orders derive real item quantities, personal credit, fee and one cash/material receipt',async()=>{const f=await fixture('pixel',s=>{for(const o of townOrders(s)){s.inventory[o.item]=o.quantity;s.economy.playerGoods[o.item]=o.quantity;}});for(let slot=0;slot<3;slot++){const d=await f.current(),o=townOrders(d.state)[slot],r=await f.call('order',{slot,reward:999,net:999});assert.equal(r.receipt.cashDelta,o.net);assert.equal(r.receipt.stockDelta[o.item],-o.quantity);assert.equal(r.document.state.economy.playerGoods[o.item],0);assert.equal(r.document.state.economy.cashLedger.at(-1).cost,o.cost);assert(r.document.state.resourceLedger.receipts['cash:'+o.receipt]);const repeat=await f.store.action(f.theme,{kind:'commerce',operation:'order',day:1,slot,requestId:r.ticket.requestId,expectedVersion:'stale'});assert(repeat.replayed);assert.equal(repeat.document.state.coins,r.document.state.coins);await assert.rejects(f.call('order',{slot}),e=>e.code==='commerce_order');}});
test('automatic or purchased stock cannot fill personal order and held goods cannot be delivered',async()=>{const f=await fixture('pixel',s=>s.inventory.wood=3);await assert.rejects(f.call('order',{slot:0}),e=>e.code==='commerce_order');const g=await fixture('pixel',s=>{s.inventory.wood=3;s.economy.playerGoods.wood=3;reserveResources(s,'task:order-hold',{wood:1});});await assert.rejects(g.call('order',{slot:0}),e=>e.code==='commerce_order');assert.equal((await g.current()).state.inventory.wood,3);});
test('buy supplies derives catalog price and goods, never adds personal order credit',async()=>{const f=await fixture(),r=await f.call('supply',{supply:'timber',coins:0,items:{wood:999}});assert.equal(r.receipt.cashDelta,-42);assert.deepEqual(r.receipt.stockDelta,{wood:8,stone:4});assert.equal(r.document.state.economy.playerGoods.wood||0,0);assert.equal(r.document.state.discovered.wood,true);const repeat=await f.store.action(f.theme,{kind:'commerce',operation:'supply',day:1,supply:'timber',requestId:r.ticket.requestId,expectedVersion:'old'});assert(repeat.replayed);assert.equal(repeat.document.state.inventory.wood,8);await assert.rejects(f.store.action(f.theme,{kind:'commerce',operation:'supply',day:1,supply:'metal',requestId:r.ticket.requestId,expectedVersion:r.document.version}),e=>e.code==='action_id_conflict');});
test('upgrade and maintenance use actual escalating cost, materials, quality cap and condition',async()=>{const f=await fixture('pixel',s=>{s.coins=1000;s.inventory.wood=15;s.inventory.stone=10;s.facilities[0].condition=50;});const r=await f.call('upgrade',{buildingId:0});assert.equal(r.receipt.cashDelta,-80);assert.deepEqual(r.receipt.stockDelta,{wood:-3,stone:-2});assert.equal(r.document.state.facilities[0].upgrades,1);assert.equal(r.document.state.facilities[0].quality,55);assert.equal(r.document.state.facilities[0].condition,70);const m=await f.call('maintain',{buildingId:0});assert.equal(m.receipt.cashDelta,-21);assert.deepEqual(m.receipt.stockDelta,{wood:-1,stone:-1});assert.equal(m.document.state.facilities[0].condition,100);await assert.rejects(f.call('maintain',{buildingId:0}),e=>e.code==='commerce_facility');});
test('reserved cash and materials are respected and failed commerce does not partially mutate stock or ledger',async()=>{const f=await fixture('pixel',s=>{s.coins=42;reserveResources(s,'task:cash',{coins:1});});const d=await f.current();await assert.rejects(f.call('supply',{supply:'timber'}),e=>e.code==='commerce_funds');assert.equal((await f.current()).version,d.version);assert.equal((await f.current()).state.inventory.wood,0);});
test('stale day cannot deliver a different rotating order and same ID cannot change the operation',async()=>{const f=await fixture('pixel',s=>{s.inventory.wood=3;s.economy.playerGoods.wood=3;s.economy.daySeconds=899;});await f.save(1);await assert.rejects(f.call('order',{slot:0,day:1}),e=>e.code==='commerce_day');const r=await f.call('supply',{supply:'timber'});await assert.rejects(f.store.action(f.theme,{kind:'commerce',operation:'order',day:2,slot:0,requestId:r.ticket.requestId,expectedVersion:r.document.version}),e=>e.code==='action_id_conflict');});
test('two processes replay one supply purchase and do not double charge',async()=>{const f=await fixture(),d=await f.current(),body={kind:'commerce',operation:'supply',supply:'timber',day:1,requestId:randomUUID(),expectedVersion:d.version},other=createSaveStore({directory:f.directory,now:f.time});const r=await Promise.all([f.store.action(f.theme,body),other.action(f.theme,body)]);assert.equal(r.filter(r=>r.replayed).length,1);assert.equal((await f.current()).state.coins,158);});
test('farm visitor and daily clocks advance from same bounded save without duplicate replay',async()=>{const f=await fixture();for(const kind of['farm','visitor'])await f.store.action(f.theme,{kind,operation:'enable',requestId:randomUUID(),expectedVersion:(await f.current()).version});const d=await f.current();f.setTime(f.time()+5000);const body={state:d.state,expectedVersion:d.version,activeSeconds:5,saveId:randomUUID()},r=await f.store.save(f.theme,body);assert.equal(r.document.actions.commerce.activeSeconds,5);assert.equal(r.document.actions.farm.activeSeconds,5);assert.equal(r.document.actions.visitor.activeSeconds,5);assert.equal((await f.store.save(f.theme,body)).document.actions.commerce.activeSeconds,5);});
test('import restore and reset clear old mirror and retain actual earned cash or genuine zero state',async()=>{const f=await fixture(),r=await f.call('supply',{supply:'timber'}),backup=await f.store.backup(f.theme,{expectedVersion:r.document.version}),restored=await f.store.restore(f.theme,{id:backup.id,expectedVersion:r.document.version});assert.equal(restored.document.state.coins,158);assert(!restored.document.state.commerceControl);await assert.rejects(f.store.action(f.theme,{kind:'commerce',operation:'supply',supply:'timber',day:1,requestId:r.ticket.requestId,expectedVersion:restored.document.version}),e=>e.code==='commerce_not_enabled');const reset=await f.store.restart(f.theme,{requestId:randomUUID(),expectedVersion:restored.document.version});assert.equal(reset.document.state.coins,0);assert.equal(reset.document.state.day,1);assert(!reset.document.actions.commerce);});
test('quality specialization delivery pays only after accepted true post-order player production',async()=>{const f=await fixture('pixel',s=>{hydrateJourney(s);refreshAchievements(s);s.inventory.lantern=1;s.inventory.wheat=2;s.partyInvites={0:true,2:true};const party=reserveParty(s);assert(party);assert(completeParty(s,3));s.activities++;trackJourney(s,'party',{kind:'night',eventId:party.id});chooseSpecialization(s,'artisan');const offer=specializationOffer(s);acceptSpecializationCommission(s,offer.id,offer.item);const recipe=ALL_RECIPES.find(r=>r.item===offer.item);for(const[id,n]of Object.entries(recipe.cost))s.inventory[id]=n;const command=nextOperationId(s,'player:craft')+':result';assert(commitRecipe(recipe,s,{commandId:command}));s.economy.playerGoods[recipe.item]=1;trackSpecialization(s,'craft',{commandId:command,item:recipe.item,quality:93});});const d=await f.current(),c=d.state.specialization.commission,r=await f.call('career',{commissionId:c.id});assert.equal(r.receipt.cashDelta,c.net);assert.equal(r.receipt.stockDelta[c.item],-1);assert.equal(r.document.state.specialization.commission.status,'delivered');assert.equal(r.document.state.specialization.deliveries.artisan,1);await assert.rejects(f.call('career',{commissionId:c.id}),e=>e.code==='commerce_career');});

import {applyCraftEvent,craftResult} from '../src/craftGameReplay.js';
import {chooseAction} from './v19-play-helpers.mjs';
for(const theme of ['pixel','origami'])test(theme+' actual server crafted commission has one monotonic personal proof and delivers once',async()=>{
 const f=await fixture(theme,s=>{
  hydrateJourney(s);refreshAchievements(s);s.inventory.lantern=1;s.inventory.wheat=2;s.partyInvites={0:true,2:true};
  const p=reserveParty(s);assert(p);assert(completeParty(s,3));s.activities++;trackJourney(s,'party',{kind:'night',eventId:p.id});
  for(let i=0;i<10000;i++){s.saveSlot='server-craft-career-'+i;if(specializationOffer(s,'artisan').item==='lantern')break;}
  assert(chooseSpecialization(s,'artisan').ok);const offer=specializationOffer(s);assert.equal(offer.item,'lantern');assert(acceptSpecializationCommission(s,offer.id,offer.item).ok);
  const recipe=ALL_RECIPES.find(r=>r.item===offer.item);for(const[id,n]of Object.entries(recipe.cost))s.inventory[id]=n;
  for(let i=0;i<3;i++)nextOperationId(s,'player:craft');
 });
 let d=await f.current();const beforeSeq=d.state.resourceLedger.sequence,original=d.state.inventory.lantern;
 let r=await f.store.action(theme,{kind:'craft',operation:'begin',recipeId:'recipe_lantern',mode:'2',requestId:randomUUID(),epoch:d.actions.epoch,expectedSequence:d.actions.sequence,expectedVersion:d.version});
 const game=structuredClone(r.ticket.game),trace=[];const emit=e=>{trace.push(e);applyCraftEvent(game,e)};
 emit({action:{type:'start'}});
 for(let i=0;i<18000&&game.state.phase!=='result';i++){const a=chooseAction(game.state);if(a)emit({action:a});emit({dt:1/30});}
 assert(craftResult(game)?.passed);
 for(let i=0;i<trace.length;i+=500){const events=trace.slice(i,i+500);f.setTime(f.time()+Math.ceil(events.reduce((n,e)=>n+(e.dt||0),0)*1000)+10);r=await f.store.action(theme,{kind:'craft',operation:'checkpoint',requestId:r.ticket.requestId,epoch:r.ticket.epoch,sequence:r.ticket.sequence,expectedVersion:r.document.version,batch:r.ticket.nextBatch,events});}
 f.setTime(f.time()+2100);const finish={kind:'craft',operation:'finish',requestId:r.ticket.requestId,epoch:r.ticket.epoch,sequence:r.ticket.sequence,expectedVersion:r.document.version};
 const done=await f.store.action(theme,finish),s=done.document.state,c=s.specialization.commission,proof=c.production.command;
 assert.equal(done.receipt.resourceReceiptId,proof);assert.match(proof,/^player:craft:[1-9]\d*:result$/);assert.equal(s.resourceLedger.sequence,beforeSeq+1);assert(s.resourceLedger.receipts[proof]);assert.equal(s.inventory.lantern,original+1);assert.equal(c.production.quality,craftResult(game).quality);
 const replay=await f.store.action(theme,finish);assert(replay.replayed);assert.equal(replay.document.state.resourceLedger.sequence,beforeSeq+1);
 const paid=await f.call('career',{commissionId:c.id});assert.equal(paid.receipt.cashDelta,c.net);assert.equal(paid.document.state.specialization.deliveries.artisan,1);assert.equal(paid.document.state.inventory.lantern,original);
 await assert.rejects(f.call('career',{commissionId:c.id}),e=>e.code==='commerce_career');
});
