import {traceNightGame} from './night-trace-fixture.mjs';
import {itemUse} from '../src/contentCatalog.js';

import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {randomUUID} from 'node:crypto';
import {createSaveStore} from '../server/saveStore.mjs';import {createZeroState} from '../src/freshStart.js';import {hydrateTown} from '../src/townSimulation.js';import {createNightPartyGame,applyNightPartyEvent,nightLight} from '../src/nightPartyReplay.js';
import {createRecruitmentStore} from '../server/recruitmentStore.mjs';import {bindRecruitment,hireOwner} from '../src/recruitment.js';import {createProject,projectSteps} from '../src/projectPlans.js';import {beginTaskStep} from '../src/taskBoard.js';
async function fixture(theme='pixel',edit=()=>{}){let now=100000;const directory=await mkdtemp(join(tmpdir(),'hd-v53-')),store=createSaveStore({directory,now:()=>now}),s=hydrateTown(createZeroState());s.freshStartPending=false;s.coins=100;s.inventory.lantern=1;s.inventory.wheat=2;s.partyInvites={0:true,2:true};edit(s);await store.open(theme,{legacyState:s});
 const current=()=>store.current(theme),call=async(kind,operation,args={})=>{const d=await current();return store.action(theme,{kind,operation,requestId:randomUUID(),epoch:d.actions?.epoch??null,expectedSequence:d.actions?.sequence||0,expectedVersion:d.version,day:d.state.day,...(kind==='party'&&operation==='begin'?{gameVersion:2}:{}),...args});},save=async(edit)=>{const d=await current(),s=structuredClone(d.state);edit(s);return store.save(theme,{state:s,expectedVersion:d.version});};await call('commerce','enable');return{theme,directory,store,current,call,save,advance:dt=>now+=dt,other:()=>createSaveStore({directory,now:()=>now})};}
const identity=(r,operation,extra={})=>({kind:'party',operation,requestId:r.ticket.requestId,epoch:r.ticket.epoch,sequence:r.ticket.sequence,expectedVersion:r.document.version,...extra});
async function night(f,r){await f.save(s=>{s.nightAttendance={id:r.ticket.eventId,people:{0:{x:735,y:430,inside:null,arrived:true},2:{x:845,y:430,inside:null,arrived:true}}};s.npcPresence=[{id:0,x:735,y:430,inside:null},{id:2,x:845,y:430,inside:null}];});r.document=await f.current();const {game,events}=traceNightGame(r.ticket.game);
 f.advance(Math.ceil(game.elapsed*1000)+10);r=await f.store.action(f.theme,identity(r,'checkpoint',{batch:1,events}));return r;}
for(const theme of ['pixel','origami'])test(theme+' real replay computes four releases and applies exact one entry and reward',async()=>{const f=await fixture(theme);await f.call('party','enable');const r=await f.call('party','begin',{fireworks:false,score:999,reward:999});assert.equal(r.document.state.coins,92);assert.equal(r.document.state.inventory.lantern,0);assert.equal(r.document.state.inventory.wheat,0);await assert.rejects(f.store.action(theme,identity(r,'finish')),e=>e.code==='party_unfinished');
 const played=await night(f,r);assert.equal(played.ticket.game.score,4);await assert.rejects(f.store.action(theme,identity(played,'finish')),e=>e.code==='action_early');f.advance(2300);const done=await f.store.action(theme,identity(played,'finish',{score:999,reward:999}));assert.equal(done.receipt.reward,28);assert.equal(done.document.state.coins,120);assert.equal(done.document.state.activities,1);assert.equal(done.document.state.npcAffinity[0],23);assert.equal(done.document.state.partySession,null);
 const replay=await f.other().action(theme,identity(played,'finish'));assert(replay.replayed);assert.equal(replay.document.state.coins,120);await assert.rejects(f.call('party','begin'),e=>e.code==='party_not_ready');});
test('entry consumes only actual extras and reserve failure has no partial fee',async()=>{const f=await fixture('pixel',s=>{s.inventory.firework=1;s.inventory.outfit=1;assert(itemUse('outfit',s).ok);});await f.call('party','enable');const r=await f.call('party','begin',{fireworks:true});assert.equal(r.document.state.inventory.firework,0);assert.equal(r.document.state.coins,92);const p=await night(f,r);f.advance(2300);const paid=await f.store.action('pixel',identity(p,'finish'));assert.equal(paid.receipt.reward,33);
 const poor=await fixture('pixel',s=>s.coins=7);await poor.call('party','enable');const before=await poor.current();await assert.rejects(poor.call('party','begin'),e=>e.code==='party_not_ready');assert.equal((await poor.current()).version,before.version);assert.equal((await poor.current()).state.inventory.lantern,1);});
test('same begin and batches replay; changed content or wall clock cheats cannot change game',async()=>{const f=await fixture();await f.call('party','enable');const start=await f.call('party','begin'),d=await f.current();const req=identity(start,'checkpoint',{batch:1,events:[{dt:.05}]});await assert.rejects(f.store.action('pixel',identity(start,'checkpoint',{batch:1,events:[{dt:1}]})),e=>e.code==='party_input');await assert.rejects(f.store.action('pixel',identity(start,'checkpoint',{batch:1,events:[{dt:.05},{dt:.05},{dt:.05},{dt:.05}]})),e=>e.code==='party_clock');f.advance(50);const saved=await f.store.action('pixel',req);assert((await f.store.action('pixel',req)).replayed);await assert.rejects(f.store.action('pixel',{...req,events:[{action:{type:'tap'}}]}),e=>e.code==='party_batch_conflict');assert.deepEqual((await f.other().current('pixel')).actions.active.game,saved.ticket.game);
 const replay=await f.store.action('pixel',{kind:'party',operation:'begin',gameVersion:2,requestId:start.ticket.requestId,expectedVersion:'stale'});assert(replay.replayed);await assert.rejects(f.store.action('pixel',{kind:'party',operation:'begin',gameVersion:2,requestId:start.ticket.requestId,fireworks:true}),e=>e.code==='action_id_conflict');});
test('save cannot alter game projection, nightly payment flags or completions',async()=>{const f=await fixture();await f.call('party','enable');await f.call('party','begin');for(const edit of[s=>s.partySession.score=4,s=>s.partySession.round=4,s=>s.partyControl.completions=99,s=>s.economy.cashReceipts['party-1-fake']=true])await assert.rejects(f.save(edit),e=>e.code==='party_state_conflict');});
test('partial cancel and expired party retain used entry, never award completion and old finish stays cancelled',async()=>{const f=await fixture();await f.call('party','enable');const r=await f.call('party','begin');f.advance(86400001);await assert.rejects(f.store.action('pixel',identity(r,'checkpoint',{batch:1,events:[{action:{type:'tap'}}]})),e=>e.code==='action_expired');const cancelled=await f.store.action('pixel',identity(r,'cancel'));assert.equal(cancelled.receipt.reward,0);assert.equal(cancelled.document.state.coins,92);assert.equal(cancelled.document.state.activities,0);assert.equal((await f.store.action('pixel',identity(r,'finish'))).receipt.outcome,'cancelled');});
test('concurrent processes finish one night with one payout; restoration cannot finish old epoch',async()=>{const f=await fixture();await f.call('party','enable');let r=await f.call('party','begin');r=await night(f,r);f.advance(2300);const result=await Promise.all([f.store.action('pixel',identity(r,'finish')),f.other().action('pixel',identity(r,'finish'))]);assert.equal(result.filter(r=>r.replayed).length,1);const d=await f.current(),backup=await f.store.backup('pixel',{expectedVersion:d.version}),restored=await f.store.restore('pixel',{id:backup.id,expectedVersion:d.version});assert.equal(restored.document.state.coins,120);assert(!restored.document.state.partyControl);await assert.rejects(f.store.action('pixel',{...identity(r,'finish'),expectedVersion:restored.document.version}),e=>e.code==='party_not_enabled');});
test('legacy ongoing night is not silently reset or paid; explicit close retains cost and used daily opportunity',async()=>{const f=await fixture('origami',s=>{s.coins=92;s.inventory.lantern=0;s.inventory.wheat=0;s.lastPartyDay=1;s.partySession={id:'party-1-0',round:2,score:1,phase:2,day:1,fireworks:false,outfit:null};});await assert.rejects(f.call('party','enable'),e=>e.code==='party_legacy_active');assert.equal((await f.current()).state.partySession.round,2);const closed=await f.call('commerce','party_legacy_close');assert.equal(closed.receipt.cashDelta,0);assert.equal(closed.document.state.coins,92);assert.equal(closed.document.state.activities,0);await f.call('party','enable');await assert.rejects(f.call('party','begin'),e=>e.code==='party_not_ready');});
async function hired(){const f=await fixture('pixel',s=>{s.inventory.lantern=0;s.inventory.wheat=0;const r=createProject(s,{id:'v53-real-work',title:'采六份木材',targets:{wood:6}});assert(r.ok);});await f.call('commerce','hire_enable');const registry=createRecruitmentStore({directory:f.directory}),doc=await f.current(),started=await registry.start('pixel',doc,{requestId:randomUUID(),candidateId:'mai',projectId:'v53-real-work',source:'user'}),c=started.contract,ids=c.context.steps.map(t=>t.id);
 const run={source:'hermes',model:'deepseek-flash',parent:{id:'hd-parent-v53-fixture',status:'completed',tools:['recruitment_delegate']},child:{id:'hd-child-v53-fixture',parentId:'hd-parent-v53-fixture',status:'completed',tools:['recruitment_take_step'],acceptedSteps:ids},events:[{actor:'parent',tool:'recruitment_delegate',status:'done'},{actor:'child',tool:'recruitment_take_step',status:'done'}]};
 await registry.complete('pixel',c.id,c.attempt,run);const activated=await registry.activate('pixel',await f.current(),c.id);await f.save(s=>{assert(bindRecruitment(s,activated.contract).ok);s.recruitment.active.phase='working';});return {...f,registry,contract:activated.contract};}
async function work(f){await f.save(s=>{const t=s.agentTaskLedger.find(t=>t.id===f.contract.agreedSteps[0].id);beginTaskStep(s,t.id);});const d=await f.current(),t=d.state.agentTaskLedger.find(t=>t.id===f.contract.agreedSteps[0].id),r=await f.call('resident','begin',{actorId:16,gameTime:0,intent:{goal:'forest',action:'work',resource:'wood',buildingId:null,assignmentId:t.id,operationId:t.operationId}});f.advance(20000);return f.store.action('pixel',{kind:'resident',operation:'finish',requestId:r.ticket.requestId,epoch:r.ticket.epoch,sequence:r.ticket.sequence,expectedVersion:r.document.version});}
test('actual resident delivery accrues registry-confirmed wage and replay cannot double charge',async()=>{const f=await hired(),w=await work(f),amount=w.receipt.gain.wood;assert(amount>0);const d=await f.current(),c=d.actions.hire.contracts[f.contract.id];assert.equal(c.delivered[f.contract.agreedSteps[0].id],amount);assert.equal(c.legacyBaseline,false);
 const paid=await f.call('commerce','hire_handover',{contractId:f.contract.id,fee:999,delivered:999}),fee=Math.ceil(8*amount/6);assert.equal(paid.receipt.cashDelta,-fee);assert.equal(paid.document.state.recruitment.active.feePaid,fee);assert(!paid.document.state.resourceLedger.reservations[hireOwner(f.contract.id)]);
 const replay=await f.other().action('pixel',{kind:'commerce',operation:'hire_handover',requestId:paid.ticket.requestId,contractId:f.contract.id,day:1,expectedVersion:'old'});assert(replay.replayed);assert.equal(replay.document.state.coins,paid.document.state.coins);await assert.rejects(f.save(s=>s.recruitment.active.feePaid=null),e=>e.code==='hire_state_conflict');});
test('accepted contract without actual work has zero wage; forged contract inputs and agreements are rejected',async()=>{const f=await hired();await assert.rejects(f.call('commerce','hire_handover',{contractId:'missing-contract'}),e=>e.code==='recruitment_missing');await f.save(s=>s.recruitment.active.wage=0);await assert.rejects(f.call('commerce','hire_handover',{contractId:f.contract.id}),e=>e.code==='hire_contract_changed');await f.save(s=>s.recruitment.active.wage=8);const paid=await f.call('commerce','hire_handover',{contractId:f.contract.id,verifiedContract:{id:f.contract.id},fee:8});assert.equal(paid.receipt.cashDelta,0);assert.equal(paid.document.state.recruitment.active.feePaid,0);});
test('unknown registry ID cannot be replaced with client supplied Hermes proof',async()=>{const f=await hired();const c=f.contract;await f.save(s=>s.recruitment.active.id='fake-contract-v53');const d=await f.current();await assert.rejects(f.call('commerce','hire_handover',{contractId:'fake-contract-v53',verifiedContract:c}),e=>e.code==='recruitment_missing');assert.equal((await f.current()).version,d.version);});

test('night releases require both saved residents at separate plaza positions',async()=>{const f=await fixture();await f.call('party','enable');const r=await f.call('party','begin');const tap=identity(r,'checkpoint',{batch:1,events:[{action:{type:'tap'}}]});await assert.rejects(f.store.action('pixel',tap),e=>e.code==='party_arrival');await f.save(s=>{s.nightAttendance={id:r.ticket.eventId,people:{0:{x:735,y:430,inside:null,arrived:true},2:{x:845,y:430,inside:null,arrived:true}}};s.npcPresence=[{id:0,x:735,y:430,inside:null},{id:2,x:735,y:430,inside:null}];});await assert.rejects(f.store.action('pixel',{...tap,expectedVersion:(await f.current()).version}),e=>e.code==='party_arrival');assert.equal((await f.current()).actions.active.game.round,0);});
test('unsettled actual recruit work blocks wages and client evidence cannot raise canonical pay',async()=>{const f=await hired();await f.save(s=>{const t=s.agentTaskLedger.find(t=>t.id===f.contract.agreedSteps[0].id);beginTaskStep(s,t.id);});const d=await f.current(),t=d.state.agentTaskLedger.find(t=>t.id===f.contract.agreedSteps[0].id);await f.call('resident','begin',{actorId:16,gameTime:0,intent:{goal:'forest',action:'work',resource:'wood',buildingId:null,assignmentId:t.id,operationId:t.operationId}});await assert.rejects(f.call('commerce','hire_handover',{contractId:f.contract.id}),e=>e.code==='hire_busy');const clean=await hired();await clean.save(s=>{s.agentTaskLedger.find(t=>t.id===clean.contract.agreedSteps[0].id).evidence=[{npcId:16,contractId:clean.contract.id,amount:6}];});const result=await clean.call('commerce','hire_handover',{contractId:clean.contract.id});assert.equal(result.receipt.cashDelta,0);assert.equal(result.document.state.recruitment.active.feePaid,0);});
test('protected old four-tap ticket reopens from disk and finishes once on the new server',async()=>{
 const f=await fixture();await f.call('party','enable');await f.call('party','begin');
 const doc=await f.current();doc.actions.active.game=createNightPartyGame(623,'normal');delete doc.actions.active.gameVersion;
 doc.state.partySession.phase=doc.actions.active.game.phase;
 const {createHash}=await import('node:crypto'),{writeFile}=await import('node:fs/promises');
 const digest=v=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
 doc.checksum=digest(doc.state);doc.actionsChecksum=digest(doc.actions);
 // This fixture models a trusted pre-upgrade disk document, never a client save.
 await writeFile(join(f.directory,'pixel','current.json'),JSON.stringify(doc));
 const reopened=await f.other().current('pixel');assert.equal(reopened.actions.active.game.engine,'night');
 let r={ticket:reopened.actions.active,document:reopened};r=await night(f,r);assert.equal(r.ticket.game.score,4);f.advance(2300);
 const paid=await f.other().action('pixel',identity(r,'finish'));assert.equal(paid.receipt.reward,28);assert.equal(paid.receipt.score,4);
 assert((await f.other().action('pixel',identity(r,'finish'))).replayed);assert.equal((await f.current()).state.partyControl.completions,1);
});


test('night begin negotiates current physics and absent capability retains the old client game',async()=>{
 for(const version of [undefined,1,2]){
  const f=await fixture();await f.call('party','enable');const started=await f.call('party','begin',{gameVersion:version});
  assert.equal(started.ticket.gameVersion,version??1);assert.equal(started.ticket.game.engine,version===2?'night-sky':'night');
  const replay=await f.store.action('pixel',{kind:'party',operation:'begin',gameVersion:version,requestId:started.ticket.requestId,expectedVersion:'stale'});assert(replay.replayed);assert.equal(replay.ticket.game.seed,started.ticket.game.seed);
  const played=await night(f,started);f.advance(2300);const paid=await f.other().action('pixel',identity(played,'finish'));assert.equal(paid.receipt.reward,28);assert.equal(paid.receipt.ticket.gameVersion,version??1);
 }
});

test('unsupported night capability cannot charge entry or change the action sequence',async()=>{
 const f=await fixture();await f.call('party','enable');const before=await f.current();
 for(const gameVersion of [null,0,3,'2',false])await assert.rejects(f.call('party','begin',{gameVersion}),e=>e.code==='party_game_version');
 assert.deepEqual(await f.current(),before);
});

test('same night begin ID cannot switch rules after entry or after receipt',async()=>{
 const f=await fixture();await f.call('party','enable');const started=await f.call('party','begin');const before=await f.current();
 const request={kind:'party',operation:'begin',gameVersion:1,requestId:started.ticket.requestId,expectedVersion:'stale'};
 await assert.rejects(f.store.action('pixel',request),e=>e.code==='action_id_conflict');assert.deepEqual(await f.current(),before);
 const played=await night(f,started);f.advance(2300);await f.store.action('pixel',identity(played,'finish'));
 const paid=await f.current();await assert.rejects(f.store.action('pixel',request),e=>e.code==='action_id_conflict');assert.deepEqual(await f.current(),paid);
});
