
import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {randomUUID} from 'node:crypto';
import {createSaveStore} from '../server/saveStore.mjs';import {createPartyProposalStore} from '../server/partyProposalStore.mjs';import {hydrateTown} from '../src/townSimulation.js';import {createZeroState} from '../src/freshStart.js';import {partyDraftStamp} from '../src/partyPlanning.js';import {applyFishingEvent} from '../src/fishingReplay.js';import {fishingSpots} from '../src/fishingPartyRuntime.js';import {createFishingEvent,inviteFishingNpc,startFishingParty} from '../src/fishingParty.js';
async function fixture(theme='pixel',edit=()=>{}){let now=100000;const directory=await mkdtemp(join(tmpdir(),'hd-v54-')),store=createSaveStore({directory,now:()=>now}),s=hydrateTown(createZeroState());s.freshStartPending=false;s.coins=100;Object.assign(s.inventory,{rod:1,c8_2:1,c16_4:1,c16_2:2,bread:5});for(const n of Object.values(s.npcNeeds)){n.hunger=n.energy=n.social=100;}edit(s);await store.open(theme,{legacyState:s});
 const current=()=>store.current(theme),call=async(kind,operation,args={})=>{const d=await current();return store.action(theme,{kind,operation,requestId:randomUUID(),expectedVersion:d.version,epoch:d.actions?.epoch??null,expectedSequence:d.actions?.sequence||0,day:d.state.day,...args});},manage=async(operation,args={})=>{const d=await current(),f=d.state.fishingParty?.draft;return call('commerce',operation,{eventId:f?.id||null,eventVersion:f?.version||null,eventStamp:partyDraftStamp(f),...args});},save=async edit=>{const d=await current(),s=structuredClone(d.state);edit(s);return store.save(theme,{state:s,expectedVersion:d.version});};
 await call('commerce','enable');return{directory,theme,store,current,call,manage,save,advance:ms=>now+=ms,other:()=>createSaveStore({directory,now:()=>now})};}
async function begin(f){await f.manage('fish_create',{proposal:{name:'六竿海风',difficulty:'normal'}});for(const npcId of[8,2])await f.manage('fish_invite',{npcId});const d=await f.current(),g=d.state.fishingParty.draft;return f.call('fishing','begin',{eventId:g.id,eventVersion:g.version});}
const identity=(r,operation,extra={})=>({kind:'fishing',operation,requestId:r.ticket.requestId,epoch:r.ticket.epoch,sequence:r.ticket.sequence,expectedVersion:r.document.version,...extra});
async function arrive(f){const d=await f.current(),g=d.state.fishingParty.session,spots=fishingSpots(f.theme);await f.save(s=>{s.player={...spots[2]};s.fishingAttendance={id:g.id,people:{'-1':{...spots[2],inside:null},8:{...spots[0],inside:null},2:{...spots[1],inside:null}}};s.npcPresence=[{id:8,...spots[0],inside:null},{id:2,...spots[1],inside:null}];});return f.manage('fish_checkin',{eventId:g.id});}
export function playFishing(game){
 const events=[],emit=e=>{applyFishingEvent(game,e);events.push(e)},dt=()=>emit({dt:.05});let guard=0;
 while(game.match.phase!=='results'&&guard++<8000){const m=game.match,c=m.current,l=m.rounds[Math.min(m.index,5)];
  if(['ready','round_result'].includes(m.phase)){emit({action:{type:'next'}});continue;}
  if(c.mode==='aim')emit({action:{type:'down',x:l.spot.x-l.wind,y:l.spot.y}});
  else if(c.mode==='bite'&&c.modeT>=.52)emit({action:{type:'down'}});
  else if(c.mode==='fight'){emit({action:{type:'point',x:c.fish.x,y:c.fish.y}});const hold=!c.surge&&c.tension<.72;if(hold!==c.holding)emit({action:{type:hold?'down':'up'}});}
  dt();
 }
 assert.equal(game.match.phase,'results');return events;
}
async function play(f,r){const game=structuredClone(r.ticket.game),events=playFishing(game);for(let at=0;at<events.length;at+=2048){const batch=events.slice(at,at+2048);f.advance(Math.ceil(batch.reduce((n,e)=>n+(e.dt||0),0)*1000)+1);r.document=await f.current();r=await f.store.action(f.theme,identity(r,'checkpoint',{batch:r.ticket.nextBatch,events:batch}));}return r;}
for(const theme of['pixel','origami'])test(theme+' invitation gift, entry, six-cast replay, rivals and unique exact reward',async()=>{const f=await fixture(theme),r=await begin(f),s=r.document.state;assert.equal(s.coins,90);assert.equal(s.inventory.c16_4,0);assert.equal(s.inventory.bread,2);assert.equal(s.inventory.c16_2,1);assert.deepEqual(s.resourceLedger.reservations['event:'+r.ticket.eventId].items,{c8_2:1,rod:1});await assert.rejects(f.store.action(theme,identity(r,'checkpoint',{batch:1,events:[{action:{type:'next'}}]})),e=>e.code==='fishing_arrival');
 await arrive(f);const played=await play(f,r);assert(played.ticket.game.match.results.filter(r=>r.caught).length>=4);await assert.rejects(f.store.action(theme,identity(played,'finish')),e=>e.code==='action_early');f.advance(2200);const done=await f.store.action(theme,identity(played,'finish',{score:999,reward:999}));assert.equal(done.receipt.reward,30+Math.floor(done.receipt.details.result.normalized*.12));assert.equal(done.document.state.coins,90+done.receipt.reward);assert.equal(done.document.state.activities,1);assert.equal(done.document.state.inventory.fish,0);assert(done.document.state.eventWonders.owned.seashell_cup);assert(!done.document.state.resourceLedger.reservations['event:'+r.ticket.eventId]);assert.equal((await f.other().action(theme,identity(played,'finish'))).document.state.coins,done.document.state.coins);assert.equal((await f.current()).state.fishingParty.history.length,1);});
test('invitation replay and critical revision reconfirm without duplicate gifts; changed request rejected',async()=>{const f=await fixture();await f.manage('fish_create',{proposal:{name:'旧海风',difficulty:'normal'}});const given=await f.manage('fish_invite',{npcId:8}),before=given.document.state.inventory.c16_2;const replay=await f.store.action('pixel',{kind:'commerce',operation:'fish_invite',requestId:given.ticket.requestId,day:1,eventId:given.receipt.details.eventId||given.document.state.fishingParty.draft.id,eventVersion:1,eventStamp:partyDraftStamp(given.document.state.fishingParty.draft),npcId:8,expectedVersion:'stale'});assert(replay.replayed);assert.equal(replay.document.state.inventory.c16_2,before);await assert.rejects(f.store.action('pixel',{kind:'commerce',operation:'fish_invite',requestId:given.ticket.requestId,day:1,npcId:2}),e=>e.code==='action_id_conflict');await f.manage('fish_update',{proposal:{name:'新海风',difficulty:'easy'}});const changed=await f.current();assert.equal(changed.state.fishingParty.draft.version,2);await f.manage('fish_invite',{npcId:8});assert.equal((await f.current()).state.inventory.c16_2,before);});
test('checkpoint ordered and durable; altered batch, invalid action and wall-clock speedup rejected',async()=>{const f=await fixture(),r=await begin(f);await arrive(f);r.document=await f.current();const input=identity(r,'checkpoint',{batch:1,events:[{action:{type:'next'}},{dt:.05}]});const saved=await f.store.action('pixel',input);assert((await f.store.action('pixel',input)).replayed);assert.deepEqual((await f.other().current('pixel')).actions.active.game,saved.ticket.game);await assert.rejects(f.store.action('pixel',{...input,events:[{dt:.05}]}),e=>e.code==='fishing_batch_conflict');await assert.rejects(f.store.action('pixel',identity(saved,'checkpoint',{batch:2,events:[{dt:1}]})),e=>e.code==='fishing_input');await assert.rejects(f.store.action('pixel',identity(saved,'checkpoint',{batch:2,events:Array.from({length:20},()=>({dt:.05}))})),e=>e.code==='fishing_clock');});
test('activity, gifts, match, daily opportunity and reserved gear reject full-save overwrite',async()=>{const f=await fixture(),r=await begin(f);await arrive(f);r.document=await f.current();await f.store.action('pixel',identity(r,'checkpoint',{batch:1,events:[{action:{type:'next'}}]}));for(const edit of[s=>s.fishingParty.session.match.elapsed++,s=>s.lastPartyDay=0,s=>s.fishingControl.lastPartyDay=0,s=>s.fishingParty.session.invites[8].version=999,s=>delete s.resourceLedger.reservations['event:'+r.ticket.eventId]])await assert.rejects(f.save(edit),e=>['fishing_state_conflict','action_hold_conflict'].includes(e.code));});
test('arrival cannot be forged by saying arrived or sharing a fishing spot',async()=>{const f=await fixture(),r=await begin(f);await assert.rejects(f.manage('fish_checkin',{eventId:r.ticket.eventId,arrived:true}),e=>e.code==='fishing_arrival');await arrive(f);const g=(await f.current()).state.fishingParty.session;assert.equal(g.phase,'running');const fresh=await fixture(),other=await begin(fresh),spots=fishingSpots();await fresh.save(s=>{s.player={...spots[2]};s.fishingAttendance={id:other.ticket.eventId,people:{'-1':{...spots[2],inside:null},8:{...spots[0],inside:null},2:{...spots[0],inside:null}}};s.npcPresence=[{id:8,...spots[0],inside:null},{id:2,...spots[0],inside:null}];});await assert.rejects(fresh.manage('fish_checkin',{eventId:other.ticket.eventId}),e=>e.code==='fishing_arrival');});
test('partial cancellation, expiry and old finish cannot award or return used supplies',async()=>{const f=await fixture(),r=await begin(f);f.advance(86400001);await assert.rejects(f.store.action('pixel',identity(r,'checkpoint',{batch:1,events:[{neutral:true}]})),e=>e.code==='action_expired');const done=await f.store.action('pixel',identity(r,'cancel'));assert.equal(done.document.state.coins,90);assert.equal(done.receipt.reward,0);assert.equal(done.document.state.fishingParty.session.phase,'abandoned');assert(!done.document.state.resourceLedger.reservations['event:'+r.ticket.eventId]);assert.equal((await f.store.action('pixel',identity(r,'finish'))).receipt.outcome,'cancelled');});
test('simultaneous processes claim once, archived results preserve one history and day',async()=>{const f=await fixture();let r=await begin(f);await arrive(f);r=await play(f,r);f.advance(2200);const results=await Promise.all([f.store.action('pixel',identity(r,'finish')),f.other().action('pixel',identity(r,'finish'))]);assert.equal(results.filter(r=>r.replayed).length,1);await f.manage('fish_archive',{eventId:r.ticket.eventId});assert.equal((await f.current()).state.fishingParty.history.length,1);assert.equal((await f.current()).state.lastPartyDay,1);});
test('night party shares the server daily opportunity with fishing regardless of legacy reset',async()=>{const f=await fixture('pixel',s=>{s.inventory.lantern=1;s.inventory.wheat=2;s.partyInvites={0:true,2:true};});const r=await begin(f);await f.store.action('pixel',identity(r,'cancel'));await f.call('commerce','party_enable');await assert.rejects(f.call('party','begin'),e=>e.code==='party_not_ready');await assert.rejects(f.save(s=>s.lastPartyDay=0),e=>e.code==='fishing_state_conflict');});
test('service party proof bound to island and exact run; client forged proposal ignored',async()=>{const f=await fixture(),runId='hd-island-'+ 'a'.repeat(32),proposalId='b'.repeat(32),p={id:proposalId,expectedId:null,expectedVersion:null,expectedStamp:null,name:'管家海风',difficulty:'normal',description:'',tags:[],guestId:null};await assert.rejects(f.manage('fish_steward',{runId,proposalId,verifiedProposal:p}),e=>e.code==='fishing_proof');const proof=createPartyProposalStore({directory:f.directory});await proof.record({theme:'pixel',worldKey:(await f.current()).state.saveSlot||'legacy-pixel',runId,parties:[p]});const applied=await f.manage('fish_steward',{runId,proposalId});assert(applied.receipt.details.ok);assert.equal(applied.document.state.fishingParty.draft.source,'hermes');assert(applied.document.state.fishingParty.draft.projectId);assert.equal(await proof.peek({theme:'origami',worldKey:applied.document.state.saveSlot||'legacy-pixel',runId,proposalId}),null);await assert.rejects(proof.record({theme:'pixel',worldKey:applied.document.state.saveSlot||'legacy-pixel',runId,parties:[{...p,name:'篡改'}]}));assert.equal(applied.document.state.fishingParty.draft.proposalId,proposalId);await f.manage('fish_cancel');const replay=await f.manage('fish_steward',{runId,proposalId});assert(replay.receipt.details.replayed);assert.equal(replay.document.state.fishingParty.draft,null);assert.equal(replay.document.state.coins,applied.document.state.coins);});
test('legacy running competition not silently reset or paid; explicit ending releases only equipment',async()=>{const f=await fixture('pixel',s=>{assert(createFishingEvent(s,{seed:99}).ok);assert(inviteFishingNpc(s,8,{version:1}).ok);assert(inviteFishingNpc(s,2,{version:1}).ok);assert(startFishingParty(s).ok);});await assert.rejects(f.call('commerce','fish_enable'),e=>e.code==='fishing_legacy_active');const d=await f.current();assert.equal(d.state.coins,90);const end=await f.manage('fish_legacy_close');assert.equal(end.receipt.cashDelta,0);assert.equal(end.document.state.coins,90);assert.equal(end.document.state.activities,0);assert.equal(end.document.state.fishingParty.session,null);await f.call('commerce','fish_enable');assert.equal((await f.current()).state.lastPartyDay,1);});
