import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {randomUUID} from 'node:crypto';
import {createSaveStore} from '../server/saveStore.mjs';import {hydrateTown} from '../src/townSimulation.js';import {createZeroState} from '../src/freshStart.js';import {hydratePlacements,decorate,checkDecoration} from '../src/placements.js';import {hydrateFunctionalFacilities,functionalUnit,functionalCommand,tickFunctionalFacilities} from '../src/functionalFacilities.js';import {reserveResources} from '../src/resourceLedger.js';
async function fixture(theme='pixel',edit=()=>{}){let now=100000;const directory=await mkdtemp(join(tmpdir(),'hd-v55-')),store=createSaveStore({directory,now:()=>now}),s=hydrateTown(createZeroState());s.freshStartPending=false;s.journey={completed:{harvest:true}};hydratePlacements(s,theme);s.placementBook.theme=theme;const ids={};
for(const item of ['c6_8','c1_9','c14_6']){s.inventory[item]=1;s.economy.playerGoods[item]=1;const p=position(s,item);const r=decorate(s,{commandId:'fixture:'+item,action:'place',...p},{theme});assert(r.ok,r.reason);ids[item]=r.id;}
hydrateFunctionalFacilities(s);Object.assign(s.inventory,{shrimp:2,c6_0:2,tea:6,wood:2,c6_5:2,seaweed:2,sand:2,c6_8:1});for(const n of Object.values(s.npcNeeds))n.hunger=n.energy=n.social=100;edit(s,ids);await store.open(theme,{legacyState:s});
const current=()=>store.current(theme),call=async(kind,operation,args={})=>{const d=await current();return store.action(theme,{kind,operation,requestId:randomUUID(),expectedVersion:d.version,epoch:d.actions?.epoch??null,expectedSequence:d.actions?.sequence||0,day:d.state.day,...args});},facility=async(operation,item='c6_8',extra={})=>{const d=await current();return call('facility',operation,{displayId:ids[item],expectedRevision:['move','store','place'].includes(operation)?d.state.placementBook.revision:d.state.functionalFacilities.revision,...extra});},save=async(edit=()=>{},seconds=0,wall=seconds*1000)=>{now+=wall;const d=await current(),state=structuredClone(d.state);edit(state);return store.save(theme,{state,expectedVersion:d.version,saveId:randomUUID(),activeSeconds:seconds});};
await call('facility','enable');return{theme,directory,store,current,call,facility,save,ids,advance:ms=>now+=ms,other:()=>createSaveStore({directory,now:()=>now})};}
function position(s,item,except){const theme=s.placementBook.theme,candidates=[];for(let y=88;y<820;y+=16)for(let x=88;x<1430;x+=16){const d=Math.hypot(x-430,y-703);if(item==='c14_6'&&d>300)continue;candidates.push({item,x,y,rotation:0,d});}candidates.sort((a,b)=>a.d-b.d);const p=candidates.find(p=>checkDecoration(s,p,{theme,except}).ok);if(!p)throw Error('No legal test site');return p;}
const unit=(d,id)=>functionalUnit(d.state,id),identity=(r,operation)=>({kind:r.ticket.kind,operation,requestId:r.ticket.requestId,epoch:r.ticket.epoch,sequence:r.ticket.sequence,expectedVersion:r.document.version});
async function mature(f,seconds){while(seconds>0){const n=Math.min(15,seconds);await f.save(()=>{},n);seconds-=n;}}
for(const theme of ['pixel','origami']){
test(theme+' nursery follows effective time, pause/reload/resume, harvest once without coins/personal credit',async()=>{const f=await fixture(theme),id=f.ids.c6_8;const r=await f.facility('load');assert.equal(r.document.state.inventory.shrimp,1);await mature(f,123);assert.equal(unit(await f.current(),id).elapsed,123);await f.facility('pause');await mature(f,15);assert.equal(unit(await f.other().current(theme),id).elapsed,123);await f.facility('resume');await mature(f,117);assert.equal(unit(await f.current(),id).phase,'ready');const done=await f.facility('harvest'),body={kind:'facility',operation:'harvest',requestId:done.ticket.requestId,displayId:id,expectedRevision:done.receipt.details.revision-1,day:1};
const replay=await f.other().action(theme,{...body,expectedRevision:JSON.parse(done.ticket.signature)[7]});assert(replay.replayed);assert.equal(replay.document.state.inventory.shrimp,4);assert.equal(replay.document.state.coins,0);assert.equal(replay.document.state.economy.playerGoods.shrimp||0,0);await assert.rejects(f.facility('harvest'),e=>e.code==='facility_not_ready');});
test(theme+' placement conserves personal ownership; production move retains contents; store requires empty unit',async()=>{const f=await fixture(theme),id=f.ids.c6_8;assert.equal((await f.current()).state.economy.playerGoods.c6_8,0);await f.facility('load');await mature(f,15);const before=await f.current(),p=position(before.state,'c6_8',id);await f.facility('move','c6_8',p);assert.equal(unit(await f.current(),id).elapsed,15);await assert.rejects(f.facility('store'),e=>e.code==='facility_not_ready');await f.facility('clear');assert.equal((await f.current()).state.inventory.shrimp,1);await f.facility('store');const d=await f.current();assert.equal(d.state.inventory.c6_8,2);assert.equal(d.state.economy.playerGoods.c6_8,1);assert(!d.state.functionalFacilities.units[id]);const site=position(d.state,'c6_8');const placed=await f.call('facility','place',{...site,expectedRevision:d.state.placementBook.revision});assert(placed.receipt.details.id);assert.equal(placed.document.state.inventory.c6_8,1);assert.equal(placed.document.state.economy.playerGoods.c6_8,0);});
}
test('raw-save progress, cups, location, bonuses, ledger receipts and active clock overwrite rejected',async()=>{const f=await fixture();await f.facility('load');for(const edit of[s=>s.functionalFacilities.units[f.ids.c6_8].elapsed=240,s=>s.functionalFacilities.units[f.ids.c1_9].servings=3,s=>s.placedItems[0].x+=8,s=>s.decorBonuses.fake=999,s=>s.facilityControl.activeSeconds=999,s=>delete s.resourceLedger.receipts[Object.keys(s.resourceLedger.receipts).find(k=>k.startsWith('facility:'))]])await assert.rejects(f.save(edit),e=>['facility_state_conflict','invalid_save'].includes(e.code));});
test('save clock is wall bounded, replayed once, report bounded; GET and offline never produce',async()=>{const f=await fixture();await f.facility('load');const id=f.ids.c6_8,d=await f.current();f.advance(2000);const body={state:d.state,expectedVersion:d.version,activeSeconds:15,saveId:randomUUID()},first=await f.store.save('pixel',body);assert.equal(unit(first.document,id).elapsed,2);assert((await f.other().save('pixel',body)).replayed);await assert.rejects(f.store.save('pixel',{...body,activeSeconds:14}),e=>e.code==='save_id_conflict');f.advance(999999);assert.equal(unit(await f.current(),id).elapsed,2);await f.save(()=>{},0,0);assert.equal(unit(await f.current(),id).elapsed,2);await assert.rejects(f.save(()=>{},16),e=>e.code==='facility_clock');});
test('shared reservation prevents loading and failed command has no stock/placement changes',async()=>{const f=await fixture('pixel',s=>reserveResources(s,'party:shrimp',{shrimp:2})),before=await f.current();await assert.rejects(f.facility('load'),e=>e.code==='facility_not_ready');assert.equal((await f.current()).version,before.version);await assert.rejects(f.call('facility','place',{item:'c6_8',x:0,y:0,rotation:0,expectedRevision:before.state.placementBook.revision}),e=>e.code==='facility_not_ready');assert.equal((await f.current()).state.inventory.c6_8,1);});
test('exact request replay ignores stale version, changed inputs rejected; concurrent claim settles once',async()=>{const f=await fixture(),id=f.ids.c6_8;await f.facility('load');await mature(f,240);const d=await f.current(),body={kind:'facility',operation:'harvest',requestId:randomUUID(),displayId:id,day:1,expectedRevision:d.state.functionalFacilities.revision,expectedVersion:d.version};const results=await Promise.all([f.store.action('pixel',body),f.other().action('pixel',body)]);assert.equal(results.filter(r=>r.replayed).length,1);assert.equal((await f.current()).state.inventory.shrimp,4);await assert.rejects(f.store.action('pixel',{...body,operation:'clear'}),e=>e.code==='action_id_conflict');await assert.rejects(f.facility('clear','c6_8',{expectedRevision:0}),e=>e.code==='facility_revision');});
test('tea uses real resident lease, blocks clear/move/pause; finish consumes one and canonical snapshot syncs',async()=>{const f=await fixture();await f.facility('load','c1_9');await mature(f,12);const id=f.ids.c1_9;const r=await f.call('resident','begin',{actorId:5,intent:{goal:'tea',buildingId:null,action:'eat',facilityId:id}});assert.equal(unit(r.document,id).servings,3);for(const op of['clear','move','pause'])await assert.rejects(f.facility(op,'c1_9',{x:800,y:560,rotation:0}),e=>e.code==='facility_occupied');f.advance(10000);const d=await f.store.action('pixel',identity(r,'finish'));assert.equal(unit(d.document,id).servings,2);assert.equal(unit(d.document,id).delivered,1);await f.save();assert.equal(unit(await f.other().current('pixel'),id).servings,2);await f.facility('clear','c1_9');assert.equal(unit(await f.current(),id).servings,0);});
test('drip real farm begin/finish consumes one charge; reconfigure cancels current lease with no charge',async()=>{const f=await fixture('pixel',s=>Object.assign(s.plots[2],{stage:2,crop:'wheat',growth:0})),id=f.ids.c14_6;await f.call('farm','enable');await f.facility('load','c14_6');await f.facility('configure','c14_6',{targets:[2],enabled:true});const r=await f.call('farm','begin',{actor:'facility',actorId:id,index:2,step:'water'});await assert.rejects(f.facility('store','c14_6'),e=>e.code==='facility_occupied');await f.facility('configure','c14_6',{targets:[2],enabled:false});const stopped=await f.current();assert.equal(unit(stopped,id).charges,8);assert.equal(Object.keys(stopped.actions.farm.leases).length,0);assert.equal(stopped.state.plots[2].stage,2);await f.facility('configure','c14_6',{targets:[2],enabled:true});const real=await f.call('farm','begin',{actor:'facility',actorId:id,index:2,step:'water'});await assert.rejects(f.store.action('pixel',identity(real,'finish')),e=>e.code==='action_early');f.advance(3000);const done=await f.store.action('pixel',identity(real,'finish'));assert.equal(unit(done.document,id).charges,7);assert.equal(unit(done.document,id).delivered,1);assert.equal(done.document.state.plots[2].stage,3);assert.equal(done.document.state.plots[2].growth,0);await f.save();});
test('clean spends exact inputs; import keeps in-progress legacy elapsed but removes epoch and active clock',async()=>{const f=await fixture();await f.facility('load');await mature(f,240);await f.facility('harvest');const clean=await f.facility('clean');assert.equal(unit(clean.document,f.ids.c6_8).condition,100);assert.equal(clean.document.state.inventory.seaweed,1);assert.equal(clean.document.state.inventory.sand,1);await f.facility('load');await mature(f,123);const d=await f.current(),imported=await f.store.import('pixel',{data:d,expectedVersion:d.version});assert.equal(unit(imported.document,f.ids.c6_8).elapsed,123);assert(!imported.document.actions.facility);assert(!imported.document.state.facilityControl);await f.call('facility','enable');await mature(f,117);assert.equal(unit(await f.current(),f.ids.c6_8).phase,'ready');});

test('batch cannot inherit game time from before load or paused time at resume',async()=>{const f=await fixture();f.advance(15000);await f.facility('load','c1_9');await f.save(()=>{},15,0);assert.equal(unit(await f.current(),f.ids.c1_9).elapsed,0);await f.save(()=>{},5);assert.equal(unit(await f.current(),f.ids.c1_9).elapsed,5);await f.facility('pause','c1_9');f.advance(15000);await f.facility('resume','c1_9');await f.save(()=>{},15,0);assert.equal(unit(await f.current(),f.ids.c1_9).elapsed,5);});
