import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,readFile,writeFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {randomUUID} from 'node:crypto';import {createCoCreationStore} from '../server/cocreationStore.mjs';import {CO_CREATION_EXAMPLES,validateCoCreationPack} from '../src/cocreation.js';import {craftResult} from '../src/craftGameReplay.js';import {chooseAction} from './v19-play-helpers.mjs';
const pack=()=>structuredClone(CO_CREATION_EXAMPLES[0]);
async function fixture(theme='pixel'){let now=1_800_000_000_000;const directory=await mkdtemp(join(tmpdir(),'hd-v56-')),options={directory,now:()=>now,worldExists:async(t,k)=>t===theme&&k==='island-fixture'},store=createCoCreationStore(options),current=()=>store.current(theme),call=async(operation,args={})=>store.action(theme,{operation,requestId:randomUUID(),expectedVersion:(await current()).version,...args});return{store,directory,theme,current,call,other:()=>createCoCreationStore(options),advance:ms=>now+=ms};}
async function publish(f,p=pack()){await f.call('import',{pack:p});await f.call('submit',{packageId:p.id,version:1,hash:(await f.current()).packages[p.id].versions[0].hash});const h=(await f.current()).packages[p.id].versions[0].hash;await f.call('review',{packageId:p.id,version:1,hash:h,decision:'approve',note:'目标与说明清晰，课程模板试玩可完成。'});await f.call('activate',{packageId:p.id,version:1,hash:h});return h;}
async function begin(f,h){return f.call('trial_begin',{packageId:pack().id,version:1,hash:h,challengeId:'welcome-tea',worldKey:'island-fixture'});}
test('strict declarative packs reject executable fields, bad IDs, links, recipes, limits and ambiguous duplicates',()=>{assert.equal(validateCoCreationPack(pack()).challenges[0].recipeId,'recipe_tea');for(const change of[p=>p.javascript='eval(1)',p=>p.assets=['https://remote/image'],p=>p.id='../escape',p=>p.source='file:///secret',p=>p.source='https://user:password@example.com',p=>p.themeNotes.extra='x',p=>p.challenges[0].recipeId='invalid',p=>p.challenges[0].minQuality=101,p=>p.challenges[0].seed=0,p=>p.challenges.push(structuredClone(p.challenges[0])),p=>p.challenges[0].hints=Array(7).fill('提示'),p=>p.title='\0bad']){const p=pack();change(p);assert.throws(()=>validateCoCreationPack(p),e=>e.code==='cocreation_invalid');}});
for(const theme of ['pixel','origami']){
test(theme+' import-submit-review-fork-republish and rollback preserves frozen versions and attribution',async()=>{const f=await fixture(theme),h=await publish(f),d=await f.current();assert.equal(d.packages[pack().id].active.hash,h);await assert.rejects(f.call('submit',{packageId:pack().id,version:1,hash:h}),e=>e.code==='cocreation_frozen');const p=pack();p.title='改进后的潮汐茶席';p.challenges[0].seed++;const edit=await f.call('edit',{packageId:p.id,pack:p});assert.equal(edit.selection.version,2);assert.equal(edit.document.packages[p.id].versions[0].hash,h);const h2=edit.document.packages[p.id].versions[1].hash;await f.call('submit',{packageId:p.id,version:2,hash:h2});await assert.rejects(f.call('review',{packageId:p.id,version:2,hash:h,decision:'approve',note:'明确通过'}),e=>e.code==='cocreation_hash');await f.call('review',{packageId:p.id,version:2,hash:h2,decision:'request_changes',note:'请加入具体的新手操作提示。'});p.challenges[0].hints.push('先观察再点，不用连续翻动。');await f.call('edit',{packageId:p.id,pack:p});const h3=(await f.current()).packages[p.id].versions[1].hash;assert.notEqual(h3,h2);await f.call('submit',{packageId:p.id,version:2,hash:h3});await f.call('review',{packageId:p.id,version:2,hash:h3,decision:'approve',note:'修改提示后审核通过。'});await assert.rejects(f.call('rollback',{packageId:p.id,version:2,hash:h3}),e=>e.code==='cocreation_not_approved');await f.call('activate',{packageId:p.id,version:2,hash:h3});await f.call('rollback',{packageId:p.id,version:1,hash:h});const exported=await f.other().export(theme,p.id,1);assert.deepEqual(exported.pack,validateCoCreationPack(pack()));assert.equal(exported.sha256,h);assert.equal((await f.current()).packages[p.id].active.version,1);});
test(theme+' repeated uncertain commands and concurrent windows settle once; changed requests and stale CAS fail',async()=>{const f=await fixture(theme),d=await f.current(),i={operation:'import',pack:pack(),requestId:randomUUID(),expectedVersion:d.version},rs=await Promise.all([f.store.action(theme,i),f.other().action(theme,i)]);assert.equal(rs.filter(r=>r.replayed).length,1);assert.equal((await f.current()).revision,1);await assert.rejects(f.store.action(theme,{...i,pack:{...pack(),title:'不同的海岛作品'}}),e=>e.code==='cocreation_id_conflict');await assert.rejects(f.call('edit',{packageId:pack().id,pack:pack(),expectedVersion:d.version}),e=>e.code==='cocreation_version');assert.equal((await f.current()).revision,1);});
test(theme+' live replay checkpoints resume immutable author version and finish once; practice never calls inventory adapter',async()=>{const f=await fixture(theme),h=await publish(f);await assert.rejects(f.call('trial_begin',{packageId:pack().id,version:1,hash:h,challengeId:'welcome-tea',worldKey:'another-island'}),e=>e.code==='cocreation_world');await begin(f,h);let t=(await f.current()).trial;await assert.rejects(f.call('trial_finish',{runId:t.runId}),e=>e.code==='cocreation_unfinished');await assert.rejects(f.call('trial_checkpoint',{runId:t.runId,batch:1,events:[{result:{quality:100}}]}),e=>e.code==='cocreation_input');await assert.rejects(f.call('trial_checkpoint',{runId:t.runId,batch:4,events:[]}),e=>e.code==='cocreation_batch');const before=(await f.current()).version;await assert.rejects(f.call('trial_checkpoint',{runId:t.runId,batch:1,events:Array(100).fill({dt:.05})}),e=>e.code==='cocreation_clock');assert.equal((await f.current()).version,before);
 for(let step=0;step<2000&&!craftResult(t.game);step++){const events=[],s=t.game.state,a=chooseAction(s);if(a)events.push({action:a});events.push({dt:.05});f.advance(50);const r=await f.call('trial_checkpoint',{runId:t.runId,batch:t.nextBatch,events});t=r.ticket;if(step===50){const restart=await f.other().current(theme);assert.deepEqual(restart.trial,t);const p=pack();p.title='练习时另一草稿';await f.call('edit',{packageId:p.id,pack:p});assert.equal((await f.current()).trial.packageHash,h);}}
 assert(craftResult(t.game)?.passed);const d=await f.current(),i={operation:'trial_finish',runId:t.runId,requestId:randomUUID(),expectedVersion:d.version},r=await f.store.action(theme,i);assert.equal(r.receipt.outcome,'passed');assert.equal(r.receipt.author,pack().author);assert.equal(r.receipt.packageHash,h);assert((await f.other().action(theme,i)).replayed);assert.equal((await f.current()).results.length,1);assert.equal((await f.current()).trial,null);assert(!Object.hasOwn(await f.current(),'inventory'));assert(!Object.hasOwn(await f.current(),'coins'));assert.equal((await f.other().export(theme,pack().id,1)).sha256,h);
});
}
test('cancel, expiry, structural corruption and double-theme separation preserve existing files',async()=>{const f=await fixture(),h=await publish(f);await begin(f,h);const id=(await f.current()).trial.runId;f.advance(86400001);await assert.rejects(f.call('trial_checkpoint',{runId:id,batch:1,events:[]}),e=>e.code==='cocreation_expired');await f.call('trial_cancel',{runId:id});assert.equal((await f.current()).results[0].outcome,'cancelled');assert.equal(Object.keys((await f.store.current('origami')).packages).length,0);const file=join(f.store.directory,'pixel/current.json'),bytes=await readFile(file);const doc=JSON.parse(bytes);doc.packages[pack().id].versions[0].pack.title='篡改';await writeFile(file,JSON.stringify(doc));await assert.rejects(f.current(),e=>e.code==='cocreation_corrupt');assert.equal(JSON.parse(await readFile(file)).packages[pack().id].versions[0].pack.title,'篡改');});

test('changed island identity rejects old checkpoint and finish, while explicit cancel remains available',async()=>{const f=await fixture(),h=await publish(f);await begin(f,h);const d=await f.current(),changed=createCoCreationStore({directory:f.directory,worldExists:async()=>false});for(const operation of ['trial_checkpoint','trial_finish'])await assert.rejects(changed.action('pixel',{operation,runId:d.trial.runId,batch:1,events:[],expectedVersion:d.version,requestId:randomUUID()}),e=>e.code==='cocreation_world');const r=await changed.action('pixel',{operation:'trial_cancel',runId:d.trial.runId,expectedVersion:d.version,requestId:randomUUID()});assert.equal(r.receipt.outcome,'cancelled');});
