import test from 'node:test';import assert from 'node:assert/strict';
import {CROPS,FARM_LAYOUTS,cropInfo,hydrateCrops,tickCrops,harvestPlot,insidePlot,plotPoint,farmWalkable} from '../src/farming.js';
import {createState,findPath} from '../src/world.js';import {roomWalkable} from '../src/rooms.js';
import {roomSpots,acquireRoomSpot,promoteRoomSpot,releaseRoomGroup,releaseRoomSpot,inspectRoomClaims} from '../src/sceneOccupancy.js';import {ROOM_GAMES,gameResult} from '../src/roomGames.js';import {directionIndex,facingIndex} from '../src/directions.js';
test('crop durations, exact maturity, real yield and save migration',()=>{for(const [id,c] of Object.entries(CROPS)){const s=createState();hydrateCrops(s);const p=s.plots[0];p.crop=id;p.stage=3;assert.ok(c.seconds>=180);tickCrops(s,c.seconds-1);assert.equal(p.stage,3);assert.equal(tickCrops(s,1).length,1);assert.equal(p.stage,4);const seed=s.inventory.seed;const before=s.inventory[c.item]||0;assert.equal(harvestPlot(s,0).amount,c.yield);assert.equal(s.inventory[c.item],before+c.yield);assert.equal(s.inventory.seed,seed+1);assert.equal(harvestPlot(s,0),null)}const s=createState();hydrateCrops(s);assert.equal(cropInfo(s.plots[0]).name,'小麦')});
test('plants stay on painted soil and all beds have reachable walking entries',()=>{for(const theme of ['pixel','origami'])for(const q of FARM_LAYOUTS[theme]){for(let row=0;row<3;row++)for(let col=0;col<5;col++)assert.ok(insidePlot(q,plotPoint(q,.15+col*.175,.25+row*.27)));assert.ok(farmWalkable(theme,q.entry.x,q.entry.y));assert.ok(findPath({x:500,y:545},q.entry,(x,y)=>farmWalkable(theme,x,y),20).length>0,theme+' plot '+q.id)}});
test('shared rooms allocate reachable separated work, queue and visitor positions',()=>{for(let id=0;id<25;id++){releaseRoomGroup('qa-');const points=roomSpots(id);assert.ok(points.length>=4,'room '+id);for(const p of points)assert.ok((Math.hypot(p.x-500,p.y-585)<30||findPath({x:500,y:585},p,(x,y)=>roomWalkable(id,x,y),20).length>0),'path '+id+JSON.stringify(p));const work=acquireRoomSpot(id,'qa-worker','work');assert.equal(work.role,'work');assert.equal(acquireRoomSpot(id,'qa-worker2','work').role,'queue');acquireRoomSpot(id,'qa-guest','visitor');for(const a of inspectRoomClaims())for(const b of inspectRoomClaims())if(a.token!==b.token)assert.ok(Math.hypot(a.point.x-b.point.x,a.point.y-b.point.y)>66);releaseRoomSpot('qa-worker');assert.equal(promoteRoomSpot('qa-worker2').role,'work')}releaseRoomGroup('qa-')});
test('all 25 rooms have independent playable objectives and failures do not pass',()=>{assert.equal(new Set(ROOM_GAMES.map(g=>g.title)).size,25);assert.ok(new Set(ROOM_GAMES.map(g=>g.kind)).size>=15);for(const g of ROOM_GAMES){assert.equal(gameResult(g,0,4).passed,false);assert.equal(gameResult(g,4,4).quality,100)}});
test('eight headings preserve anatomy and hysteresis avoids angle chatter',()=>{for(let i=0;i<8;i++)assert.equal(directionIndex(Math.PI/2+i*Math.PI/4),i);const a={direction:0};assert.equal(facingIndex(a),6);a.direction=Math.PI/8+.02;assert.equal(facingIndex(a),6);a.direction=Math.PI/8+.1;assert.equal(facingIndex(a),7);a.direction=Math.PI/2;assert.equal(facingIndex(a),0)});
