import {chromium} from 'playwright-core';import assert from 'node:assert/strict';import {writeFile} from 'node:fs/promises';import {ROOM_GAMES} from '../src/roomGames.js';import {ROOMS} from '../src/rooms.js';
const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,args:['--no-sandbox','--disable-background-timer-throttling','--disable-renderer-backgrounding','--disable-backgrounding-occluded-windows']});
async function range(el,value){await el.focus();await el.press('Home');const min=Number(await el.getAttribute('min'))||0;for(let i=min;i<value;i++)await el.press('ArrowRight')}
const results=await Promise.all(['pixel','origami'].map(async theme=>{const page=await browser.newPage({viewport:{width:1440,height:900}}),r={theme,rooms:[],errors:[],assetErrors:[]};page.on('pageerror',e=>r.errors.push(e.message));page.on('response',res=>{if(res.url().includes('/assets/')&&res.status()>=400)r.assetErrors.push(res.url())});await page.addInitScript(()=>{const t=location.port==='4173'?'pixel':'origami';localStorage.setItem('hyper-dimension-'+t+'-v3',JSON.stringify({inventory:Object.fromEntries(['wood','stone','seed','wheat','ore','herb','fish','lantern','tea','firework','meal','bouquet','outfit','remedy','pottery','rod','bread','painting','tomato','pumpkin'].map(x=>[x,99])),player:{x:781,y:518}}))});
for(const g of ROOM_GAMES){await page.goto(`http://127.0.0.1:${theme==='pixel'?4173:4174}/?qa=1&room=${g.id}&rev=resident-v6`);await page.waitForTimeout(500);const f=ROOMS[g.id].primary,scale=1.44;await page.mouse.click((f.x+f.w/2)*scale,(f.y+f.h/2)*scale+(900-660*scale)/2);await page.locator('.room-game').waitFor({timeout:35000});assert.equal(await page.locator('.room-game').getAttribute('data-game-id'),String(g.id));
 if(['timing','rhythm'].includes(g.kind)){for(let n=0;n<g.rounds.length;n++){await page.waitForFunction(()=>{const g=window.islandInspect().roomGame;const v=(Math.sin(g.t*2.8-Math.PI/2)+1)/2;return v>.40&&v<.46&&Math.cos(g.t*2.8-Math.PI/2)>0});await page.keyboard.press('Space');await page.waitForTimeout(240)}}
 else if(g.kind==='sequence'){await page.getByRole('button',{name:'我记住了 · 开始',exact:true}).click();for(const step of g.steps)await page.getByRole('button',{name:step,exact:true}).click()}
 else if(g.kind==='sort'){for(let i=0;i<g.items.length;i++){await page.locator('[data-item="'+i+'"]').click();await page.getByRole('button',{name:g.bins[g.items[i][1]],exact:true}).click()}}
 else if(g.kind==='balance'){for(let i=0;i<g.controls.length;i++)await range(page.locator('.game-controls input').nth(i),Math.round((g.controls[i][1]+g.controls[i][2])/2));await page.getByRole('button',{name:'确认状态',exact:true}).click()}
 else if(g.kind==='connect'){for(const name of g.steps)await page.getByRole('button',{name,exact:true}).click()}
 else if(g.kind==='dial'){let angle=0;for(const target of g.targets){while(angle!==target){await page.getByRole('button',{name:'顺时针 +15°',exact:true}).click();angle=(angle+15)%360}await page.getByRole('button',{name:'锁定航标',exact:true}).click()}}
 else if(g.kind==='focus'){const box=await page.locator('#photoSubject').boundingBox();await page.mouse.click(box.x+box.width/2,box.y+box.height/2);await range(page.locator('#photoFocus'),60);await page.getByRole('button',{name:'按下快门',exact:true}).click()}
 const result=await page.evaluate(()=>window.islandInspect().roomGame);assert.ok(result.done);assert.ok(result.score>0);assert.equal(await page.locator('#gameFinish').textContent(),'领取成果');if([0,5,6,19,23].includes(g.id))await page.screenshot({path:`v6-${theme}-game-${g.id}-screen.png`});await page.locator('#gameFinish').click();await page.waitForTimeout(2300);assert.equal(await page.locator('.modal').count(),0);const history=await page.evaluate(()=>window.islandInspect().roomHistory);assert.equal(history[g.id].best,Math.round(55+45*result.score/(g.steps?.length||g.items?.length||g.rounds?.length||g.targets?.length||(g.kind==='balance'?3:1))));r.rooms.push({id:g.id,title:g.title,kind:g.kind,score:result.score,plays:history[g.id].plays});await writeFile('v6-game-'+theme+'-progress.json',JSON.stringify(r,null,2));console.log(theme+' room '+g.id+' PASS')}
 await page.goto(`http://127.0.0.1:${theme==='pixel'?4173:4174}/?qa=1&rev=resident-v6`);await page.waitForTimeout(1000);await page.locator('#stewardBtn').click();assert.equal(await page.locator('.half-portrait').count(),1);assert.equal(await page.locator('#hermesSend').count(),1);await page.screenshot({path:`v6-${theme}-hermes-screen.png`});await page.setViewportSize({width:640,height:780});await page.screenshot({path:`v6-${theme}-resident-mobile-screen.png`});r.overflow=await page.evaluate(()=>[...document.querySelectorAll('.conversation-body,.resident-facts dd,.portrait-caption')].some(e=>e.scrollWidth>e.clientWidth+1));assert.equal(r.overflow,false);await page.locator('#closeModal').click();const assets=await page.evaluate(()=>window.islandInspect().characterAssets);for(const packs of Object.values(assets))for(const p of packs)assert.equal(p.ready,true);assert.deepEqual(r.errors,[]);assert.deepEqual(r.assetErrors,[]);await page.close();return r}));await writeFile('v6-game-qa.json',JSON.stringify(results,null,2));await browser.close();console.log('PASS all 50 room flows, adult resident cards and mobile wrapping');
