import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir} from 'node:fs/promises';import {resolve} from 'node:path';import {randomUUID} from 'node:crypto';import {createLanHttpServer} from '../server/lanServer.mjs';import {invitation} from '../server/lanTravelParty.mjs';
async function fixture(theme){await mkdir('qa/v64',{recursive:true});let time=1800000000000;const directory=await mkdtemp(resolve('qa/v64/authority-')),s=await createLanHttpServer({directory,port:0,enrollmentKey:'PRESENCE-FIXTURE',now:()=>time}),accounts=[];for(let n=0;n<2;n++){const a=await s.identities.register({login:'home_'+n,password:'fixture-password',name:'原岛岛主'+n,islandName:'原岛暂停'+n,avatar:'male_'+n,theme});await s.tenants.open(a.token,theme,{});accounts.push(a);}const call=(n,operation,args={})=>s.identities.action(accounts[n].token,{operation,requestId:randomUUID(),...args});return{s,accounts,call,theme,directory,advance:ms=>time+=ms};}
for(const theme of ['pixel','origami']){
test(theme+' travel blocks original-island writes, reset and work until explicit return; reads and escrow still operate',async()=>{const f=await fixture(theme);try{const contexts=await Promise.all(f.accounts.map(a=>f.s.tenants.get(a.token))),before=await Promise.all(contexts.map(c=>c.saves.current(theme))),r=await f.call(0,'room_create',{title:'原岛唯一生产验证',maxPlayers:2});await f.call(1,'travel_invite',{npcId:0});await f.call(1,'room_join',{code:r.view.room.code});
for(let n=0;n<2;n++){const c=contexts[n];for(const method of ['open','save','action','restore','import','restart'])await assert.rejects(c.saves[method](theme,{state:before[n].state,expectedVersion:before[n].version,operation:'begin',requestId:randomUUID()}),e=>e.code==='lan_travel_active',method+' must not bypass travel');assert.equal((await c.saves.current(theme)).version,before[n].version);await c.saves.backups(theme);}
f.advance(60000);const guest=await f.s.identities.view(f.accounts[1].token);assert.equal(guest.room.members.find(m=>m.id===f.accounts[1].view.me.id).travel.members[0].kind,'hermes');assert.equal((await contexts[1].saves.current(theme)).version,before[1].version);
const presence=await f.s.identities.presence(f.accounts[1].token);assert.equal(presence.roomId,r.view.room.id);
await f.s.identities.logout(f.accounts[1].token);const login=await f.s.identities.login({login:'home_1',password:'fixture-password'});f.accounts[1].token=login.token;assert(login.view.room);assert.equal((await f.s.identities.presence(login.token)).roomId,presence.roomId);
await f.call(1,'room_leave',{roomId:guest.room.id,expectedRevision:guest.room.revision});assert.equal(await f.s.identities.presence(login.token),null);await contexts[1].saves.save(theme,{state:before[1].state,expectedVersion:before[1].version});const host=await f.s.identities.view(f.accounts[0].token);await f.call(0,'room_close',{roomId:host.room.id,expectedRevision:host.room.revision});await contexts[0].saves.save(theme,{state:before[0].state,expectedVersion:before[0].version});}finally{await f.s.close();}});
test(theme+' join and home writes serialize; no lease can be acquired in the departure gap',async()=>{const f=await fixture(theme);try{const room=await f.call(0,'room_create',{title:'并发出行核验',maxPlayers:2}),a=f.accounts[1],c=await f.s.tenants.get(a.token);let entered,release;const start=new Promise(r=>entered=r),hold=new Promise(r=>release=r);const guarded=f.s.identities.withHomeIsland(a.view.me.id,theme,async()=>{entered();await hold;});await start;let joined=false;const join=f.call(1,'room_join',{code:room.view.room.code}).then(r=>{joined=true;return r;});await new Promise(r=>setTimeout(r,100));assert.equal(joined,false);release();await guarded;await join;await assert.rejects(c.saves.action(theme,{kind:'resident',operation:'enable',requestId:randomUUID()}),e=>e.code==='lan_travel_active');}finally{await f.s.close();}});
}
test('HTTP replay of a successful room join remains valid while away; /play resumes the room',async()=>{const f=await fixture('pixel');try{const r=await f.call(0,'room_create',{title:'断线重发核验',maxPlayers:2}),base='http://127.0.0.1:'+f.s.port,a=f.accounts[1],headers={'Content-Type':'application/json',Cookie:'hd_lan_session='+a.token,'X-HD-Island':a.view.me.id},body={operation:'room_join',requestId:randomUUID(),code:r.view.room.code};for(let n=0;n<2;n++){const res=await fetch(base+'/api/lan/action',{method:'POST',headers,body:JSON.stringify(body)}),data=await res.json();assert.equal(res.status,200,JSON.stringify(data));assert.equal(data.replayed,!!n);}const p=await fetch(base+'/play',{headers,redirect:'manual'});assert.equal(p.status,303);assert.equal(p.headers.get('location'),'/?resume=travel');const d=(await f.s.tenants.get(a.token));const before=await d.saves.current('pixel'),res=await fetch(base+'/api/saves/pixel/save',{method:'POST',headers,body:JSON.stringify({state:before.state,expectedVersion:before.version})});assert.equal(res.status,409);assert.equal((await res.json()).code,'lan_travel_active');assert.equal((await d.saves.current('pixel')).version,before.version);}finally{await f.s.close();}});
test('active farm, mine and due social commitments refuse invitations without changing the source',async()=>{const f=await fixture('pixel');try{const c=await f.s.tenants.get(f.accounts[1].token),doc=await c.saves.current('pixel'),a=f.accounts[1].view.me;for(const field of ['farmControl','mineControl','residentControl']){const d=structuredClone(doc);d.state[field]={leases:[{actorId:0}]};assert.equal(invitation(a,d,0).accepted,false);}const d=structuredClone(doc);d.state.residentStories={episodes:[{people:[0,1],status:'scheduled',dueDay:d.state.day}]};assert.equal(invitation(a,d,0).accepted,false);assert.equal(invitation(a,doc,0).accepted,true);}finally{await f.s.close();}});
