import test from 'node:test';import assert from 'node:assert/strict';import {mkdir,mkdtemp} from 'node:fs/promises';import {resolve} from 'node:path';
import {createRecruitmentStore,recruitmentContext,validateRecruitmentRun} from '../server/recruitmentStore.mjs';import {createZeroState} from '../src/freshStart.js';import {hydrateTown} from '../src/townSimulation.js';import {createProject} from '../src/projectPlans.js';import {RECRUIT_CANDIDATES,candidateStepAllowed} from '../src/recruitmentCatalog.js';
async function fixture(theme='pixel'){await mkdir('qa/v71',{recursive:true});const directory=await mkdtemp(resolve('qa/v71/store-')),store=createRecruitmentStore({directory}),state=hydrateTown(createZeroState());state.saveSlot='test-world-'+theme;state.coins=30;assert(createProject(state,{id:'supplies',title:'欢迎朋友到岛',targets:{lantern:1,bread:1,rose:1,outfit:1}}).ok);return{directory,store,doc:{theme,state},theme};}
function run(context,steps=context.steps.slice(0,1).map(s=>s.id)){return{source:'hermes',model:'deepseek-flash',parent:{id:'hd-parent-test',status:'completed',tools:['recruitment_delegate']},child:{id:'hd-child-test',parentId:'hd-parent-test',status:'completed',tools:['recruitment_take_step'],acceptedSteps:steps},events:[{actor:'parent',tool:'recruitment_delegate',status:'done'},{actor:'child',tool:'recruitment_take_step',status:'done'}]};}
test('each catalog candidate exposes only real matching work; wrong building steps fail proof validation',async()=>{
 const f=await fixture(),all=recruitmentContext(f.doc,'supplies');assert.equal(RECRUIT_CANDIDATES.length,4);assert.equal(new Set(RECRUIT_CANDIDATES.map(c=>c.appearance)).size,4);
 for(const c of RECRUIT_CANDIDATES){const context=recruitmentContext(f.doc,'supplies',c);assert.equal(context.candidate.id,c.id);assert(context.steps.length);assert(context.steps.every(s=>candidateStepAllowed(c,s)));const forbidden=all.steps.find(s=>!candidateStepAllowed(c,s));if(forbidden)assert.throws(()=>validateRecruitmentRun(run(context,[forbidden.id]),context),e=>e.code==='recruitment_evidence');}
 const miner=recruitmentContext(f.doc,'supplies',RECRUIT_CANDIDATES.find(c=>c.id==='yan'));assert(!miner.steps.some(s=>s.buildingId===4||s.buildingId===17));assert(miner.steps.some(s=>s.goal==='mine'));
});
for(const theme of ['pixel','origami'])test(theme+': selected candidate survives retries, activation and store restart; replay cannot change person',async()=>{
 const f=await fixture(theme),input={requestId:'candidate-hire-1',projectId:'supplies',candidateId:'yan'};const start=await f.store.start(theme,f.doc,input);assert.equal(start.contract.profile.name,'岩川');assert.equal(start.contract.context.candidate.id,'yan');
 await assert.rejects(f.store.start(theme,f.doc,{...input,candidateId:'mai'}),e=>e.code==='recruitment_conflict');await f.store.complete(theme,input.requestId,1,null,'injected interrupted worker');const retried=await f.store.retry(theme,f.doc,input.requestId);assert.equal(retried.contract.context.candidate.id,'yan');await f.store.complete(theme,input.requestId,2,run(retried.contract.context));
 const active=await f.store.activate(theme,f.doc,input.requestId);assert.equal(active.contract.profile.appearance,'male_1');assert(active.contract.agreedSteps.length);assert.equal(active.contract.candidateId,'yan');const reopened=await createRecruitmentStore({directory:f.directory}).list(theme,f.doc);assert.equal(reopened.active.profile.name,'岩川');assert.equal(reopened.rules.temporary,1);await assert.rejects(f.store.start(theme,f.doc,{...input,requestId:'other-hire',candidateId:'he'}),e=>e.code==='recruitment_full');
});
test('custom candidate creation is bounded, idempotent, world scoped, does not charge or expand tools; contract snapshots retain identity',async()=>{
 const f=await fixture(),input={name:'青石',roleId:'yan',appearance:'male_2',personality:'冷静细致，会先核对物资',backstory:'沿群岛寻找矿石与木材的旅人'},requestId='custom-profile-1';
 const made=await f.store.candidate('pixel',f.doc,{requestId,input});assert.equal(made.candidate.id,'custom-'+requestId);assert.deepEqual(made.candidate.workBuildings,RECRUIT_CANDIDATES.find(c=>c.id==='yan').workBuildings);assert.equal(f.doc.state.coins,30);
 assert((await f.store.candidate('pixel',f.doc,{requestId,input})).replayed);await assert.rejects(f.store.candidate('pixel',f.doc,{requestId,input:{...input,name:'替换'}}),e=>e.code==='recruitment_conflict');
 for(const patch of [{appearance:'unverified-art'},{roleId:'root'},{tools:['terminal']},{name:'x'.repeat(17)}])await assert.rejects(f.store.candidate('pixel',f.doc,{requestId:'bad-custom-'+Object.keys(patch)[0],input:{...input,...patch}}));
 for(let n=2;n<=3;n++)await f.store.candidate('pixel',f.doc,{requestId:'custom-profile-'+n,input:{...input,name:'朋友'+n}});
 await assert.rejects(f.store.candidate('pixel',f.doc,{requestId:'custom-profile-4',input}),e=>e.code==='recruitment_candidate_limit');assert.equal((await f.store.list('pixel',f.doc)).candidates.length,7);
 await assert.rejects(f.store.start('origami',{theme:'origami',state:{...f.doc.state,saveSlot:'other-world'}},{requestId:'other-world-hire',projectId:'supplies',candidateId:made.candidate.id}),e=>e.code==='recruitment_candidate');
 const hired=await f.store.start('pixel',f.doc,{requestId:'custom-real-hire',projectId:'supplies',candidateId:made.candidate.id});assert.equal(hired.contract.context.candidate.name,'青石');assert.equal(hired.contract.profile.appearance,'male_2');
 const next={theme:'pixel',state:{...f.doc.state,saveSlot:'reset-world'}};assert.equal((await f.store.list('pixel',next)).candidates.length,4);assert.equal((await f.store.peek('pixel','custom-real-hire')).profile.name,'青石');
});
