import test from 'node:test';import assert from 'node:assert/strict';import {mkdir,mkdtemp} from 'node:fs/promises';import {resolve} from 'node:path';import {randomUUID} from 'node:crypto';
import {createRecruitmentStore} from '../server/recruitmentStore.mjs';import {createRecruitmentService} from '../server/recruitmentService.mjs';import {createZeroState} from '../src/freshStart.js';import {hydrateTown} from '../src/townSimulation.js';import {createProject} from '../src/projectPlans.js';import {proof,finishVisit} from './v72-recruitment-fixture.mjs';
const profile={name:'青石',roleId:'yan',appearance:'male_2',personality:'细致冷静',backstory:'沿着群岛采风的匠人'};
async function fixture(theme='pixel'){await mkdir('qa/v72',{recursive:true});const directory=await mkdtemp(resolve('qa/v72/store-')),store=createRecruitmentStore({directory}),state=hydrateTown(createZeroState());state.saveSlot='lifecycle-'+theme;state.coins=40;assert(createProject(state,{id:'first-plan',title:'码头木料',targets:{wood:6}}).ok);const doc={state,theme},created=await store.candidate(theme,doc,{requestId:'candidate-life-1',input:profile});return{directory,store,doc,theme,id:created.candidate.id};}
const manage=(f,action,version,input,requestId=randomUUID())=>f.store.candidate_manage(f.theme,f.doc,{id:f.id,action,expectedVersion:version,input,requestId});
test('edit uses CAS and durable replay; creation replay survives edits; archive frees quota and restore checks capacity',async()=>{
 const f=await fixture(),input={...profile,name:'新青石',roleId:'he',appearance:'female_1'},id=randomUUID();const edited=await manage(f,'edit',1,input,id);assert.equal(edited.version,2);assert.equal(edited.candidate.roleId,'he');assert((await manage(f,'edit',1,input,id)).replayed);await assert.rejects(manage(f,'edit',1,profile),e=>e.code==='recruitment_conflict');await assert.rejects(manage(f,'edit',1,profile,id),e=>e.code==='recruitment_conflict');
 assert((await f.store.candidate(f.theme,f.doc,{requestId:'candidate-life-1',input:profile})).replayed);
 for(let i=2;i<=3;i++)await f.store.candidate(f.theme,f.doc,{requestId:'candidate-life-'+i,input:profile});
 await manage(f,'archive',2);await assert.rejects(f.store.start(f.theme,f.doc,{requestId:'archived-hire',projectId:'first-plan',candidateId:f.id}),e=>e.code==='recruitment_candidate');assert.equal((await f.store.list(f.theme,f.doc)).candidates.length,6);await f.store.candidate(f.theme,f.doc,{requestId:'candidate-life-4',input:profile});
 await assert.rejects(manage(f,'restore',3),e=>e.code==='recruitment_candidate_limit');await f.store.candidate_manage(f.theme,f.doc,{id:'custom-candidate-life-4',requestId:randomUUID(),action:'archive',expectedVersion:1});const restored=await manage(f,'restore',3);assert.equal(restored.version,4);assert(!restored.archived);
 const again=await createRecruitmentStore({directory:f.directory}).list(f.theme,f.doc);assert.equal(again.candidateRecords.find(c=>c.profile.id===f.id).edits.length,3);assert.equal(again.candidates.length,7);assert.equal(f.doc.state.coins,40);
 await assert.rejects(f.store.candidate_manage('origami',{...f.doc,theme:'origami'},{id:f.id,requestId:randomUUID(),action:'archive',expectedVersion:4}),e=>e.code==='recruitment_candidate');
});
test('candidate management cannot change planning/active identity; archived candidates cannot be hired',async()=>{
 const f=await fixture(),c=(await f.store.start(f.theme,f.doc,{requestId:'live-hire-one',projectId:'first-plan',candidateId:f.id})).contract;
 await assert.rejects(manage(f,'edit',1,{...profile,name:'替换'}),e=>e.code==='recruitment_candidate_busy');await f.store.complete(f.theme,c.id,1,proof(c.context));await f.store.activate(f.theme,f.doc,c.id);await assert.rejects(manage(f,'archive',1),e=>e.code==='recruitment_candidate_busy');
 const old=JSON.stringify(await f.store.peek(f.theme,c.id));await assert.rejects(f.store.start(f.theme,f.doc,{requestId:'invalid-recall',projectId:'first-plan',candidateId:f.id,recallId:c.id}));assert.equal(JSON.stringify(await f.store.peek(f.theme,c.id)),old);
});
for(const theme of ['pixel','origami'])test(theme+': a finished visit recalls exact previous person, creates new real work and separate wages once',async()=>{
 const f=await fixture(theme);let c=(await f.store.start(theme,f.doc,{requestId:'first-hire',projectId:'first-plan',candidateId:f.id})).contract;await f.store.complete(theme,c.id,1,proof(c.context));c=(await f.store.activate(theme,f.doc,c.id)).contract;const previous=await finishVisit(f.store,f.doc,c);assert.equal(previous.delivery.delivered,6);assert.equal(previous.delivery.fee,8);
 const old=JSON.stringify(await f.store.peek(theme,c.id));await manage(f,'edit',1,{...profile,name:'候选新名字',appearance:'female_3',roleId:'he'});assert.equal(JSON.stringify(await f.store.peek(theme,c.id)),old);assert(createProject(f.doc.state,{id:'second-plan',title:'新的栈桥木料',targets:{wood:10}}).ok);
 let runs=0,lastContext;const service=createRecruitmentService({directory:f.directory,store:f.store,saves:{current:async()=>f.doc},run:async ctx=>{runs++;lastContext=ctx;return proof(ctx);},cancel:async()=>{}});
 try{const input={id:c.id,requestId:'second-hire',projectId:'second-plan'},a=await service.recall(theme,input);assert.equal(a.contract.profile.name,'青石');assert.equal(a.contract.profile.appearance,'male_2');assert.equal(a.contract.previousContractId,c.id);assert((await service.recall(theme,input)).replayed);for(let i=0;i<100;i++){const s=await service.status(theme);if(s.active?.phase==='available')break;await new Promise(r=>setTimeout(r,10));}
 assert.equal(runs,1);assert.equal(lastContext.previousVisit.delivered,6);assert.equal(lastContext.previousVisit.fee,8);const active=(await service.activate(theme,{id:input.requestId})).contract;assert.notEqual(active.runs[0].parent.id,c.runs[0].parent.id);await finishVisit(f.store,f.doc,active);assert.equal(f.doc.state.inventory.wood,16);assert.equal(f.doc.state.coins,24);assert.equal(f.doc.state.economy.cashLedger.filter(r=>r.category==='recruitment').length,2);assert.equal(JSON.stringify(await f.store.peek(theme,c.id)),old);
 const replay=await service.recall(theme,input);assert(replay.replayed);assert.equal(runs,1);
 }finally{await service.close();}
});
