import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,writeFile,readFile,symlink} from 'node:fs/promises';import {resolve,join} from 'node:path';import {sha256,saveJson,verifyPayload} from '../tools/releaseCommon.mjs';import {portableProvenance,buildLocalRelease} from '../tools/build-local-release.mjs';
async function fixture(){const base=resolve('qa/v80/verification-fixtures');await mkdir(base,{recursive:true});const root=await mkdtemp(join(base,'package-'));await mkdir(join(root,'src'));await writeFile(join(root,'src/game.js'),'export const ready=true;\n');return root;}
async function seal(root,records){const files=records||[{path:'src/game.js',bytes:24,sha256:sha256(await readFile(join(root,'src/game.js')))}];if(!records)files[0].bytes=(await readFile(join(root,'src/game.js'))).length;await saveJson(join(root,'release-manifest.json'),{schema:80,release:'verification-fixture',target:'windows-x64',files});await writeFile(join(root,'release-manifest.sha256'),sha256(await readFile(join(root,'release-manifest.json'))));}
test('release payload verifies every original byte and rejects changed code',async()=>{const root=await fixture();await seal(root);assert.equal((await verifyPayload(root,{pristine:true})).verified,true);await writeFile(join(root,'src/game.js'),'export const ready=false;\n');await assert.rejects(verifyPayload(root),/payload changed/);});
test('clean release rejects an accidentally packaged credential file',async()=>{const root=await fixture();await seal(root);await writeFile(join(root,'.env.local'),'DEEPSEEK_API_KEY=fixture-value');await assert.rejects(verifyPayload(root,{pristine:true}),/Unexpected file/);assert.equal((await verifyPayload(root)).verified,true);});
test('checksums are integrity evidence and damaged manifest is rejected',async()=>{const root=await fixture();await seal(root);await writeFile(join(root,'release-manifest.json'),'{}');await assert.rejects(verifyPayload(root),/checksum mismatch/);});
test('even a checksummed manifest rejects traversal, duplicate and invalid size records',async()=>{const root=await fixture();for(const records of [[{path:'../outside',bytes:1,sha256:'0'.repeat(64)}],[{path:'src/game.js',bytes:-1,sha256:'0'.repeat(64)}],[{path:'src/game.js',bytes:1,sha256:'0'.repeat(64)},{path:'src/game.js',bytes:1,sha256:'0'.repeat(64)}]]){await seal(root,records);await assert.rejects(verifyPayload(root),/Invalid release/);}});
test('a junction cannot substitute a checksummed package directory',async()=>{const root=await fixture(),other=await fixture();await symlink(join(other,'src'),join(root,'linked'),process.platform==='win32'?'junction':'dir');const bytes=await readFile(join(other,'src/game.js'));await seal(root,[{path:'linked/game.js',bytes:bytes.length,sha256:sha256(bytes)}]);await assert.rejects(verifyPayload(root),/symlink or junction/);});
test('art provenance keeps quantities and facing data while removing personal paths',()=>{const value={source:'C:/Users/fixture-user/generated/cups.png',cups:3,frames:['front','back'],other:'public/assets/cups.png'};assert.deepEqual(portableProvenance(value),{...value,source:'source-artifact:cups.png'});assert.equal(value.source.startsWith('C:/'),true);});
test('builder never replaces an existing directory or development data',async()=>{const root=await fixture();await assert.rejects(buildLocalRelease({root,inputs:root,output:root}),/cannot replace/);await assert.rejects(buildLocalRelease({root,inputs:root,output:join(root,'data')}),/cannot replace/);await assert.rejects(buildLocalRelease({root,inputs:root,output:join(root,'src')}),/cannot replace/);await assert.rejects(buildLocalRelease({root,inputs:root,output:join(root,'src','nested')}),/cannot replace/);});

test("release revision rejects path-like or invalid version input before creating files",async()=>{const root=await fixture();for(const revision of ["81",0,-1,10000,NaN,"../../outside"])await assert.rejects(buildLocalRelease({root,inputs:root,output:join(root,"candidate"),revision}),/Invalid release revision/);});
