import test from 'node:test';import assert from 'node:assert/strict';import {resolve} from 'node:path';import {parseRuntimeEnvironment,resolveRuntimePaths,loadRuntimeEnvironment} from '../server/runtimeConfig.mjs';
test('allowed configuration parses quoted paths literally; executable text is never evaluated',()=>{const v=parseRuntimeEnvironment("HD_HERMES_INSTALL=\".runtime/hermes agent\" # local\nHD_MODEL_PYTHON='python3'\nDEEPSEEK_API_KEY=fixture-key\nHD_DOCUMENT_ROOT=$(do-not-execute)\nHD_NPC_MODEL=deepseek-pro\nPATH=ignored");assert.equal(v.HD_HERMES_INSTALL,'.runtime/hermes agent');assert.equal(v.HD_DOCUMENT_ROOT,'$(do-not-execute)');assert(!v.HD_NPC_MODEL);assert(!v.PATH);});
test('duplicates and malformed quotes fail without printing secret values',()=>{for(const src of ['DEEPSEEK_API_KEY=private-fixture\nDEEPSEEK_API_KEY=again','DEEPSEEK_API_KEY="private-fixture'])assert.throws(()=>parseRuntimeEnvironment(src),e=>!e.message.includes('private-fixture'));});
test('owner-specific inherited paths beat project settings and secrets stay out of result',()=>{const root=resolve('qa/v80/config'),e={DEEPSEEK_API_KEY:'owner-secret',HD_HERMES_HOME:resolve(root,'owner-hermes'),HD_DOCUMENT_ROOT:resolve(root,'owner-documents')};const r=loadRuntimeEnvironment({root,environment:e,read:()=> 'DEEPSEEK_API_KEY=project-secret\nHD_DOCUMENT_ROOT=shared\nHD_HERMES_HOME=shared-hermes\nHD_MODEL_PYTHON=python3',exists:()=>false});assert.equal(e.DEEPSEEK_API_KEY,'owner-secret');assert.equal(e.HD_DOCUMENT_ROOT,resolve(root,'owner-documents'));assert.equal(e.HD_HERMES_HOME,resolve(root,'owner-hermes'));assert(!JSON.stringify(r).includes('secret'));});
test('relative data and document settings resolve against installed project rather than launch cwd',()=>{const root=resolve('qa/v80/config'),e={};loadRuntimeEnvironment({root,environment:e,read:()=> 'HD_SAVE_DIR=profile/saves\nHD_DOCUMENT_ROOT=profile/documents',exists:()=>false});assert.equal(e.HD_SAVE_DIR,resolve(root,'profile/saves'));assert.equal(e.HD_DOCUMENT_ROOT,resolve(root,'profile/documents'));});
test('newly installed runtime wins over the previous machine-specific Python location',()=>{const root=resolve('qa/v80/config'),p=resolveRuntimePaths({root,environment:{USERPROFILE:'legacy-user',LOCALAPPDATA:'legacy-app'},platform:'win32',exists:file=>file.includes('.runtime')});assert.equal(p.install,resolve(root,'.runtime/hermes-agent'));assert.equal(p.modelPython,resolve(root,'.runtime/python/Scripts/python.exe'));assert.equal(p.documentPython,p.modelPython);assert.equal(p.hermesPython,p.modelPython);});
test('Linux default uses project runtime and bin/python, never Windows venv layout',()=>{const root=resolve('qa/v80/config'),p=resolveRuntimePaths({root,platform:'linux',exists:()=>false});assert.equal(p.install,resolve(root,'.runtime/hermes-agent'));assert.equal(p.hermesPython,resolve(root,'.runtime/hermes-agent/venv/bin/python'));assert.equal(p.modelPython,'python3');});
test('existing Windows deployment retains available legacy Hermes and document executables until configured',()=>{const root=resolve('qa/v80/config'),p=resolveRuntimePaths({root,environment:{USERPROFILE:'legacy-user',LOCALAPPDATA:'legacy-app'},platform:'win32',exists:file=>file.includes('codex-primary-runtime')});assert.equal(p.install,resolve('legacy-app/hermes/hermes-agent'));assert(p.documentPython.includes('codex-primary-runtime'));});
test('missing optional local configuration initializes without inventing a key',()=>{const e={},r=loadRuntimeEnvironment({root:resolve('qa/v80/config'),environment:e,read:()=>{throw Object.assign(Error('missing'),{code:'ENOENT'})},exists:()=>false});assert.equal(r.configuredKey,false);assert(!e.DEEPSEEK_API_KEY);});
