import {createCoutureRuntime} from '../src/coutureRuntime.js';
import {createFestivalLayout} from '../src/festivalLayout.js';
import {createProject} from '../src/projectPlans.js';
import test from 'node:test';import assert from 'node:assert/strict';import {mkdir,mkdtemp} from 'node:fs/promises';import {resolve} from 'node:path';import {randomUUID} from 'node:crypto';
import {createCoutureGame,validCoutureGame,coutureSolutions,coutureReview,currentCoutureBrief,applyCoutureEvent,coutureSummary,COUTURE_CLOTHES,COUTURE_EQUIPMENT} from '../src/coutureRules.js';
import {createZeroState} from '../src/freshStart.js';import {hydrateTown} from '../src/townSimulation.js';import {createSaveStore} from '../server/saveStore.mjs';import {validActionBook} from '../server/playerActions.mjs';import {coutureTarget} from '../src/coutureLayout.js';import {partyDraftStamp,eventRequests} from '../src/partyPlanning.js';import {validCoutureParty,createCoutureEvent,createCouturePlan} from '../src/coutureParty.js';import {availableQuantity} from '../src/resourceLedger.js';
await mkdir('qa/v89',{recursive:true});
function fit(g){const brief=currentCoutureBrief(g),used=g.reports.map(r=>JSON.stringify(r.outfit));return coutureSolutions(g.wardrobe,brief).sort((a,b)=>(coutureReview(b,brief).score-(used.includes(JSON.stringify(b))?8:0))-(coutureReview(a,brief).score-(used.includes(JSON.stringify(a))?8:0)))[0];}
const tick=(g,n)=>{for(let i=0;i<Math.ceil(n/.05);i++)applyCoutureEvent(g,{dt:.05});};
const dress=g=>{for(const id of Object.values(fit(g)).filter(Boolean))applyCoutureEvent(g,{action:{type:'wear',item:id}});applyCoutureEvent(g,{action:{type:'submit'}});};
function show(g){applyCoutureEvent(g,{action:{type:'arrive',index:currentCoutureBrief(g).npcId}});for(let beat=0;beat<4;beat++){while(g.clock<beat*1.8+.9-.001)applyCoutureEvent(g,{dt:.05});applyCoutureEvent(g,{action:{type:'pose',item:currentCoutureBrief(g).cues[beat]}});}while(g.phase==='showing'||g.phase==='review')applyCoutureEvent(g,{dt:.05});}
test('actual garment slots and all randomized briefs are feasible with six real baseline clothes',()=>{
 const signatures=new Set();for(let seed=1;seed<=150;seed++)for(const mode of ['easy','normal']){const g=createCoutureGame(seed,mode);assert(validCoutureGame(g));assert.deepEqual([...g.level.models].sort((a,b)=>a-b),[0,4,12]);for(const b of g.level.rounds)assert(coutureSolutions(g.wardrobe,b).length);signatures.add(JSON.stringify(g.level));}assert(signatures.size>=150);
});
test('one-piece body and actual bottoms exclude each other; every garment stays in its actual slot',()=>{
 const g=createCoutureGame(24,'normal',COUTURE_CLOTHES.map(i=>i.id));applyCoutureEvent(g,{action:{type:'start'}});applyCoutureEvent(g,{action:{type:'wear',item:'c4_7'}});assert.equal(g.outfit.bottom,'c4_7');assert.equal(g.outfit.body,null);applyCoutureEvent(g,{action:{type:'wear',item:'c4_8'}});assert.equal(g.outfit.body,'c4_8');assert.equal(g.outfit.bottom,null);applyCoutureEvent(g,{action:{type:'wear',item:'c4_10'}});assert.equal(g.outfit.head,'c4_10');assert(validCoutureGame(g));assert.throws(()=>applyCoutureEvent(g,{action:{type:'wear',item:'rod'}}));assert.throws(()=>createCoutureGame(1,'normal',Object.keys(COUTURE_EQUIPMENT)));
});
test('three real modeled rounds require feasible styling, runway arrival and four timed pose responses; rank and reward derive from actual reports',()=>{
 const g=createCoutureGame(91);for(let round=0;round<3;round++){applyCoutureEvent(g,{action:{type:'start'}});dress(g);assert.equal(g.phase,'walking');assert.throws(()=>applyCoutureEvent(g,{action:{type:'pose',item:'wave'}}));tick(g,2);assert.equal(g.phase,'walking');show(g);assert(validCoutureGame(g));}
 assert.equal(g.phase,'results');const result=coutureSummary(g);assert(result.passed);assert.equal(result.poseHits,12);assert.equal(result.completed,3);assert.equal(result.rank.length,3);assert.equal(result.reward,Math.floor(result.quality*.54));assert(result.reward<=54);assert.throws(()=>applyCoutureEvent(g,{action:{type:'submit'}}));
 const forged=structuredClone(g);forged.reports[0].quality=1000;assert(!validCoutureGame(forged));
});
test('early taps, wrong poses, timeouts and paused walking never grant a false successful show',()=>{
 const g=createCoutureGame(77);applyCoutureEvent(g,{action:{type:'start'}});dress(g);tick(g,60);assert.equal(g.elapsed,0);assert.equal(g.reports.length,0);applyCoutureEvent(g,{action:{type:'arrive',index:currentCoutureBrief(g).npcId}});for(let i=0;i<100;i++)applyCoutureEvent(g,{action:{type:'pose',item:'wave'}});assert.equal(g.show.mistakes,1);tick(g,11);assert.equal(g.reports.length,1);assert.equal(g.reports[0].stage,0);assert(!coutureSummary(g).passed);applyCoutureEvent(g,{action:{type:'start'}});tick(g,91);applyCoutureEvent(g,{action:{type:'start'}});tick(g,91);assert(validCoutureGame(g));assert(!coutureSummary(g).passed);assert.equal(coutureSummary(g).completed,1);
});
async function fixture(theme='pixel'){
 let now=1791300000000;const directory=await mkdtemp(resolve('qa/v89/service-')),store=createSaveStore({directory,now:()=>now}),s=hydrateTown(createZeroState());s.freshStartPending=false;s.coins=160;s.roomGames[4]={plays:5};s.facilities[4].quality=65;Object.assign(s.inventory,{...COUTURE_EQUIPMENT,fiber:5,tea:3,bread:1,wheat:1,rose:1,bamboo:1,shell:1,c4_8:1});
 await store.open(theme,{legacyState:s});const current=()=>store.current(theme),call=async input=>{const d=await current();return store.action(theme,{expectedVersion:d.version,requestId:randomUUID(),...input});},manage=async(op,extra={})=>{const d=await current(),draft=d.state.coutureParty?.draft;return call({kind:'commerce',operation:op,day:d.state.day,eventId:draft?.id||null,eventVersion:draft?.version||null,eventStamp:partyDraftStamp(draft),...extra});};
 await manage('enable');await manage('plan_enable');await manage('couture_enable');await manage('couture_create',{proposal:{template:'couture',name:'三轮海岛穿搭',tags:['sea','stars'],difficulty:'normal',guestId:null}});
 return{theme,directory,store,current,call,manage,advance:ms=>now+=ms};
}
async function start(f){for(const p of eventRequests((await f.current()).state.coutureParty.draft))await f.manage('couture_invite',{npcId:p.id});const d=await f.current(),e=d.state.coutureParty.draft;return f.call({kind:'couture',operation:'begin',eventId:e.id,eventVersion:e.version,eventStamp:partyDraftStamp(e),expectedSequence:d.actions.sequence,epoch:d.actions.epoch});}
async function place(f){const d=await f.current(),s=structuredClone(d.state),g=s.coutureParty.session;s.coutureAttendance={id:g.id,people:{}};s.npcPresence??=[];for(const id of [-1,...g.participants.map(p=>p.id)]){const p=coutureTarget(g,id);s.coutureAttendance.people[id]={...p,inside:null,controlled:true,arrived:true};if(id===-1)s.player={...p};else{s.npcPresence=s.npcPresence.filter(n=>n.id!==id);s.npcPresence.push({id,...p,inside:null});}}
 return f.store.save(f.theme,{state:s,expectedVersion:d.version});}
async function checkpoint(f,events,overrides={}){const d=await f.current(),t=d.actions.active,elapsed=events.reduce((v,e)=>v+(e.dt||0),0);f.advance(elapsed*1000+100);return f.call({kind:'couture',operation:'checkpoint',requestId:t.requestId,epoch:t.epoch,sequence:t.sequence,batch:t.nextBatch,events,...overrides});}
for(const theme of ['pixel','origami'])test(theme+' actual store holds real clothes, protects game and gifts, checks real presence, replays inputs once, pays once and releases outfits',async()=>{
 const f=await fixture(theme),startResponse=await start(f),eventId=startResponse.ticket.eventId,base=await f.current();assert(validActionBook(base.actions));assert(validCoutureParty(base.state));assert.equal(base.state.coins,148);assert.equal(availableQuantity(base.state,'c4_1'),0);assert.equal(base.state.inventory.c4_1,1);assert.equal(base.state.inventory.fiber,2);
 const forged=structuredClone(base.state);forged.coutureParty.session.game.reports.push({quality:100});await assert.rejects(f.store.save(theme,{state:forged,expectedVersion:base.version}));
 await assert.rejects(checkpoint(f,[{action:{type:'start'}}]),e=>e.code==='couture_arrival');
 await assert.rejects(f.call({kind:'couture',operation:'finish',requestId:base.actions.active.requestId,epoch:base.actions.epoch,sequence:base.actions.active.sequence}),e=>e.code==='couture_unfinished');
 for(let round=0;round<3;round++){
  await place(f);await checkpoint(f,[{action:{type:'start'}}]);let d=await f.current(),local=structuredClone(d.state.coutureParty.session.game),events=Object.values(fit(local)).filter(Boolean).map(item=>({action:{type:'wear',item}}));events.push({action:{type:'submit'}});await checkpoint(f,events);d=await f.current();const id=d.state.coutureParty.session.game.level.models[round];await assert.rejects(checkpoint(f,[{action:{type:'arrive',index:id}}]),e=>e.code==='couture_arrival');
  await place(f);await checkpoint(f,[{action:{type:'arrive',index:id}}]);local=structuredClone((await f.current()).state.coutureParty.session.game);events=[];const push=e=>{events.push(e);applyCoutureEvent(local,e);};for(let beat=0;beat<4;beat++){while(local.clock<beat*1.8+.9-.001)push({dt:.05});push({action:{type:'pose',item:currentCoutureBrief(local).cues[beat]}});}while(['showing','review'].includes(local.phase))push({dt:.05});const before=await f.current(),t=before.actions.active,r=await checkpoint(f,events);assert(validActionBook(r.document.actions));const replay=await f.call({kind:'couture',operation:'checkpoint',requestId:t.requestId,epoch:t.epoch,sequence:t.sequence,batch:t.nextBatch,events});assert(replay.replayed);assert.equal(replay.document.version,r.document.version);await assert.rejects(f.call({kind:'couture',operation:'checkpoint',requestId:t.requestId,epoch:t.epoch,sequence:t.sequence,batch:t.nextBatch,events:[{neutral:true}]}),e=>e.code==='couture_batch_conflict');
 }
 const d=await f.current(),t=d.actions.active;f.advance(2500);const input={kind:'couture',operation:'finish',requestId:t.requestId,epoch:t.epoch,sequence:t.sequence},finished=await f.call(input),again=await f.call(input);
 assert.equal(again.document.version,finished.document.version);assert(again.replayed);assert(finished.receipt.details.result.passed);assert.equal(finished.document.state.coins,148+finished.receipt.reward);assert.equal(finished.document.state.inventory.c4_1,1);assert.equal(availableQuantity(finished.document.state,'c4_1'),1);assert.equal(finished.document.state.activities,1);assert(finished.document.state.eventWonders.owned.couture_ribbon);assert.equal(finished.document.state.eventWonders.owned.couture_ribbon.marks,0);assert.deepEqual(finished.receipt.details.newWonders,['couture_ribbon','muse_wardrobe']);assert(finished.document.state.eventWonders.owned.muse_wardrobe);assert.equal(again.document.state.eventWonders.owned.couture_ribbon.marks,0);assert.equal(finished.document.state.achievementBook.hosted[finished.document.state.coutureParty.session.id].template,'couture');assert.equal(finished.document.actions.active,null);assert(validActionBook(finished.document.actions));assert(validCoutureParty(finished.document.state));
 await f.manage('fish_enable');assert.equal((await f.current()).actions.fishing.lastDay,1);
});
test('actual cancellation preserves clothes and consumed inputs; revision requires reconsent without a second gift',async()=>{
 const f=await fixture();await f.manage('couture_invite',{npcId:13});const gifted=await f.current();await f.manage('couture_update',{proposal:{template:'couture',name:'新主题',tags:['nature'],difficulty:'easy',guestId:null}});assert.deepEqual((await f.current()).state.coutureParty.draft.invites,{});await f.manage('couture_invite',{npcId:13});assert.equal((await f.current()).state.inventory.fiber,gifted.state.inventory.fiber);const r=await start(f),d=await f.current(),cancel=await f.call({kind:'couture',operation:'cancel',requestId:r.ticket.requestId,epoch:r.ticket.epoch,sequence:r.ticket.sequence});
 assert.equal(cancel.document.state.coins,148);assert.equal(cancel.document.state.inventory.c4_1,1);assert.equal(availableQuantity(cancel.document.state,'c4_1'),1);assert.equal(cancel.document.state.inventory.fiber,d.state.inventory.fiber);assert.equal(cancel.document.state.activities,0);assert.equal(cancel.document.state.coutureParty.session.phase,'abandoned');assert(validActionBook(cancel.document.actions));
});
test('couture is progression gated and a fixed model cannot be silently recast as theme guest',async()=>{
 const {validatePartyProposal}=await import('../src/partyPlanning.js');const s=hydrateTown(createZeroState());assert(!validatePartyProposal(s,{template:'couture',name:'早期大会',tags:['stars'],guestId:null}).ok);s.roomGames[4]={plays:5};s.facilities[4].quality=65;assert(!validatePartyProposal(s,{template:'couture',name:'重复模特',tags:['nature'],guestId:4}).ok);assert(validatePartyProposal(s,{template:'couture',name:'星光穿搭',tags:['stars'],guestId:3}).ok);
});

test('zero-stock couture preparation expands up to fifteen explicit targets without relaxing the ordinary eight-target project limit',()=>{
 const s=hydrateTown(createZeroState());s.freshStartPending=false;s.roomGames[4]={plays:5};s.facilities[4].quality=65;
 const r=createCoutureEvent(s,{template:'couture',name:'星织筹备',tags:['craft','stars'],difficulty:'easy',guestId:3,guestReason:'观星嘉宾'});
 assert(r.ok);const p=createCouturePlan(s);assert(p.ok,p.reason);assert(Object.keys(p.project.targets).length>8);assert(Object.keys(p.project.targets).length<=16);assert.equal(p.project.status,'preparing');assert.equal(Object.keys(s.coutureParty.draft.invites).length,0);
 assert.equal(s.coins,0);assert.equal(s.inventory.c4_1,0);assert(s.agentTaskLedger.length>0);
 const duplicate=createCouturePlan(s);assert(duplicate.replayed);assert.equal(duplicate.project.id,p.project.id);assert.equal(s.workProjects.length,1);
 const tooMany=Object.fromEntries(Object.keys(p.project.targets).slice(0,9).map(id=>[id,1]));assert.equal(createProject(s,{title:'普通计划',targets:tooMany}).ok,false);
});

test('a shown model remains at the runway until its report is acknowledged; next round waits for the actual return',()=>{
 const s=hydrateTown(createZeroState()),local=createCoutureGame(321,'easy');applyCoutureEvent(local,{action:{type:'start'}});dress(local);show(local);assert.equal(local.phase,'intermission');
 const authority=structuredClone(local);authority.reports=[];authority.phase='review';authority.clock=0;
 const layout=createFestivalLayout(s,'pixel',3),participants=eventRequests({template:'couture',guestId:null}).map(p=>({id:p.id,role:p.role,model:!!p.model})),g={id:'couture-test',phase:'running',layout,participants,game:authority};
 s.coutureParty={session:g};const npcs=[];for(const p of participants){const point=coutureTarget(g,p.id,authority);npcs[p.id]={npcId:p.id,...point,path:[],inside:null,action:null,meeting:null};}
 const r=createCoutureRuntime({state:()=>s,npcs,resident:()=>({releaseActor(){}}),followPath(){},player:()=>({...layout.player}),game:()=>local,now:()=>100});
 r.update(.02);const model=npcs[local.level.models[0]];assert.equal(model.x,layout.buyers[3].x);assert.equal(model.y,layout.buyers[3].y);assert.equal(model.path.length,0);assert.equal(r.ready(),false);
 g.game=structuredClone(local);r.update(.02);assert(model.path.length>0);const end=model.path.at(-1),waiting=coutureTarget(g,model.npcId,local);assert(Math.hypot(end.x-waiting.x,end.y-waiting.y)<1);assert.equal(r.ready(),false);
 r.release();assert.equal(model.partyControlled,false);assert.deepEqual(model.coutureGarments,[]);
});
