import test from 'node:test';import assert from 'node:assert/strict';
import {createState,RESIDENTS} from '../src/world.js';
import {hydrateTown,needs,career,purposeOptions,choosePurpose,commitWork,socialVenue} from '../src/townSimulation.js';
import {matchedCells,legalMatchMoves,playableMatchBoard,shuffledPairs} from '../src/gameBoards.js';
test('meal plans use real food destinations, sold-out dishes do not consume another food',()=>{const s=hydrateTown(createState());s.inventory.wheat=0;s.inventory.tea=0;s.inventory.bread=1;s.inventory.meal=1;for(let i=0;i<16;i++){needs(i,s).hunger=12;const d=choosePurpose(i,s,RESIDENTS[i],10);assert.equal(d.action,'eat');assert.equal(d.buildingId,d.foodId==='bread'?17:2);assert.notEqual(d.buildingId,1);}const d=choosePurpose(0,s,RESIDENTS[0],10),before=needs(0,s).hunger;s.inventory[d.foodId]=0;const another=d.foodId==='bread'?'meal':'bread',stock=s.inventory[another];commitWork(0,d,s,11);assert.equal(s.inventory[another],stock);assert.equal(needs(0,s).hunger,before);});
test('no-food hunger gathers a real edible resource and returns to a meal, never empty tea house',()=>{const s=hydrateTown(createState());for(const id of Object.keys(s.inventory))s.inventory[id]=0;needs(0,s).rations=0;needs(0,s).hunger=5;const gather=choosePurpose(0,s,RESIDENTS[0],10);assert.equal(gather.resource,'mushroom');assert.equal(gather.goal,'forest');commitWork(0,gather,s,20);assert.equal(s.inventory.mushroom,2);const eat=choosePurpose(0,s,RESIDENTS[0],22);assert.equal(eat.action,'eat');assert.equal(eat.buildingId,22);commitWork(0,eat,s,32);assert.equal(s.inventory.mushroom,1);assert.ok(needs(0,s).hunger>30);});
test('social destinations follow shared work, relationships and crowding rather than universal tea',()=>{const s=hydrateTown(createState()),venues=[];for(let i=0;i<15;i++){needs(i,s).social=30;needs(i,s).hunger=90;venues.push(choosePurpose(i,s,RESIDENTS[i],100).buildingId);}assert.ok(new Set(venues).size>=8);assert.ok(venues.filter(x=>x===1).length<3);const preferred=socialVenue(2,12,s,'friendship',100);s.npcPresence=Array.from({length:5},(_,k)=>({id:k+3,inside:preferred}));assert.notEqual(socialVenue(2,12,s,'friendship',100),preferred);});
test('growing crops lead to a personal break, and work resumes after the break',()=>{const s=hydrateTown(createState());s.plots.forEach(p=>p.stage=3);needs(0,s).hunger=90;needs(0,s).social=90;const d=choosePurpose(0,s,RESIDENTS[0],100);assert.equal(d.action,'visit');const seeds=s.inventory.seed;commitWork(0,d,s,112);assert.equal(s.inventory.seed,seeds);s.plots[0].stage=4;assert.equal(choosePurpose(0,s,RESIDENTS[0],115).goal,'farm');career(1,s).workSinceBreak=3;assert.equal(choosePurpose(1,s,RESIDENTS[1],100).action,'visit');});
test('new and shuffled match boards always have legal moves without auto-scoring',()=>{for(const random of [()=>0,()=>.999999,Math.random])for(let i=0;i<80;i++){const board=playableMatchBoard(random);assert.equal(board.length,36);assert.equal(matchedCells(board).length,0);assert.ok(legalMatchMoves(board).length);assert.deepEqual([...shuffledPairs(random)].sort(),[0,0,1,1,2,2,3,3]);}});

import {groundedConversation} from '../src/conversationFallback.js';
test('offline relationships are grounded, asymmetric and do not force romance',()=>{const s=hydrateTown(createState());let result=groundedConversation([0,6],s,i=>RESIDENTS[i],'friendship',100);assert.equal(result.source,'local');assert.equal(result.lines.length,4);assert.ok(result.lines[0].text.includes('打算'));s.npcRelations[0][6].affection=16;s.npcRelations[0][6].trust=12;result=groundedConversation([0,6],s,i=>RESIDENTS[i],'confession',100);assert.ok(result.summary.includes('先做朋友'));assert.equal(result.changes[1].affection,0);s.npcRelations[0][6].tension=20;s.npcRelations[0][6].affinity=-20;result=groundedConversation([0,6],s,i=>RESIDENTS[i],'reconcile',100);assert.ok(result.summary.includes('暂未和解'));assert.ok(result.changes[0].tension>0);assert.equal(result.changes[0].affinity,0);});

test('social invitations respect a hungry or exhausted partner',()=>{const s=hydrateTown(createState());needs(2,s).social=20;needs(12,s).hunger=15;assert.ok(purposeOptions(2,s,RESIDENTS[2],100).every(o=>o.action!=='social'));needs(12,s).hunger=80;needs(12,s).energy=15;assert.ok(purposeOptions(2,s,RESIDENTS[2],100).every(o=>o.action!=='social'));needs(12,s).energy=80;assert.ok(purposeOptions(2,s,RESIDENTS[2],100).some(o=>o.action==='social'));});
