import test from 'node:test';import assert from 'node:assert/strict';import {mkdir,mkdtemp} from 'node:fs/promises';import {resolve} from 'node:path';import {randomUUID} from 'node:crypto';
import {createFireworksGame,applyFireworksEvent,validFireworksGame,currentFireworksAct,fireworksWind,fireworksSummary} from '../src/fireworksRules.js';
import {createFireworksEvent,updateFireworksEvent,createFireworksPlan,inviteFireworksNpc,startFireworksParty,finishFireworksParty,abandonFireworksParty,validFireworksParty} from '../src/fireworksParty.js';
import {createZeroState} from '../src/freshStart.js';import {hydrateTown} from '../src/townSimulation.js';import {createSaveStore} from '../server/saveStore.mjs';import {validActionBook} from '../server/playerActions.mjs';import {fireworksTarget} from '../src/fireworksLayout.js';import {eventRequests,partyDraftStamp,partyPlanningContexts} from '../src/partyPlanning.js';import {availableQuantity} from '../src/resourceLedger.js';import {completedFireworksProof} from '../src/eventWonders.js';
await mkdir('qa/v90',{recursive:true});
const tick=(g,n,emit=e=>applyFireworksEvent(g,e))=>{const limit=g.clock+n;while(g.clock<limit-1e-8)emit({dt:Math.min(.05,limit-g.clock)});};
function arm(g,emit=e=>applyFireworksEvent(g,e)){
 const act=currentFireworksAct(g);for(const t of act.targets){for(const [field,value]of [['lane',t.lane],['color',t.color],['shape',t.shape]])emit({action:{type:'configure',index:t.index,item:field+':'+value}});const at=t.at-t.flight;emit({action:{type:'aim',index:t.index,x:t.x-fireworksWind(g,at)*t.flight*.55,y:t.y}});}emit({action:{type:'submit'}});
}
function playAct(g,emit=e=>applyFireworksEvent(g,e)){
 emit({action:{type:'start'}});arm(g,emit);
 for(const t of [...currentFireworksAct(g).targets].sort((a,b)=>(a.at-a.flight)-(b.at-b.flight))){tick(g,t.at-t.flight-g.clock,emit);emit({action:{type:'launch',index:t.index}});}
 while(['performing','review'].includes(g.phase))emit({dt:.05});
}
const state=()=>{const s=hydrateTown(createZeroState());s.freshStartPending=false;s.coins=100;Object.assign(s.inventory,{firework:6,c8_2:1,tea:2,resin:2,quartz:2,bamboo:2,shell:1});return s;};
test('seeded wind, six distinct targets and normal/easy windows vary; every request is reachable with actual aiming limits',()=>{
 const signatures=new Set();for(let seed=1;seed<=180;seed++)for(const difficulty of ['normal','easy']){const g=createFireworksGame(seed,difficulty,['sea']);assert(validFireworksGame(g));for(let i=0;i<3;i++){g.round=i;const a=currentFireworksAct(g);assert.notEqual(a.targets[0].lane,a.targets[1].lane);for(const t of a.targets){const aim=t.x-fireworksWind(g,t.at-t.flight)*t.flight*.55;assert(aim>=.08&&aim<=.92);assert(t.at-t.flight>0&&t.at+t.flight<12);}}signatures.add(JSON.stringify(g.level));}assert(signatures.size>=180);
});
test('three interactive acts score colors, patterns, actual wind-compensated bursts and beat; replays remain identical',()=>{
 const g=createFireworksGame(571),trace=[];for(let i=0;i<3;i++)playAct(g,e=>{trace.push(e);applyFireworksEvent(g,e);});assert(validFireworksGame(g));assert.deepEqual(fireworksSummary(g),{quality:100,hits:6,fired:6,completed:3,passed:true,reward:78});const copy=createFireworksGame(571);for(const e of trace)applyFireworksEvent(copy,e);assert.deepEqual(copy,g);const forged=structuredClone(g);forged.shots[0].quality=999;assert(!validFireworksGame(forged));forged.shots[0]=g.shots[0];forged.level.rounds[0].wind=0;assert(!validFireworksGame(forged));
});
test('one shell launches once; wrong configuration/late firing/timeouts do not create an infinite or false success',()=>{
 const g=createFireworksGame(18);applyFireworksEvent(g,{action:{type:'start'}});arm(g);for(let i=0;i<80;i++)applyFireworksEvent(g,{action:{type:'launch',index:0}});assert.equal(g.shots.length,1);tick(g,10);applyFireworksEvent(g,{action:{type:'launch',index:1}});assert.equal(g.shots.length,1);while(['performing','review'].includes(g.phase))applyFireworksEvent(g,{dt:.05});for(let i=0;i<2;i++){applyFireworksEvent(g,{action:{type:'start'}});while(['arming','review'].includes(g.phase))applyFireworksEvent(g,{dt:.05});}assert(validFireworksGame(g));assert(!fireworksSummary(g).passed);assert.equal(fireworksSummary(g).fired,1);assert.throws(()=>applyFireworksEvent(createFireworksGame(1),{action:{type:'launch',index:0}}));
});
test('version changes re-confirm three jobs without a second gift; real preparation includes six shells and flag',()=>{
 const s=state(),created=createFireworksEvent(s,{name:'星海之约',tags:['sea'],difficulty:'normal',guestId:null});assert(created.ok);const plan=createFireworksPlan(s);assert(plan.ok);assert.equal(plan.project.targets.firework,6);assert.equal(plan.project.targets.c8_2,1);
 for(const id of [1,3,12])assert(inviteFireworksNpc(s,id).ok);const before=structuredClone(s.inventory);assert(updateFireworksEvent(s,{name:'星海之约改名',tags:['sea'],difficulty:'normal',guestId:null}).ok);assert.equal(s.fireworksParty.draft.version,1);assert(updateFireworksEvent(s,{name:'星海之约',tags:['stars'],difficulty:'easy',guestId:null}).reinvite);assert.deepEqual(s.fireworksParty.draft.invites,{});for(const id of [1,3,12])assert(inviteFireworksNpc(s,id).ok);assert.deepEqual(s.inventory,before);assert(validFireworksParty(s));assert.equal(partyPlanningContexts(s).fireworks.fixedRoles.length,3);
});
test('real finite inventory is reserved; partial cancellation consumes fired shells only and pays no reward',()=>{
 const s=state();assert(createFireworksEvent(s,{name:'星海之约',tags:['sea'],difficulty:'normal',guestId:null}).ok);for(const id of [1,3,12])assert(inviteFireworksNpc(s,id).ok);assert(startFireworksParty(s,{seed:2,theme:'pixel'}).ok);assert.equal(availableQuantity(s,'firework'),0);assert.equal(s.inventory.firework,6);const g=s.fireworksParty.session.game;applyFireworksEvent(g,{action:{type:'start'}});arm(g);applyFireworksEvent(g,{action:{type:'launch',index:0}});assert(abandonFireworksParty(s).ok);assert.equal(s.inventory.firework,5);assert.equal(availableQuantity(s,'firework'),5);assert.equal(s.coins,86);assert(!completedFireworksProof(s,s.fireworksParty.session));assert(!abandonFireworksParty(s).ok);
});
async function fixture(theme){
 let now=1791300000000;const directory=await mkdtemp(resolve('qa/v90/service-')),store=createSaveStore({directory,now:()=>now});await store.open(theme,{legacyState:state()});const current=()=>store.current(theme),call=async input=>{const d=await current();return store.action(theme,{expectedVersion:d.version,requestId:randomUUID(),...input});},manage=async(operation,extra={})=>{const d=await current(),e=d.state.fireworksParty?.draft;return call({kind:'commerce',operation,day:d.state.day,eventId:e?.id||null,eventVersion:e?.version||null,eventStamp:partyDraftStamp(e),...extra});};
 await manage('enable');await manage('plan_enable');await manage('fireworks_enable');await manage('fireworks_create',{proposal:{template:'fireworks',name:'实际三幕星海',tags:['stars'],difficulty:'normal',guestId:null}});for(const id of [1,3,12])await manage('fireworks_invite',{npcId:id});let d=await current(),e=d.state.fireworksParty.draft;await call({kind:'fireworks',operation:'begin',eventId:e.id,eventVersion:e.version,eventStamp:partyDraftStamp(e),expectedSequence:d.actions.sequence,epoch:d.actions.epoch});
 return{store,theme,current,call,advance:ms=>now+=ms};
}
async function place(f){const d=await f.current(),s=structuredClone(d.state),g=s.fireworksParty.session;s.fireworksAttendance={id:g.id,people:{}};s.npcPresence??=[];for(const id of [-1,...g.participants.map(p=>p.id)]){const p=fireworksTarget(g,id);s.fireworksAttendance.people[id]={...p,inside:null,controlled:true,arrived:true};if(id===-1)s.player={...p};else{s.npcPresence=s.npcPresence.filter(n=>n.id!==id);s.npcPresence.push({id,...p,inside:null});}}await f.store.save(f.theme,{state:s,expectedVersion:d.version});}
async function checkpoint(f,events,override={}){const d=await f.current(),t=d.actions.active;f.advance(events.reduce((v,e)=>v+(e.dt||0),0)*1000+100);return f.call({kind:'fireworks',operation:'checkpoint',requestId:t.requestId,epoch:t.epoch,sequence:t.sequence,batch:t.nextBatch,events,...override});}
for(const theme of ['pixel','origami'])test(theme+' actual disk service requires real arrival, protects receipts, replays once and settles six shells/reward/SR once',async()=>{
 const f=await fixture(theme),base=await f.current();assert(validActionBook(base.actions));assert(validFireworksParty(base.state));assert.equal(base.state.coins,86);assert.equal(availableQuantity(base.state,'firework'),0);await assert.rejects(checkpoint(f,[{action:{type:'start'}}]),e=>e.code==='fireworks_arrival');
 for(let i=0;i<3;i++){await place(f);const g=structuredClone((await f.current()).state.fireworksParty.session.game),events=[];playAct(g,e=>{events.push(e);applyFireworksEvent(g,e);});const d=await f.current(),t=d.actions.active,r=await checkpoint(f,events);assert(validActionBook(r.document.actions));const again=await f.call({kind:'fireworks',operation:'checkpoint',requestId:t.requestId,epoch:t.epoch,sequence:t.sequence,batch:t.nextBatch,events});assert(again.replayed);assert.equal(again.document.version,r.document.version);await assert.rejects(f.call({kind:'fireworks',operation:'checkpoint',requestId:t.requestId,epoch:t.epoch,sequence:t.sequence,batch:t.nextBatch,events:[{neutral:true}]}),e=>e.code==='fireworks_batch_conflict');}
 const before=await f.current(),t=before.actions.active;f.advance(2500);const input={kind:'fireworks',operation:'finish',requestId:t.requestId,epoch:t.epoch,sequence:t.sequence},done=await f.call(input),again=await f.call(input),s=done.document.state;assert(again.replayed);assert.equal(again.document.version,done.document.version);assert.equal(s.coins,164);assert.equal(s.inventory.firework,0);assert.equal(availableQuantity(s,'c8_2'),1);assert.equal(s.eventWonders.owned.fireworks_orbit.rarity,'SR');assert.equal(s.eventWonders.owned.fireworks_orbit.wins,1);assert(completedFireworksProof(s,s.fireworksParty.session));assert(validActionBook(done.document.actions));
 const forged=structuredClone(s);forged.resourceLedger.receipts['fireworks-fired:'+s.fireworksParty.session.id].delta.firework=-5;await assert.rejects(f.store.save(theme,{state:forged,expectedVersion:done.document.version}),e=>e.code==='fireworks_state_conflict');
 const reload=await f.store.current(theme);assert.equal(reload.state.coins,164);assert.equal(reload.state.eventWonders.owned.fireworks_orbit.wins,1);
});
