import test from 'node:test';
import assert from 'node:assert/strict';
import {createZeroState} from '../src/freshStart.js';
import {hydrateTown} from '../src/townSimulation.js';
import {ITEM_BY_ID} from '../src/contentCatalog.js';
import {PARTY_GUIDES,partyGuide,partyGuideSummary} from '../src/partyGuide.js';
import {createNightEvent} from '../src/nightPartyPlanning.js';
import {createFishingEvent} from '../src/fishingParty.js';
import {createFestivalEvent} from '../src/festivalParty.js';
import {createCoutureEvent} from '../src/coutureParty.js';
import {createFireworksEvent} from '../src/fireworksParty.js';
import {eventRequests} from '../src/partyPlanning.js';
import {reserveResources} from '../src/resourceLedger.js';
const create={night:createNightEvent,fishing:createFishingEvent,market:createFestivalEvent,couture:createCoutureEvent,fireworks:createFireworksEvent};
function island(){const s=hydrateTown(createZeroState());s.coins=500;for(const id of Object.keys(ITEM_BY_ID))s.inventory[id]=30;for(let i=0;i<25;i++){s.buildings[i]??=1;s.roomGames[i]={plays:10};s.facilities[i].quality=75;}return s;}
function draft(s,t){const r=create[t](s,{template:t,name:'真实筹备',description:'',tags:[t==='fishing'?'sea':'craft'],guestId:null,difficulty:'normal'});assert(r.ok,r.reason);return r.event;}
function agree(s,t){const d=draft(s,t);for(const p of eventRequests(d)){d.invites[p.id]={version:d.version,day:s.day};d.inviteGifts[p.id]={delivered:{[p.item]:p.quantity},affinityGranted:true,day:s.day};}return d;}
test('opening all five guides is read-only and reports each actual current-version role',()=>{const s=island();for(const t of Object.keys(create))draft(s,t);const before=structuredClone(s),a=partyGuideSummary(s);assert.equal(a.cards.length,5);assert.equal(a.due,5);for(const c of a.cards){assert.equal(c.phase,'inviting');assert.equal(c.people.length,eventRequests(s[PARTY_GUIDES.find(x=>x.template===c.template).field].draft).length);assert(c.people.every(p=>!p.confirmed&&p.canInvite));}assert.deepEqual(s,before);});
test('reserving stock for another task changes missing quantities; own ready project counts only once',()=>{const s=island(),d=draft(s,'fireworks');s.inventory.firework=6;reserveResources(s,'other:work',{firework:5});let c=partyGuide(s,'fireworks');assert.equal(c.missing.find(x=>x.item==='firework').missing,5);delete s.resourceLedger.reservations['other:work'];d.projectId='supplies';s.workProjects=[{id:'supplies',status:'ready',title:'烟花筹备'}];reserveResources(s,'project:supplies',{firework:6});c=partyGuide(s,'fireworks');assert(!c.missing.some(x=>x.item==='firework'));assert.equal(s.inventory.firework,6);});
test('paused/preparing projects lead to actual task board instead of suggesting unavailable reserved gifts',()=>{const s=island(),d=draft(s,'fireworks');d.projectId='supplies';s.workProjects=[{id:'supplies',status:'paused',title:'烟花筹备'}];const c=partyGuide(s,'fireworks');assert.equal(c.phase,'preparing');assert.equal(c.next.kind,'project');assert(c.people.every(p=>!p.canInvite));assert.equal(c.label,'筹备已暂停');});
test('a new version requires consent again, retains delivered gifts, and never fabricates acceptance',()=>{const s=island(),d=agree(s,'fireworks');assert(partyGuide(s,'fireworks').ready);d.version++;const before=structuredClone(s),c=partyGuide(s,'fireworks');assert.equal(c.phase,'inviting');assert(c.people.every(p=>p.gift&&!p.confirmed&&p.canInvite));assert.deepEqual(s,before);});
test('shared daily opportunity and another active event override a prepared start in all templates',()=>{const s=island();for(const t of Object.keys(create))agree(s,t);for(const t of Object.keys(create))assert(partyGuide(s,t).ready);s.lastPartyDay=s.day;for(const t of Object.keys(create)){assert.equal(partyGuide(s,t).phase,'tomorrow');assert(!partyGuide(s,t).ready);}s.festivalParty.session={phase:'running',game:{phase:'checkin'},name:'已在开市'};for(const t of ['night','fishing','couture','fireworks']){const c=partyGuide(s,t);assert.equal(c.phase,'waiting');assert.equal(c.next.template,'market');}assert.equal(partyGuide(s,'market').phase,'active');});
test('current emotional conflict directs mediation, not an implicit agreement or reward',()=>{const s=island(),d=agree(s,'fireworks');s.residentStories.episodes.push({id:'resident-story-91',kind:'conflict',status:'scheduled',stage:'talk',people:[1,3],mediated:false,expiresDay:s.day+2});const before=structuredClone(s),c=partyGuide(s,'fireworks');assert.equal(c.phase,'relationship');assert.equal(c.next.kind,'story');assert.equal(c.next.npcId,1);assert(!c.ready);assert.deepEqual(s,before);});
test('claimed results route to the real activity receipt; uncreated locked events retain growth conditions',()=>{const s=island();s.fireworksParty={session:{phase:'claimed',name:'真实烟花',game:{phase:'results'}}};const c=partyGuide(s,'fireworks');assert.equal(c.phase,'results');assert.equal(c.next.kind,'book');assert(!c.ready);const zero=hydrateTown(createZeroState()),before=structuredClone(zero);const couture=partyGuide(zero,'couture');assert.equal(couture.phase,'locked');assert.equal(couture.next.kind,'item');assert.deepEqual(zero,before);});
