import {readFile,writeFile,mkdir,copyFile,stat} from 'node:fs/promises';import {resolve} from 'node:path';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';import assert from 'node:assert/strict';
const out=resolve('qa/v93/final');await mkdir(out,{recursive:true});
const sources=['index.html','package.json','server/commerceActions.mjs','server/playerActions.mjs','server/saveStore.mjs','server/partyHostingActions.mjs','server/party_protocol.py','server/hermes_worker.py','src/partyPlanning.js','src/partyHosting.js','src/partyHostingRuntime.js','src/party-hosting-v93.css','src/partyGuideUI.js','src/app.js','tests/v93-party-hosting.test.mjs','tests/v93-hosting-fixture.mjs','tests/v93-hosting-browser.mjs','tests/v93-hosting-hermes.mjs','tests/v93-hosting-protocol.test.py','tests/v93-save-continuity.mjs','tests/v93-live-files.mjs','docs/current-baseline-v93.md','docs/delivery-goal-v25.json','docs/acceptance-countdown-20261007.md','README.md'];
const evidence=['qa/v93/rules-final.log','qa/v93/default-regression.log','qa/v93/browser/report.json','qa/v93/browser-style-corrected/report.json','qa/v93/real-hermes/report.json','qa/v93/live-files.json','qa/v93/deployment.json','qa/v93/save-continuity-stopped.json','qa/v93/save-continuity-after.json','qa/v93/backup-create.log','qa/v93/backup-verify.log','qa/v93/browser-style-corrected/pixel-night-mandate-390.png','qa/v93/browser-style-corrected/origami-night-mandate-390.png','qa/v93/browser/pixel-fireworks-arrived.png','qa/v93/browser/origami-fireworks-arrived.png','qa/v93/real-hermes/report-initial-identity.json','qa/v93/real-hermes/report-initial-request.json','qa/v93/real-hermes/report-initial-travel.json','qa/v93/browser-style-final/report.json'];
const hash=b=>createHash('sha256').update(b).digest('hex'),records=[];
for(const file of [...sources,...evidence]){const bytes=await readFile(file),target=file.replaceAll('/','__');await copyFile(file,resolve(out,target));records.push({file,bytes:bytes.length,sha256:hash(bytes),frozen:target});}
const syntax=[];for(const file of sources.filter(p=>/\.(js|mjs)$/.test(p))){execFileSync(process.execPath,['--check',file]);syntax.push(file);}
const r=await readFile('qa/v93/rules-final.log','utf8'),defaultLog=await readFile('qa/v93/default-regression.log','utf8');assert.match(r,/pass 81/);assert.match(defaultLog,/pass 524/);assert.match(defaultLog,/fail 0/);
const browser=JSON.parse(await readFile('qa/v93/browser/report.json','utf8')),styles=JSON.parse(await readFile('qa/v93/browser-style-corrected/report.json','utf8')),hermes=JSON.parse(await readFile('qa/v93/real-hermes/report.json','utf8'));assert(browser.passed&&browser.checks.length===10);assert(styles.passed&&styles.checks.length===2);assert(hermes.passed&&hermes.checks.length===2);
const tracker=JSON.parse(await readFile('docs/delivery-goal-v25.json','utf8')),requirements=Object.fromEntries(['complete','in_progress'].map(status=>[status,tracker.requirements.filter(r=>r.status===status).length])),links=[];
for(const p of ['docs/current-baseline-v93.md','README.md','docs/acceptance-countdown-20261007.md']){const txt=await readFile(p,'utf8');for(const match of txt.matchAll(/\[[^\]]*\]\(([^)]+)\)/g)){const target=match[1];if(/^(https?:|#)/.test(target)||target.includes('$'+'{'))continue;const file=resolve(p,'..',target);if(target==='../qa/v93/final/verification-summary.json')continue;await stat(file);links.push({document:p,target});}}
const summary={version:'V93',at:new Date().toISOString(),deadline:tracker.acceptanceDeadline,wholeGoalComplete:false,requirements,formalArtifactsUpdated:false,savePerformanceRetested:false,proof:{relatedRules:81,hostingRules:14,defaultRules:524,ruleSetsOverlap:true,pythonProtocol:4,actualBrowserActivities:10,additionalCurrentWorldThemeChecks:2,actualManualFlashHermesRequests:2,providerPrecheckFailures:3,actualStaticResponses:20,backupFiles:789},scope:'Hosting delegates only actual summon/start after personal consent and goods, preserves player-operated games. Server completion tests have injected time and fixture positions; browser routes are actual movement with progressed stock. Not full zero-resource growth, real human or physical multi-device acceptance.',syntax,documentLinks:links.length,records};
await writeFile('qa/v93/doc-links.json',JSON.stringify({links},null,2));await writeFile(resolve(out,'verification-summary.json'),JSON.stringify(summary,null,2));console.log({version:summary.version,wholeGoalComplete:false,requirements,sources:sources.length,evidence:evidence.length,syntax:syntax.length,documentLinks:links.length});
