import {readFile,writeFile,mkdir,copyFile,stat} from 'node:fs/promises';import {resolve} from 'node:path';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';import assert from 'node:assert/strict';
const out=resolve('qa/v94/final');await mkdir(out,{recursive:true});
const sources=['package.json','src/app.js','src/harbor.js','src/characters.js','src/garmentArt.js','src/rasterQuality.js','src/rasterQualityWorker.js','src/rasterProcessing.js','src/houseAtlasBounds.js','src/themeArtwork.js','tools/build-house-bounds.py','tests/fixtures/raster-pre-v94.js','tests/v94-raster.test.mjs','tests/v94-cold-raster-browser.mjs','tests/v94-raster-parity-browser.mjs','tests/v94-save-continuity.mjs','tests/v94-live-files.mjs','tests/v94-freeze.mjs','docs/current-baseline-v94.md','docs/delivery-goal-v25.json','docs/acceptance-countdown-20261007.md','README.md'];
const evidence=['qa/v94/cold-before/report.json','qa/v94/cold-current/report.json','qa/v94/cold-fractional/report.json','qa/v94/cold-current/pixel-cold.json','qa/v94/cold-current/origami-cold.json','qa/v94/parity/report.json','qa/v94/stage-render/report.json','qa/v94/default-regression.log','qa/v94/render-rules.log','qa/v94/live-files.json','qa/v94/deployment.json','qa/v94/save-continuity-before.json','qa/v94/save-continuity-after.json','qa/v94/cold-theme-final/report.json','qa/v94/cold-verified/report.json','qa/v94/cold-current/pixel-100.png','qa/v94/cold-current/origami-100.png','qa/v94/cold-current/pixel-300.png','qa/v94/cold-current/origami-300.png','qa/v94/cold-current/pixel-switched.png','qa/v94/cold-current/origami-switched.png','qa/v94/stage-render/pixel-stage.png','qa/v94/stage-render/origami-stage.png','qa/v94/stage-render/pixel-stage-390.png','qa/v94/stage-render/origami-stage-390.png'];
const hash=b=>createHash('sha256').update(b).digest('hex'),records=[];
for(const file of [...sources,...evidence]){const bytes=await readFile(file),target=file.replaceAll('/','__');await copyFile(file,resolve(out,target));records.push({file,bytes:bytes.length,sha256:hash(bytes),frozen:target});}
const syntax=[];for(const file of sources.filter(p=>/\.(js|mjs)$/.test(p))){execFileSync(process.execPath,['--check',file]);syntax.push(file);}
for(const [file,count]of [['qa/v94/default-regression.log',527],['qa/v94/render-rules.log',12]]){const text=await readFile(file,'utf8');assert.match(text,new RegExp('pass '+count));assert.match(text,/fail 0/);}
for(const file of ['qa/v94/cold-current/report.json','qa/v94/cold-fractional/report.json','qa/v94/stage-render/report.json']){const r=JSON.parse(await readFile(file,'utf8'));assert(r.passed&&r.checks.length===2);assert.deepEqual(r.errors,[]);assert.deepEqual(r.badAssets,[]);}
const parity=JSON.parse(await readFile('qa/v94/parity/report.json','utf8'));assert(parity.passed&&parity.checks.length===8);assert(parity.checks.every(c=>c.max===0&&c.crops.every(x=>x.max===0)));assert.equal(parity.fallback.max,0);
const tracker=JSON.parse(await readFile('docs/delivery-goal-v25.json','utf8')),requirements=Object.fromEntries(['complete','in_progress'].map(status=>[status,tracker.requirements.filter(r=>r.status===status).length]));assert.equal(tracker.acceptanceDeadline.deadlineUTC,'2026-10-07T05:18:38.000Z');assert.deepEqual(requirements,{complete:4,in_progress:14});const links=[];
for(const p of ['docs/current-baseline-v94.md','README.md','docs/acceptance-countdown-20261007.md']){const txt=await readFile(p,'utf8');for(const match of txt.matchAll(/\[[^\]]*\]\(([^)]+)\)/g)){const target=match[1];if(/^(https?:|#)/.test(target)||target.includes('$'+'{'))continue;if(target==='../qa/v94/final/verification-summary.json')continue;await stat(resolve(p,'..',target));links.push({document:p,target});}}
const summary={version:'V94',at:new Date().toISOString(),deadline:tracker.acceptanceDeadline,wholeGoalComplete:false,requirements,formalArtifactsUpdated:false,savePerformanceRetested:false,coldStallsRemain:true,backendRestarted:false,newOfflineBackup:false,lastBackup:'V93 verified 789 files',proof:{defaultRules:527,renderRules:12,ruleSetsOverlap:true,artworkComparisons:8,cropComparisons:6,maximumRGBADelta:0,unsupportedWorkerShoreMaximumDelta:0,actualColdZoomThemeCases:4,steadyStageCases:2,servedFiles:29,onlineCurrentFiles:6},scope:'Real isolated browser artwork/rendering with provider calls blocked. Default and fractional DPR; actual protected theme switching. Not all scenes without stutter, full zero-resource growth, one-hour physical-device/human acceptance or new package/formal document delivery.',syntax,documentLinks:links.length,records};
await writeFile('qa/v94/doc-links.json',JSON.stringify({links},null,2));await writeFile(resolve(out,'verification-summary.json'),JSON.stringify(summary,null,2));console.log({version:summary.version,wholeGoalComplete:false,requirements,sources:sources.length,evidence:evidence.length,syntax:syntax.length,documentLinks:links.length});
