import {readFile,writeFile,mkdir,copyFile,stat} from 'node:fs/promises';import {resolve} from 'node:path';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';import assert from 'node:assert/strict';
const out=resolve('qa/v95/final');await mkdir(out,{recursive:true});const hash=b=>createHash('sha256').update(b).digest('hex'),parse=text=>JSON.parse(text.replace(/^\uFEFF/,''));
await copyFile('qa/v79/data-backup-report.json','qa/v95/backup-regression.json');
const sources=['server/saveBootstrap.mjs','server/saveImportIO.mjs','server/saveStore.mjs','server/fieldActions.mjs','server/residentActions.mjs','server/dataBackup.mjs','server/lanTenantServices.mjs','server/lanServer.mjs','server.mjs','src/saveClient.js','src/saveUI.js','src/save-import-v95.css','index.html','package.json','tests/v95-save-trust.test.mjs','tests/v95-save-trust-browser.mjs','tests/v95-save-continuity.mjs','tests/v95-live-files.mjs','tests/v95-freeze.mjs','tests/fixtures/trusted-initial-state.mjs','tests/v74-travel-fixture.mjs','tests/v58-lan-fixtures.mjs','tests/v57-lan-activities.test.mjs','tests/v57-lan-http.test.mjs','tests/save-journal-20261006-browser.mjs','docs/current-baseline-v95.md','docs/delivery-goal-v25.json','docs/acceptance-countdown-20261007.md','docs/data-backup-v79.md','README.md'];
const evidence=['qa/v95/default-tests.log','qa/v95/trust-rules.log','qa/v95/save-regression.log','qa/v95/browser/report.json','qa/v95/journal/journal-report.json','qa/v95/backup-regression.json','qa/v95/backup-create.json','qa/v95/backup-verify.json','qa/v95/deployment.json','qa/v95/live-files.json','qa/v95/save-continuity-before.json','qa/v95/save-continuity-after.json','qa/v95/default-first.log','qa/v95/journal/initial-failure.json',...['pixel','origami'].flatMap(t=>['migration','preview-desktop','preview-mobile','lost-response','recovered'].map(k=>'qa/v95/browser/'+t+'-'+k+'.png'))];
const records=[];for(const file of [...sources,...evidence]){const bytes=await readFile(file),target=file.replaceAll('/','__');await copyFile(file,resolve(out,target));records.push({file,bytes:bytes.length,sha256:hash(bytes),frozen:target});}
const syntax=[];for(const file of sources.filter(f=>/\.(js|mjs)$/.test(f))){execFileSync(process.execPath,['--check',file]);syntax.push(file);}
for(const[file,count]of [['qa/v95/default-tests.log',540],['qa/v95/trust-rules.log',21],['qa/v95/save-regression.log',28]]){const t=await readFile(file,'utf8');assert.match(t,new RegExp('pass '+count));assert.match(t,/fail 0/);}
for(const file of ['qa/v95/browser/report.json','qa/v95/journal/journal-report.json']){const r=parse(await readFile(file,'utf8'));assert(r.passed&&r.checks.length===2);assert.deepEqual(r.errors,[]);}
const backup=parse(await readFile('qa/v95/backup-verify.json','utf8'));assert(backup.ok&&backup.verified&&backup.files===788);assert.deepEqual(backup.warnings,[]);const live=parse(await readFile('qa/v95/live-files.json','utf8'));assert.equal(live.checks.length,20);
const continuity=parse(await readFile('qa/v95/save-continuity-after.json','utf8'));assert.equal(continuity.files,6);assert(continuity.changes.every(c=>c.worldPreserved!==false&&c.partsUnchanged!==false));
const tracker=parse(await readFile('docs/delivery-goal-v25.json','utf8')),requirements=Object.fromEntries(['complete','in_progress'].map(s=>[s,tracker.requirements.filter(r=>r.status===s).length]));assert.deepEqual(requirements,{complete:4,in_progress:14});assert.equal(tracker.acceptanceDeadline.deadlineUTC,'2026-10-07T05:18:38.000Z');
const links=[];for(const file of ['docs/current-baseline-v95.md','docs/data-backup-v79.md','docs/acceptance-countdown-20261007.md','README.md'])for(const m of (await readFile(file,'utf8')).matchAll(/\[[^\]]*\]\(([^)]+)\)/g)){const target=m[1];if(/^(https?:|#)/.test(target)||target.includes('$'+'{')||target==='../qa/v95/final/verification-summary.json')continue;await stat(resolve(file,'..',target));links.push({document:file,target});}
const deployment=parse(await readFile('qa/v95/deployment.json','utf8')),manifest=await readFile(resolve(deployment.backup,'manifest.json'));
const summary={version:'V95',at:new Date().toISOString(),deadline:tracker.acceptanceDeadline,wholeGoalComplete:false,requirements,formalArtifactsUpdated:false,savePerformanceRetested:false,coldStallsRemain:true,backendRestarted:true,offlineBackup:{id:backup.id,files:backup.files,verified:true,warnings:[],manifestSha256:hash(manifest)},proof:{newTrustRules:13,relatedRules:21,defaultRules:540,saveRules:28,backupAndEconomyRules:23,ruleSetsOverlap:true,actualImportThemes:2,actualJournalThemes:2,servedFiles:20,currentFiles:6},scope:'Actual isolated local save/import UI and durable journal, with provider calls blocked and gameplay paused for import QA. Not full zero-growth gameplay, one-hour performance, human/physical multi-device acceptance, complete anti-cheat or new package/formal document delivery.',syntax,documentLinks:links.length,records};
await writeFile('qa/v95/doc-links.json',JSON.stringify({links},null,2));await writeFile(resolve(out,'verification-summary.json'),JSON.stringify(summary,null,2));console.log({version:'V95',sources:sources.length,evidence:evidence.length,syntax:syntax.length,documentLinks:links.length,requirements,wholeGoalComplete:false});
