import test from 'node:test';import assert from 'node:assert/strict';import {resolve,join} from 'node:path';import {readFile} from 'node:fs/promises';
import {deploymentPlan,nodeSupported,parseArguments} from '../tools/agent-deploy.mjs';import {darwinLegacyProcesses} from '../server/dataLease.mjs';import {resolveRuntimePaths} from '../server/runtimeConfig.mjs';
test('Windows, Apple Silicon, Intel Mac and Linux plans use native venv paths and explicit argv',()=>{for(const [platform,arch] of [['win32','x64'],['darwin','arm64'],['darwin','x64'],['linux','x64'],['linux','arm64']]){const root=resolve('qa/agent source with spaces'),p=deploymentPlan({root,platform,arch});assert.equal(p.python,join(root,'.runtime/python',platform==='win32'?'Scripts/python.exe':'bin/python'));assert.equal(p.shell,false);assert.equal(p.args[0],join(root,'server/lanServer.mjs'));assert.equal(p.url,'http://127.0.0.1:4175/play');assert(!JSON.stringify(p).includes('actual-key'));}});
test('deployment does not allow unsupported modes, ports, hosts or platforms',()=>{for(const options of [{mode:'wrong'},{port:0},{port:65536},{port:'$()'},{host:'public.invalid'},{mode:'pixel',host:'0.0.0.0'},{platform:'freebsd'},{platform:'win32',arch:'arm64'}])assert.throws(()=>deploymentPlan({root:resolve('.'),...options}));});
test('deployment CLI accepts literal executable paths and rejects unknown commands/flags',()=>{assert.deepEqual(parseArguments(['setup','--python=C:/Python Dir/python.exe','--offline']),{command:'setup',options:{python:'C:/Python Dir/python.exe',offline:true}});assert.throws(()=>parseArguments(['wipe']));assert.throws(()=>parseArguments(['setup','--reset']));assert.throws(()=>parseArguments(['run','--port']));});
test('Node runtime gate matches real source support, including the 23.4 minimum',()=>{for(const v of ['22.13.0','23.4.0','24.19.0','25.8.1'])assert(nodeSupported(v));for(const v of ['21.9.0','22.12.0','23.3.0'])assert(!nodeSupported(v));});
test('Mac runtime uses bin/python when locally installed and never a Windows fallback',()=>{for(const exists of [()=>false,f=>f.includes('.runtime')]){const root=resolve('qa/mac source'),p=resolveRuntimePaths({root,platform:'darwin',exists});assert.equal(p.install,join(root,'.runtime/hermes-agent'));assert(p.hermesPython.replaceAll('\\','/').endsWith('bin/python'));assert(!p.hermesPython.includes('Scripts'));assert(!p.documentPython.includes('codex-primary-runtime'));}});
function fakeProcesses(rows,details){return async(exe,args)=>{if(args[0]==='-axo')return{stdout:rows};const pid=args[args.indexOf('-p')+1],d=details[pid];if(!d)throw Object.assign(Error('Gone'),{code:1});if(exe==='/bin/ps')return{stdout:d.command+'\n'};if(d.error)throw Object.assign(Error('Denied'),{code:d.error});return{stdout:'p'+pid+'\nn'+d.cwd+'\n'};};}
test('Mac legacy process check matches actual project cwd and absolute scripts with spaces',async()=>{const root=resolve('qa/project with spaces'),other=resolve('qa/other'),rows='998881 node server.mjs\n998882 node '+join(root,'server/lanAgentWorker.mjs')+'\n998883 node server.mjs\n998884 python server.mjs\n';const ids=await darwinLegacyProcesses(root,{execute:fakeProcesses(rows,{'998881':{command:'/usr/local/bin/node',cwd:root},'998882':{command:'/opt/homebrew/bin/node',cwd:other},'998883':{command:'/usr/local/bin/node',cwd:other},'998884':{command:'/usr/bin/python',cwd:root}})});assert.deepEqual(ids,[998881,998882]);});
test('Mac inspection uses argument arrays and refuses live ambiguous inspection failures',async()=>{let called=false;await assert.rejects(darwinLegacyProcesses(resolve('qa/mac'),{execute:async(exe,args)=>{assert(Array.isArray(args));called=true;if(args[0]==='-axo')return{stdout:'998887 node server.mjs\n'};if(exe==='/bin/ps')return{stdout:'/usr/bin/node\n'};throw Object.assign(Error('Denied'),{code:'EACCES'});}}),e=>e.code==='data_process_unverified');assert(called);});
test('Mac vanished process is ignored without touching unrelated processes',async()=>{assert.deepEqual(await darwinLegacyProcesses(resolve('qa/mac'),{execute:fakeProcesses('998889 node server.mjs\n',{})}),[]);});
test('source installer rebuilds environments without destructive clearing or shell execution',async()=>{const py=await readFile(new URL('../tools/agent-install.py',import.meta.url),'utf8');assert(py.includes("'Scripts/python.exe' if os.name=='nt' else 'bin/python'"));assert(py.includes('--require-hashes'));assert(py.includes('--only-binary=:all:'));assert(!py.includes('rmtree'));assert(!py.includes('shell=True'));assert(py.includes('Existing environment differs; preserve it'));});
