import {assertResourceState} from '../server/resourceAuthority.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import {mkdir,mkdtemp,readFile,writeFile} from 'node:fs/promises';import {join,resolve} from 'node:path';import {createHash} from 'node:crypto';
import {setup} from './v93-hosting-fixture.mjs';import {finish} from './v92-cooperation-fixture.mjs';import {createSaveStore,validateState} from '../server/saveStore.mjs';
import {syncWonders,awardNightCooperation,awardCoutureWonder,setWonderDisplay,NATIVE_WONDER_IDS_V98} from '../src/eventWonders.js';
import {wonderPlacements} from '../src/fishingWonderArt.js';import {setWorldTheme,setWorldDisplayColliders,worldWalkable,findPath,SLOTS,HARBOR} from '../src/world.js';import {checkDecoration} from '../src/placements.js';
import {assertWonderState,validWonderBook} from '../server/wonderAuthority.mjs';
export async function completed(template,theme,{fireworks=false}={}){const f=await setup(template,theme);if(template==='night'&&fireworks){const d=await f.current();await f.manage('night_update',{proposal:{...d.state.nightParty.draft,fireworks:true}});}await f.invite();await f.begin();const result=await finish(f);return{f,result};}
for(const theme of ['pixel','origami'])test(theme+' real server replay awards ordinary/exceptional night and couture memorabilia once, preserves all cash/material formulas and survives disk reload',async()=>{
 const plain=await completed('night',theme),p=plain.result.document.state;assert(p.eventWonders.owned.island_pinwheel);assert(!p.eventWonders.owned.starlit_diorama);assert.equal(plain.result.receipt.score,4);assert.equal(plain.result.receipt.reward,28);
 const bright=await completed('night',theme,{fireworks:true}),s=bright.result.document.state;assert(s.eventWonders.owned.island_pinwheel);assert.equal(s.eventWonders.owned.starlit_diorama.rarity,'SR');assert.equal(bright.result.receipt.reward,31);assert.equal(s.inventory.firework,19);
 const fashion=await completed('couture',theme),c=fashion.result.document.state,g=c.coutureParty.session;assert.equal(g.result.completed,3);assert(g.result.quality>=85);assert.equal(g.result.poseHits,12);assert(c.eventWonders.owned.couture_ribbon);assert(c.eventWonders.owned.muse_wardrobe);assert.equal(c.eventWonders.owned.muse_wardrobe.rarity,'SR');
 for(const {f,result}of [plain,bright,fashion]){const d=result.document,old=structuredClone(d.state.eventWonders),coins=d.state.coins,inventory=structuredClone(d.state.inventory);for(let n=0;n<5;n++)syncWonders(d.state);assert.deepEqual(d.state.eventWonders,old);assert.equal(d.state.coins,coins);assert.deepEqual(d.state.inventory,inventory);const t=result.ticket;const replay=await f.other().action(theme,{kind:f.config.kind,operation:'finish',requestId:t.requestId,epoch:t.epoch,sequence:t.sequence,expectedVersion:'lost response'});assert(replay.replayed);assert.deepEqual(replay.document.state.eventWonders,old);assert(validWonderBook(replay.document.actions.wonders));const disk=await f.other().current(theme);assert.deepEqual(disk.state.eventWonders,old);validateState(disk.state,theme);}
 await mkdir('qa/v98',{recursive:true});await writeFile('qa/v98/'+theme+'-earned.json',JSON.stringify({scope:'Actual server input replays, isolated progressed stock, injected time and attendance; no model or human claims',theme,nightDirectory:bright.f.directory,coutureDirectory:fashion.f.directory,ordinary:p.eventWonders.owned.island_pinwheel,exceptional:s.eventWonders.owned.starlit_diorama,fashion:c.eventWonders.owned.muse_wardrobe,coutureQuality:g.result.quality,cashUnchanged:true,duplicateStable:true,reloaded:true},null,2));
});
test('no award for missing payment, cancelled or partial outcomes; forged display rewards/marks/control are rejected while display requests remain independent',async()=>{
 const {f,result}=await completed('night','pixel',{fireworks:true}),d=result.document,g={...d.state.nightParty.history.at(-1),id:d.state.nightParty.history.at(-1).eventId};
 for(const change of [x=>delete x.economy.cashReceipts[g.id],x=>delete x.resourceLedger.receipts['cash:'+g.id],x=>x.resourceLedger.receipts['cash:'+g.id+':entry'].delta.firework=0]){const s=structuredClone(d.state);change(s);const old=structuredClone(s.eventWonders);assert.equal(awardNightCooperation(s,g).ok,false);assert.deepEqual(s.eventWonders,old);}
 for(const phase of ['draft','running','cancelled'])assert.equal(awardNightCooperation(structuredClone(d.state),{...g,phase}).ok,false);
 for(const edit of [s=>s.eventWonders.owned.island_pinwheel.marks++,s=>delete s.eventWonders.owned.starlit_diorama,s=>s.wonderControl.version=99,s=>s.eventWonders.receipts['wonder:island_pinwheel:fake']=true]){const s=structuredClone(d.state);edit(s);await assert.rejects(f.store.save('pixel',{state:s,expectedVersion:d.version}),e=>e.code==='wonder_state_conflict');}
 const s=structuredClone(d.state);setWonderDisplay(s,'island_pinwheel',true);const saved=await f.store.save('pixel',{state:s,expectedVersion:d.version});assert(saved.document.state.eventWonders.displays.island_pinwheel);assertWonderState(saved.document.state,saved.document.actions);
});
test('trusted old server document backfills and seals memorabilia once; empty first client cannot invent reward ownership',async()=>{
 const {f,result}=await completed('night','origami',{fireworks:true}),d=structuredClone(result.document);delete d.actions.wonders;delete d.state.wonderControl;for(const id of NATIVE_WONDER_IDS_V98)delete d.state.eventWonders.owned[id];for(const k of Object.keys(d.state.eventWonders.receipts))if(k.startsWith('wonder:'))delete d.state.eventWonders.receipts[k];const hash=x=>createHash('sha256').update(JSON.stringify(x)).digest('hex');d.checksum=hash(d.state);d.actionsChecksum=hash(d.actions);await writeFile(join(f.directory,'origami/current.json'),JSON.stringify(d));const opened=await f.other().openClient('origami');assert.equal(opened.document.reason,'resource-migration');assert(opened.document.actions.personal&&opened.document.actions.resources);assertResourceState(opened.document.state,opened.document.actions);assert(opened.document.state.eventWonders.owned.starlit_diorama);assert(validWonderBook(opened.document.actions.wonders));const again=await f.other().openClient('origami');assert.equal(again.document.version,opened.document.version);assert.deepEqual(again.document.state.eventWonders,opened.document.state.eventWonders);
 const directory=await mkdtemp(resolve('qa/v98/zero-')),fresh=createSaveStore({directory}),first=await fresh.openClient('pixel',{legacyState:d.state}),bad=structuredClone(first.document.state);assert.equal(bad.coins,0);assert(Object.values(bad.inventory).every(n=>n===0));bad.eventWonders.owned.island_pinwheel=structuredClone(result.document.state.eventWonders.owned.island_pinwheel);await assert.rejects(fresh.save('pixel',{state:bad,expectedVersion:first.document.version}),e=>e.code==='wonder_state_conflict');
});
test('all eight exhibit sites coexist in both styles with walkable entrances and ferry routes; decoration cannot consume reserved future sites',()=>{
 for(const theme of ['pixel','origami']){setWorldTheme(theme);const ids=['seashell_cup','cooperation_monument','market_lantern','couture_ribbon','fireworks_orbit',...NATIVE_WONDER_IDS_V98],s={eventWonders:{owned:Object.fromEntries(ids.map(id=>[id,{}])),displays:Object.fromEntries(ids.map(id=>[id,true])),displayed:'seashell_cup'}};const p=wonderPlacements(s,SLOTS);assert.equal(p.length,8);setWorldDisplayColliders(p);try{for(const pos of p)assert(!worldWalkable(pos.x,pos.y));for(const slot of SLOTS)assert(findPath(HARBOR.gate,slot.entry).length,theme+' entrance '+slot.id);for(const id of NATIVE_WONDER_IDS_V98){const pos=p.find(p=>p.id===id),r=checkDecoration({placedItems:[]},{item:'c0_6',x:pos.x,y:pos.y,rotation:0},{theme});assert(!r.ok);assert.match(r.reason,/奇观陈列位/);}}finally{setWorldDisplayColliders([]);}}
});

test('a second real qualified night adds exactly one imprint after 900 accepted active seconds, then retry/reopen stays stable',async()=>{
 const {f,result}=await completed('night','pixel',{fireworks:true}),first=result.document.state.eventWonders.owned.starlit_diorama,day=result.document.state.day;
 for(let i=0;i<60;i++){f.advance(15000);const d=await f.current();await f.store.save('pixel',{state:d.state,expectedVersion:d.version,activeSeconds:15});}
 assert.equal((await f.current()).state.day,day+1);
 await f.manage('night_create',{proposal:{template:'night',name:'又一场认真准备的星灯夜集',description:'不同活动的纪念需要真实再次完成。',tags:['stars'],difficulty:'normal',guestId:null,fireworks:true}});await f.invite();await f.begin();const again=await finish(f),s=again.document.state;
 assert.notEqual(s.eventWonders.owned.starlit_diorama.eventId,again.receipt.eventId);assert.equal(s.eventWonders.owned.starlit_diorama.eventId,first.eventId);for(const id of ['island_pinwheel','starlit_diorama']){assert.equal(s.eventWonders.owned[id].wins,2);assert.equal(s.eventWonders.owned[id].marks,1);assert.equal(Object.keys(s.eventWonders.receipts).filter(k=>k.startsWith('wonder:'+id+':')).length,2);}
 const stable=structuredClone(s.eventWonders);syncWonders(s);assert.deepEqual(s.eventWonders,stable);const t=again.ticket,retry=await f.other().action('pixel',{kind:'party',operation:'finish',requestId:t.requestId,epoch:t.epoch,sequence:t.sequence,expectedVersion:'lost response'});assert(retry.replayed);assert.deepEqual(retry.document.state.eventWonders,stable);assert.deepEqual((await f.other().current('pixel')).state.eventWonders,stable);
});
