import {assertResourceState} from '../server/resourceAuthority.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import {writeFile,mkdir,readFile} from 'node:fs/promises';import {join} from 'node:path';import {randomUUID,createHash} from 'node:crypto';
import {fixture,produce,start,finish,fixtureProof,CONFIG} from './v92-cooperation-fixture.mjs';import {completed} from './v98-wonders.test.mjs';
import {archiveRecruitment,finishRecruitmentDeparture} from '../src/recruitment.js';import {validActionBook} from '../server/playerActions.mjs';import {validWonderBook} from '../server/wonderAuthority.mjs';import {syncWonders,setWonderDisplay,validEventWonders} from '../src/eventWonders.js';import {setWorldTheme,setWorldDisplayColliders,SLOTS,HARBOR,findPath} from '../src/world.js';import {wonderPlacements} from '../src/fishingWonderArt.js';import {checkDecoration} from '../src/placements.js';
async function newDay(f){for(let i=0;i<60;i++){f.advance(15000);const d=await f.current();await f.store.save(f.theme,{state:d.state,expectedVersion:d.version,activeSeconds:15});}}
async function depart(f){const id=(await f.current()).state.recruitment.active.id;await f.registry.cancel(f.theme,await f.current(),id);await f.manage('hire_handover',{contractId:id});await f.save(s=>{assert(finishRecruitmentDeparture(s));});await f.registry.departed(f.theme,await f.current(),id);await f.save(s=>assert(archiveRecruitment(s,id)));}
async function next(f){await depart(f);await newDay(f);await f.manage('night_create',{proposal:{template:'night',name:'伙伴的又一场星灯夜集',description:'每次都用新的实际交付准备本场活动。',tags:['stars'],difficulty:'normal',guestId:null,fireworks:false}});const plan=await f.manage('night_plan');f.projectId=plan.receipt.details.project.id;const c=(await f.registry.start(f.theme,await f.current(),{requestId:randomUUID(),candidateId:'mai',projectId:f.projectId})).contract,run=fixtureProof(c.context);assert(run.child.acceptedSteps.length);await f.registry.complete(f.theme,c.id,c.attempt,run);f.contract=(await f.registry.activate(f.theme,await f.current(),c.id)).contract;f.run=run;await f.call('commerce','hire_bind',{contractId:c.id});await f.save(s=>{s.recruitment.active.phase='working';s.recruitment.active.hasArrived=true;});}
for(const theme of ['pixel','origami'])test(theme+' ten actually protected recruited deliveries and finished nights on ONE island unlock one SSR; historical replay, disk reopen and forged saves cannot increase it',{timeout:360000},async()=>{
 const f=await fixture('night',theme,{nonTargetStock:240}),events=[];let done;const total=theme==='pixel'?20:10;for(let i=0;i<total;i++){if(i)await next(f);await produce(f);await start(f);done=await finish(f);const s=done.document.state,b=done.document.actions;events.push(done.ticket.eventId);assert.equal(Object.keys(s.wonderControl.cooperations).length,i+1);assert.equal(!!s.eventWonders.owned.cooperation_tree,i>=9);assert(validActionBook(b));assert(validWonderBook(b.wonders));assert(validEventWonders(s));}
 const s=done.document.state,a=s.eventWonders.owned.cooperation_tree;assert.equal(a.rarity,'SSR');assert.equal(a.marks,Math.floor(total/10)-1);assert.equal(a.wins,Math.floor(total/10));assert.equal(a.proof.length,10);assert.equal(new Set(a.proof.map(p=>p.operationId)).size,10);assert.equal(new Set(a.proof.map(p=>p.contractId)).size,10);assert.equal(a.cooperationEvents.length,10);const stable=structuredClone(s.eventWonders),coins=s.coins,inv=structuredClone(s.inventory);syncWonders(s);syncWonders(s);assert.deepEqual(s.eventWonders,stable);assert.equal(s.coins,coins);assert.deepEqual(s.inventory,inv);
 const t=done.ticket,replayed=await f.other().action(theme,{kind:'party',operation:'finish',requestId:t.requestId,epoch:t.epoch,sequence:t.sequence,expectedVersion:'lost response'});assert(replayed.replayed);assert.deepEqual(replayed.document.state.eventWonders,stable);
 for(const change of [s=>delete s.wonderControl.cooperations[events[0]],s=>s.wonderControl.cooperations[events[0]].proof[0].amount++,s=>s.eventWonders.owned.cooperation_tree.marks++,s=>delete s.eventWonders.owned.cooperation_tree,s=>s.eventWonders.receipts['wonder:cooperation_tree:invented']=true]){const x=structuredClone(s);change(x);await assert.rejects(f.store.save(theme,{state:x,expectedVersion:done.document.version}),e=>e.code==='wonder_state_conflict');}
 const x=structuredClone(s);setWonderDisplay(x,'cooperation_tree',true);const saved=await f.store.save(theme,{state:x,expectedVersion:done.document.version});assert(saved.document.state.eventWonders.displays.cooperation_tree);assert.deepEqual((await f.other().current(theme)).state.eventWonders,saved.document.state.eventWonders);
 await mkdir('qa/v99',{recursive:true});await writeFile('qa/v99/'+theme+'-tree-earned.json',JSON.stringify({directory:f.directory,theme,events,proof:a.proof,scope:'One isolated progressed island, non-target stock240 but each new wood/lantern deficit requires real production; ten real protected production/party transactions; canonical synthetic lineage, injected clock/attendance/departure, no providers or humans'},null,2));
});
test('all five completed templates record actual new main/sub contribution; ordinary unassisted events and cancelled acts do not progress the SSR',async()=>{
 for(const template of Object.keys(CONFIG)){const f=await fixture(template);await produce(f);await start(f);const d=await finish(f);assert.equal(Object.keys(d.document.state.wonderControl.cooperations).length,1);}
 const {result}=await completed('night','pixel');assert.equal(Object.keys(result.document.state.wonderControl.cooperations).length,0);
 const f=await fixture('night');await produce(f);const begun=await start(f);await f.call('party','cancel',{requestId:begun.ticket.requestId,epoch:begun.ticket.epoch,sequence:begun.ticket.sequence});assert.equal(Object.keys((await f.current()).state.wonderControl.cooperations).length,0);
});
test('V98 server book upgrades and freezes existing qualified history once without changing cash or inventory',async()=>{
 const f=await fixture('night');await produce(f);await start(f);const done=await finish(f),d=structuredClone(done.document),coins=d.state.coins,inventory=structuredClone(d.state.inventory);d.actions.wonders.version=1;delete d.actions.wonders.cooperations;delete d.actions.wonders.visits;delete d.actions.wonders.lanEvents;delete d.actions.wonders.externalRequests;d.state.wonderControl={version:1};const hash=x=>createHash('sha256').update(JSON.stringify(x)).digest('hex');d.checksum=hash(d.state);d.actionsChecksum=hash(d.actions);await writeFile(join(f.directory,'pixel/current.json'),JSON.stringify(d));const opened=await f.other().openClient('pixel');assert.equal(opened.document.reason,'resource-migration');assert(opened.document.actions.personal&&opened.document.actions.resources);assertResourceState(opened.document.state,opened.document.actions);assert.equal(opened.document.state.wonderControl.version,3);assert.equal(Object.keys(opened.document.state.wonderControl.cooperations).length,1);assert.equal(opened.document.state.coins,coins);assert.deepEqual(opened.document.state.inventory,inventory);assert.equal((await f.other().openClient('pixel')).document.version,opened.document.version);
});
test('ten coexisting exhibits retain all doors/ferry routes, and future tree site cannot be consumed by furniture',()=>{
 for(const theme of ['pixel','origami']){setWorldTheme(theme);const ids=['archipelago_lighthouse','cooperation_tree','seashell_cup','cooperation_monument','market_lantern','couture_ribbon','fireworks_orbit','island_pinwheel','starlit_diorama','muse_wardrobe'],s={eventWonders:{owned:Object.fromEntries(ids.map(id=>[id,{}])),displays:Object.fromEntries(ids.map(id=>[id,true])),displayed:'seashell_cup'}};const places=wonderPlacements(s,SLOTS);assert.equal(places.length,10);setWorldDisplayColliders(places);try{for(const slot of SLOTS)assert(findPath(HARBOR.gate,slot.entry).length,theme+' door '+slot.id);const pos=places.find(x=>x.id==='cooperation_tree');assert.equal(checkDecoration({placedItems:[]},{item:'c0_6',x:pos.x,y:pos.y,rotation:0},{theme}).ok,false);}finally{setWorldDisplayColliders([]);}}
});
