import {mkdir,readFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {randomBytes,randomUUID,createHash} from 'node:crypto';
import {atomicJSON} from './atomicJson.mjs';
const hash=v=>createHash('sha256').update(typeof v==='string'?v:JSON.stringify(v)).digest('hex');
const clone=structuredClone;
const fail=(message,code='bridge_invalid',status=409)=>Object.assign(Error(message),{code,status});
const uuid=v=>typeof v==='string'&&/^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$/.test(v);
const methods=new Set(['command','steward','a2a','recruit','cancelRecruit','suggestParty','list','project','detail','preview','download','ledger','policy']);
const terminal=new Set(['completed','failed','unconfirmed','cancelled']);
const checksum=v=>hash({...v,checksum:undefined});
const text=(v,n)=>typeof v==='string'?v.trim().slice(0,n):'';
export const BRIDGE_BODY_BYTES=64*1024*1024;
export function createDeviceBridgeStore({directory,identities,now=Date.now,callTimeoutMs=260000,onlineMs=45000}){
 const root=resolve(directory,'_lan','device-bridge'),file=resolve(root,'registry.json');let state=null,tail=Promise.resolve(),closed=false;
 const waiters=new Map(),jobCache=new Map();
 function lock(fn){const next=tail.then(fn,fn);tail=next.catch(()=>{});return next;}
 async function load(){if(state)return state;await mkdir(root,{recursive:true});try{const s=JSON.parse(await readFile(file,'utf8'));if(s.schema!==1||!s.devices||!s.pairs||s.checksum!==checksum(s))throw Error();state=s;}catch(e){if(e.code!=='ENOENT')throw fail('原机配对记录无法核验，文件已保留','bridge_corrupt',503);state={schema:1,pairs:{},devices:{}};}return state;}
 async function save(){state.updatedAt=now();state.checksum=checksum(state);await atomicJSON(file,state);}
 async function owner(token){const a=await identities.authorize(token);if(!uuid(a.id))throw fail('岛主身份无效','bridge_owner',403);return a.id;}
 const online=d=>!!d&&d.phase==='approved'&&d.active&&now()-(d.lastSeen||0)<=onlineMs;
 const active=id=>Object.values(state?.devices||{}).find(d=>d.ownerId===id&&d.active&&d.phase==='approved');
 const publicDevice=d=>d?{id:d.id,name:d.name,platform:d.platform,workspace:d.workspace,verification:d.verification,phase:d.phase,active:!!d.active,online:online(d),lastSeen:d.lastSeen||null,createdAt:d.createdAt}:null;
 async function device(secret){await load();if(typeof secret!=='string'||!/^device-[a-f0-9]{64}$/.test(secret))throw fail('原机凭证无效','bridge_credential',401);const digest=hash(secret),d=Object.values(state.devices).find(d=>d.secretDigest===digest);if(!d||d.phase==='revoked')throw fail('原机已解绑，请重新配对','bridge_revoked',403);return d;}
 async function approved(secret){const d=await device(secret);if(d.phase!=='approved'||!d.active)throw fail('等待岛主确认这台原机','bridge_approval_pending',423);return d;}
 async function readJob(id){if(!uuid(id))throw fail('委托编号无效','bridge_job',400);if(jobCache.has(id))return jobCache.get(id);try{const j=JSON.parse(await readFile(resolve(root,'job-'+id+'.json'),'utf8'));if(j.schema!==1||j.id!==id||!uuid(j.ownerId)||!uuid(j.deviceId)||!methods.has(j.method)||j.checksum!==checksum(j))throw Error();jobCache.set(id,j);return j;}catch(e){if(e.code==='ENOENT')return null;throw fail('原机委托回执无法核验，请检查原机成果','bridge_job_corrupt',503);}}
 async function writeJob(j){j.updatedAt=now();j.checksum=checksum(j);await atomicJSON(resolve(root,'job-'+j.id+'.json'),j);jobCache.set(j.id,j);}
 function publish(j){const waiting=waiters.get(j.id);if(!waiting||!terminal.has(j.phase))return;clearTimeout(waiting.timer);waiters.delete(j.id);j.phase==='completed'?waiting.resolve(clone(j.result)):waiting.reject(fail(j.error||'原机执行结果尚待核对','bridge_'+j.phase,503));}
 async function finish(j,phase,error){j.phase=phase;j.error=error;await writeJob(j);publish(j);}
 async function view(token){const id=await owner(token);await load();const devices=Object.values(state.devices).filter(d=>d.ownerId===id),bound=active(id);return {ownerId:id,bound:publicDevice(bound),pending:devices.filter(d=>d.phase==='pending').map(publicDevice),history:devices.filter(d=>d.phase==='revoked').slice(-8).map(publicDevice),supports:['owner-documents','steward-a2a','parent-child-recruitment','work-artifacts'],serverFallback:!bound};}
 return {
  view,
  async authenticate(secret,pending=false){const d=pending?await device(secret):await approved(secret);return d.id;},
  async pair(token,input={}){const id=await owner(token);return lock(async()=>{await load();const nowAt=now();for(const [key,p]of Object.entries(state.pairs))if(p.expiresAt<nowAt||p.ownerId===id)delete state.pairs[key];const code='HD-'+randomBytes(10).toString('hex').toUpperCase();state.pairs[hash(code)]={ownerId:id,expiresAt:nowAt+600000};await save();return {code,expiresAt:nowAt+600000,ownerId:id};});},
  async enroll(input){return lock(async()=>{await load();const code=text(input.code,40).toUpperCase(),pair=state.pairs[hash(code)];if(!pair||pair.expiresAt<now())throw fail('配对码已失效，请重新生成','bridge_pair_expired',403);
   if(!uuid(input.deviceId)||typeof input.secret!=='string'||!/^device-[a-f0-9]{64}$/.test(input.secret)||!text(input.name,60)||!text(input.workspace,400))throw fail('请提供有效设备与选定工作区','bridge_enroll',400);
   const descriptor={id:input.deviceId,ownerId:pair.ownerId,secretDigest:hash(input.secret),name:text(input.name,60),platform:text(input.platform,60),workspace:text(input.workspace,400)},fingerprint=hash(descriptor),old=state.devices[input.deviceId];
   if(pair.deviceId){if(pair.deviceId!==input.deviceId||old?.enrollmentFingerprint!==fingerprint)throw fail('配对码已用于另一台设备','bridge_pair_used',409);return {device:publicDevice(old),ownerId:old.ownerId};}
   if(old)throw fail('设备编号已有记录，请使用新的配对记录','bridge_device_conflict',409);
   if(Object.values(state.devices).filter(d=>d.ownerId===pair.ownerId&&d.phase==='pending').length>=3)throw fail('有待确认设备，请先处理已有配对','bridge_pending_limit',409);
   const d={...descriptor,enrollmentFingerprint:fingerprint,verification:hash(input.secret+code).slice(0,6).toUpperCase(),phase:'pending',active:false,createdAt:now(),jobs:[]};state.devices[d.id]=d;pair.deviceId=d.id;await save();return {device:publicDevice(d),ownerId:d.ownerId};});},
  async approve(token,input){const id=await owner(token);return lock(async()=>{await load();const d=state.devices[input.deviceId];if(!d||d.ownerId!==id)throw fail('只能绑定自己的设备','bridge_owner',403);if(d.phase==='approved'&&d.active)return view(token);if(d.phase!=='pending'||input.verification!==d.verification)throw fail('请核对原机的六位确认标记','bridge_verification',409);
   const prior=active(id);if(prior){for(const jobId of prior.jobs){const j=await readJob(jobId);if(j&&!terminal.has(j.phase))throw fail('原机仍有委托，请先核对或解绑','bridge_busy',409);}prior.active=false;prior.phase='revoked';prior.revokedAt=now();}
   d.phase='approved';d.active=true;d.approvedAt=now();await save();return view(token);});},
  async revoke(token,input){const id=await owner(token);return lock(async()=>{await load();const d=state.devices[input.deviceId];if(!d||d.ownerId!==id)throw fail('只能解绑自己的设备','bridge_owner',403);if(d.phase==='revoked')return view(token);d.phase='revoked';d.active=false;d.revokedAt=now();await save();for(const jobId of d.jobs){const j=await readJob(jobId);if(j&&!terminal.has(j.phase))await finish(j,j.phase==='queued'?'cancelled':'unconfirmed','原机已解绑，进行中的结果请到原机核对；不会转交服务器重做。');}return view(token);});},
  async heartbeat(secret,input={}){return lock(async()=>{const d=await device(secret);d.lastSeen=now();if(input.status&&typeof input.status==='object'){const h=input.status.hermes||{},m=input.status.deepseek||{};d.runtimeStatus={hermes:{configured:h.configured===true&&h.model==='deepseek-flash',model:h.model==='deepseek-flash'?'deepseek-flash':null,verified:h.verified===true,calls:Number.isFinite(h.calls)?h.calls:0,lastError:text(h.lastError,160)},deepseek:{configured:m.configured===true,model:m.model==='deepseek-flash'?'deepseek-flash':null},automaticRequests:clone(input.status.automaticRequests||{})};}await save();return {device:publicDevice(d),ownerId:d.ownerId};});},
  async next(secret){return lock(async()=>{const d=await approved(secret);for(const id of d.jobs){const j=await readJob(id);if(!j||terminal.has(j.phase))continue;if(j.expiresAt<now()){await finish(j,j.phase==='queued'?'cancelled':'unconfirmed','原机委托超过核对时间，请先检查成果。');continue;}if(j.phase==='queued')j.phase='delivered';await writeJob(j);return {job:{id:j.id,ownerId:j.ownerId,deviceId:j.deviceId,method:j.method,args:clone(j.args),fingerprint:j.fingerprint,expiresAt:j.expiresAt}};}return {job:null};});},
  async claim(secret,input){return lock(async()=>{const d=await approved(secret),j=await readJob(input.jobId);if(!j||j.ownerId!==d.ownerId||j.deviceId!==d.id)throw fail('委托不属于这台原机','bridge_owner',403);if(j.fingerprint!==input.fingerprint)throw fail('委托内容与原记录不一致','bridge_job_fingerprint',409);if(terminal.has(j.phase))return {phase:j.phase};if(j.expiresAt<now()){await finish(j,'unconfirmed','原委托已过期，请核对原机成果。');return {phase:j.phase};}if(j.phase==='queued')throw fail('请先领取这项委托','bridge_job_phase',409);j.phase='running';j.startedAt??=now();await writeJob(j);return {phase:j.phase};});},
  async complete(secret,input){return lock(async()=>{const d=await approved(secret),j=await readJob(input.jobId);if(!j||j.ownerId!==d.ownerId||j.deviceId!==d.id)throw fail('回执不属于这台原机','bridge_owner',403);if(j.fingerprint!==input.fingerprint)throw fail('回执对应的委托已变化','bridge_job_fingerprint',409);const output=hash({result:input.result??null,error:input.error??null});if(j.outputDigest){if(j.outputDigest!==output)throw fail('原回执已登记，不能更换结果','bridge_result_conflict',409);return {phase:j.phase,replayed:true};}if(j.phase!=='running'&&!(j.phase==='unconfirmed'&&j.startedAt))throw fail('原委托已停止，请在原机检查成果','bridge_job_phase',409);
   j.outputDigest=output;if(input.error){j.phase='unconfirmed';j.error=text(input.error.message||input.error,400);}else{if(input.result===undefined)throw fail('请提供实际结果','bridge_result_invalid',400);j.phase='completed';j.result=clone(input.result);}j.finishedAt=now();await writeJob(j);publish(j);return {phase:j.phase,replayed:false};});},
  async bound(ownerId){await load();return publicDevice(active(ownerId));},
  descriptor(ownerId){return publicDevice(active(ownerId));},
  async runtimeStatus(ownerId){await load();const d=active(ownerId);if(!d)return null;const status=clone(d.runtimeStatus||{hermes:{configured:false,model:'deepseek-flash'},deepseek:{configured:false,model:'deepseek-flash'}});if(!online(d))status.hermes.configured=false;return {...status,deviceBridge:{supported:true,bound:true,online:online(d),device:publicDevice(d)},workspace:d.workspace};},
  async call(ownerId,method,args={}){if(closed)throw fail('原机桥接正在关闭','bridge_closed',503);if(!methods.has(method))throw fail('此操作不支持原机转发','bridge_method',400);
   const j=await lock(async()=>{await load();const d=active(ownerId);if(!d)throw fail('尚未绑定原机','bridge_not_bound',409);if(!online(d))throw fail('你的原机离线，本次未启动；连接原机后再寄出。','bridge_offline',503);
    const pending=[];for(const id of d.jobs){const old=await readJob(id);if(old&&!terminal.has(old.phase))pending.push(old);}if(pending.length>=6)throw fail('原机正在处理已有委托，请稍后再试','bridge_busy',429);if(d.jobs.length>=1000)throw fail('原机回执已达容量，请保留记录后整理','bridge_capacity',503);
    if(Buffer.byteLength(JSON.stringify(args))>1024*1024)throw fail('原机委托过大','bridge_body_size',413);const id=randomUUID(),job={schema:1,id,ownerId,deviceId:d.id,method,args:clone(args),fingerprint:hash([method,args]),requestId:method==='command'?args.requestId||null:null,worldKey:args.saveSlot||null,phase:'queued',createdAt:now(),expiresAt:now()+callTimeoutMs};await writeJob(job);d.jobs.push(id);try{await save();}catch(e){await finish(job,'cancelled','原机委托登记未完成，未派发执行。');throw e;}return job;});
   if(terminal.has(j.phase)){if(j.phase==='completed')return clone(j.result);throw fail(j.error,'bridge_unconfirmed',503);}
   return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{waiters.delete(j.id);void lock(async()=>{const current=await readJob(j.id);if(current&&!terminal.has(current.phase))await finish(current,current.phase==='queued'?'cancelled':'unconfirmed','原机回复超时，请先核对原机成果；不会重新执行。');}).catch(()=>{});reject(fail('原机回复超时，请先核对原机成果','bridge_timeout',503));},callTimeoutMs);waiters.set(j.id,{resolve,reject,timer});void lock(async()=>{const current=await readJob(j.id);if(current)publish(current);}).catch(e=>{clearTimeout(timer);waiters.delete(j.id);reject(e);});});
  },
  async recoverRequest(ownerId,requestId){await load();for(const d of Object.values(state.devices).filter(d=>d.ownerId===ownerId)){for(const id of d.jobs){const j=await readJob(id);if(j?.method==='command'&&j.requestId===requestId)return {id:j.id,theme:j.args?.theme,worldKey:j.worldKey,phase:j.phase,result:j.phase==='completed'?clone(j.result):null,device:publicDevice(d),finishedAt:j.finishedAt||null};}}return null;},
  async close(){closed=true;for(const w of waiters.values()){clearTimeout(w.timer);w.reject(fail('服务正在重启，原机委托不会自动重放','bridge_interrupted',503));}waiters.clear();await tail;}
 };
}
