import {lanWonderStep} from './lanWonderSettlement.mjs';
import {createLanSettlementCoordinator} from './lanSettlementCoordinator.mjs';import {createLanActivityEconomy,publicLanEconomy,LAN_ECONOMY_RULES} from './lanActivityEconomy.mjs';
import {mkdir,readFile,writeFile,rename,unlink,open,stat} from 'node:fs/promises';
import {resolve,join} from 'node:path';import {randomUUID,randomBytes,createHash} from 'node:crypto';
import {createCraftGame,applyCraftTrace,craftResult} from '../src/craftGameReplay.js';import {DEFAULT_RECIPES,ITEM_BY_ID} from '../src/contentCatalog.js';
import {GARMENTS,wornItems} from '../src/equipmentRules.js';import {availableQuantity} from '../src/resourceLedger.js';
const clone=v=>structuredClone(v),sha=v=>createHash('sha256').update(JSON.stringify(v)).digest('hex'),fail=(message,code='lan_event_conflict',status=409)=>Object.assign(Error(message),{code,status});
export const LAN_EVENT_KINDS=[{id:'tea',name:'海风茶会',building:1,brief:'一起把茶材配成对，泡好一桌迎客茶。'},{id:'fashion',name:'主题衣橱会',building:4,brief:'按主题完成搭配，给朋友展示你的衣橱灵感。'},{id:'pottery',name:'陶艺共作会',building:15,brief:'塑形、上釉和烧制，为聚会留下手作纪念。'},{id:'kitchen',name:'海边双灶会',building:2,brief:'分辨客人的订单，掌握切配与火候。'}].map(k=>({...k,recipeId:DEFAULT_RECIPES[k.building].id}));
const kinds=Object.fromEntries(LAN_EVENT_KINDS.map(k=>[k.id,k]));
const string=(v,min,max)=>{if(typeof v!=='string'||v.trim().length<min||v.trim().length>max||/[\u0000-\u001f]/.test(v))throw fail('活动文字长度或格式无效','lan_event_invalid',400);return v.trim();};
const strict=(v,keys)=>{if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).some(k=>!keys.includes(k)))throw fail('活动请求包含不支持的字段','lan_event_invalid',400);};
async function atomic(file,d){const tmp=file+'.'+randomUUID()+'.tmp';let h;try{h=await open(tmp,'wx',0o600);await h.writeFile(JSON.stringify(d));await h.sync();await h.close();h=null;await rename(tmp,file);}finally{await h?.close().catch(()=>{});await unlink(tmp).catch(()=>{});}}
export function createLanActivityStore({directory,identities,tenants,now=()=>Date.now(),settlementFault=()=>{}}){
 const root=resolve(directory,'_lan'),file=join(root,'activities.json'),previous=join(root,'activities.previous.json'),lock=join(root,'activities.lock');
 async function locked(fn){await mkdir(root,{recursive:true});const token=randomUUID(),start=Date.now();let acquired=false;while(!acquired){try{const f=await open(lock,'wx',0o600);await f.writeFile(JSON.stringify({pid:process.pid,token}));await f.close();acquired=true;}catch(e){if(e.code!=='EEXIST')throw e;try{const owner=JSON.parse(await readFile(lock,'utf8'));try{process.kill(owner.pid,0)}catch(e){if(e.code!=='EPERM'){await unlink(lock);continue;}}}catch{try{if(Date.now()-(await stat(lock)).mtimeMs>30000){await unlink(lock);continue;}}catch{}}if(Date.now()-start>5000)throw fail('活动档案正在写入，请稍后重试','lan_event_busy',503);await new Promise(r=>setTimeout(r,30));}}try{return await fn();}finally{try{if(JSON.parse(await readFile(lock,'utf8')).token===token)await unlink(lock)}catch{}}}
 async function read(){try{const d=JSON.parse(await readFile(file,'utf8'));if(d.schema!==1||!d.events||!d.follows||!Array.isArray(d.requests)||d.checksum!==sha({...d,checksum:undefined}))throw fail('活动档案校验失败，原文件已保留','lan_event_corrupt',503);return d;}catch(e){if(e.code!=='ENOENT')throw e.code==='lan_event_corrupt'?e:fail('活动档案无法读取，原文件已保留','lan_event_corrupt',503);const d={schema:1,revision:0,events:{},follows:{},requests:[],updatedAt:now()};d.checksum=sha(d);await atomic(file,d);return d;}}
 async function save(d,old){d.revision=old.revision+1;d.updatedAt=now();delete d.checksum;d.checksum=sha(d);await atomic(previous,old);await atomic(file,d);}
 const economy=createLanActivityEconomy({tenants,now}),settlements=createLanSettlementCoordinator({file:join(root,'settlement-pending.json'),tenants,save,fault:settlementFault});
 async function reconcile(){await settlements.recover();let d=await read();for(const e of Object.values(d.events)){if(!e.economy||['completed','cancelled'].includes(e.phase))continue;let closed=false;try{await identities.roomStateForServer(e.roomId)}catch(error){if(error.code==='lan_room_missing'||error.code==='lan_room_closed')closed=true;else throw error;}if(now()<=e.expiresAt&&!closed)continue;const next=clone(d),row=next.events[e.id],reason=closed?'会客房关闭，自动退回待结算物资':'活动到期，自动退回待结算物资',steps=economy.stamp(economy.settle(row,{cancel:true,reason}),randomUUID());row.phase='cancelled';row.trials={};row.cancelledAt=now();row.revision++;await settlements.commit({old:d,next,steps});d=await read();}return d;}
 function phase(e){return ['completed','cancelled'].includes(e.phase)?e.phase:now()>e.expiresAt?'expired':e.phase;}
 function projection(d,a){const mine=Object.values(d.events).filter(e=>e.owner===a.id||e.invitations[a.id]||d.follows[a.id]?.[e.owner]&&e.createdAt>=d.follows[a.id][e.owner]);const events=mine.map(e=>{const t=e.trials[a.id];return{id:e.id,owner:e.owner,ownerName:e.ownerName,islandName:e.islandName,roomId:e.roomId,theme:e.theme,title:e.title,kind:e.kind,brief:e.brief,recipeId:e.recipeId,startsAt:e.startsAt,expiresAt:e.expiresAt,phase:phase(e),revision:e.revision,createdAt:e.createdAt,requirements:clone(e.requirements),economy:publicLanEconomy(e,a.id),wonder:clone(e.wonderOutcome||null),difficulty:e.difficulty,minQuality:e.minQuality,invited:!!e.invitations[a.id],participants:Object.entries(e.invitations).map(([id,x])=>({id,name:x.name,response:x.response,checkedIn:!!x.admission,completed:!!e.results[id],result:e.results[id]?{quality:e.results[id].result.quality,outcome:e.results[id].outcome}:null})),results:Object.values(e.results).map(r=>({accountId:r.accountId,name:r.name,at:r.at,quality:r.result.quality,outcome:r.outcome,runId:r.runId})),reviews:clone(Object.values(e.reviews)),trial:t?clone(t):null,myReview:clone(e.reviews[a.id]||null)};});
 const hostIds=new Set([...Object.values(d.events).map(e=>e.owner),...Object.keys(d.follows[a.id]||{})]);const hosts=[...hostIds].map(id=>{const rows=Object.values(d.events).filter(e=>e.owner===id),reviews=rows.flatMap(e=>Object.values(e.reviews)),completed=rows.filter(e=>e.phase==='completed');return{id,name:rows.at(-1)?.ownerName||'',hosted:completed.length,verifiedParticipants:completed.reduce((n,e)=>n+Object.keys(e.results).filter(x=>x!==id).length,0),ratingCount:reviews.length,rating:reviews.length?Math.round(reviews.reduce((n,r)=>n+r.stars,0)/reviews.length*10)/10:null,subscribed:!!d.follows[a.id]?.[id]};});return{events:events.sort((a,b)=>b.createdAt-a.createdAt),hosts,me:a.id,at:now(),kinds:LAN_EVENT_KINDS,economyRules:LAN_ECONOMY_RULES};}
 function eventRow(d,id){const e=d.events[id];if(!e)throw fail('活动不存在','lan_event_missing',404);return e;}
 function owner(e,a){if(e.owner!==a.id)throw fail('只有主办岛主可以操作这项活动','lan_event_forbidden',403);}
 function participant(e,a){const i=e.invitations[a.id];if(!i||i.response!=='accepted')throw fail('请先接受主办岛主发给你的邀请','lan_event_not_invited',403);return i;}
 function revision(e,i){if(e.revision!==i.expectedRevision)throw fail('活动信息已更新，请刷新后重试','lan_event_revision');}
 async function checkRoom(e,a){const r=await identities.roomStateForServer(e.roomId);if(r.owner!==e.owner||!r.members[a.id])throw fail('请先用会客口令进入主办岛主的房间','lan_event_room');return r;}
 async function admission(e,a){const room=await checkRoom(e,a);const proof=await economy.admission(e,a,a.profile.theme),doc=proof.document,missing=proof.missing;if(missing.length)throw fail('尚未带齐：'+missing.join('、'),'lan_event_items');if(e.requirements.garment&&!(e.economy&&a.id===e.owner)&&!wornItems(doc.state).includes(e.requirements.garment))throw fail('请先穿上'+GARMENTS[e.requirements.garment].name,'lan_event_outfit');return{worldKey:doc.state.saveSlot,theme:doc.theme,saveVersion:doc.version,at:now(),items:clone(e.requirements.items),garment:e.requirements.garment,arrivalProof:clone(room.members[a.id].arrivalProof||null)};}
 return{directory:root,
 async reconcile(){return locked(async()=>{await reconcile();});},
 async view(token){const a=await identities.authorize(token);return locked(async()=>projection(await reconcile(),a));},
 async action(token,i){strict(i,['operation','requestId','eventId','expectedRevision','roomId','title','kind','brief','invitees','requirements','prepareSeconds','difficulty','minQuality','response','runId','batch','events','stars','comment','hostId','subscribed','economyMode','deliveryMode']);if(!/^[a-zA-Z0-9-]{8,80}$/.test(i.requestId||''))throw fail('请求编号无效','lan_event_invalid',400);const a=await identities.authorize(token);
 return locked(async()=>{const old=await reconcile(),d=clone(old),fingerprint=sha(i),prior=[...(d.fundedRequests||[]),...d.requests].find(r=>r.accountId===a.id&&r.id===i.requestId);if(prior){if(prior.fingerprint!==fingerprint)throw fail('同一请求不能修改活动内容','lan_event_id_conflict');if(prior.error)throw Object.assign(Error(prior.error.message),prior.error);return{view:projection(d,a),...clone(prior.result),replayed:true};}let result={eventId:null,receipt:null},walletSteps=[];
 if(i.operation==='subscribe'){if(i.hostId===a.id||typeof i.subscribed!=='boolean'||!(await identities.view(token)).users.some(u=>u.id===i.hostId))throw fail('请选择其他岛主订阅','lan_event_invalid',400);d.follows[a.id]??={};if(i.subscribed)d.follows[a.id][i.hostId]??=now();else delete d.follows[a.id][i.hostId];}
 else if(i.operation==='publish'){
 const room=await identities.roomStateForServer(i.roomId);if(room.owner!==a.id)throw fail('请先在自己的会客房发布活动','lan_event_forbidden',403);if(Object.values(d.events).some(e=>e.roomId===room.id&&['preparing','live'].includes(phase(e))))throw fail('这间会客房已有待完成活动','lan_event_active');if(Object.keys(d.events).length>=256)throw fail('课程服务器最多保留256场活动','lan_event_limit');
 if(!kinds[i.kind]||!Number.isInteger(i.prepareSeconds)||i.prepareSeconds<60||i.prepareSeconds>86400||![1,2,3].includes(i.difficulty)||!Number.isInteger(i.minQuality)||i.minQuality<55||i.minQuality>95)throw fail('请选择活动类型、1–3级难度、55–95品质及至少60秒准备时间','lan_event_invalid',400);
 if(!Array.isArray(i.invitees)||!i.invitees.length||i.invitees.length>room.maxPlayers-1||new Set(i.invitees).size!==i.invitees.length||i.invitees.includes(a.id))throw fail('邀请人数需在会客房座位内且不能重复','lan_event_invalid',400);
 const users=(await identities.view(token)).users,selected=i.invitees.map(id=>users.find(u=>u.id===id));if(selected.some(x=>!x))throw fail('受邀岛主不存在','lan_event_invalid',400);
 strict(i.requirements,['items','garment']);const items=i.requirements.items;if(!Array.isArray(items)||items.length>3||new Set(items.map(x=>x.item)).size!==items.length)throw fail('携物要求最多3种且不能重复','lan_event_invalid',400);for(const x of items){strict(x,['item','quantity']);if(!Object.hasOwn(ITEM_BY_ID,x.item)||!Number.isInteger(x.quantity)||x.quantity<1||x.quantity>10)throw fail('携物要求使用现有物品，每种1–10件','lan_event_invalid',400);}const garment=i.requirements.garment;if(garment!==null&&!Object.hasOwn(GARMENTS,garment))throw fail('穿着要求使用现有服装','lan_event_invalid',400);
 const id=randomUUID(),kind=kinds[i.kind],seed=randomBytes(4).readUInt32LE()||1;const hostDocument=await tenants.readIslandForServer(a.id,room.theme);eCreate();
 function eCreate(){const invitations=Object.fromEntries(selected.map(u=>[u.id,{name:u.profile.name,response:'pending',admission:null}]));invitations[a.id]={name:a.profile.name,response:'accepted',admission:null};d.events[id]={id,owner:a.id,ownerName:a.profile.name,islandName:a.profile.islandName,roomId:room.id,hostWorldKey:hostDocument?.state.saveSlot||null,theme:room.theme,title:string(i.title,2,40),kind:kind.id,recipeId:kind.recipeId,building:kind.building,brief:string(i.brief||kind.brief,2,240),createdAt:now(),startsAt:now()+i.prepareSeconds*1000,expiresAt:now()+(i.prepareSeconds+3600)*1000,phase:'preparing',revision:1,seed,difficulty:i.difficulty,minQuality:i.minQuality,requirements:{items:clone(items),garment},invitations,trials:{},results:{},reviews:{},attempts:{}};}result.eventId=id;walletSteps=await economy.publish(d.events[id],a,i.economyMode||'social',i.deliveryMode||'bring');
 }else{
 const e=eventRow(d,i.eventId);result.eventId=e.id;const state=phase(e);
 if(i.operation==='arrive'){participant(e,a);if(!['preparing','live'].includes(state))throw fail('活动已结束，无法入岛','lan_event_expired');const r=await identities.roomStateForServer(e.roomId);if(!r.members[a.id])await identities.action(token,{operation:'room_join',requestId:'arrive-'+i.requestId,code:r.code,entry:'harbor'});}
 else if(i.operation==='respond'){if(!e.invitations[a.id]||a.id===e.owner)throw fail('这张邀请不是发给你的','lan_event_not_invited',403);if(!['preparing','live'].includes(state)||now()>e.startsAt+600000)throw fail('活动邀请已截止','lan_event_expired');if(!['accepted','declined'].includes(i.response))throw fail('邀请答复无效','lan_event_invalid',400);if(e.trials[a.id]||e.results[a.id])throw fail('已经参加本场活动，不能改为拒绝','lan_event_participated');if(i.response==='declined')walletSteps=economy.releaseGuest(e,a.id);e.invitations[a.id].response=i.response;e.invitations[a.id].admission=null;e.revision++;}
 else if(i.operation==='checkin'){const row=participant(e,a);if(!['preparing','live'].includes(state))throw fail('活动已结束','lan_event_expired');row.admission=await admission(e,a);walletSteps=await economy.checkin(e,a,row.admission);e.revision++;}
 else if(i.operation==='start'){owner(e,a);revision(e,i);if(state!=='preparing'||now()<e.startsAt)throw fail('给朋友留出完整准备时间，再开场','lan_event_not_ready');const present=await checkRoom(e,a);const guests=Object.entries(e.invitations).filter(([id,x])=>id!==e.owner&&x.response==='accepted'&&x.admission&&present.members[id]);if(!guests.length)throw fail('至少需要一位朋友接受邀请并核对准备','lan_event_guests');for(const[id]of guests)await admission(e,{id,profile:{theme:e.invitations[id].admission.theme}});walletSteps=economy.start(e);e.phase='live';e.startedAt=now();e.revision++;}
 else if(i.operation==='trial_begin'){participant(e,a);if(state!=='live'||e.results[a.id])throw fail('活动尚未开场、已经结束或你已完成本场','lan_event_not_live');if(e.economy&&a.id!==e.owner&&!e.economy.guests[a.id])throw fail('请先核对并预留入场费与约定物资','lan_event_economy');if(e.trials[a.id])throw fail('请继续上次活动关卡','lan_event_trial_active');if((e.attempts[a.id]||0)>=3)throw fail('每场活动最多三次挑战，请保留下次进步的机会','lan_event_attempts');const proof=await admission(e,a);e.invitations[a.id].admission=proof;e.attempts[a.id]=(e.attempts[a.id]||0)+1;e.trials[a.id]={kind:'lan-event',runId:randomUUID(),accountId:a.id,name:e.title,recipeId:e.recipeId,building:e.building,theme:e.theme,worldKey:proof.worldKey,worldTheme:proof.theme,seed:e.seed,difficulty:e.difficulty,minQuality:e.minQuality,startedAt:now(),expiresAt:e.expiresAt,nextBatch:1,game:createCraftGame(e.building,e.seed,e.difficulty)};e.revision++;}
 else if(['trial_checkpoint','trial_finish','trial_cancel'].includes(i.operation)){participant(e,a);const t=e.trials[a.id];if(!t||t.runId!==i.runId)throw fail('这项关卡不是你当前的活动进度','lan_event_trial_stale');if(i.operation==='trial_cancel'){delete e.trials[a.id];e.revision++;}
 else{if(state!=='live')throw fail('活动已结束，请结束旧关卡','lan_event_expired');await checkRoom(e,a);const doc=await tenants.readIslandForServer(a.id,t.worldTheme);if(!doc||doc.state.saveSlot!==t.worldKey)throw fail('当前小岛已经重开，请结束旧关卡','lan_event_world');
 if(i.operation==='trial_checkpoint'){if(i.batch!==t.nextBatch)throw fail('活动操作批次不符','lan_event_batch');try{applyCraftTrace(t.game,i.events)}catch{throw fail('活动操作无法通过规则回放','lan_event_input',400);}if(t.game.elapsed*1000>now()-t.startedAt+150)throw fail('活动操作超出真实时间','lan_event_clock');t.nextBatch++;}
 else{const r=craftResult(t.game);if(!r)throw fail('请完成关卡再提交成绩','lan_event_unfinished');const receipt={eventId:e.id,runId:t.runId,accountId:a.id,name:a.profile.name,worldKey:t.worldKey,worldTheme:t.worldTheme,at:now(),result:clone(r),outcome:r.passed&&r.quality>=e.minQuality?'completed':'practiced'};if(receipt.outcome==='completed')e.results[a.id]=receipt;delete e.trials[a.id];result.receipt=receipt;e.revision++;}}
 }
 else if(i.operation==='finish'){owner(e,a);revision(e,i);if(state!=='live'||Object.keys(e.trials).length)throw fail('请先让进行中的关卡提交或收起结束','lan_event_not_ready');if(!Object.keys(e.results).some(id=>id!==e.owner))throw fail('至少一位受邀朋友完成挑战后才能结束活动','lan_event_guests');walletSteps=economy.settle(e);e.phase='completed';e.completedAt=now();e.revision++;const wonder=lanWonderStep(e);if(wonder)walletSteps.push(wonder);}
 else if(i.operation==='cancel'){owner(e,a);revision(e,i);if(!['preparing','live','expired'].includes(state))throw fail('活动已经结束','lan_event_ended');walletSteps=economy.settle(e,{cancel:true,reason:'主办方取消活动'});e.phase='cancelled';e.trials={};e.cancelledAt=now();e.revision++;}
 else if(i.operation==='rate'){if(state!=='completed'||a.id===e.owner||!e.results[a.id])throw fail('只有完成本场活动的受邀朋友可以评价','lan_event_rating',403);if(e.reviews[a.id])throw fail('你已留下本场活动的评价','lan_event_rating_once');if(!Number.isInteger(i.stars)||i.stars<1||i.stars>5)throw fail('评价为1–5颗星','lan_event_invalid',400);e.reviews[a.id]={eventId:e.id,accountId:a.id,name:a.profile.name,stars:i.stars,comment:string(i.comment||'',0,200),at:now(),runId:e.results[a.id].runId};e.revision++;}
 else throw fail('不支持此活动动作','lan_event_invalid',400);
 }
 const recorded={accountId:a.id,id:i.requestId,fingerprint,result:clone(result)};d.requests.push(recorded);d.requests=d.requests.slice(-1000);if(walletSteps.length){d.fundedRequests??=[];if(d.fundedRequests.length>=4096)throw fail('活动结算收据达到4096笔上限，现有档案已保留','lan_event_limit');d.fundedRequests.push(clone(recorded));await settlements.commit({old,next:d,steps:economy.stamp(walletSteps,i.requestId),request:recorded});}else await save(d,old);return{view:projection(d,a),...result,replayed:false};});
 }
 };
}
