import {syncResourceState} from './resourceAuthority.mjs';
import {syncPlanningState} from './planningAuthority.mjs';
import {syncPersonalState} from './personalActions.mjs';
import {readFile,open,unlink,rename} from 'node:fs/promises';import {randomUUID,createHash} from 'node:crypto';import {commitResources} from '../src/resourceLedger.js';
const clone=v=>structuredClone(v),sha=v=>createHash('sha256').update(JSON.stringify(v)).digest('hex'),fail=(message,code='lan_wallet_conflict',status=409)=>Object.assign(Error(message),{code,status});
const amounts=o=>o&&typeof o==='object'&&!Array.isArray(o)&&Object.entries(o).every(([id,n])=>/^[a-zA-Z0-9_-]{1,80}$/.test(id)&&Number.isSafeInteger(n)&&n>=0),same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
async function atomic(file,d){const tmp=file+'.'+randomUUID()+'.tmp';let h;try{h=await open(tmp,'wx',0o600);await h.writeFile(JSON.stringify(d));await h.sync();await h.close();h=null;await rename(tmp,file);}finally{await h?.close().catch(()=>{});await unlink(tmp).catch(()=>{});}}
export function createLanEconomyJournal({paths:p,theme,now=()=>Date.now(),validateDocument,fault=()=>{}}){
 async function read(){try{const d=JSON.parse(await readFile(p.external,'utf8'));if(d.schema!==1||d.theme!==theme||!Number.isSafeInteger(d.sequence)||!d.receipts||!d.holds||!d.checkpoint||d.checksum!==sha({...d,checksum:undefined}))throw Error();validateDocument(d.checkpoint,theme);return d;}catch(e){if(e.code==='ENOENT')return null;throw fail('跨岛账本校验失败，现有存档已保留','lan_wallet_corrupt',503);}}
 async function write(d){delete d.checksum;d.checksum=sha(d);await atomic(p.external,d);}
 const marker=d=>({version:1,sequence:d.sequence,worldKey:d.checkpoint.state.saveSlot,holds:clone(d.holds)});
 async function repair(document){const book=await read();if(!book)return document;const sameWorld=document?.state.saveSlot===book.checkpoint.state.saveSlot,mark=document?.state.lanEconomyControl;
 if(sameWorld&&same(mark,marker(book))){if(book.pending){book.pending=false;await write(book);}return document;}
 // A settled wallet can start a new island; an escrow cannot silently follow it.
 if(document&&!sameWorld&&!Object.keys(book.holds).length&&!book.pending)return document;
 const recovered=clone(book.checkpoint);recovered.version=randomUUID();recovered.revision=Math.max(recovered.revision,document?.revision||0)+1;recovered.parentVersion=document?.version||recovered.parentVersion;recovered.reason='lan-wallet-recovery';recovered.updatedAt=new Date(now()).toISOString();await atomic(p.current,recovered);book.checkpoint=clone(recovered);book.pending=false;await write(book);return recovered;
 }
 function assertState(state,old){if(!same(state.lanEconomyControl,old?.state.lanEconomyControl))throw fail('跨岛物资与收据由服务端保存，请读取最新进度','lan_wallet_state');if(old?.state.lanEconomyControl&&state.coins!==old.state.coins)throw fail('岛币由经营与跨岛结算处理，请读取最新进度','lan_wallet_cash');}
 async function assertReplacement(source,old,{restart=false}={}){const book=await read();if(!book)return;if(Object.keys(book.holds).length)throw fail('仍有物资或奖励在活动中预留，请先取消或完成活动','lan_wallet_held');if(!restart&&book.checkpoint.state.saveSlot===old?.state.saveSlot&&!same(source?.lanEconomyControl,old.state.lanEconomyControl))throw fail('备份早于最新跨岛结算，请选择结算后的备份','lan_wallet_old_backup');}
 async function transact(document,input){
 if(!input||Object.keys(input).some(k=>!['id','worldKey','operation','holdId','cost','gain','credit','note','eventId'].includes(k))||typeof input.id!=='string'||!/^[a-zA-Z0-9:._-]{8,160}$/.test(input.id)||!['reserve','release','capture','credit'].includes(input.operation))throw fail('跨岛服务事务格式无效','lan_wallet_invalid',400);
 let book=await read();const fingerprint=sha(input),prior=book?.receipts[input.id];if(prior){if(prior.fingerprint!==fingerprint)throw fail('同一跨岛事务不能改动金额或物资','lan_wallet_id');return{document,result:clone(prior.result),replayed:true};}
 if(!document||input.worldKey!==document.state.saveSlot)throw fail('事务来自已经重开的小岛，不能发往新存档','lan_wallet_world');if(book&&(Object.keys(book.receipts).length>=4096||input.operation==='reserve'&&!book.holds[input.holdId]&&Object.keys(book.receipts).length+1+(Object.keys(book.holds).length+1)*4>4096))throw fail('跨岛账本容量不足，已留出当前活动结算空间，请结束活动并保留档案','lan_wallet_limit');
 const old=clone(document),state=clone(document.state),cost=input.cost||{},gain=input.gain||{};if(!amounts(cost)||!amounts(gain))throw fail('跨岛数量无效','lan_wallet_invalid',400);
 book=book||{schema:1,theme,sequence:0,holds:{},receipts:{},checkpoint:clone(document),pending:false};let actualCost={},actualGain={},personal={},unchanged=false,recognizedCost=0;
 if(input.operation!=='credit'&&(!input.holdId||!/^[a-zA-Z0-9:._-]{8,160}$/.test(input.holdId)))throw fail('预留编号无效','lan_wallet_invalid',400);
 if(input.operation==='reserve'){const h=book.holds[input.holdId];if(h){if(h.worldKey!==input.worldKey||!same(h.cost,cost))throw fail('该预留已有不同物资','lan_wallet_hold');unchanged=true;}else{actualCost=cost;personal=Object.fromEntries(Object.entries(cost).filter(([id])=>id!=='coins').map(([id,n])=>[id,Math.min(n,state.economy?.playerGoods?.[id]||0)]));book.holds[input.holdId]={id:input.holdId,worldKey:input.worldKey,cost:clone(cost),personal,at:now(),eventId:input.eventId};}}
 else if(input.operation==='credit'){actualGain=gain;}
 else{const h=book.holds[input.holdId];if(!h||h.worldKey!==input.worldKey)throw fail('预留已结算或不存在','lan_wallet_hold');if(input.operation==='release'){actualGain=h.cost;personal=h.personal;}else recognizedCost=h.cost.coins||0;delete book.holds[input.holdId];}
 const exchange=commitResources(state,{id:'lan-wallet:'+input.id,cost:actualCost,gain:actualGain,category:'lan-event',note:input.note||input.operation});if(!exchange.ok)throw fail(exchange.reason==='insufficient_resources'?'可用物资或岛币不足，未扣除任何一笔':'跨岛物资数量超出限制','lan_wallet_funds');if(input.operation==='release'){state.economy??={};state.economy.playerGoods??={};for(const[id,n]of Object.entries(personal))state.economy.playerGoods[id]=(state.economy.playerGoods[id]||0)+n;}
 if((actualCost.coins||0)||(actualGain.coins||0)||recognizedCost){state.economy??={};const escrow=['reserve','release'].includes(input.operation),income=escrow?0:actualGain.coins||0,cost=escrow?0:recognizedCost;state.economy.costs=(state.economy.costs||0)+cost;state.economy.cashLedger??=[];state.economy.cashLedger.push({day:state.day,category:escrow?'lan-escrow':'lan-event',note:input.note||input.operation,income,cost,net:income-cost,...escrow?{escrowDelta:(actualGain.coins||0)-(actualCost.coins||0)}:{}});state.economy.cashLedger=state.economy.cashLedger.slice(-300);}
 book.sequence++;const result={id:input.id,operation:input.operation,eventId:input.eventId,holdId:input.holdId||null,cost:actualCost,gain:actualGain,unchanged,sequence:book.sequence,at:now()};
 const next={...clone(document),revision:document.revision+1,version:randomUUID(),parentVersion:document.version,updatedAt:new Date(now()).toISOString(),reason:'lan-'+input.operation,state};book.checkpoint=next;state.lanEconomyControl=marker(book);syncPlanningState(state,next.actions);syncPersonalState(state,next.actions);syncResourceState(state,next.actions);if(next.actions)next.actionsChecksum=sha(next.actions);next.checksum=sha(state);book.receipts[input.id]={fingerprint,worldKey:input.worldKey,result};book.pending=true;validateDocument(next,theme);await write(book);await fault('wallet-prepared',{input});
 await atomic(p.previous,old);await atomic(p.current,next);await fault('wallet-committed',{input});book.pending=false;await write(book);return{document:next,result,replayed:false};
 }
 return{repair,assertState,assertReplacement,transact,raw:read};
}
