import {openExclusiveFile} from './atomicJson.mjs';
import {seedRoomResidents,advanceResidents,stepPerson,roomPeople,publicPerson,prepareMeeting,meetingReady,finishMeeting,prepareRoomWork,roomWorkProgress} from './lanRoomResidents.mjs';
import {travelPreparation,freezeTravelParty} from './lanTravelParty.mjs';
import {mkdir,readFile,writeFile,rename,unlink,open,stat} from 'node:fs/promises';import {resolve,join} from 'node:path';import {randomUUID,randomBytes,createHash,scrypt as scryptCallback,timingSafeEqual} from 'node:crypto';import {promisify} from 'node:util';import {AVATAR_BY_ID} from '../src/avatarCatalog.js';import {worldWalkableForTheme,findPath,WORLD,HARBOR_LAYOUTS} from '../src/world.js';
const scrypt=promisify(scryptCallback),sha=v=>createHash('sha256').update(typeof v==='string'?v:JSON.stringify(v)).digest('hex'),fail=(message,code='lan_conflict',status=409)=>Object.assign(Error(message),{code,status}),clone=v=>structuredClone(v),themes=new Set(['pixel','origami']);
const text=(v,min,max)=>{if(typeof v!=='string'||v.trim().length<min||v.trim().length>max||/[\u0000-\u001f]/.test(v))throw fail('文字长度或格式不符合要求','lan_invalid',400);return v.trim();};
const strict=(v,keys)=>{if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).some(k=>!keys.includes(k)))throw fail('联机请求包含不支持的字段','lan_invalid',400);};
async function atomic(file,v){const tmp=file+'.'+randomUUID()+'.tmp';await writeFile(tmp,JSON.stringify(v,null,2)+'\n',{mode:0o600});await rename(tmp,file);}
function profile(input){const p={name:text(input.name,2,24),islandName:text(input.islandName,2,32),avatar:input.avatar,theme:input.theme};if(!AVATAR_BY_ID[p.avatar]||!themes.has(p.theme))throw fail('请选择有效画风与形象','lan_invalid',400);return p;}
function privateAccount(a){return{id:a.id,profile:clone(a.profile),createdAt:a.createdAt};}
function spawnPoint(theme,index){const candidates=[];for(let y=408;y<=552;y+=24)for(let x=720;x<=888;x+=24)if(worldWalkableForTheme(theme,x,y))candidates.push({x,y});candidates.sort((a,b)=>Math.hypot(a.x-786,a.y-458)-Math.hypot(b.x-786,b.y-458));return candidates[index]||candidates[0];}
function segmentWalkable(theme,a,b){const n=Math.max(2,Math.ceil(Math.hypot(b.x-a.x,b.y-a.y)/4));for(let i=0;i<=n;i++)if(!worldWalkableForTheme(theme,a.x+(b.x-a.x)*i/n,a.y+(b.y-a.y)*i/n))return false;return true;}
function safeRoute(theme,start,end,avoid=[]){const free=(x,y)=>worldWalkableForTheme(theme,x,y)&&!avoid.some(p=>Math.hypot(p.x-x,p.y-y)<15);const clear=(a,b)=>{const n=Math.max(2,Math.ceil(Math.hypot(b.x-a.x,b.y-a.y)/3));for(let i=0;i<=n;i++)if(!free(a.x+(b.x-a.x)*i/n,a.y+(b.y-a.y)*i/n))return false;return true;};const tryRoute=from=>{const path=findPath(from,end,free);if(!path.length)return null;let a=from;for(const b of path){if(!clear(a,b))return null;a=b;}return path;};const direct=tryRoute(start);if(direct)return direct;const points=[];for(let y=-24;y<=24;y+=12)for(let x=-24;x<=24;x+=12)if(x||y)points.push({x:start.x+x,y:start.y+y});points.sort((a,b)=>Math.hypot(a.x-start.x,a.y-start.y)-Math.hypot(b.x-start.x,b.y-start.y));for(const p of points){if(!free(p.x,p.y)||!clear(start,p))continue;const path=tryRoute(p);if(path)return[p,...path];}throw fail('无法找到连续可行走的路线','lan_path');}
export function createLanIdentityStore({directory,now=()=>Date.now(),sessionMs=72*3600000,resolveTravel=null,personalRuntime=false}){
 const root=resolve(directory,'_lan'),file=join(root,'identity.json'),previous=join(root,'identity.previous.json'),lock=join(root,'identity.lock');
 async function locked(fn){await mkdir(root,{recursive:true});const token=randomUUID(),start=Date.now();let acquired=false;while(!acquired){try{const f=await openExclusiveFile(lock);await f.writeFile(JSON.stringify({pid:process.pid,token}));await f.close();acquired=true;}catch(e){if(e.code!=='EEXIST')throw e;try{const owner=JSON.parse(await readFile(lock,'utf8'));try{process.kill(owner.pid,0)}catch(e){if(e.code!=='EPERM'){await unlink(lock);continue;}}}catch{try{if(Date.now()-(await stat(lock)).mtimeMs>30000){await unlink(lock);continue;}}catch{}}if(Date.now()-start>5000)throw fail('联机档案正在写入，请稍后重试','lan_busy',503);await new Promise(r=>setTimeout(r,25));}}
 try{return await fn();}finally{try{if(JSON.parse(await readFile(lock,'utf8')).token===token)await unlink(lock)}catch{}}}
 async function read(){try{const d=JSON.parse(await readFile(file,'utf8'));if(d.schema!==1||d.checksum!==sha({...d,checksum:undefined})||!Number.isSafeInteger(d.revision)||!d.accounts||!d.rooms||!Array.isArray(d.sessions)||!Array.isArray(d.requests))throw fail('联机档案校验失败，原文件已保留','lan_corrupt',503);return d;}catch(e){if(e.code!=='ENOENT')throw e.code==='lan_corrupt'?e:fail('联机档案无法读取，原文件已保留','lan_corrupt',503);const d={schema:1,revision:0,accounts:{},sessions:[],rooms:{},requests:[],events:[],updatedAt:now()};d.checksum=sha(d);await atomic(file,d);return d;}}
 async function save(d,old){d.revision=old.revision+1;d.updatedAt=now();delete d.checksum;d.checksum=sha(d);await atomic(previous,old);await atomic(file,d);}
 function auth(d,token){if(typeof token!=='string'||!/^[A-Za-z0-9_-]{43}$/.test(token))throw fail('请先登录自己的岛主身份','lan_unauthorized',401);const digest=sha(token),s=d.sessions.find(s=>s.digest===digest&&s.expiresAt>now()),a=s&&d.accounts[s.accountId];if(!a)throw fail('登录已到期，请重新登录','lan_unauthorized',401);return{session:s,account:a};}
 function mint(d,id){const token=randomBytes(32).toString('base64url');d.sessions=d.sessions.filter(s=>s.expiresAt>now());if(d.sessions.filter(s=>s.accountId===id).length>=8)throw fail('该岛主同时登录设备已达到8个，请退出旧设备','lan_session_limit');d.sessions.push({accountId:id,digest:sha(token),createdAt:now(),expiresAt:now()+sessionMs});return token;}
 function room(d,id){const r=d.rooms[id];if(!r||r.phase!=='open')throw fail('房间已关闭或不存在','lan_room_missing',404);return r;}
 function membership(d,id){return Object.values(d.rooms).find(r=>r.phase==='open'&&r.members[id]);}
 function ownRoom(d,id,user){const r=room(d,id);if(!r.members[user])throw fail('只能操作自己参加的房间','lan_forbidden',403);return r;}
 function revision(r,i){if(i.expectedRevision!==r.revision)throw fail('房间信息已更新，请刷新后操作','lan_room_revision');}
 function event(d,type,accountId,roomId,extra={}){if(['room_create','room_join','room_leave'].includes(type))d.accounts[accountId].travelEpoch=(d.accounts[accountId].travelEpoch||0)+1;if(type==='room_close')for(const id of Object.keys(d.rooms[roomId].members))d.accounts[id].travelEpoch=(d.accounts[id].travelEpoch||0)+1;d.events.push({id:randomUUID(),at:now(),type,accountId,roomId,...extra});d.events=d.events.slice(-200);}
 function recordArrival(r,m){
 const owner=r.members[r.owner],butler=m.travel?.members?.find(p=>p.kind==='hermes'&&p.npcId===15&&p.ownerAccountId===m.accountId&&p.homeWorldKey===m.travel.homeWorldKey);
 if(m.seat<1||m.arrivalProof||!butler||!owner?.travel?.homeWorldKey||Math.hypot(m.x-HARBOR_LAYOUTS[r.theme].entrance.x,m.y-HARBOR_LAYOUTS[r.theme].entrance.y)>35)return;
 m.arrivalProof={source:'server-harbor-route',roomId:r.id,accountId:m.accountId,hostAccountId:r.owner,hostWorldKey:owner.travel.homeWorldKey,guestWorldKey:m.travel.homeWorldKey,enteredAt:m.travel.frozenAt,arrivedAt:now(),butlerActorId:butler.actorId,position:{x:m.x,y:m.y}};
 }
 function advance(d){for(const r of Object.values(d.rooms)){if(r.phase!=='open')continue;advanceResidents(r,now(),safeRoute);for(const m of Object.values(r.members)){const elapsed=Math.min(2,Math.max(0,(now()-m.updatedAt)/1000));m.updatedAt=now();m.online=now()-m.lastSeen<=45000;if(!m.online){m.walking=false;advanceParty(r,m,0);continue;}let distance=elapsed*80;m.walking=false;while(distance>0&&m.path.length){const dest=m.path[0],dx=dest.x-m.x,dy=dest.y-m.y,len=Math.hypot(dx,dy),step=Math.min(distance,len),next=len?{x:m.x+dx/len*step,y:m.y+dy/len*step}:{...dest};if(!segmentWalkable(r.theme,m,next)){m.path=[];break;}if(len){m.direction=Math.atan2(dy,dx);m.walking=true;}m.x=next.x;m.y=next.y;recordArrival(r,m);distance-=step;if(len<=step+.001)m.path.shift();}if(!m.path.length)m.walking=false;advanceParty(r,m,elapsed);}}}
 function baseProjection(d,user){const own=membership(d,user),me=privateAccount(d.accounts[user]),rooms=Object.values(d.rooms).filter(r=>r.phase==='open').map(r=>({id:r.id,title:r.title,owner:privateAccount(d.accounts[r.owner]),theme:r.theme,maxPlayers:r.maxPlayers,count:Object.keys(r.members).length,revision:r.revision}));
 const selected=own?{id:own.id,title:own.title,owner:own.owner,theme:own.theme,maxPlayers:own.maxPlayers,code:own.code,revision:own.revision,createdAt:own.createdAt,residents:(own.residents||[]).map(c=>publicPerson(c,now()-own.members[own.owner].lastSeen<=45000)),members:Object.values(own.members).map(m=>({...privateAccount(d.accounts[m.accountId]),position:{x:m.x,y:m.y,direction:m.direction,walking:m.walking,online:m.online,updatedAt:m.updatedAt,route:m.path.slice(0,12),speed:80},seat:m.seat,travel:m.travel?{...clone(m.travel),arrival:clone(m.arrivalProof||null)}:null,companions:(m.companions||[]).map(c=>({...clone(c.person),position:{x:c.x,y:c.y,direction:c.direction,walking:c.walking,online:m.online,updatedAt:m.updatedAt,route:c.path.slice(0,12),speed:c.meeting?.kind==='work'?62:72},work:c.meeting?.kind==='work'?clone(c.meeting):null,activity:c.activity||'',meetingId:c.meeting?.id||null,speech:c.speech||null}))})),chat:clone(own.chat)}:null;
 return{me,room:selected,rooms,at:now(),worldSize:WORLD,users:Object.values(d.accounts).map(a=>privateAccount(a))};}
 async function projection(d,user){const v=baseProjection(d,user);if(resolveTravel){const a=d.accounts[user],doc=await resolveTravel(a);v.travel=travelPreparation(a,doc,d.travelChoices?.[user]);v.travel.frozen=!!membership(d,user);v.travel.agentRuntime=personalRuntime?'owner-isolated':'not-connected';}return v;}
 async function attachParty(d,a,r,m){if(!resolveTravel||m.travel)return;const doc=await resolveTravel(a);m.travel=freezeTravelParty(a,doc,d.travelChoices?.[a.id],now());const occupied=Object.values(r.members).flatMap(x=>[x,...(x.companions||[])]);m.companions=[];for(const person of m.travel.members){const h=HARBOR_LAYOUTS[r.theme],anchor=m.seat>0?{x:h.arrival[1][0]-((m.seat-1)*3+2-m.companions.length)*26,y:h.arrival[1][1]}:m;const points=[];for(let y=-72;y<=72;y+=18)for(let x=-72;x<=72;x+=18){const p={x:anchor.x+x,y:anchor.y+y};if(worldWalkableForTheme(r.theme,p.x,p.y)&&!occupied.some(q=>Math.hypot(q.x-p.x,q.y-p.y)<17))points.push(p);}points.sort((p,q)=>Math.hypot(p.x-anchor.x,p.y-anchor.y)-Math.hypot(q.x-anchor.x,q.y-anchor.y));let point=null;for(const p of points){try{safeRoute(r.theme,p,m);point=p;break;}catch{}}if(!point)throw fail('码头等待区暂满，请稍后登岛','lan_travel_queue');const c={person,...point,path:[],direction:m.direction,walking:false,routeAt:0};m.companions.push(c);occupied.push(c);}}
 function advanceParty(r,m,elapsed){let leader=m;const occupied=Object.values(r.members).flatMap(x=>[x,...(x.companions||[])]);for(const c of m.companions||[]){c.walking=false;if(!m.online){leader=c;continue;}if(c.meeting&&c.meeting.until>now()){stepPerson(r,c,elapsed,safeRoute,[...occupied,...(r.residents||[])]);leader=m;continue;}if(c.meeting){c.meeting=null;c.path=[];}const distance=Math.hypot(leader.x-c.x,leader.y-c.y);if(distance>32&&now()-c.routeAt>500){try{c.path=safeRoute(r.theme,c,leader,occupied.filter(q=>q!==c&&q!==leader));}catch{c.path=[];}c.routeAt=now();}let left=Math.min(elapsed*72,Math.max(0,distance-25));while(left>0&&c.path.length){const p=c.path[0],dx=p.x-c.x,dy=p.y-c.y,len=Math.hypot(dx,dy),step=Math.min(left,len,4),next=len?{x:c.x+dx/len*step,y:c.y+dy/len*step}:p;if(!segmentWalkable(r.theme,c,next)){c.path=[];break;}if(occupied.some(q=>q!==c&&Math.hypot(q.x-next.x,q.y-next.y)<15))break;if(len)c.direction=Math.atan2(dy,dx);c.x=next.x;c.y=next.y;c.walking=step>0;left-=step;if(len<=step+.001)c.path.shift();}if(distance<=32)c.path=[];leader=c;}}
 return{
 directory:root,
 async register(input){strict(input,['login','password','name','islandName','avatar','theme']);const login=text(input.login,3,24).toLowerCase();if(!/^[a-z0-9_-]+$/.test(login))throw fail('登录名使用3–24位英文、数字、下划线或连字符','lan_invalid',400);const password=text(input.password,8,128),p=profile(input),salt=randomBytes(16).toString('hex'),digest=Buffer.from(await scrypt(password,salt,64)).toString('hex');return locked(async()=>{const old=await read(),d=clone(old);if(Object.values(d.accounts).some(a=>a.login===login))throw fail('登录名已存在','lan_login_exists');if(Object.keys(d.accounts).length>=32)throw fail('本地课程服务器最多32个岛主身份','lan_account_limit');const id=randomUUID();d.accounts[id]={id,login,salt,digest,profile:p,createdAt:now()};const token=mint(d,id);event(d,'register',id,null);await save(d,old);return{token,view:await projection(d,id)};});},
 async login(input){strict(input,['login','password']);const login=text(input.login,3,24).toLowerCase(),password=text(input.password,8,128);return locked(async()=>{const old=await read(),d=clone(old),a=Object.values(d.accounts).find(a=>a.login===login),salt=a?.salt||'invalid-login-dummy',actual=Buffer.from(await scrypt(password,salt,64)),expected=a?Buffer.from(a.digest,'hex'):Buffer.alloc(64);if(!a||!timingSafeEqual(actual,expected))throw fail('登录名或密码错误','lan_unauthorized',401);const token=mint(d,a.id);await save(d,old);return{token,view:await projection(d,a.id)};});},
 async authorize(token){return locked(async()=>{const {account}=auth(await read(),token);return privateAccount(account);});},
 async logout(token){return locked(async()=>{const old=await read(),d=clone(old),{session,account}=auth(d,token);d.sessions=d.sessions.filter(s=>s.digest!==session.digest);if(!d.sessions.some(s=>s.accountId===account.id&&s.expiresAt>now())){const r=membership(d,account.id),m=r?.members[account.id];if(m){m.lastSeen=now()-45001;m.online=false;m.path=[];m.walking=false;advanceParty(r,m,0);}}await save(d,old);return{ok:true};});},
 async view(token){return locked(async()=>{const old=await read(),d=clone(old),{account}=auth(d,token);advance(d);const r=membership(d,account.id);if(r){await attachParty(d,account,r,r.members[account.id]);if(resolveTravel&&!r.residents)seedRoomResidents(r,d.accounts[r.owner],await resolveTravel(d.accounts[r.owner]),safeRoute,now());r.members[account.id].lastSeen=now();r.members[account.id].online=true;await save(d,old);}return await projection(d,account.id);});},
 async action(token,i){strict(i,['operation','requestId','roomId','expectedRevision','title','maxPlayers','code','message','x','y','profile','entry','npcId']);if(!/^[a-zA-Z0-9-]{8,80}$/.test(i.requestId||''))throw fail('请求编号无效','lan_invalid',400);return locked(async()=>{const old=await read(),d=clone(old),{account:a}=auth(d,token),fingerprint=sha(i),prior=d.requests.find(r=>r.accountId===a.id&&r.id===i.requestId);if(prior){if(prior.fingerprint!==fingerprint)throw fail('同一请求不能修改联机内容','lan_id_conflict');return{view:await projection(d,a.id),replayed:true,...clone(prior.result)};}advance(d);let result={roomId:null};
 if(['travel_invite','travel_remove'].includes(i.operation)){if(!resolveTravel)throw fail('当前服务未启用出行队伍','lan_travel_unavailable');if(membership(d,a.id))throw fail('登岛后同行名单已冻结，回会客厅后再修改','lan_travel_frozen');const doc=await resolveTravel(a),p=travelPreparation(a,doc,d.travelChoices?.[a.id]);if(!p.available)throw fail(p.reason,'lan_travel_home');if(!Number.isInteger(i.npcId)||i.npcId<0||i.npcId>16||i.npcId===15)throw fail('管家自动同行，请选择居民或临时伙伴','lan_travel_invalid');const selected=[...p.selected],candidate=p.residents.find(r=>r.npcId===i.npcId);if(i.operation==='travel_invite'){if(!candidate)throw fail('临时伙伴的聘约已结束或尚未确认','lan_travel_contract');if(!candidate.accepted)throw fail(candidate.name+'：'+candidate.reason,'lan_travel_consent');if(!selected.includes(i.npcId)){if(selected.length>=2)throw fail('最多邀请两位居民同行','lan_travel_limit');selected.push(i.npcId);}}else{const n=selected.indexOf(i.npcId);if(n>=0)selected.splice(n,1);}d.travelChoices??={};d.travelChoices[a.id]={homeWorldKey:p.homeWorldKey,selected,recruitedContractId:selected.includes(16)?i.operation==='travel_invite'&&i.npcId===16?candidate.contractId:p.recruitedContractId:null};result.travelUpdated=true;}
 else if(i.operation==='profile'){if(membership(d,a.id))throw fail('请离开房间后再修改岛主身份','lan_profile_in_room');strict(i.profile,['name','islandName','avatar','theme']);a.profile=profile(i.profile);}
 else if(i.operation==='room_create'){if(membership(d,a.id))throw fail('请先离开当前房间','lan_already_in_room');if(![2,4].includes(i.maxPlayers))throw fail('房间仅支持2或4位岛主','lan_invalid',400);if(Object.values(d.rooms).filter(r=>r.phase==='open').length>=16)throw fail('当前服务器最多16个开放房间','lan_room_limit');const closed=Object.values(d.rooms).filter(r=>r.phase==='closed').sort((a,b)=>a.closedAt-b.closedAt);while(Object.keys(d.rooms).length>=64&&closed.length)delete d.rooms[closed.shift().id];if(Object.keys(d.rooms).length>=64)throw fail('房间历史已达到上限','lan_room_limit');const id=randomUUID(),theme=a.profile.theme,point=spawnPoint(theme,0);if(!point)throw fail('地图入口不可用','lan_map',503);const r={id,title:text(i.title,2,40),owner:a.id,theme,maxPlayers:i.maxPlayers,code:randomBytes(6).toString('hex').toUpperCase(),revision:1,createdAt:now(),phase:'open',members:{},chat:[]};r.members[a.id]={accountId:a.id,seat:0,...point,path:[],direction:Math.PI/2,walking:false,online:true,lastSeen:now(),updatedAt:now(),lastMoveAt:0};await attachParty(d,a,r,r.members[a.id]);if(resolveTravel)seedRoomResidents(r,a,await resolveTravel(a),safeRoute,now());d.rooms[id]=r;result.roomId=id;event(d,'room_create',a.id,id);}
 else if(i.operation==='room_join'){if(membership(d,a.id))throw fail('请先离开当前房间','lan_already_in_room');const r=Object.values(d.rooms).find(r=>r.phase==='open'&&r.code===String(i.code||'').trim().toUpperCase());if(!r)throw fail('邀请口令无效或房间已关闭','lan_room_missing',404);if(Object.keys(r.members).length>=r.maxPlayers)throw fail('房间已满','lan_room_full');const used=Object.values(r.members).map(m=>m.seat),seat=Array.from({length:r.maxPlayers},(_,i)=>i).find(i=>!used.includes(i));if(i.entry!==undefined&&i.entry!=='harbor')throw fail('入岛入口无效','lan_invalid',400);const harbor=!!resolveTravel||i.entry==='harbor',h=HARBOR_LAYOUTS[r.theme],point=harbor?{...h.boarding}:spawnPoint(r.theme,seat),route=harbor?h.arrival.slice(1).map(([x,y])=>({x,y})):[];if(harbor){const tail=safeRoute(r.theme,h.entrance,spawnPoint(r.theme,seat));route.push(...tail);if(!route.every(p=>worldWalkableForTheme(r.theme,p.x,p.y)))throw fail('码头入岛通路不可用','lan_map',503);}r.members[a.id]={accountId:a.id,seat,...point,path:route,direction:Math.PI,walking:harbor,online:true,lastSeen:now(),updatedAt:now(),lastMoveAt:0};await attachParty(d,a,r,r.members[a.id]);r.revision++;result.roomId=r.id;event(d,'room_join',a.id,r.id);}
 else if(['room_leave','room_close','room_chat','room_move','room_resize'].includes(i.operation)){const r=ownRoom(d,i.roomId,a.id);result.roomId=r.id;
  if(i.operation==='room_leave'){revision(r,i);if(r.owner===a.id)throw fail('主办岛主需要关闭房间才能离开','lan_owner_leave');delete r.members[a.id];r.revision++;event(d,'room_leave',a.id,r.id);}
  if(i.operation==='room_close'){revision(r,i);if(r.owner!==a.id)throw fail('只有主办岛主可以关闭房间','lan_forbidden',403);r.phase='closed';r.closedAt=now();r.revision++;for(const m of Object.values(r.members)){m.path=[];m.walking=false;}event(d,'room_close',a.id,r.id);}
  if(i.operation==='room_resize'){revision(r,i);if(r.owner!==a.id)throw fail('只有主办岛主可以调整容量','lan_forbidden',403);if(![2,4].includes(i.maxPlayers)||i.maxPlayers<Object.keys(r.members).length)throw fail('容量不能低于已入岛人数','lan_invalid',400);r.maxPlayers=i.maxPlayers;r.revision++;event(d,'room_resize',a.id,r.id);}
  if(i.operation==='room_chat'){const message=text(i.message,1,240);r.chat.push({id:randomUUID(),accountId:a.id,name:a.profile.name,at:now(),message});r.chat=r.chat.slice(-100);}
  if(i.operation==='room_move'){const m=r.members[a.id];if(!Number.isFinite(i.x)||!Number.isFinite(i.y)||i.x<0||i.y<0||i.x>WORLD.width||i.y>WORLD.height||!worldWalkableForTheme(r.theme,i.x,i.y))throw fail('目的地不可行走，请点击道路或栈桥','lan_destination',400);if(now()-m.lastMoveAt<200)throw fail('移动指令过于频繁','lan_move_rate',429);const end={x:i.x,y:i.y},path=safeRoute(r.theme,m,end);if(!path.length){if(Math.hypot(i.x-m.x,i.y-m.y)>24||!segmentWalkable(r.theme,m,end))throw fail('无法找到可行走的路线','lan_path');path.push(end);}if(path.length>500||!path.every(p=>worldWalkableForTheme(r.theme,p.x,p.y)))throw fail('行路路径超出限制','lan_path');m.path=path;m.lastMoveAt=now();m.lastSeen=now();m.online=true;}
 }else throw fail('不支持此联机动作','lan_invalid',400);
 d.requests.push({accountId:a.id,id:i.requestId,fingerprint,result:clone(result)});d.requests=d.requests.slice(-500);await save(d,old);return{view:await projection(d,a.id),replayed:false,...result};});
 },
 async prepareSocialMeeting(roomId,ids,id){return locked(async()=>{const old=await read(),d=clone(old),r=room(d,roomId);advance(d);prepareMeeting(r,ids,id,now(),safeRoute);await save(d,old);return clone(r);});},
 async socialMeetingReady(roomId,ids,id){return locked(async()=>{const old=await read(),d=clone(old),r=room(d,roomId);advance(d);const ready=meetingReady(r,ids,id,now());await save(d,old);return ready;});},
 async prepareGuestWork(roomId,parts,id){return locked(async()=>{const old=await read(),d=clone(old),r=room(d,roomId);advance(d);prepareRoomWork(r,parts,id,now(),safeRoute);await save(d,old);return clone(r);});},
 async guestWorkProgress(roomId,id,elapsed=null){return locked(async()=>{const old=await read(),d=clone(old),r=room(d,roomId);advance(d);const progress=roomWorkProgress(r,id,now(),elapsed);await save(d,old);return progress;});},
 async finishGuestWork(roomId,id){return locked(async()=>{const old=await read(),d=clone(old),r=d.rooms[roomId];if(!r||!roomPeople(r).some(c=>c.meeting?.id===id))return;finishMeeting(r,id);await save(d,old);});},
 async finishSocialMeeting(roomId,id,event=null){return locked(async()=>{const old=await read(),d=clone(old),r=d.rooms[roomId];if(!r)return;finishMeeting(r,id,event);await save(d,old);});},
 async homeAgentContext(token){return locked(async()=>{const d=await read(),{account:a}=auth(d,token);if(membership(d,a.id))throw fail('岛主正在会客，原岛自动安排已暂停','lan_travel_active');return{ownerId:a.id,travelEpoch:a.travelEpoch||0};});},
 async presence(token){return locked(async()=>{const d=await read(),{account:a}=auth(d,token),r=membership(d,a.id);return r?{roomId:r.id,owner:r.owner,homeTheme:r.members[a.id].travel?.homeTheme||a.profile.theme}:null;});},
 async withHomeIsland(accountId,theme,work){return locked(async()=>{const d=await read(),a=d.accounts[accountId];if(!a)throw fail('岛主身份不存在','lan_unauthorized',401);const r=membership(d,accountId);if(resolveTravel&&r&&(r.members[accountId].travel?.homeTheme||a.profile.theme)===theme)throw fail('岛主与随行伙伴正在会客，请先结束行程再恢复原岛生产','lan_travel_active');return work();});},
 async roomStateForServer(id){return locked(async()=>{const d=await read();return clone(room(d,id));});}
 };
}
