import{hydrateNightParty,nightSnapshot,createNightEvent,updateNightEvent,createNightPlan,inviteNightNpc,cancelNightDraft,validNightParty}from'../src/nightPartyPlanning.js';
import{partyDraftStamp}from'../src/partyPlanning.js';
import {applyStewardEvent} from '../src/stewardParties.js';
const fail=(text,code='night_draft_changed')=>Object.assign(Error(text),{status:409,code});
const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
export const NIGHT_OPERATIONS=['night_enable','night_create','night_update','night_invite','night_plan','night_cancel','night_steward'];
export function enableNightPlanning(s,b){if(!b.party)throw fail('先启用派对账本','party_not_enabled');if(!b.party.design){hydrateNightParty(s);b.party.design=nightSnapshot(s);b.party.invites=structuredClone(s.partyInvites||{});}assertNightPlanning(s,b);}
export function assertNightPlanning(s,b){if(b?.party?.design&&(!same(nightSnapshot(s),b.party.design)||!same(s.partyInvites||{},b.party.invites)))throw fail('夜集方案、同意与邀请物资由服务端确认，请核对已保存进度','night_state_conflict');}
export function syncNightPlanning(s,b){if(b?.party?.design){b.party.design=nightSnapshot(s);b.party.invites=structuredClone(s.partyInvites||{});}}
export function checkNightEvent(s,i){const d=hydrateNightParty(s).draft;if((d?.id||null)!==(i.eventId??null)||(d?.version||null)!==(i.eventVersion??null)||partyDraftStamp(d)!==(i.eventStamp??null))throw fail('夜集方案已变化，请重新打开本次筹备');return d;}
export function applyNightManagement(s,b,i){enableNightPlanning(s,b);if(i.operation==='night_enable')return{ok:true};if(i.operation!=='night_steward')checkNightEvent(s,i);if(s.partySession)throw fail('先结束正在进行的夜集');let r;if(i.operation==='night_steward'){if(!i.verifiedProposal)throw fail('没有当前岛屿的服务端管家活动回执','night_proof');r=applyStewardEvent(s,i.verifiedProposal,i.runId,'night');}else if(i.operation==='night_create')r=createNightEvent(s,i.proposal);else if(i.operation==='night_update')r=updateNightEvent(s,i.proposal);else if(i.operation==='night_invite')r=inviteNightNpc(s,i.npcId);else if(i.operation==='night_plan')r=createNightPlan(s);else if(i.operation==='night_cancel')r=cancelNightDraft(s);else throw fail('夜集操作无效','night_invalid');if(!r?.ok)throw fail(r?.reason||'夜集条件未达成','night_not_ready');if(!validNightParty(s))throw fail('夜集记录无效','night_invalid');syncNightPlanning(s,b);return{...r,text:r.text||({'night_create':'夜集方案已发布','night_update':'夜集方案已更新','night_invite':'物品已送达，居民确认参加当前版本','night_plan':'夜集物资筹备已登记','night_steward':'管家夜集方案和实际物资清单已登记'})[i.operation]};}
